### ISSUE TITLE
Assertion hit at mediator state machine during mediation

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden#1013]
## Problem Definition

Mediating 5 "parallel" transfers (new mediated transfer requests arriving before the previous one for that pair were finished), **at least one** of them triggered assertions in the state machine, which repeated on every new mined block, and changed but kept occurring after expiration block was hit.

The mediated transfer logs I could find before the error started, is as follow:
- My address: `0xb0d5eeaeb7b084a2ba92c24b79f4f2d079a3062b`
- Token: `RTT 0x0f114a1e9db192502e7856309cc899952b3db1ed`
- Originator channel: `0x0bd6ca510d42773f4943f8c00da94b7acc798e4c`
- Originator partner: `0x008311788dff04e3c0426a3eb19622b2035ba49d`
- Target channel: `0xc5ba20b92c3066421868cf40e919e577836ca016`
- Target partner: `0x02f4b6bc65561a792836212ebc54434db0ab759a` (echo node)
- Amount: 7

### Mediation logs:
```
DEBUG:raiden.tasks	new block timestamp=1505316501.39 number=1666736
DEBUG:raiden.network.protocol.ping	PING RECEIVED node=b0d5eeae message=<Ping [msghash=f569c689]> sender=02f4b6bc echohash=664931e8
DEBUG:raiden.network.protocol	ACK RECEIVED node=b0d5eeae receiver=00831178 echohash=df4c1d2c
DEBUG:raiden.network.protocol	ACK RECEIVED node=b0d5eeae receiver=02f4b6bc echohash=a7f97bf8
INFO:raiden.network.protocol	MESSAGE RECEIVED node=b0d5eeae message=<MediatedTransfer [channel:0bd6ca51 nonce:2 transferred_amount:0 locksroot:a7e100c9 hash:1e23b31a id:13328499716505091091 hashlock:b5f8922b expiration:1666826 amount:7]> message_sender=00831178 echohash=a0754b33
DEBUG:raiden.channel.netting_channel	REGISTERED LOCK node=b0d5eeae currentlocksroot=48d6154f lock_expiration=1666826 to=b0d5eeae lock_amount=7 lock_hashlock=b5f8922b from_=00831178 lockhashes=['48d6154f'] lockhash=c81f970e
DEBUG:raiden.channel.netting_channel	REGISTERED TRANSFER node=b0d5eeae nonce=None transfer=<MediatedTransfer [channel:0bd6ca51 nonce:2 transferred_amount:0 locksroot:a7e100c9 hash:1e23b31a id:13328499716505091091 hashlock:b5f8922b expiration:1666826 amount:7]> to=b0d5eeae transferred_amount=0 from_=00831178 current_locksroot=a7e100c9
DEBUG:raiden.channel.netting_channel	REGISTERED LOCK node=b0d5eeae currentlocksroot=cbae5128 lock_expiration=1666814 to=02f4b6bc lock_amount=7 lock_hashlock=b5f8922b from_=b0d5eeae lockhashes=['cbae5128'] lockhash=63e551fa
DEBUG:raiden.channel.netting_channel	REGISTERED TRANSFER node=b0d5eeae nonce=32 transfer=<MediatedTransfer [channel:c5ba20b9 nonce:36 transferred_amount:94 locksroot:488f7684 hash:5a1695de id:13328499716505091091 hashlock:b5f8922b expiration:1666814 amount:7]> to=02f4b6bc transferred_amount=94 from_=b0d5eeae current_locksroot=488f7684
DEBUG:raiden.network.protocol	SENDING MESSAGE node=b0d5eeae to=02f4b6bc message=<MediatedTransfer [channel:c5ba20b9 nonce:36 transferred_amount:94 locksroot:488f7684 hash:5a1695de id:13328499716505091091 hashlock:b5f8922b expiration:1666814 amount:7]> echohash=d7d9b817
DEBUG:raiden.network.protocol	SENDING ACK node=b0d5eeae to=00831178 echohash=a0754b33
DEBUG:raiden.network.protocol	ACK RECEIVED node=b0d5eeae receiver=02f4b6bc echohash=d7d9b817
...
DEBUG:raiden.tasks	new block timestamp=1505317331.21 number=1666806
INFO:raiden.network.protocol	MESSAGE RECEIVED node=b0d5eeae message=<RevealSecret [hashlock:b5f8922b hash:fdb99a97]> message_sender=02f4b6bc echohash=052b62a8
DEBUG:raiden.channel.netting_channel	SECRET REGISTERED node=b0d5eeae hashlock=b5f8922b token=0f114a1e to=00831178 amount=7 from_=b0d5eeae
DEBUG:raiden.network.protocol	SENDING MESSAGE node=b0d5eeae to=00831178 message=<RevealSecret [hashlock:b5f8922b hash:8eb71b0d]> echohash=2dc5c410
DEBUG:raiden.channel.netting_channel	SECRET REGISTERED node=b0d5eeae hashlock=b5f8922b token=0f114a1e to=b0d5eeae amount=7 from_=02f4b6bc
DEBUG:raiden.network.protocol	SENDING MESSAGE node=b0d5eeae to=02f4b6bc message=<RevealSecret [hashlock:b5f8922b hash:8eb71b0d]> echohash=01bc880d
DEBUG:raiden.channel.netting_channel	SECRET REGISTERED node=b0d5eeae hashlock=b5f8922b token=0f114a1e to=00831178 amount=7 from_=b0d5eeae
DEBUG:raiden.channel.netting_channel	REGISTERED TRANSFER node=b0d5eeae nonce=32 transfer=<Secret [channel:c5ba20b9 nonce:41 transferred_amount:108 locksroot:9573d5e8 hash:8c8a5f6c hashlock:b5f8922b]> to=02f4b6bc transferred_amount=108 from_=b0d5eeae current_locksroot=9573d5e8
DEBUG:raiden.network.protocol	SENDING MESSAGE node=b0d5eeae to=02f4b6bc message=<Secret [channel:c5ba20b9 nonce:41 transferred_amount:108 locksroot:9573d5e8 hash:8c8a5f6c hashlock:b5f8922b]> echohash=746e2093
DEBUG:raiden.network.protocol	SENDING ACK node=b0d5eeae to=02f4b6bc echohash=052b62a8
DEBUG:raiden.network.protocol	ACK RECEIVED node=b0d5eeae receiver=02f4b6bc echohash=0b6c8ed9
```

### Initial assertion, repeated on every new block
```
DEBUG:raiden.tasks	new block timestamp=1505317390.52 number=1666810
ERROR:raiden.tasks	unexpected exception on alarm 
Traceback (most recent call last):
  File "/apps/raiden/raiden/tasks.py", line 107, in poll_for_new_block
    result = callback(current_block)
  File "/apps/raiden/raiden/raiden_service.py", line 369, in set_block_number
    self.state_machine_event_handler.log_and_dispatch_to_all_tasks(state_change)
  File "/apps/raiden/raiden/event_handler.py", line 63, in log_and_dispatch_to_all_tasks
    events = self.dispatch(manager, state_change)
  File "/apps/raiden/raiden/event_handler.py", line 95, in dispatch
    all_events = state_manager.dispatch(state_change)
  File "/apps/raiden/raiden/transfer/architecture.py", line 130, in dispatch
    state_change,
  File "/apps/raiden/raiden/transfer/mediated_transfer/mediator.py", line 941, in state_transition
    iteration = handle_block(state, state_change)
  File "/apps/raiden/raiden/transfer/mediated_transfer/mediator.py", line 708, in handle_block
    block_number,
  File "/apps/raiden/raiden/transfer/mediated_transfer/mediator.py", line 394, in set_expired_pairs
    assert pair.payee_state not in STATE_TRANSFER_PAID
AssertionError
```

### Assertion after expiration, repeated every new block
```
DEBUG:raiden.tasks	new block timestamp=1505317776.99 number=1666829
ERROR:raiden.tasks	unexpected exception on alarm 
Traceback (most recent call last):
  File "/apps/raiden/raiden/tasks.py", line 107, in poll_for_new_block
    result = callback(current_block)
  File "/apps/raiden/raiden/raiden_service.py", line 369, in set_block_number
    self.state_machine_event_handler.log_and_dispatch_to_all_tasks(state_change)
  File "/apps/raiden/raiden/event_handler.py", line 63, in log_and_dispatch_to_all_tasks
    events = self.dispatch(manager, state_change)
  File "/apps/raiden/raiden/event_handler.py", line 95, in dispatch
    all_events = state_manager.dispatch(state_change)
  File "/apps/raiden/raiden/transfer/architecture.py", line 130, in dispatch
    state_change,
  File "/apps/raiden/raiden/transfer/mediated_transfer/mediator.py", line 941, in state_transition
    iteration = handle_block(state, state_change)
  File "/apps/raiden/raiden/transfer/mediated_transfer/mediator.py", line 708, in handle_block
    block_number,
  File "/apps/raiden/raiden/transfer/mediated_transfer/mediator.py", line 381, in set_expired_pairs
    assert pair.payee_state == 'payee_expired'
AssertionError
```

### Changing assertion above to give more information about the `pair` object (linebreaks added):
```
...
     assert pair.payee_state == 'payee_expired', repr(pair)                         
AssertionError: <MediationPairState payer_route:<RouteState opened hop:00831178 available_balance:31 settle:90 reveal:10> 
    payer_transfer:<HashTimeLocked id=13328499716505091091 amount=7 token=0f114a1e9db192502e7856309cc899952b3db1ed target=02f4b6bc65561a792836212ebc54434db0ab759a expire=1666826 hashlock=b5f8922b3bd3db744de9a1fdb98d7158a23a560c0e215192e4ff594f317aa181>
    payer_state:payer_waiting_close payee_route:<RouteState opened hop:02f4b6bc available_balance:221 settle:90 reveal:10> 
    payee_transfer:<HashTimeLocked id=13328499716505091091 amount=7 token=0f114a1e9db192502e7856309cc899952b3db1ed target=02f4b6bc65561a792836212ebc54434db0ab759a expire=1666814 hashlock=b5f8922b3bd3db744de9a1fdb98d7158a23a560c0e215192e4ff594f317aa181> 
    payee_state:payee_balance_proof>
```

## Solution

Investigate why a `STATE_TRANSFER_PAID` pair ended up in pending pairs, and handle it.

## System Description
Master 7f5cf59887f7c172353ad8f3f7abcdb125346c66 over `geth 1.6.7-stable-ab5646c5`

**Comment by andrevmatos** [comment]
Possibly related to #917

**Comment by hackaugusto** [comment]
Something is weird, the "Initial assertion" happened around these lines:

```python
  1         elif block_number > pair.payee_transfer.expiration:
394             assert pair.payee_state not in STATE_TRANSFER_PAID
  1             assert pair.payee_transfer.expiration < pair.payer_transfer.expiration
```
Which is setting the transfer to the expired state and asserting that it was not paid.

But the logs show that assertion occurred on block `1666810` while the transfer's lock `expire=1666814`

**Comment by andrevmatos** [comment]
Hmm.. this `pair` object I put there were retrieved later, after editing the code and restarting Raiden. May it be it's from another similar error from another (of the 5) transfers my node tried to mediate on the time. Did some digging  to identify which of them were responsible for the traceback (which didn't contain much information on the `assert`), but if multiple happened, I may have mistaken one for the another, although the incoming request data and effects are pretty similar.

**Comment by hackaugusto** [comment]
Makes sense.

Let's extend these assertions with the `repr` like you did and move the state check up, so that it doesn't happen on every block, e.g.:

```python
    for pair in pending_transfers_pairs:
        if block_number > pair.payer_transfer.expiration and pair.payer_state != 'payer_expired':
            assert pair.payee_state == 'payee_expired'
            assert pair.payee_transfer.expiration < pair.payer_transfer.expiration

            pair.payer_state = 'payer_expired'
            withdraw_failed = EventWithdrawFailed(
                pair.payer_transfer.identifier,
                pair.payer_transfer.hashlock,
                'lock expired',
            )
            events.append(withdraw_failed)
```

**Comment by andrevmatos** [comment]
Another strange thing, related to what you mentioned, is that searching the [full logs](https://github.com/raiden-network/raiden/files/1300645/raiden.2.txt) didn't show any transfer with `lock_expiration=1666810`

**Comment by hackaugusto** [comment]
The lock expires at block 1666809 but it's state is changed in the next block. This is the transfer:

```
DEBUG:raiden.channel.netting_channel	REGISTERED LOCK node=b0d5eeae currentlocksroot=00000000 lock_expiration=1666809 to=02f4b6bc lock_amount=7 lock_hashlock=5e122de2 from_=b0d5eeae lockhashes=[] lockhash=cbae5128
DEBUG:raiden.channel.netting_channel	REGISTERED TRANSFER node=b0d5eeae nonce=32 transfer=<MediatedTransfer [channel:c5ba20b9 nonce:35 transferred_amount:94 locksroot:cbae5128 hash:b1e13fad id:11048222380839261755 hashlock:5e122de2 expiration:1666809 amount:7]> to=02f4b6bc transferred_amount=94 from_=b0d5eeae current_locksroot=cbae5128
DEBUG:raiden.network.protocol	SENDING MESSAGE node=b0d5eeae to=02f4b6bc message=<MediatedTransfer [channel:c5ba20b9 nonce:35 transferred_amount:94 locksroot:cbae5128 hash:b1e13fad id:11048222380839261755 hashlock:5e122de2 expiration:1666809 amount:7]> echohash=cfd36251
```

**Comment by hackaugusto** [comment]
So, the logs from my previous comment are the messages *sent* by the `node=b0d5eeae` `to:02f4b6bc`, this message contained `hashlock:5e122de2` and used `channel:c5ba20b9`.

We can see from the logs that `02f4b6bc` knew the secret and a balance proof was sent to him, this means the payee transfer was payed and it's state was `payee_balance_proof`:

```
DEBUG:raiden.tasks	new block timestamp=1505317331.21 number=1666806
INFO:raiden.network.protocol	MESSAGE RECEIVED node=b0d5eeae message=<RevealSecret [hashlock:5e122de2 hash:f622b23f]> message_sender=02f4b6bc echohash=d9f4a3b8
DEBUG:raiden.channel.netting_channel	SECRET REGISTERED node=b0d5eeae hashlock=5e122de2 token=0f114a1e to=00831178 amount=7 from_=b0d5eeae
...
DEBUG:raiden.channel.netting_channel	REGISTERED TRANSFER node=b0d5eeae nonce=32 transfer=<Secret [channel:c5ba20b9 nonce:40 transferred_amount:101 locksroot:40791400 hash:bce65c12 hashlock:5e122de2]> to=02f4b6bc transferred_amount=101 from_=b0d5eeae current_locksroot=40791400
DEBUG:raiden.network.protocol	SENDING MESSAGE node=b0d5eeae to=02f4b6bc message=<Secret [channel:c5ba20b9 nonce:40 transferred_amount:101 locksroot:40791400 hash:bce65c12 hashlock:5e122de2]> echohash=0b6c8ed9
```
So, the payee transfer was paid but *not complete* when the expiration hit, which is fine, that just means the transfer is entering the unsafe region in 2 blocks and the node may need to settle on-chain. We need to loose a little bit the assertions there.

Now, I need to check if the payer transfer actually completed.

**Comment by hackaugusto** [comment]
This happened because the initiator node was changing networks (started running inside a vpn that was switched off).

These are the needed fixes:

- Handle the case were the node change ip (roaming)
- Loosen the asserts, the payee transfer *can* be at a payed state before the transfer is completed, this happens when the secret is known and the mediator is entering the unsafe region.
- Fix the function to avoid repeating the assertions.
- Check the automatic settlement
