### ISSUE TITLE
Getting "Address is in use" on start

### ISSUE THREAD

**Issue by kesar** [raiden-network/raiden#1032]
## Problem Definition
Getting always ```Address is in use``` and ports are open. Ubuntu (just the one from digitalocean, in case that you want to reproduce environment) firewall is off. Tested without --listen-address.

Steps to reproduce:
Get a Ubuntu server in digitalocean
Install Parity / Geth
Install Raiden & run

```
➜  ~ raiden --keystore-path ~/.local/share/io.parity.ethereum/keys/test --listen-address 138.68.154.XXX:12124
Welcome to Raiden, version 0.1.0+git.ree25ac5!
INFO:raiden.network.sockfactory	trying to find uPnP port mapper... 
ERROR:raiden.network.upnpsock	no upnp providers found 
INFO:raiden.network.sockfactory	uPnP not available, trying STUN for port mapping... 
The following accounts were found in your machine:

[  0] - 0x000f612cd387e6a8a42a5d6b3185f2924c04d3eX

Select one of them by index to continue: 0
Enter the password to unlock 000f612cd387e6a8a42a5d6b3185f2924c04d3eX: 
INFO:raiden.network.discovery	registered endpoint in discovery node_address=000f612c host=138.68.154.XXX port=12124
INFO:filelock	Lock 140096305830608 acquired on /root/.raiden/000f612c/.lock 
ERROR: Address 138.68.154.XXX:12124 is in use. Use --listen-address <host:port> to specify port to listen on.
```

Smoke tests log:
```
================================ RAIDEN VERSION ================================
{"python_version": "2.7.12", "python_implementation": "CPython", "system": "Linux 64bit_ELF 4.4.0-93-generic", "raiden": "0.1.0"}
================================== RAIDEN LOG ==================================
2017-09-17 09:43:12,076 DEBUG:eth.chain.tx	deserialized tx tx=4d479531
2017-09-17 09:43:14,156 INFO:raiden.network.discovery	registered endpoint in discovery node_address=67a5e21e host=0.0.0.0 port=40001
2017-09-17 09:43:14,163 DEBUG:raiden.tasks	starting block number block_number=29
2017-09-17 09:43:14,297 DEBUG:filelock	Attempting to acquire lock 139662033322256 on /tmp/tmp7MIePN/keystore/0x67a5e2/.lock 
2017-09-17 09:43:14,297 INFO:filelock	Lock 139662033322256 acquired on /tmp/tmp7MIePN/keystore/0x67a5e2/.lock 
========================== SMOKETEST ASSERTION ERROR ===========================
Traceback (most recent call last):
  File "/tmp/.mount_sUmJPQ/usr/lib/python2.7/site-packages/raiden-0.1.0-py2.7.egg/raiden/tests/utils/smoketest.py", line 133, in run_smoketests
    run_restapi_smoketests(raiden_service, test_config)
  File "/tmp/.mount_sUmJPQ/usr/lib/python2.7/site-packages/raiden-0.1.0-py2.7.egg/raiden/tests/utils/smoketest.py", line 97, in run_restapi_smoketests
    assert response.status_code == httplib.OK
AssertionError

2017-09-17 09:43:14,359 DEBUG:filelock	Attempting to release lock 139662033322256 on /tmp/tmp7MIePN/keystore/0x67a5e2/.lock 
2017-09-17 09:43:14,359 INFO:filelock	Lock 139662033322256 released on /tmp/tmp7MIePN/keystore/0x67a5e2/.lock 
```

### System Description
```
➜  ~ raiden version
{
  "python_version": "2.7.12", 
  "python_implementation": "CPython", 
  "system": "Linux 64bit_ELF 4.4.0-93-generic", 
  "raiden": "0.1.0+git.ree25ac5"
}

➜  ~ ifconfig 
eth0      Link encap:Ethernet  HWaddr 1a:26:82:e5:e3:13  
          inet addr:138.68.154.XXX  Bcast:138.68.159.255  Mask:255.255.240.0
          inet6 addr: fe80::1826:82ff:fee5:e313/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:29182771 errors:0 dropped:0 overruns:0 frame:0
          TX packets:19541762 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:15555636657 (15.5 GB)  TX bytes:5236016249 (5.2 GB)

➜  ~ uname -a
Linux ethereum-testing 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

➜  ~ sudo lsof -i -P -n | grep LISTEN
sshd     1371 root    3u  IPv4  14394      0t0  TCP *:22 (LISTEN)
sshd     1371 root    4u  IPv6  14396      0t0  TCP *:22 (LISTEN)
ipfs     9127 ipfs    9u  IPv4  79001      0t0  TCP *:4001 (LISTEN)
ipfs     9127 ipfs   11u  IPv6  79002      0t0  TCP *:4001 (LISTEN)
ipfs     9127 ipfs   18u  IPv4  79484      0t0  TCP 127.0.0.1:5001 (LISTEN)
ipfs     9127 ipfs   22u  IPv4  79485      0t0  TCP 127.0.0.1:8080 (LISTEN)
parity  16394 root   41u  IPv4 351372      0t0  TCP *:30303 (LISTEN)
parity  16394 root   51u  IPv4 351377      0t0  TCP *:8546 (LISTEN)
parity  16394 root   53u  IPv4 351379      0t0  TCP *:8545 (LISTEN)
parity  16394 root   57u  IPv4 351381      0t0  TCP *:8180 (LISTEN)
```

**Comment by kesar** [comment]
solved it using --api-address 138.68.154.XXX:40002 instead of the suggested --listen-address. Probably worth to change error msg (and not sure about why I had to do it)

**Comment by ulope** [comment]
@kesar The API listen address defaults to `127.0.0.1:5001` which shows up as being used by `ipfs` in your `lsof ` output. 

However you are quite correct that the error message is highly confusing.
Thanks for bringing this to our attention.

**Comment by ulope** [comment]
We'll track the actual cause in #1039.

Again thanks @kesar for discovering this.
