### ISSUE TITLE
many warnings when starting raiden

### ISSUE THREAD

**Issue by drandreaskrueger** [raiden-network/raiden#1057]
# too many warnings IMHO when starting raiden

```
raiden --keystore-path ~/.local/share/io.parity.ethereum/keys/test
```

```
Welcome to Raiden, version 0.1.0+git.r72845c7a!
ERROR:raiden.network.upnpsock	could not query your lanaddr reported=
INFO:raiden.network.sockfactory	Network port opened internal=0.0.0.0:40001 method=stun external=my.ip.address.removed:40001
The following accounts were found in your machine:

[  0] - 0x003...
[  1] - 0x001...

Select one of them by index to continue: 0
Enter the password to unlock 003...
```
So far so fine, but then comes a huge wall of text:

```Checking if the ethereum node is synchronized
Warning: This is a pre-release compiler version, please do not use it in production.
Token.sol:6:5: Warning: No visibility specified. Defaulting to "public".
    function totalSupply() constant returns (uint256 supply);
    ^-------------------------------------------------------^
Token.sol:10:5: Warning: No visibility specified. Defaulting to "public".
    function balanceOf(address _owner) constant returns (uint256 balance);
    ^--------------------------------------------------------------------^
Token.sol:16:5: Warning: No visibility specified. Defaulting to "public".
    function transfer(address _to, uint256 _value) returns (bool success);
    ^--------------------------------------------------------------------^
Token.sol:23:5: Warning: No visibility specified. Defaulting to "public".
    function transferFrom(address _from, address _to, uint256 _value) returns (bool success);
    ^---------------------------------------------------------------------------------------^
Token.sol:29:5: Warning: No visibility specified. Defaulting to "public".
    function approve(address _spender, uint256 _value) returns (bool success);
    ^------------------------------------------------------------------------^
Token.sol:34:5: Warning: No visibility specified. Defaulting to "public".
    function allowance(address _owner, address _spender) constant returns (uint256 remaining);
    ^----------------------------------------------------------------------------------------^
StandardToken.sol:14:5: Warning: No visibility specified. Defaulting to "public".
    function transfer(address _to, uint256 _value) returns (bool success) {
    ^
Spanning multiple lines.
StandardToken.sol:27:5: Warning: No visibility specified. Defaulting to "public".
    function transferFrom(address _from, address _to, uint256 _value) returns (bool success) {
    ^
Spanning multiple lines.
StandardToken.sol:39:5: Warning: No visibility specified. Defaulting to "public".
    function balanceOf(address _owner) constant returns (uint256 balance) {
    ^
Spanning multiple lines.
StandardToken.sol:43:5: Warning: No visibility specified. Defaulting to "public".
    function approve(address _spender, uint256 _value) returns (bool success) {
    ^
Spanning multiple lines.
StandardToken.sol:49:5: Warning: No visibility specified. Defaulting to "public".
    function allowance(address _owner, address _spender) constant returns (uint256 remaining) {
    ^
Spanning multiple lines.
StandardToken.sol:53:5: Warning: No visibility specified. Defaulting to "public".
    function totalSupply() constant returns (uint256 supply) {
    ^
Spanning multiple lines.
HumanStandardToken.sol:18:5: Warning: No visibility specified. Defaulting to "public".
    function () {
    ^
Spanning multiple lines.
HumanStandardToken.sol:36:5: Warning: No visibility specified. Defaulting to "public".
    function HumanStandardToken(
    ^
Spanning multiple lines.
HumanStandardToken.sol:50:5: Warning: No visibility specified. Defaulting to "public".
    function approveAndCall(address _spender, uint256 _value, bytes _extraData) returns (bool success) {
    ^
Spanning multiple lines.
HumanStandardToken.sol:54:46: Warning: "sha3" has been deprecated in favour of "keccak256"
        require(_spender.call(bytes4(bytes32(sha3("receiveApproval(address,uint256,address,bytes)"))), msg.sender, _value, this, _extraData));
                                             ^----------------------------------------------------^
Warning: This is a pre-release compiler version, please do not use it in production.
Token.sol:6:5: Warning: No visibility specified. Defaulting to "public".
    function totalSupply() constant returns (uint256 supply);
    ^-------------------------------------------------------^
Token.sol:10:5: Warning: No visibility specified. Defaulting to "public".
    function balanceOf(address _owner) constant returns (uint256 balance);
    ^--------------------------------------------------------------------^
Token.sol:16:5: Warning: No visibility specified. Defaulting to "public".
    function transfer(address _to, uint256 _value) returns (bool success);
    ^--------------------------------------------------------------------^
Token.sol:23:5: Warning: No visibility specified. Defaulting to "public".
    function transferFrom(address _from, address _to, uint256 _value) returns (bool success);
    ^---------------------------------------------------------------------------------------^
Token.sol:29:5: Warning: No visibility specified. Defaulting to "public".
    function approve(address _spender, uint256 _value) returns (bool success);
    ^------------------------------------------------------------------------^
Token.sol:34:5: Warning: No visibility specified. Defaulting to "public".
    function allowance(address _owner, address _spender) constant returns (uint256 remaining);
    ^----------------------------------------------------------------------------------------^
Utils.sol:8:5: Warning: No visibility specified. Defaulting to "public".
    function contractExists(address channel) constant returns (bool) {
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:67:5: Warning: No visibility specified. Defaulting to "public".
    function deposit(Data storage self, uint256 amount)
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:92:5: Warning: No visibility specified. Defaulting to "public".
    function close(
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:142:5: Warning: No visibility specified. Defaulting to "public".
    function updateTransfer(
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:216:5: Warning: No visibility specified. Defaulting to "public".
    function withdraw(Data storage self, bytes locked_encoded, bytes merkle_proof, bytes32 secret)
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:294:5: Warning: No visibility specified. Defaulting to "public".
    function settle(Data storage self)
    ^
Spanning multiple lines.
NettingChannelContract.sol:22:5: Warning: No visibility specified. Defaulting to "public".
    function NettingChannelContract(
    ^
Spanning multiple lines.
NettingChannelContract.sol:44:5: Warning: No visibility specified. Defaulting to "public".
    function deposit(uint256 amount) returns (bool) {
    ^
Spanning multiple lines.
NettingChannelContract.sol:59:5: Warning: No visibility specified. Defaulting to "public".
    function addressAndBalance()
    ^
Spanning multiple lines.
NettingChannelContract.sol:77:5: Warning: No visibility specified. Defaulting to "public".
    function close(
    ^
Spanning multiple lines.
NettingChannelContract.sol:96:5: Warning: No visibility specified. Defaulting to "public".
    function updateTransfer(
    ^
Spanning multiple lines.
NettingChannelContract.sol:117:5: Warning: No visibility specified. Defaulting to "public".
    function withdraw(bytes locked_encoded, bytes merkle_proof, bytes32 secret) {
    ^
Spanning multiple lines.
NettingChannelContract.sol:127:5: Warning: No visibility specified. Defaulting to "public".
    function settle() {
    ^
Spanning multiple lines.
NettingChannelContract.sol:134:5: Warning: No visibility specified. Defaulting to "public".
    function settleTimeout() constant returns (uint) {
    ^
Spanning multiple lines.
NettingChannelContract.sol:140:5: Warning: No visibility specified. Defaulting to "public".
    function tokenAddress() constant returns (address) {
    ^
Spanning multiple lines.
NettingChannelContract.sol:146:5: Warning: No visibility specified. Defaulting to "public".
    function opened() constant returns (uint) {
    ^
Spanning multiple lines.
NettingChannelContract.sol:152:5: Warning: No visibility specified. Defaulting to "public".
    function closed() constant returns (uint) {
    ^
Spanning multiple lines.
NettingChannelContract.sol:158:5: Warning: No visibility specified. Defaulting to "public".
    function closingAddress() constant returns (address) {
    ^
Spanning multiple lines.
NettingChannelContract.sol:162:5: Warning: No visibility specified. Defaulting to "public".
    function () { revert(); }
    ^-----------------------^
ChannelManagerLibrary.sol:22:5: Warning: No visibility specified. Defaulting to "public".
    function getChannelWith(Data storage self, address partner) constant returns (address) {
    ^
Spanning multiple lines.
ChannelManagerLibrary.sol:35:5: Warning: No visibility specified. Defaulting to "public".
    function newChannel(Data storage self, address partner, uint settle_timeout)
    ^
Spanning multiple lines.
ChannelManagerContract.sol:28:5: Warning: No visibility specified. Defaulting to "public".
    function ChannelManagerContract(address token_address) {
    ^
Spanning multiple lines.
ChannelManagerContract.sol:34:5: Warning: No visibility specified. Defaulting to "public".
    function getChannelsAddresses() constant returns (address[]) {
    ^
Spanning multiple lines.
ChannelManagerContract.sol:40:5: Warning: No visibility specified. Defaulting to "public".
    function getChannelsParticipants() constant returns (address[]) {
    ^
Spanning multiple lines.
ChannelManagerContract.sol:75:5: Warning: No visibility specified. Defaulting to "public".
    function nettingContractsByAddress(address node_address) constant returns (address[]) {
    ^
Spanning multiple lines.
ChannelManagerContract.sol:81:5: Warning: No visibility specified. Defaulting to "public".
    function tokenAddress() constant returns (address) {
    ^
Spanning multiple lines.
ChannelManagerContract.sol:88:5: Warning: No visibility specified. Defaulting to "public".
    function getChannelWith(address partner) constant returns (address) {
    ^
Spanning multiple lines.
ChannelManagerContract.sol:96:5: Warning: No visibility specified. Defaulting to "public".
    function newChannel(address partner, uint settle_timeout) returns (address) {
    ^
Spanning multiple lines.
ChannelManagerContract.sol:107:5: Warning: No visibility specified. Defaulting to "public".
    function () { revert(); }
    ^-----------------------^
NettingChannelLibrary.sol:199:23: Warning: "sha3" has been deprecated in favour of "keccak256"
        signed_hash = sha3(
                      ^
Spanning multiple lines.
NettingChannelLibrary.sol:243:29: Warning: "sha3" has been deprecated in favour of "keccak256"
        require(hashlock == sha3(secret));
                            ^----------^
NettingChannelLibrary.sol:275:13: Warning: "sha3" has been deprecated in favour of "keccak256"
        h = sha3(lock);
            ^--------^
NettingChannelLibrary.sol:282:21: Warning: "sha3" has been deprecated in favour of "keccak256"
                h = sha3(h, el);
                    ^---------^
NettingChannelLibrary.sol:284:21: Warning: "sha3" has been deprecated in favour of "keccak256"
                h = sha3(el, h);
                    ^---------^
ChannelManagerLibrary.sol:85:20: Warning: "sha3" has been deprecated in favour of "keccak256"
            return sha3(address_one, address_two);
                   ^----------------------------^
ChannelManagerLibrary.sol:90:20: Warning: "sha3" has been deprecated in favour of "keccak256"
            return sha3(address_two, address_one);
                   ^----------------------------^
ChannelManagerLibrary.sol:83:5: Warning: Function state mutability can be restricted to pure
    function partyHash(address address_one, address address_two) internal constant returns (bytes32) {
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:207:25: Warning: Function declared as view, but this expression (potentially) modifies the state and thus requires non-payable (the default) or payable.
        var (r, s, v) = signatureSplit(signature);
                        ^-----------------------^
NettingChannelLibrary.sol:264:5: Warning: Function state mutability can be restricted to pure
    function computeMerkleRoot(bytes lock, bytes merkle_proof)
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:390:5: Warning: Function state mutability can be restricted to pure
    function decodeLock(bytes lock) internal returns (uint64 expiration, uint amount, bytes32 hashlock) {
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:404:5: Warning: Function state mutability can be restricted to pure
    function signatureSplit(bytes signature) internal returns (bytes32 r, bytes32 s, uint8 v) {
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:422:5: Warning: Function state mutability can be restricted to view
    function index_or_throw(Data storage self, address participant_address) private returns (uint8) {
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:430:5: Warning: Function state mutability can be restricted to pure
    function min(uint a, uint b) constant internal returns (uint) {
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:434:5: Warning: Function state mutability can be restricted to pure
    function max(uint a, uint b) constant internal returns (uint) {
    ^
Spanning multiple lines.
Warning: This is a pre-release compiler version, please do not use it in production.
EndpointRegistry.sol:32:5: Warning: No visibility specified. Defaulting to "public".
    function registerEndpoint(string socket) noEmptyString(socket)
    ^
Spanning multiple lines.
EndpointRegistry.sol:54:5: Warning: No visibility specified. Defaulting to "public".
    function findEndpointByAddress(address eth_address) constant returns (string socket)
    ^
Spanning multiple lines.
EndpointRegistry.sol:65:5: Warning: No visibility specified. Defaulting to "public".
    function findAddressByEndpoint(string socket) constant returns (address eth_address)
    ^
Spanning multiple lines.
EndpointRegistry.sol:72:13: Warning: "sha3" has been deprecated in favour of "keccak256"
        if (sha3(a) == sha3(b)) {
            ^-----^
EndpointRegistry.sol:72:24: Warning: "sha3" has been deprecated in favour of "keccak256"
        if (sha3(a) == sha3(b)) {
                       ^-----^
EndpointRegistry.sol:70:5: Warning: Function state mutability can be restricted to pure
    function equals(string a, string b) internal constant returns (bool result)
    ^
Spanning multiple lines.
Warning: This is a pre-release compiler version, please do not use it in production.
Token.sol:6:5: Warning: No visibility specified. Defaulting to "public".
    function totalSupply() constant returns (uint256 supply);
    ^-------------------------------------------------------^
Token.sol:10:5: Warning: No visibility specified. Defaulting to "public".
    function balanceOf(address _owner) constant returns (uint256 balance);
    ^--------------------------------------------------------------------^
Token.sol:16:5: Warning: No visibility specified. Defaulting to "public".
    function transfer(address _to, uint256 _value) returns (bool success);
    ^--------------------------------------------------------------------^
Token.sol:23:5: Warning: No visibility specified. Defaulting to "public".
    function transferFrom(address _from, address _to, uint256 _value) returns (bool success);
    ^---------------------------------------------------------------------------------------^
Token.sol:29:5: Warning: No visibility specified. Defaulting to "public".
    function approve(address _spender, uint256 _value) returns (bool success);
    ^------------------------------------------------------------------------^
Token.sol:34:5: Warning: No visibility specified. Defaulting to "public".
    function allowance(address _owner, address _spender) constant returns (uint256 remaining);
    ^----------------------------------------------------------------------------------------^
NettingChannelLibrary.sol:67:5: Warning: No visibility specified. Defaulting to "public".
    function deposit(Data storage self, uint256 amount)
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:92:5: Warning: No visibility specified. Defaulting to "public".
    function close(
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:142:5: Warning: No visibility specified. Defaulting to "public".
    function updateTransfer(
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:216:5: Warning: No visibility specified. Defaulting to "public".
    function withdraw(Data storage self, bytes locked_encoded, bytes merkle_proof, bytes32 secret)
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:294:5: Warning: No visibility specified. Defaulting to "public".
    function settle(Data storage self)
    ^
Spanning multiple lines.
NettingChannelContract.sol:22:5: Warning: No visibility specified. Defaulting to "public".
    function NettingChannelContract(
    ^
Spanning multiple lines.
NettingChannelContract.sol:44:5: Warning: No visibility specified. Defaulting to "public".
    function deposit(uint256 amount) returns (bool) {
    ^
Spanning multiple lines.
NettingChannelContract.sol:59:5: Warning: No visibility specified. Defaulting to "public".
    function addressAndBalance()
    ^
Spanning multiple lines.
NettingChannelContract.sol:77:5: Warning: No visibility specified. Defaulting to "public".
    function close(
    ^
Spanning multiple lines.
NettingChannelContract.sol:96:5: Warning: No visibility specified. Defaulting to "public".
    function updateTransfer(
    ^
Spanning multiple lines.
NettingChannelContract.sol:117:5: Warning: No visibility specified. Defaulting to "public".
    function withdraw(bytes locked_encoded, bytes merkle_proof, bytes32 secret) {
    ^
Spanning multiple lines.
NettingChannelContract.sol:127:5: Warning: No visibility specified. Defaulting to "public".
    function settle() {
    ^
Spanning multiple lines.
NettingChannelContract.sol:134:5: Warning: No visibility specified. Defaulting to "public".
    function settleTimeout() constant returns (uint) {
    ^
Spanning multiple lines.
NettingChannelContract.sol:140:5: Warning: No visibility specified. Defaulting to "public".
    function tokenAddress() constant returns (address) {
    ^
Spanning multiple lines.
NettingChannelContract.sol:146:5: Warning: No visibility specified. Defaulting to "public".
    function opened() constant returns (uint) {
    ^
Spanning multiple lines.
NettingChannelContract.sol:152:5: Warning: No visibility specified. Defaulting to "public".
    function closed() constant returns (uint) {
    ^
Spanning multiple lines.
NettingChannelContract.sol:158:5: Warning: No visibility specified. Defaulting to "public".
    function closingAddress() constant returns (address) {
    ^
Spanning multiple lines.
NettingChannelContract.sol:162:5: Warning: No visibility specified. Defaulting to "public".
    function () { revert(); }
    ^-----------------------^
NettingChannelLibrary.sol:199:23: Warning: "sha3" has been deprecated in favour of "keccak256"
        signed_hash = sha3(
                      ^
Spanning multiple lines.
NettingChannelLibrary.sol:243:29: Warning: "sha3" has been deprecated in favour of "keccak256"
        require(hashlock == sha3(secret));
                            ^----------^
NettingChannelLibrary.sol:275:13: Warning: "sha3" has been deprecated in favour of "keccak256"
        h = sha3(lock);
            ^--------^
NettingChannelLibrary.sol:282:21: Warning: "sha3" has been deprecated in favour of "keccak256"
                h = sha3(h, el);
                    ^---------^
NettingChannelLibrary.sol:284:21: Warning: "sha3" has been deprecated in favour of "keccak256"
                h = sha3(el, h);
                    ^---------^
NettingChannelLibrary.sol:207:25: Warning: Function declared as view, but this expression (potentially) modifies the state and thus requires non-payable (the default) or payable.
        var (r, s, v) = signatureSplit(signature);
                        ^-----------------------^
NettingChannelLibrary.sol:264:5: Warning: Function state mutability can be restricted to pure
    function computeMerkleRoot(bytes lock, bytes merkle_proof)
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:390:5: Warning: Function state mutability can be restricted to pure
    function decodeLock(bytes lock) internal returns (uint64 expiration, uint amount, bytes32 hashlock) {
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:404:5: Warning: Function state mutability can be restricted to pure
    function signatureSplit(bytes signature) internal returns (bytes32 r, bytes32 s, uint8 v) {
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:422:5: Warning: Function state mutability can be restricted to view
    function index_or_throw(Data storage self, address participant_address) private returns (uint8) {
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:430:5: Warning: Function state mutability can be restricted to pure
    function min(uint a, uint b) constant internal returns (uint) {
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:434:5: Warning: Function state mutability can be restricted to pure
    function max(uint a, uint b) constant internal returns (uint) {
    ^
Spanning multiple lines.
Warning: This is a pre-release compiler version, please do not use it in production.
Token.sol:6:5: Warning: No visibility specified. Defaulting to "public".
    function totalSupply() constant returns (uint256 supply);
    ^-------------------------------------------------------^
Token.sol:10:5: Warning: No visibility specified. Defaulting to "public".
    function balanceOf(address _owner) constant returns (uint256 balance);
    ^--------------------------------------------------------------------^
Token.sol:16:5: Warning: No visibility specified. Defaulting to "public".
    function transfer(address _to, uint256 _value) returns (bool success);
    ^--------------------------------------------------------------------^
Token.sol:23:5: Warning: No visibility specified. Defaulting to "public".
    function transferFrom(address _from, address _to, uint256 _value) returns (bool success);
    ^---------------------------------------------------------------------------------------^
Token.sol:29:5: Warning: No visibility specified. Defaulting to "public".
    function approve(address _spender, uint256 _value) returns (bool success);
    ^------------------------------------------------------------------------^
Token.sol:34:5: Warning: No visibility specified. Defaulting to "public".
    function allowance(address _owner, address _spender) constant returns (uint256 remaining);
    ^----------------------------------------------------------------------------------------^
Utils.sol:8:5: Warning: No visibility specified. Defaulting to "public".
    function contractExists(address channel) constant returns (bool) {
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:67:5: Warning: No visibility specified. Defaulting to "public".
    function deposit(Data storage self, uint256 amount)
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:92:5: Warning: No visibility specified. Defaulting to "public".
    function close(
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:142:5: Warning: No visibility specified. Defaulting to "public".
    function updateTransfer(
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:216:5: Warning: No visibility specified. Defaulting to "public".
    function withdraw(Data storage self, bytes locked_encoded, bytes merkle_proof, bytes32 secret)
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:294:5: Warning: No visibility specified. Defaulting to "public".
    function settle(Data storage self)
    ^
Spanning multiple lines.
NettingChannelContract.sol:22:5: Warning: No visibility specified. Defaulting to "public".
    function NettingChannelContract(
    ^
Spanning multiple lines.
NettingChannelContract.sol:44:5: Warning: No visibility specified. Defaulting to "public".
    function deposit(uint256 amount) returns (bool) {
    ^
Spanning multiple lines.
NettingChannelContract.sol:59:5: Warning: No visibility specified. Defaulting to "public".
    function addressAndBalance()
    ^
Spanning multiple lines.
NettingChannelContract.sol:77:5: Warning: No visibility specified. Defaulting to "public".
    function close(
    ^
Spanning multiple lines.
NettingChannelContract.sol:96:5: Warning: No visibility specified. Defaulting to "public".
    function updateTransfer(
    ^
Spanning multiple lines.
NettingChannelContract.sol:117:5: Warning: No visibility specified. Defaulting to "public".
    function withdraw(bytes locked_encoded, bytes merkle_proof, bytes32 secret) {
    ^
Spanning multiple lines.
NettingChannelContract.sol:127:5: Warning: No visibility specified. Defaulting to "public".
    function settle() {
    ^
Spanning multiple lines.
NettingChannelContract.sol:134:5: Warning: No visibility specified. Defaulting to "public".
    function settleTimeout() constant returns (uint) {
    ^
Spanning multiple lines.
NettingChannelContract.sol:140:5: Warning: No visibility specified. Defaulting to "public".
    function tokenAddress() constant returns (address) {
    ^
Spanning multiple lines.
NettingChannelContract.sol:146:5: Warning: No visibility specified. Defaulting to "public".
    function opened() constant returns (uint) {
    ^
Spanning multiple lines.
NettingChannelContract.sol:152:5: Warning: No visibility specified. Defaulting to "public".
    function closed() constant returns (uint) {
    ^
Spanning multiple lines.
NettingChannelContract.sol:158:5: Warning: No visibility specified. Defaulting to "public".
    function closingAddress() constant returns (address) {
    ^
Spanning multiple lines.
NettingChannelContract.sol:162:5: Warning: No visibility specified. Defaulting to "public".
    function () { revert(); }
    ^-----------------------^
ChannelManagerLibrary.sol:22:5: Warning: No visibility specified. Defaulting to "public".
    function getChannelWith(Data storage self, address partner) constant returns (address) {
    ^
Spanning multiple lines.
ChannelManagerLibrary.sol:35:5: Warning: No visibility specified. Defaulting to "public".
    function newChannel(Data storage self, address partner, uint settle_timeout)
    ^
Spanning multiple lines.
ChannelManagerContract.sol:28:5: Warning: No visibility specified. Defaulting to "public".
    function ChannelManagerContract(address token_address) {
    ^
Spanning multiple lines.
ChannelManagerContract.sol:34:5: Warning: No visibility specified. Defaulting to "public".
    function getChannelsAddresses() constant returns (address[]) {
    ^
Spanning multiple lines.
ChannelManagerContract.sol:40:5: Warning: No visibility specified. Defaulting to "public".
    function getChannelsParticipants() constant returns (address[]) {
    ^
Spanning multiple lines.
ChannelManagerContract.sol:75:5: Warning: No visibility specified. Defaulting to "public".
    function nettingContractsByAddress(address node_address) constant returns (address[]) {
    ^
Spanning multiple lines.
ChannelManagerContract.sol:81:5: Warning: No visibility specified. Defaulting to "public".
    function tokenAddress() constant returns (address) {
    ^
Spanning multiple lines.
ChannelManagerContract.sol:88:5: Warning: No visibility specified. Defaulting to "public".
    function getChannelWith(address partner) constant returns (address) {
    ^
Spanning multiple lines.
ChannelManagerContract.sol:96:5: Warning: No visibility specified. Defaulting to "public".
    function newChannel(address partner, uint settle_timeout) returns (address) {
    ^
Spanning multiple lines.
ChannelManagerContract.sol:107:5: Warning: No visibility specified. Defaulting to "public".
    function () { revert(); }
    ^-----------------------^
Registry.sol:30:5: Warning: No visibility specified. Defaulting to "public".
    function addToken(address token_address)
    ^
Spanning multiple lines.
Registry.sol:49:5: Warning: No visibility specified. Defaulting to "public".
    function channelManagerByToken(address token_address)
    ^
Spanning multiple lines.
Registry.sol:59:5: Warning: No visibility specified. Defaulting to "public".
    function tokenAddresses()
    ^
Spanning multiple lines.
Registry.sol:68:5: Warning: No visibility specified. Defaulting to "public".
    function channelManagerAddresses()
    ^
Spanning multiple lines.
Registry.sol:86:5: Warning: No visibility specified. Defaulting to "public".
    function () { revert(); }
    ^-----------------------^
NettingChannelLibrary.sol:199:23: Warning: "sha3" has been deprecated in favour of "keccak256"
        signed_hash = sha3(
                      ^
Spanning multiple lines.
NettingChannelLibrary.sol:243:29: Warning: "sha3" has been deprecated in favour of "keccak256"
        require(hashlock == sha3(secret));
                            ^----------^
NettingChannelLibrary.sol:275:13: Warning: "sha3" has been deprecated in favour of "keccak256"
        h = sha3(lock);
            ^--------^
NettingChannelLibrary.sol:282:21: Warning: "sha3" has been deprecated in favour of "keccak256"
                h = sha3(h, el);
                    ^---------^
NettingChannelLibrary.sol:284:21: Warning: "sha3" has been deprecated in favour of "keccak256"
                h = sha3(el, h);
                    ^---------^
ChannelManagerLibrary.sol:85:20: Warning: "sha3" has been deprecated in favour of "keccak256"
            return sha3(address_one, address_two);
                   ^----------------------------^
ChannelManagerLibrary.sol:90:20: Warning: "sha3" has been deprecated in favour of "keccak256"
            return sha3(address_two, address_one);
                   ^----------------------------^
ChannelManagerLibrary.sol:83:5: Warning: Function state mutability can be restricted to pure
    function partyHash(address address_one, address address_two) internal constant returns (bytes32) {
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:207:25: Warning: Function declared as view, but this expression (potentially) modifies the state and thus requires non-payable (the default) or payable.
        var (r, s, v) = signatureSplit(signature);
                        ^-----------------------^
NettingChannelLibrary.sol:264:5: Warning: Function state mutability can be restricted to pure
    function computeMerkleRoot(bytes lock, bytes merkle_proof)
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:390:5: Warning: Function state mutability can be restricted to pure
    function decodeLock(bytes lock) internal returns (uint64 expiration, uint amount, bytes32 hashlock) {
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:404:5: Warning: Function state mutability can be restricted to pure
    function signatureSplit(bytes signature) internal returns (bytes32 r, bytes32 s, uint8 v) {
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:422:5: Warning: Function state mutability can be restricted to view
    function index_or_throw(Data storage self, address participant_address) private returns (uint8) {
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:430:5: Warning: Function state mutability can be restricted to pure
    function min(uint a, uint b) constant internal returns (uint) {
    ^
Spanning multiple lines.
NettingChannelLibrary.sol:434:5: Warning: Function state mutability can be restricted to pure
    function max(uint a, uint b) constant internal returns (uint) {
    ^
Spanning multiple lines.
```
Wouldn't it make sense to switch off the warnings? Or to fix the .sol code so that it does not result in so many warnings?

### System Description
```
raiden version
{
  "python_version": "2.7.13", 
  "python_implementation": "CPython", 
  "system": "Linux 64bit_ 4.9.0-3-amd64", 
  "raiden": "0.1.0+git.r72845c7a"
}

parity version
Parity/v1.8.0-unstable-684b14271-20170921/x86_64-linux-gnu/rustc1.20.0

solc --version
Version: 0.4.18-develop.2017.9.25+commit.a23f7f38.Linux.g++
```

**Comment by LefterisJP** [comment]
These warnings are coming only with the new v0.4.17 solc. We recommend using v0.4.16 solc at the moment, even though compatibility with the new version comes soon: 

https://github.com/raiden-network/raiden/pull/1056

**Comment by drandreaskrueger** [comment]
ah, good to know, I try to downgrade then.

**Comment by drandreaskrueger** [comment]
It would be nice if there was some sort of status which gives feedback that (in spite of all those warnings) everything is fine and raiden has been started.

Instead of this last line:

    Spanning multiple lines.

and then ... nothing. Because I really don't know:

- Do I have to wait longer now?
- Is the program stuck?
- What do I do next?
- etc.

**Comment by LefterisJP** [comment]
When the REST API prompt has appeared then Raiden has completely launched.

**Comment by drandreaskrueger** [comment]
ah, resolved. It does get back ... only minutes later:

```
Traceback (most recent call last):
  File "/home/akrueger/Documents/Code/github/non-electron/raiden-network/raiden/env/raidenpython/local/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/akrueger/Documents/Code/github/non-electron/raiden-network/raiden/raiden/network/discovery.py", line 92, in register
    self.discovery_proxy.register_endpoint(node_address, endpoint)
  File "/home/akrueger/Documents/Code/github/non-electron/raiden-network/raiden/raiden/network/rpc/client.py", line 580, in register_endpoint
    timeout=self.poll_timeout,
  File "/home/akrueger/Documents/Code/github/non-electron/raiden-network/raiden/env/raidenpython/local/lib/python2.7/site-packages/pyethapp/rpc_client.py", line 753, in poll
    raise Exception('timeout when polling for transaction')
Exception: timeout when polling for transaction
<Greenlet at 0x7f0c34574910: <bound method ContractDiscovery.register of <raiden.network.discovery.ContractDiscovery object at 0x7f0c333ccd10>>('\x00=$\xb3\xb8^\x10\xf6\xa4i\xc1m\xa1\xb9\x05I\x1, 'my.external.ip.addr', 40001)> failed with Exception

CRITICAL:raiden.raiden_service	Endpoint registry failed: Exception('timeout when polling for transaction',). Ethereum RPC API might be unreachable. 
```

Is that because it is trying my *public* IP address?  
see the above `my.external.ip.addr`



How to point it to localhost? Parity Ropsten is running.

**Comment by drandreaskrueger** [comment]
> > We recommend using v0.4.16 solc  

> ah, good to know, I try to downgrade then.

how to get solc v0.4.16:

```
git clone --recursive https://github.com/ethereum/solidity.git
cd solidity
git checkout tags/v0.4.16  
git submodule update --init

./scripts/install_deps.sh
./scripts/build.sh

solc --version
  Version: 0.4.16-develop.2017.9.25+commit.d7661dd9.Linux.g++
```

**Comment by drandreaskrueger** [comment]
after downgrading solc to v0.4.16 I see no more wall of warnings, but this:

```
Welcome to Raiden, version 0.1.0+git.r72845c7a!
ERROR:raiden.network.upnpsock	could not query your lanaddr reported=
INFO:raiden.network.sockfactory	Network port opened internal=0.0.0.0:40001 method=stun external=my.EXTERNAL.ip.address:40001
Checking if the ethereum node is synchronized
Warning: This is a pre-release compiler version, please do not use it in production.
Warning: This is a pre-release compiler version, please do not use it in production.
Warning: This is a pre-release compiler version, please do not use it in production.
Warning: This is a pre-release compiler version, please do not use it in production.
Warning: This is a pre-release compiler version, please do not use it in production.
```
and then after ~5 minutes:
```
Traceback (most recent call last):
  File "/home/akrueger/Documents/Code/github/non-electron/raiden-network/raiden/env/raidenpython/local/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/akrueger/Documents/Code/github/non-electron/raiden-network/raiden/raiden/network/discovery.py", line 92, in register
    self.discovery_proxy.register_endpoint(node_address, endpoint)
  File "/home/akrueger/Documents/Code/github/non-electron/raiden-network/raiden/raiden/network/rpc/client.py", line 580, in register_endpoint
    timeout=self.poll_timeout,
  File "/home/akrueger/Documents/Code/github/non-electron/raiden-network/raiden/env/raidenpython/local/lib/python2.7/site-packages/pyethapp/rpc_client.py", line 753, in poll
    raise Exception('timeout when polling for transaction')
Exception: timeout when polling for transaction
<Greenlet at 0x7ffb85374910: <bound method ContractDiscovery.register of <raiden.network.discovery.ContractDiscovery object at 0x7ffb842004d0>>('\x00=$\xb3\xb8^\x10\xf6\xa4i\xc1m\xa1\xb9\x05I\x1, 'my.EXTERNAL.ip.address', 40001)> failed with Exception

CRITICAL:raiden.raiden_service	Endpoint registry failed: Exception('timeout when polling for transaction',). Ethereum RPC API might be unreachable. 

```
