### ISSUE TITLE
CRITICAL:raiden.raiden_service	Endpoint registry failed: JSONRPCClientReplyError(u'Method not found',).  

### ISSUE THREAD

**Issue by drandreaskrueger** [raiden-network/raiden#1067]
### Error
```
CRITICAL:raiden.raiden_service
Endpoint registry failed: JSONRPCClientReplyError(u'Method not found',).  
```

### Details
```
source env/raidenpython/bin/activate
raiden --keystore-path ~/.local/share/io.parity.ethereum/keys/test --address $ETHADDRESS --password-file $ETHADDRESSPASSWORDFILE
```
```
Welcome to Raiden, version 0.1.0+git.rcee8f459!
ERROR:raiden.network.upnpsock	could not query your lanaddr reported=
INFO:raiden.network.sockfactory	Network port opened internal=0.0.0.0:40001 method=stun external=217.138.50.154:1918
Checking if the ethereum node is synchronized
Warning: This is a pre-release compiler version, please do not use it in production.
Warning: This is a pre-release compiler version, please do not use it in production.
NettingChannelLibrary.sol:388:5: Warning: Function is marked pure. Be careful, pureness is not enforced yet.
    function decodeLock(bytes lock)
    ^
Spanning multiple lines.
[... 15 such warnings ...]
ChannelManagerLibrary.sol:108:5: Warning: Function is marked pure. Be careful, pureness is not enforced yet.
    function partyHash(address address_one, address address_two)
    ^
Spanning multiple lines.
```
And then a critical error:
```
Traceback (most recent call last):
  File "~/env/raidenpython/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "~/raiden/raiden/network/discovery.py", line 92, in register
    self.discovery_proxy.register_endpoint(node_address, endpoint)
  File "~/raiden/raiden/network/rpc/client.py", line 583, in register_endpoint
    receipt_or_none = check_transaction_threw(self.client, transaction_hash)
  File "~/raiden/raiden/network/rpc/client.py", line 84, in check_transaction_threw
    debug = client.call('debug_traceTransaction', encoded_transaction)
  File "~/env/raidenpython/lib/python2.7/site-packages/pyethapp/rpc_client.py", line 413, in call
    raise JSONRPCClientReplyError(jsonrpc_reply.error)
JSONRPCClientReplyError: Method not found
<Greenlet at 0x7fd392a1a370: <bound method ContractDiscovery.register of <raiden.network.discovery.ContractDiscovery object at 0x7fd391615050>>('\xa1<\xeeiI\xe9\x91\xa2[\xe4\xbf\x86x\xf8q\xb8\xf, 'my.public.ip.addr', 1918)> failed with JSONRPCClientReplyError

CRITICAL:raiden.raiden_service	Endpoint registry failed: JSONRPCClientReplyError(u'Method not found',).  
```

### Version Numbers

```
rustup --version; rustc --version; cargo --version; solc --version; parity --version

rustup 1.6.0
rustc 1.20.0 (f3d6973f4 2017-08-27)
cargo 0.21.0 (5b4b8b2ae 2017-08-12)
solc Version: 0.4.16-develop.2017.9.27+commit.d7661dd9.Linux.g++
Parity  version Parity/v1.7.2-unstable-9f47909ed-20170918/x86_64-linux-gnu/rustc1.20.0
```

```
raiden version
{
  "python_version": "2.7.14", 
  "python_implementation": "CPython", 
  "system": "Linux 64bit_ 4.12.4-1-ARCH", 
  "raiden": "0.1.0+git.rcee8f459"
}
```

**Comment by drandreaskrueger** [comment]
P.S.: It happens often but not always. In about 1 out of 4 cases, instead I see:

```
...
The Raiden API RPC server is now running at http://127.0.0.1:5001/.

See the Raiden documentation for all available endpoints at
http://raiden-network.readthedocs.io/en/stable/rest_api.html
```

**Comment by hackaugusto** [comment]
Parity is not supported, this will be the case until the JSON RPC interface exposes the transaction's status code in the receipt, please refer to EIP658 .

For the time being please use geth. Also, if you're running from the source code, please keep up with the latest master.

**Comment by 5chdn** [comment]
Parity should support EIP658 in versions 1.8+ (nightly).

**Comment by LefterisJP** [comment]
@5chdn Ah thank you! I was about to ask in gitter. Do you know when is the release version of parity that will officially contain `'status'` in the tx receipt as per that EIP?

**Comment by 5chdn** [comment]
`'status'` is already in master, too. We expect 1.8.0 release next week or maybe in 10 days.

There will be also 1.7.3 release today but I can't comment on included features yet. Will add everything to the release notes once the PRs are merged.

**Comment by LefterisJP** [comment]
Thank you. So as soon as it's in a release (so when 1.8.0 is out) we will remove the parity restriction. Raiden is now built with metropolis in mind so we check the tx receipt for `status`.

**Comment by drandreaskrueger** [comment]
Thanks everyone for those updates, much appreciated.

> For the time being please use geth.   
> Also, if you're running from the source code, please keep up with the latest master.

raiden latest master, or geth latest master?

I am building geth like this with the latest release version:
```
git clone --recursive https://github.com/ethereum/go-ethereum.git
cd go-ethereum

git checkout tags/v1.7.1
git submodule update --init

make clean
make
```
(not) good? 

Thanks.

**Comment by LefterisJP** [comment]
> raiden latest master, or geth latest master?

Raiden master. Geth you should use latest release.

But what you posted above should be equal to the latest geth release.

**Comment by 5chdn** [comment]
Have a look at https://github.com/paritytech/parity/releases/tag/v1.7.3

**Comment by LefterisJP** [comment]
thank you @5chdn! Now I will wait till the archlinux package is out for me to test :)

https://www.archlinux.org/packages/community/x86_64/parity/

**Comment by hackaugusto** [comment]
Ffixed by https://github.com/raiden-network/raiden/pull/1080 .
