### ISSUE TITLE
'The method debug_traceTransaction does not exist/is not available'

### ISSUE THREAD

**Issue by drandreaskrueger** [raiden-network/raiden#1078]
I see this error:

```
JSONRPCClientReplyError: 
   The method debug_traceTransaction does not exist/is not available
<Greenlet at 0x7f26362be370: <bound method ContractDiscovery.register of
    <raiden.network.discovery.ContractDiscovery object at 0x7f2635734650>>
   ('\xfc\xe3\x99\xa78\xd8\xc9\xab\x98\x174\x12\x13\xc, 'my.external.ip.replaced', 1447)> 
failed with JSONRPCClientReplyError

CRITICAL:raiden.raiden_service	Endpoint registry failed:   JSONRPCClientReplyError(
u'The method debug_traceTransaction does not exist/is not available',). 
```

on this system

```
uname -a; solc --version; go version; geth version
Linux ... 4.13.3-1-ARCH #1 SMP PREEMPT Thu Sep 21 20:33:16 CEST 2017 x86_64 GNU/Linux
solc, the solidity compiler commandline interface
Version: 0.4.16-develop.2017.9.27+commit.d7661dd9.Linux.g++
go version go1.9 linux/amd64
Geth
Version: 1.7.1-stable
Git Commit: 05101641455a754936acc5ddff92f35f5e33181c
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go
```

### Details:
Now with `geth` (as `parity` is [not supported](https://github.com/raiden-network/raiden/issues/1067#issuecomment-333641359) at the moment), starting `raiden` like this:

```
raiden --keystore-path $ETHKEYSTOREGETHTESTNET  --address $ETHADDRESS --password-file $ETHADDRESSPASSWORDFILE
```

on a synced network node, and with a non-empty account:
```
Welcome to Raiden, version 0.1.0+git.rcee8f459!
ERROR:raiden.network.upnpsock	could not query your lanaddr reported=
INFO:raiden.network.sockfactory	Network port opened internal=0.0.0.0:40001 method=stun external=my.external.ip.replaced:1447
Checking if the ethereum node is synchronized
```

two dozen warnings:
```
Warning: This is a pre-release compiler version, please do not use it in production.
Warning: This is a pre-release compiler version, please do not use it in production.
NettingChannelLibrary.sol:388:5: Warning: Function is marked pure. Be careful, pureness is not enforced yet.
    function decodeLock(bytes lock)
    ^
Spanning multiple lines.
[... 15 similiar warnings removed ...]
ChannelManagerLibrary.sol:108:5: Warning: Function is marked pure. Be careful, pureness is not enforced yet.
    function partyHash(address address_one, address address_two)
    ^
Spanning multiple lines.
```

then a critical error:

```
Traceback (most recent call last):
  File "~/raiden-test/env/raidenpython/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "~/raiden-test/raiden/raiden/network/discovery.py", line 92, in register
    self.discovery_proxy.register_endpoint(node_address, endpoint)
  File "~/raiden-test/raiden/raiden/network/rpc/client.py", line 583, in register_endpoint
    receipt_or_none = check_transaction_threw(self.client, transaction_hash)
  File "~/raiden-test/raiden/raiden/network/rpc/client.py", line 84, in check_transaction_threw
    debug = client.call('debug_traceTransaction', encoded_transaction)
  File "~/raiden-test/env/raidenpython/lib/python2.7/site-packages/pyethapp/rpc_client.py", line 413, in call
    raise JSONRPCClientReplyError(jsonrpc_reply.error)
JSONRPCClientReplyError: The method debug_traceTransaction does not exist/is not available
<Greenlet at 0x7f26362be370: <bound method ContractDiscovery.register of <raiden.network.discovery.ContractDiscovery object at 0x7f2635734650>>('\xfc\xe3\x99\xa78\xd8\xc9\xab\x98\x174\x12\x13\xc, 'my.external.ip.replaced', 1447)> failed with JSONRPCClientReplyError

CRITICAL:raiden.raiden_service	Endpoint registry failed: JSONRPCClientReplyError(u'The method debug_traceTransaction does not exist/is not available',). 
```

**Comment by drandreaskrueger** [comment]
After two repetitions of the same command, it suddenly ends differently:

(same warnings but then) ...

```
INFO:raiden.network.discovery	endpoint already registered node_address=fce399a7 host=my.external.ip.replaced port=40001
INFO:filelock	Lock 140129857251216 acquired on ~/.raiden/0xfce399/.lock 
The Raiden API RPC server is now running at http://127.0.0.1:5001/.

See the Raiden documentation for all available endpoints at
http://raiden-network.readthedocs.io/en/stable/rest_api.html
```

**Comment by LefterisJP** [comment]
> JSONRPCClientReplyError: The method debug_traceTransaction does not exist/is not available
<Greenlet at 0x7f26362be370: <bound method ContractDiscovery.register of <raiden.network.discovery.ContractDiscovery object at 0x7f2635734650>>('\xfc\xe3\x99\xa78\xd8\xc9\xab\x98\x174\x12\x13\xc, 'my.external.ip.replaced', 1447)> failed with JSONRPCClientReplyError


Please update to latest master. This method is no longer needed.

After the second time it worked, since raiden did not attempt to make the transaction to the registry again since you did not change your address.

**Comment by drandreaskrueger** [comment]
Thanks for your superfast answer.

> update to latest master.

```
git submodule update
source env/raidenpython/bin/activate
cd raiden; python setup.py develop; cd ..
raiden version
{
  "python_version": "2.7.14", 
  "python_implementation": "CPython", 
  "system": "Linux 64bit_ 4.13.3-1-ARCH", 
  "raiden": "0.1.0+git.rd4b2677f"
}
```
That's the newest, right? A release version planned anytime soon?

Hooray - I can confirm that (still tons of 'Spanning multiple lines.' warnings, but) **no more critical error**.

Fantastic, thanks.

Now I hope I can finally start playing more with the API itself.

**Comment by drandreaskrueger** [comment]
> version checks.

Great.

Yes, and it looks like you created yourself s.th. like a 2k problem ;-)

        major, minor, patch = [...
        if minor < 7 or (minor == 7 and patch < 6):
            print('You need Byzantium enabled parity. >= 1.7.6 / 1.8.0') ...

not sure, but I think this would fail for version 2.0.0, no?

**Comment by LefterisJP** [comment]
There is a new PR with tests included waitint to be merged about that: https://github.com/raiden-network/raiden/pull/1081
