### ISSUE TITLE
decode_event: raise ValueError('Unknown log type')

### ISSUE THREAD

**Issue by drandreaskrueger** [raiden-network/raiden#1084]
## Problem Definition

reading events on my channel:
```
curl -s http://127.0.0.1:5001/api/1/events/channels/0x177840481cd3063e9346169a819846600f493fee?from_block=1000000
```
results in 
```
{
  "message": "Internal Server Error"
}
```

the channel does exist:
```
curl -s http://127.0.0.1:5001/api/1/channels | jq
[
  {
    "partner_address": "0xfce399a738d8c9ab9817341213c5d411ea92caee",
    "balance": 14662,
    "reveal_timeout": 10,
    "settle_timeout": 600,
    "state": "opened",
    "channel_address": "0x177840481cd3063e9346169a819846600f493fee",
    "token_address": "0x583cbbb8a8443b38abcc0c956bece47340ea1367"
  }
]
```
raiden logging:

```
ERROR:raiden.api.rest	[2017-10-17 10:01:03,679] ERROR in app: Exception on /api/1/events/channels/0x177840481cd3063e9346169a819846600f493fee [GET] 
Traceback (most recent call last):
  File "~/raiden-test/env/raidenpython/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "~/raiden-test/env/raidenpython/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "~/raiden-test/env/raidenpython/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "~/raiden-test/env/raidenpython/local/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "~/raiden-test/env/raidenpython/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "~/raiden-test/env/raidenpython/local/lib/python2.7/site-packages/webargs/core.py", line 441, in wrapper
    return func(*args, **kwargs)
  File "~/raiden-test/raiden/raiden/api/v1/resources.py", line 115, in get
    to_block=to_block,
  File "~/raiden-test/raiden/raiden/api/rest.py", line 434, in get_channel_events
    channel_address, from_block, to_block
  File "~/raiden-test/raiden/raiden/api/python.py", line 671, in get_channel_events
    to_block=to_block,
  File "~/raiden-test/raiden/raiden/blockchain/events.py", line 155, in get_all_netting_channel_events
    to_block,
  File "~/raiden-test/raiden/raiden/blockchain/events.py", line 90, in get_contract_events
    decoded_event = translator.decode_event(event['topics'], event['data'])
  File "~/raiden-test/env/raidenpython/local/lib/python2.7/site-packages/ethereum/abi.py", line 546, in decode_event
    raise ValueError('Unknown log type')
ValueError: Unknown log type 
INFO:raiden.api.rest	127.0.0.1 - - [2017-10-17 10:01:03] "GET /api/1/events/channels/0x177840481cd3063e9346169a819846600f493fee?from_block=1000000 HTTP/1.1" 500 164 0.064420 
```

### System Description
```
source env/raidenpython/bin/activate; raiden version; geth version; solc --version; uname -a; deactivate

{
  "python_version": "2.7.13", 
  "python_implementation": "CPython", 
  "system": "Linux 64bit_ 4.9.0-3-amd64", 
  "raiden": "0.1.0+git.rf2eee151"
}

Geth
Version: 1.7.2-stable
Git Commit: 1db4ecdc0b9e828ff65777fb466fc7c1d04e0de9
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
Operating System: linux

solc, the solidity compiler commandline interface
Version: 0.4.16-develop.2017.9.25+commit.d7661dd9.Linux.g++

Linux ... 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux
```

**Comment by hackaugusto** [comment]
Closing in favor of #1085
