### ISSUE TITLE
Log decoding failed.

### ISSUE THREAD

**Issue by drandreaskrueger** [raiden-network/raiden#1085]
# Depositing from receiving end of channel ... does not work.

## Problem Definition

I had successfully created a channel, from machine A,   
channel address is 0x177840481cd3063e9346169a819846600f493fee. 

Now on machine B when I try to deposit to that channel   
(as described in [api_walkthrough.html#depositing-to-a-channel](http://raiden-network.readthedocs.io/en/stable/api_walkthrough.html#depositing-to-a-channel) ) I get this:

```
curl -X PATCH http://127.0.0.1:5001/api/1/channels/0x177840481cd3063e9346169a819846600f493fee -d '{"balance":7331}' --header 'Content-Type: application/json'

{"message": "Internal Server Error"}
```
and the log output says:

```
INFO:raiden.network.rpc.client	deposit called amount=7331 contract=17784048

ERROR:raiden.tasks	unexpected exception on alarm 
Traceback (most recent call last):
  File "raiden-test/raiden/raiden/tasks.py", line 107, in poll_for_new_block
    result = callback(current_block)
  File "raiden-test/raiden/raiden/raiden_service.py", line 398, in poll_blockchain_events
    for state_change in self.blockchain_events.poll_state_change():
  File "raiden-test/raiden/raiden/blockchain/events.py", line 265, in poll_state_change
    for event in self.poll_all_event_listeners():
  File "raiden-test/raiden/raiden/blockchain/events.py", line 258, in poll_all_event_listeners
    event_listener.translator,
  File "raiden-test/raiden/raiden/blockchain/events.py", line 50, in poll_event_listener
    log_event['data'],
  File "raiden-test/env/raidenpython/lib/python2.7/site-packages/ethereum/abi.py", line 546, in decode_event
    raise ValueError('Unknown log type')
ValueError: Unknown log type

INFO:raiden.network.rpc.client	deposit sucessfull amount=7331 contract=17784048

ERROR:raiden.api.rest	[2017-10-17 11:17:31,534] ERROR in app: Exception on /api/1/channels/0x177840481cd3063e9346169a819846600f493fee [PATCH] 
Traceback (most recent call last):
  File "raiden-test/env/raidenpython/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "raiden-test/env/raidenpython/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "raiden-test/env/raidenpython/lib/python2.7/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "raiden-test/env/raidenpython/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "raiden-test/env/raidenpython/lib/python2.7/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "raiden-test/env/raidenpython/lib/python2.7/site-packages/webargs/core.py", line 441, in wrapper
    return func(*args, **kwargs)
  File "raiden-test/raiden/raiden/api/v1/resources.py", line 60, in patch
    return self.rest_api.patch_channel(**kwargs)
  File "raiden-test/raiden/raiden/api/rest.py", line 536, in patch_channel
    balance
  File "raiden-test/raiden/raiden/api/python.py", line 281, in deposit
    wait_timeout_secs
EthNodeCommunicationError: After 10 seconds the deposit was not properly processed. 

INFO:raiden.api.rest	127.0.0.1 - - [2017-10-17 11:17:31] "PATCH /api/1/channels/0x177840481cd3063e9346169a819846600f493fee HTTP/1.1" 500 164 48.041744 
```

As I see the `deposit sucessfull` (--> successful ;-) ) ...  

I'd expect that in spite of that error, that perhaps some tokens got deposited? But no:

```
curl -s http://127.0.0.1:5001/api/1/channels | jq
[
  {
    "partner_address": "0xc62d9f5092737fa7689579e279a3a1dd5543fb9e",
    "balance": 0,
    "reveal_timeout": 10,
    "settle_timeout": 600,
    "state": "opened",
    "channel_address": "0x177840481cd3063e9346169a819846600f493fee",
    "token_address": "0x583cbbb8a8443b38abcc0c956bece47340ea1367"
  }
]
```
-->  

        "balance": 0

### interesting effect:

By the way, when I deposited more tokens onto the same channel on the originating machine A, it did (sometimes?) work:

```
curl -X PATCH http://127.0.0.1:5001/api/1/channels/0x177840481cd3063e9346169a819846600f493fee -d '{"balance":7331}' --header 'Content-Type: application/json'
{"message": "Internal Server Error"}
```
but still
```
curl -s http://127.0.0.1:5001/api/1/channels | jq
[
  {
    "partner_address": "0xfce399a738d8c9ab9817341213c5d411ea92caee",
    "balance": 14662,
    "reveal_timeout": 10,
    "settle_timeout": 600,
    "state": "opened",
    "channel_address": "0x177840481cd3063e9346169a819846600f493fee",
    "token_address": "0x583cbbb8a8443b38abcc0c956bece47340ea1367"
  }
]
```
-->

        "balance": 14662

and not zero, like above.

#### addresses

machine A (originator) 0xc62d9f5092737fa7689579e279a3a1dd5543fb9e  
machine B (destination) 0xfce399a738d8c9ab9817341213c5d411ea92caee  

### Solution

Probably this is related to https://github.com/raiden-network/raiden/issues/1084 no?

### System Description
```
source env/raidenpython/bin/activate; raiden version; geth version; solc --version; uname -a; deactivate

{
  "python_version": "2.7.13", 
  "python_implementation": "CPython", 
  "system": "Linux 64bit_ 4.9.0-3-amd64", 
  "raiden": "0.1.0+git.rf2eee151"
}

Geth
Version: 1.7.2-stable
Git Commit: 1db4ecdc0b9e828ff65777fb466fc7c1d04e0de9
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
Operating System: linux

solc, the solidity compiler commandline interface
Version: 0.4.16-develop.2017.9.25+commit.d7661dd9.Linux.g++

Linux ... 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux
```

**Comment by drandreaskrueger** [comment]
Hah.

In spite of the error messages, and the balance=0, it had actually worked; examples: [approve](https://ropsten.etherscan.io/tx/0x5e9e01bce7a3401e5025cfc067abc2ce448d07bc7e0ff3b3ddcd33ba3273b580) then [deposit](https://ropsten.etherscan.io/tx/0x04f1e48f170d0704ed1890771882ea984aecfb1e9ed4b9b561de29232090b88e) .

BUT ... raiden had not noticed. 

Ctrl-C on raiden, then restarting it, now I can see the updated balance:

```
curl -s http://127.0.0.1:5001/api/1/channels | jq
[
  {
    "partner_address": "0xc62d9f5092737fa7689579e279a3a1dd5543fb9e",
    "balance": 21993,
    "reveal_timeout": 10,
    "settle_timeout": 600,
    "state": "opened",
    "channel_address": "0x177840481cd3063e9346169a819846600f493fee",
    "token_address": "0x583cbbb8a8443b38abcc0c956bece47340ea1367"
  }
]

```

How can we get rid of those errors mentioned above?  

Manually exiting raiden, and restarting it, is not a good workaround.

**Comment by hackaugusto** [comment]
> Probably this is related to #1084 no?

Yes, this is the same problem. Raiden relies on the blockchain events to update its internal state, for each relevant smart contract a filter is installed, and when a new block is mined the filters are polled.

The first stack trace, the one for the decoding failure, is due to the event polling. Because the polled event failed to decode the internal balance was not updated, the REST server didn't see the change in balance then the second exception happened.

> How can we get rid of those errors mentioned above?

I need to investigate why the log was not in the expected format and the decoding failed.

**Comment by pcppcp** [comment]
Cause of this is a different log signatures - deployed contract logs use different parameters. I am now implementing checks that will raise a warning if there is a version incompatibility with the deployed contract. (#10991)
With the update in #1094, this bug should no more occur.
Please update to the latest master and if the problem persists, reopen the issue.

**Comment by drandreaskrueger** [comment]
The log decoding seems to work now. *Thanks a lot.*

When calling:

    curl -X PUT http://127.0.0.1:5001/api/1/channels -d @openchannel.json --header 'Content-Type: application/json'

I get 
```
{
  "partner_address": "0xfc...",
  "balance": 1337,
  "reveal_timeout": 10,
  "settle_timeout": 600,
  "state": "opened",
  "channel_address": "0x4f...",
  "token_address": "0x583cbbb8a8443b38abcc0c956bece47340ea1367"
}
```
and as log output:
```
INFO:raiden.network.rpc.client	new_netting_channel called peer1=c62d... netting_channel=4f04... peer2=fce3...
INFO:raiden.network.rpc.client	deposit called amount=1337 contract=4f04...
INFO:raiden.network.rpc.client	deposit sucessfull amount=1337 contract=4f04...
INFO:raiden.event_handler	state_change received state_change=<raiden.transfer.mediated_transfer.state_change.ContractReceiveBalance object at 0x7f22...>
INFO:raiden.event_handler	state_change received state_change=<raiden.transfer.mediated_transfer.state_change.ContractReceiveBalance object at 0x7f22...>
INFO:raiden.api.rest	127.0.0.1 - - [2017-11-01 14:41:36] "PUT /api/1/channels HTTP/1.1" 201 416 72.994740 
```



on the **not involved** nodes I see in the log:
```
INFO:raiden.event_handler	state_change received state_change=<raiden.transfer.mediated_transfer.state_change.ContractReceiveNewChannel object at 0x7fbf...>
INFO:raiden.event_handler	ignoring new channel, this node is not a participant. 
```

on the **involved** (counterparty) node I see in the log:

```
INFO:raiden.event_handler	state_change received state_change=<raiden.transfer.mediated_transfer.state_change.ContractReceiveNewChannel object at 0x7fd4...>
INFO:raiden.event_handler	state_change received state_change=<raiden.transfer.mediated_transfer.state_change.ContractReceiveBalance object at 0x7fd4...>
```

> implementing checks that will raise a warning if there is a version incompatibility 

Very useful. I ran into that, and immediately knew which node to upgrade.

Thanks.

**Comment by drandreaskrueger** [comment]
and ... finally also the `deposit` is working

```
curl -X PATCH http://127.0.0.1:5001/api/1/channels/0x4f046... -d '{"balance":7331}' --header 'Content-Type: application/json' | jq
```
now returns
```
{
  "partner_address": "0xfce39...",
  "balance": 23330,
  "reveal_timeout": 10,
  "settle_timeout": 600,
  "state": "opened",
  "channel_address": "0x4f04...",
  "token_address": "0x583cbbb8a8443b38abcc0c956bece47340ea1367"
}
```
and the log print:
```
INFO:raiden.network.rpc.client	deposit called amount=7331 contract=4f04666f
INFO:raiden.network.rpc.client	deposit sucessfull amount=7331 contract=4f04666f
INFO:raiden.event_handler	state_change received state_change=<raiden.transfer.mediated_transfer.state_change.ContractReceiveBalance object at 0x7f22...>
INFO:raiden.event_handler	state_change received state_change=<raiden.transfer.mediated_transfer.state_change.ContractReceiveBalance object at 0x7f22...>
INFO:raiden.api.rest	127.0.0.1 - - [2017-11-01 15:22:25] "PATCH /api/1/channels/0x4f04... HTTP/1.1" 200 412 27.831232 
```

Great!

Greetings to Cancun, we are watching your DevCon3 lifestream ...
