### ISSUE TITLE
Opening channel returns an exception after deposit

### ISSUE THREAD

**Issue by makemesteaks** [raiden-network/raiden#1089]
ERROR:raiden.network.upnpsock   no upnp providers found
INFO:raiden.network.sockfactory Network port opened internal=0.0.0.0:40001 method=stun external=52.23.209.93:40001
INFO:raiden.network.discovery   endpoint already registered node_address=27b2b018 host=52.23.209.93 port=40001
INFO:filelock   Lock 140662432502928 acquired on /root/.raiden/0x27b2b0/.lock
INFO:raiden.api.rest    127.0.0.1 - - [2017-10-17 15:42:14] "GET /api/1/address HTTP/1.1" 200 197 0.001039
INFO:raiden.api.rest    127.0.0.1 - - [2017-10-17 15:42:14] "GET /robots.txt HTTP/1.1" 404 342 0.003100
INFO:raiden.api.rest    127.0.0.1 - - [2017-10-17 15:42:15] "GET /favicon.ico HTTP/1.1" 404 342 0.000850
INFO:raiden.api.rest    127.0.0.1 - - [2017-10-17 15:42:34] "GET /api/1/tokens HTTP/1.1" 200 1426 0.002183
ERROR:raiden.tasks      alarm missed 1 blocks
ERROR:raiden.tasks      alarm missed 1 blocks
INFO:raiden.network.rpc.client  new_netting_channel called peer1=27b2b018 netting_channel=1eac6e9b peer2=a9a737b1
INFO:raiden.api.rest    127.0.0.1 - - [2017-10-17 15:43:41] "PUT /api/1/channels HTTP/1.1" 402 226 0.072476
INFO:raiden.network.rpc.client  new_netting_channel called peer1=27b2b018 netting_channel=1eac6e9b peer2=a9a737b1
INFO:raiden.network.rpc.client  deposit called amount=1337 contract=1eac6e9b
ERROR:raiden.api.rest   [2017-10-17 15:47:10,933] ERROR in app: Exception on /api/1/channels [PUT]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 441, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/raiden/raiden/api/v1/resources.py", line 49, in put
    return self.rest_api.open(**kwargs)
  File "/home/ubuntu/raiden/raiden/api/rest.py", line 320, in open
    balance
  File "/home/ubuntu/raiden/raiden/api/python.py", line 265, in deposit
    channel_proxy.deposit(amount)
  File "/home/ubuntu/raiden/raiden/network/rpc/client.py", line 2038, in deposit
    receipt_or_none = check_transaction_threw(self.client, transaction_hash)
  File "/home/ubuntu/raiden/raiden/network/rpc/client.py", line 103, in check_transaction_threw
    if 'status' not in receipt:
TypeError: argument of type 'NoneType' is not iterable

Running parity 1.8.0

**Comment by pcppcp** [comment]
Hi,
this is a bug in Parity 1.8.0 - the fix is already in. Either use Parity 1.7.7 or recompile dev version.

https://github.com/paritytech/parity/issues/6864
