### ISSUE TITLE
UPNP crash at startup

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#1095]
## Problem Definition

At my network at home raiden crashes at startup with the following message. 

Using `--nat=none` it starts but tells me `Using internal interface address. Connectivity issues are likely.`
Using `--nat=stun` starts as well.

```
Welcome to Raiden, version 0.1.0+git.r4493a190!
Traceback (most recent call last):
  File "/Users/paul/Work/raiden-ve/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/Users/paul/Work/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')
  File "/Users/paul/Work/raiden-ve/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/paul/Work/raiden-ve/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/paul/Work/raiden-ve/lib/python2.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/Users/paul/Work/raiden-ve/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/paul/Work/raiden-ve/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/paul/Work/raiden-ve/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/paul/Work/raiden/raiden/ui/cli.py", line 688, in run
    with SocketFactory(listen_host, listen_port, strategy=kwargs['nat']) as mapped_socket:
  File "/Users/paul/Work/raiden/raiden/network/sockfactory.py", line 75, in __enter__
    mapped_socket = getattr(self, 'map_{}'.format(method))()
  File "/Users/paul/Work/raiden/raiden/network/sockfactory.py", line 113, in map_upnp
    self.source_port,
  File "/Users/paul/Work/raiden/raiden/network/upnpsock.py", line 146, in open_port
    success = register(internal_port, external_port)
  File "/Users/paul/Work/raiden/raiden/network/upnpsock.py", line 142, in register
    '',
Exception: UnknownError
```

## Solution

It shouldn't crash and use a different provider.

### System Description

`raiden master`
`geth 1.7.2-stable-1db4ecdc`
`solc 0.4.18+commit.9cf6e910.Darwin.appleclang`

```
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1036
```

**Comment by hackaugusto** [comment]
Note: The Exception `Exception: UnknownError` is raised by the `miniupnpc.UPnP()` c-extension.

**Comment by LefterisJP** [comment]
@palango Is this still an issue for you?

**Comment by palango** [comment]
I guess so, but can only test this at home.

**Comment by LefterisJP** [comment]
As I don't think anyone else of us has seen this problem can you also add all the system information under **System Description**? Operating System e.t.c.?

**Comment by palango** [comment]
Updated.

**Comment by palango** [comment]
Can confirm that it still happens.

**Comment by LefterisJP** [comment]
@palango is this still happening? If not can you close the issue?

**Comment by palango** [comment]
Seems to work fine for me now.
