### ISSUE TITLE
closing channel not working

### ISSUE THREAD

**Issue by drandreaskrueger** [raiden-network/raiden#1109]
# Cannot close channel.

situation:
```
curl -s http://127.0.0.1:5001/api/1/channels | jq
[
  {
    "partner_address": "0xfce...",
    "balance": 37988,
    "reveal_timeout": 10,
    "settle_timeout": 600,
    "state": "opened",
    "channel_address": "0x4f04666fd1f27d57e46123a016b1cf5141f15bb4",
    "token_address": "0x583cbbb8a8443b38abcc0c956bece47340ea1367"
  }
]
```

trying to close it:

```
curl -X PATCH http://127.0.0.1:5001/api/1/channels/0x4f04666fd1f27d57e46123a016b1cf5141f15bb4 -d '{"state":"closed"}' --header 'Content-Type: application/json' | jq

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    55  100    37  100    18      3      1  0:00:18  0:00:12  0:00:06     4
{
  "message": "Internal Server Error"
}
```

the log window says:

```
INFO:raiden.api.rest	127.0.0.1 - - [2017-11-08 14:45:44] "GET /api/1/channels HTTP/1.1" 200 414 0.000651 
INFO:raiden.network.rpc.client	close called nonce=13 extra_hash=08f0ae4ad2679f7fc4cd4021b7b83bdfc7efabc2f92fb3e845334ee3791ef8bd contract=4f04666f transferred_amount=4 signature=ca11edf274e08fb8faa99665d8d67c321d08eac50efd10f700dc31dcd5bf2a6174206dfbfca3626f40756fbb166b99861911e98e62c7fb120947dfd045caf5111c locksroot=843193dcf61470691a42354d0b72062ebe5885d0604c36b536ae24fe52807750
CRITICAL:raiden.network.rpc.client	close failed nonce=13 extra_hash=08f0ae4ad2679f7fc4cd4021b7b83bdfc7efabc2f92fb3e845334ee3791ef8bd contract=4f04666f transferred_amount=4 signature=ca11edf274e08fb8faa99665d8d67c321d08eac50efd10f700dc31dcd5bf2a6174206dfbfca3626f40756fbb166b99861911e98e62c7fb120947dfd045caf5111c locksroot=843193dcf61470691a42354d0b72062ebe5885d0604c36b536ae24fe52807750
ERROR:raiden.api.rest	[2017-11-08 14:46:03,171] ERROR in app: Exception on /api/1/channels/0x4f04666fd1f27d57e46123a016b1cf5141f15bb4 [PATCH] 
Traceback (most recent call last):
  File "...//raiden-test/env/raidenpython/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "...//raiden-test/env/raidenpython/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "...//raiden-test/env/raidenpython/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "...//raiden-test/env/raidenpython/local/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "...//raiden-test/env/raidenpython/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "...//raiden-test/env/raidenpython/local/lib/python2.7/site-packages/webargs/core.py", line 441, in wrapper
    return func(*args, **kwargs)
  File "...//raiden-test/raiden/raiden/api/v1/resources.py", line 60, in patch
    return self.rest_api.patch_channel(**kwargs)
  File "...//raiden-test/raiden/raiden/api/rest.py", line 554, in patch_channel
    channel.partner_address
  File "...//raiden-test/raiden/raiden/api/python.py", line 597, in close
    channel.external_state.close(balance_proof)
  File "...//raiden-test/raiden/raiden/channel/netting_channel.py", line 125, in close
    signature,
  File "...//raiden-test/raiden/raiden/network/rpc/client.py", line 2003, in close
    raise TransactionThrew('Close', receipt_or_none)
TransactionThrew: Close transaction threw. Receipt={u'status': u'0x0', u'contractAddress': None, u'cumulativeGasUsed': u'0x13984', u'from': u'0xc62d9f5092737fa7689579e279a3a1dd5543fb9e', u'logs': [], u'blockHash': u'0x6c5c1290b1f79564dc949562aab102b360358541d25a0b7c4850fc98f2eadba2', u'transactionHash': u'0xbe79b32f913b0ca725b6d05092b2955dcb94d47aa2ef1c79a3b98a6e4581c90a', u'blockNumber': u'0x1efc4f', u'to': u'0x4f04666fd1f27d57e46123a016b1cf5141f15bb4', u'logsBloom': u'0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', u'transactionIndex': u'0x0', u'gasUsed': u'0x13984'} 
INFO:raiden.api.rest	127.0.0.1 - - [2017-11-08 14:46:03] "PATCH /api/1/channels/0x4f04666fd1f27d57e46123a016b1cf5141f15bb4 HTTP/1.1" 500 164 12.223738 
```

the receiving side shows nothing (but perhaps only because it is blocked with that approx-1-message-per-second [INVALID NONCE error](https://github.com/raiden-network/raiden/issues/1086#issuecomment-341173938)?).  

etherscan shows nothing for that extra_hash= https://ropsten.etherscan.io/tx/0x08f0ae4ad2679f7fc4cd4021b7b83bdfc7efabc2f92fb3e845334ee3791ef8bd  

BUT here is a call to close https://ropsten.etherscan.io/tx/0xbe79b32f913b0ca725b6d05092b2955dcb94d47aa2ef1c79a3b98a6e4581c90a !

And the TxReceipt Status: says FAIL !

What am I doing wrong?

Another status check shows that channel still open:

```
curl -s http://127.0.0.1:5001/api/1/channels | jq
[
  {
    "partner_address": "0xfce...",
    "balance": 37988,
    "reveal_timeout": 10,
    "settle_timeout": 600,
    "state": "opened",
    "channel_address": "0x4f04666fd1f27d57e46123a016b1cf5141f15bb4",
    "token_address": "0x583cbbb8a8443b38abcc0c956bece47340ea1367"
  }
]
```

this time, even killing raiden, and restarting it did not help - it had not learned about the closed channel.

In short - How to close that channel:

https://ropsten.etherscan.io/address/0x4f04666fd1f27d57e46123a016b1cf5141f15bb4

?

Thanks a lot

versions:

```
source env/raidenpython/bin/activate; raiden version; geth version; solc --version; uname -a; deactivate

{
  "python_version": "2.7.13", 
  "python_implementation": "CPython", 
  "system": "Linux 64bit_ 4.9.0-4-amd64", 
  "raiden": "0.2.0+git.r661fe1ee"
}

Geth
Version: 1.7.2-stable
Git Commit: 1db4ecdc0b9e828ff65777fb466fc7c1d04e0de9
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
Operating System: linux
GOPATH=/home/akrueger/Documents/Code/go
GOROOT=/usr/local/go

solc, the solidity compiler commandline interface
Version: 0.4.16-develop.2017.9.25+commit.d7661dd9.Linux.g++

Linux ... 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
```

**Comment by ChosunOne** [comment]
I'm pretty sure this is the same as #1090

**Comment by LefterisJP** [comment]
@ChosunOne @drandreaskrueger Yes they are the same issue. We will have a look at it, but would like to keep one open issue per problem, so I am closing this as a duplicate. Thank you.
