### ISSUE TITLE
Raiden does not start with syntax error

### ISSUE THREAD

**Issue by shigahi** [raiden-network/raiden#1229]
I'm using Ubuntu 16.04 / Python 2.7.12, and installed Raiden from source.
I'm running Parity with modified key and chain directory, and tried to start Raiden with that keystore. Then;

```
raiden --keystore-path /home/ubuntu/ethereum/ropsten/keys/test/
Traceback (most recent call last):
  File "/usr/local/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/home/ubuntu/raiden/raiden/__main__.py", line 7, in main
    from raiden.ui.cli import run
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/home/ubuntu/raiden/raiden/ui/cli.py", line 194
    print(syncing_str.format(local_block, etherscan_block), end='')
                                                               ^
SyntaxError: invalid syntax
```

seems gevent couldn't handle parameters.  Any ideas??

**Comment by hackaugusto** [comment]
Hy @shigahi , raiden moved from python2.7 to python3. Are you using a source install? Please make sure that your virtualenv is based on the version 3 of the interpreter3, e.g.:

```
$ python --version
Python 3.6.4
```

**Comment by shigahi** [comment]
ah ok... i retry python3, thank you.
