### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'ordered'

### ISSUE THREAD

**Issue by EasonWang01** [raiden-network/raiden#1235]
## Problem Definition

After the build process then trying to type command below.
```
raiden --keystore-path  ~/.ethereum/testnet/keystore
```
But this error occur.
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/Users/lin/raiden/raiden/__main__.py", line 7, in main
    from raiden.ui.cli import run
  File "/Users/lin/raiden/raiden/ui/cli.py", line 23, in <module>
    from raiden.api.rest import APIServer, RestAPI
  File "/Users/lin/raiden/raiden/api/rest.py", line 31, in <module>
    from raiden.api.v1.encoding import (
  File "/Users/lin/raiden/raiden/api/v1/encoding.py", line 106, in <module>
    class BaseSchema(Schema):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/marshmallow-3.0.0b6-py3.6.egg/marshmallow/schema.py", line 103, in __new__
    klass.opts = klass.OPTIONS_CLASS(meta, ordered=ordered)
TypeError: __init__() got an unexpected keyword argument 'ordered'
```

**Comment by LefterisJP** [comment]
Can you give more information as per our issue template?

What is the raiden version you are using? What is the underlying etheeum client that is connected to ropsten? What is your OS?

**Comment by EasonWang01** [comment]
```
OS: macOS
pip 9.0.1
python 3.6
geth 1.7.3
```

**Comment by EasonWang01** [comment]
When installing using python2.7 then execute will result the following
```
Traceback (most recent call last):
  File "./raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/Users/lin/raiden/raiden/__main__.py", line 7, in main
    from raiden.ui.cli import run
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/Users/lin/raiden/raiden/ui/cli.py", line 194
    print(syncing_str.format(local_block, etherscan_block), end='')
``

**Comment by LefterisJP** [comment]
Latest master does not support python 2.7

**Comment by palango** [comment]
@EasonWang01 I'm on macOS and python 3.6 as well and tried running `raiden --keystore-path  ~/.ethereum/testnet/keystore` as well but it starts up fine for me. 

How did you install Raiden? It seems that you have `marshmallow` 3.0.0, but I have `marshmallow==2.15.0` locally.

**Comment by palango** [comment]
Addition:
If I update to marshallow 3.0.0b6 manually I get the same error as you do.

**Comment by EasonWang01** [comment]
Thanks,after reinstalling it with `pip3 install 'marshmallow==2.15.0' --force-reinstall`
it works fine.
