### ISSUE TITLE
The registered tokens are not showing in WebUI  (using Parity) 

### ISSUE THREAD

**Issue by dopetard** [raiden-network/raiden#1252]
After syncing the **Ropsten** testnet, I started a raiden node, I tried to register the token from WebUI, I kept getting 500 Internal server error. I talked with @LefterisJP on gitter and he advised to increase the gas-limit, I did so by using --gas-price 10000000000 while starting raiden. It knocked off the earlier transaction and ethscan showed token as registered. I didn't see anything in WebUI and it was empty all along. 

`curl xx.xxx.xxx.xxx:xxxx/api/1/tokens` returns an array of tokens but not the one I'm intending to register.

Earlier, I created two tokens with TLA named ts1 and ts2, deployed and registered it using the **Parity Client**. I intend to register them in two separate raiden node and swap.   

### System Description

```
Linux instance-1 4.13.0-1008-gcp #11-Ubuntu SMP Thu Jan 25 11:08:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

/usr/bin/solc
Version: 0.4.19+commit.c4cbbb05.Linux.g++

/usr/bin/parity
version Parity/v1.8.9-stable-98cccd5-20180201/x86_64-linux-gnu/rustc1.23.0

Raiden version 0.2.0+git.reefa916f

[ -d .git ] && git rev-parse HEAD
eefa916f389fc3960d1f7090f90e116d2a4f06f8
```

**Comment by LefterisJP** [comment]
So to be clear the problem is twofold:

1. The Webui shows no tokens. But doing a `GET /api/1/tokens` returns a big list of tokens.
@andrevmatos Can you have a look at this?

2. The token you are trying to register is returning a 409 "Already registered" error but the token is not returned in the list of tokens from the `GET /api/1/tokens` call?

For the 2nd problem can you paste in this issue:
- The address of the token you are trying to register
- The list returned by the curcle request to `/api/1/tokens`?

**Comment by dopetard** [comment]
Address of the token I'm trying to register 

`0xe6ce7a2b221bFd15b837217189D4db6a58772308`

List of all the tokens returned by curcle request to `/api/1/tokens` call

`["0xb32beafdf5187891cead373a84365e1eda62b057", "0xd9437f0a612110f4a9c093a2296ac918b4558e4d", "0x72fff882555c0406dd3b7e1cad86e97ebafd72fc", "0xc9d3d9752b5288e3e5e2ffce1ce180606fd14f27",
 "0xbb96a15b03971f1ff62ad519228df919eb88b49f", "0xff24d15afb9eb080c089053be99881dd18aa1090", "0xab905cb5ee18fa0d704ae734c50371ebe6d60b71", "0x115676a90c5bd834d0d0b99b0ae127e64bc099ea",
 "0xa15e6fded1a3861468e7e0ed444c0f5491bcc024", "0x8d910f5124416cc8049caa56066c71dbdf748e1b", "0x5033e0064b1e7f9c2c8f1aff0ad17f2be5373533", "0x110fa800ce2e18c2ae650a57d2b7efa27c46d0c2",
 "0xe4dfebac2126d8c98d254e1bef3dde5de83669a4", "0x95733d95085d928876ac5c0eefdc5574bd7923b8", "0x0f114a1e9db192502e7856309cc899952b3db1ed", "0x1989b174eaef2764be8d178feaa897af0c121afd",
 "0x0d94b0089650635e33c6917da6c44e51863d5b81", "0x7b12bceb36bb1d23dee10b00658bd7f0d3c81201", "0x9479466fee1bd64f084c5e2ab25156d8ade8cc7d", "0x5d538965d0c5f2c21aabf16a24367fb37692cae3",
 "0x16bf6708b70b68d88355b13a4b614fef97b0ef77", "0x744e863ceb2474fb99259519d7f1e8cd20b65cdc", "0x8289e89188ce3d9bffbc8f37fe849ed7f7b1639a", "0x80cbe1c77b7b2a95846018818c58c8d22eae8c99",
 "0x4b46fa20670cbb827e825041c87a52e157487c40", "0xf5cc1d9be31bd1382701f048196451b05eb4c42e", "0x583cbbb8a8443b38abcc0c956bece47340ea1367", "0x5e8d1232eecdae123d10353c42d087e396dce343",
 "0x5bd314477ed38c9c1fd97257985f66ccba6821a3", "0xae9c237ca4df346953f8830fc88232af4b92ffde", "0xecd0ff5f622bdbd3cdf383bb29c8042349e75a3a", "0xaeabe46207c1f31f44c3f5876383b808d4280456",
 "0xe1d42f7997ac997614c62f2a3c6a798f3fc047e7", "0x0d013db85a9b9705dc6ee0f30611367eb1321dd9", "0x693ab5dcbdfc8efd30c0fc4ab304296c01edac80", "0x9aba529db3ff2d8409a1da4c9eb148879b046700",
 "0x4156405f32b20a77158553892ae8a6e326d7bcb3", "0x3426c4dc06acfc5d80655dbd661e88b2f4cf061e", "0xe6ce7a2b221bfd15b837217189d4db6a58772308", "0xb011391cc16d58e62d18aaa0992f2bcd75d3cc91",
 "0x5a93a5e5b754898f06f7a0f4abac419547600b25", "0x7c768ba34ab0c2317ba594b2ca34c32c05601247", "0x57b50d7bfc8610b2c960efceb6c070646c189725", "0xa24cf1ceb97ae5371806bb1ba3ee428c1b992fd4",
 "0x703b1015f4192f84b4db590c11b780e0a6625c6b", "0x7b319a6a153a5a073d0bc72b8a5912daa2fd187b", "0x6439a93f4eac29907e77929ec496c45838b7c4e6", "0xfffcfcbe529502bd4652a18e1ca3a01fbe316c5e",
 "0x706ffe280b3ab30719212a8b6f4a1b2ac00f0862", "0x5e818b60649234ed92f8974767401d16cf1b2d72", "0x9e05b78ea853a4b093694645561c4bfc953a6f62", "0xfc8e3d78ce79123cda17dc51bf541f928b6ab1fe",
 "0xed92b9103e9413d954d5b62b282a9ab01c9330e2", "0xd03a981e30b2a41107d241948428e0124dde05f7", "0xc8c87503ac7a98238ee034fc6429dc960e1fa4e3", "0xb0336ad0aea94b186359feba35da4f422d9e0830",
 "0xb8e15e32a693ac872ec5385e749a06770bc95337", "0x44106f9fabd3874688fc017931d1f7eb6e349a34", "0xc73ce6ea79cc86cc720303ecf2fa5af8df99fe87", "0xc6b669d0e31c2fe88e2a605a876463c2dfeb8a1f",
 "0x977dd358b3b7a52847d1e1e133bb83eef4fe6239", "0x96da5da2cb3b97212c1c9faadc8c4e855bade9b2", "0xf9c5bcc542122cfb4e8ee467ec1538ca6d358e14", "0x81935c566632f44df25b1545352e20ab81ee0ce2",
 "0x5cdbd5a01fafc8525d1d4e0808166fe2ec1eb44c", "0x4503eedbc91cf8a24009e02e6b98b58fa34f1451", "0x43e523e4e506182fb3adef09e3de76f2f0dab1b4", "0xf025f2ddb226684ab66df9fdf3928d053a237dce", `

**Comment by andrevmatos** [comment]
@dopetard can you, please, test adding `--jsonrpc-cors=all` option to parity command line? I'm pretty sure this has to do with parity not adding CORS by default, even with `--unsafe-expose` set.

**Comment by dopetard** [comment]
@andrevmatos I added the `--jsonrpc-cors=all` flag. It didn't change anything. Then I added `unsafe-expose ui` tag as well and restarted raiden, refreshed UI, It gave 500 error on UI and then weirdly loaded the 69 tokens from aforementioned list in UI.

Here's the stacktrace 

`ERROR:raiden.api.rest   [2018-02-15 02:11:54,480] ERROR in app: Exception on /api/1/events/network [GET] 
Traceback (most recent call last):
  File "/home/exchangeunion6/raidennode1/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/exchangeunion6/raidennode1/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/exchangeunion6/raidennode1/lib/python3.5/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/exchangeunion6/raidennode1/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/exchangeunion6/raidennode1/lib/python3.5/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/exchangeunion6/raidennode1/lib/python3.5/site-packages/webargs/core.py", line 441, in wrapper
    return func(*args, **kwargs)
  File "/home/exchangeunion6/raiden/raiden/api/v1/resources.py", line 89, in get
    to_block=to_block,
  File "/home/exchangeunion6/raiden/raiden/api/rest.py", line 440, in get_network_events
    return api_response(result=normalize_events_list(raiden_service_result))
  File "/home/exchangeunion6/raiden/raiden/api/rest.py", line 102, in api_response
    data = json.dumps(result)
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'TokenAdded' is not JSON serializable 
ERROR:raiden.api.rest    
INFO:raiden.api.rest    45.77.42.113 - - [2018-02-15 02:11:54] "GET /api/1/events/network?from_block=1603031&to_block=2653891 HTTP/1.1" 500 164 0.147621 `

I still cannot see my own token that I registered earlier `0xe6ce7a2b221bFd15b837217189D4db6a58772308`

**Comment by andrevmatos** [comment]
Great. This one is a different error. The Parity error was actually about something related to CORS, and was solved with that option. This 500 error you're seeing is on events fetching, not tokens, and should be solved by #1221 . We should add Parity specific instructions soon to the documentation. I'll leave it open if @LefterisJP wants any other info. It may be closed after it.
