### ISSUE TITLE
set used in find_new_partners function maybe not right

### ISSUE THREAD

**Issue by lijinchao** [raiden-network/raiden#1359]
## Problem Definition
when i connect one token network , it 's awalys failed because of "AttributeError: 'NoneType' object has no attribute 'add'"

### System Description
 Raiden:  version 0.3.0+git.r34fd1e7d!

_all raidens connect my private network , **not testnet!**_

```
solc, the solidity compiler commandline interface
Version: 0.4.22-develop.2018.4.3+commit.be261ed5.Linux.g++

Geth
Version: 1.8.0-unstable
Git Commit: 8092106abc06bb8c0435fabdd5cbd6f258abb8cf
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
Operating System: linux


/usr/bin/raiden
{
  "raiden": "0.3.0+git.r34fd1e7d",
  "python_implementation": "CPython",
  "python_version": "3.6.3",
  "system": "Linux 64bit_ELF 3.10.0-229.el7.x86_64 x86_64"
}

34fd1e7dc252bb74d189bd7f0053487ff491f336
```

```python3
 known = set(channel_state.partner_address for channel_state in open_channels)
 known = known.add(self.BOOTSTRAP_ADDR)
 known = known.add(self.raiden.address)
```
Python3 Sets data structure  method "add" return none, not Sets ;  so the seoncd "assign" is NoneType.

**Comment by LefterisJP** [comment]
Can you please use the issue template and give us all info on your system?

```
uname -a
command -v solc && solc --version
command -v geth && geth version
command -v parity && parity --version
command -v raiden && raiden version
[ -d .git ] && git rev-parse HEAD
```

Also please provide what you tried, how you ran Raiden and the entire exception stack trace.

**Comment by lijinchao** [comment]
Have update it !

```
curl -v -X PUT -H"Content-Type: application/json" -d'{"funds":1000}' http://localhost:5002/api/1/connections/0x6cfcfa8a13c9da7596c0898fc8cb6dcceed3e4ab
```
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib64/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/webargs/core.py", line 441, in wrapper
    return func(*args, **kwargs)
  File "/home/lijinchao-d/raiden/raiden/api/v1/resources.py", line 151, in put
    joinable_funds_target=joinable_funds_target,
  File "/home/lijinchao-d/raiden/raiden/api/rest.py", line 394, in connect
    joinable_funds_target
  File "/home/lijinchao-d/raiden/raiden/api/python.py", line 122, in token_network_connect
    joinable_funds_target=joinable_funds_target
  File "/home/lijinchao-d/raiden/raiden/connection_manager.py", line 116, in connect
    self._open_channels()
  File "/home/lijinchao-d/raiden/raiden/connection_manager.py", line 282, in _open_channels
    for partner in self.find_new_partners(qty_channels_to_open):
  File "/home/lijinchao-d/raiden/raiden/connection_manager.py", line 248, in find_new_partners
    known = known.add(self.raiden.address)
AttributeError: 'NoneType' object has no attribute 'add' 
```

**Comment by LefterisJP** [comment]
Thank you for the updated info @lijinchao. Let us have a look and will come back to you.
