### ISSUE TITLE
'NettingChannelState' object has no attribute 'partner_address

### ISSUE THREAD

**Issue by lijinchao** [raiden-network/raiden#1361]
## Problem Definition
```
 curl -v -X PUT -H"Content-Type: application/json" -d'{"funds":1000}' http://localhost:5002/api/1/connections/0x6cfcfa8a13c9da7596c0898fc8cb6dcceed3e4ab
```
when i used this request, I get the following traceback!

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/lijinchao-d/raiden/raiden/connection_manager.py", line 229, in retry_connect
    self._open_channels()
  File "/home/lijinchao-d/raiden/raiden/connection_manager.py", line 282, in _open_channels
    for partner in self.find_new_partners(qty_channels_to_open):
  File "/home/lijinchao-d/raiden/raiden/connection_manager.py", line 245, in find_new_partners
    known = set(channel_state.partner_address for channel_state in open_channels)
  File "/home/lijinchao-d/raiden/raiden/connection_manager.py", line 245, in <genexpr>
    known = set(channel_state.partner_address for channel_state in open_channels)
AttributeError: 'NettingChannelState' object has no attribute 'partner_address'
Tue Apr 17 16:01:38 2018 <Greenlet at 0x7f00da35d508: <bound method ConnectionManager.retry_connect of <raiden.connection_manager.ConnectionManager object at 0x7f00dcbe7a90>>> failed with AttributeError
```

### System Description
 Raiden:  version 0.3.0+git.r34fd1e7d!

_all raidens connect my private network , **not testnet!**_

```
solc, the solidity compiler commandline interface
Version: 0.4.22-develop.2018.4.3+commit.be261ed5.Linux.g++

Geth
Version: 1.8.0-unstable
Git Commit: 8092106abc06bb8c0435fabdd5cbd6f258abb8cf
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
Operating System: linux


/usr/bin/raiden
{
  "raiden": "0.3.0+git.r34fd1e7d",
  "python_implementation": "CPython",
  "python_version": "3.6.3",
  "system": "Linux 64bit_ELF 3.10.0-229.el7.x86_64 x86_64"
}

34fd1e7dc252bb74d189bd7f0053487ff491f336
```
### code where causes the  prolem 
```python3
known = set(channel_state.partner_address for channel_state in open_channels)
```
### NettingChannelState definition
https://github.com/raiden-network/raiden/blob/1f17a15c518a4af65f03c015cf13c63ef755150d/raiden/transfer/state.py#L770

I found there are no partner_address attribute

```

**Comment by LefterisJP** [comment]
Thank you for the detailed report @lijinchao. I will handle this. 

Please note we are in the middle of a refactoring so things like that may happen when you use bleeding edge `master` branch.
