### ISSUE TITLE
Fix the last failing tests for the Matrix PR

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1429]
## Problem Definition

Two tests were failing in the [matrix PR](https://github.com/raiden-network/raiden/pull/1373). 

- integration/transfer/test_refund_transfer.py::test_refund_messages
- integration/transfer/test_refund_transfer.py::test_refund_transfer

Fix them

**Comment by LefterisJP** [comment]
So tests fixed, but `test_refund_transfer` has an unclean shutdown of its state machine. Stack Trace follows:

```
2018-05-30 16:17:11 [info     ] Client reconnected                                                                                                                                                                                                                                                                                                                         
2018-05-30 16:17:15 [info     ] Deploying registry contract                                                                                                                                                                                                                                                                                                                
2018-05-30 16:17:21 [info     ] Deploying contract:            path=HumanStandardToken.sol                                                                                                                                                                                                                                                                                 
2018-05-30 16:17:23 [info     ] add_token called               node=61aa4ae5 registry_address=4773705f token_address=f4d9a6db                                                                                                                                                                                                                                              
2018-05-30 16:17:25 [info     ] add_token sucessful            manager_address=53a4de68 node=61aa4ae5 registry_address=4773705f token_address=f4d9a6db                                                                                                                                                                                                                     
2018-05-30 16:17:31 [info     ] Deploying contract:            path=EndpointRegistry.sol                                                                                                                                                                                                                                                                                   
2018-05-30 16:17:35 [info     ] registered endpoint in discovery host=127.0.0.1 node_address=4a62ecca port=29872                                                                                                                                                                                                                                                           
2018-05-30 16:17:35 [info     ] endpoint already registered    host=127.0.0.1 node_address=4a62ecca port=29872                                                                                                                                                                                                                                                             
2018-05-30 16:17:37 [info     ] registered endpoint in discovery host=127.0.0.1 node_address=6e2cc640 port=29873                                                                                                                                                                                                                                                           
2018-05-30 16:17:37 [info     ] endpoint already registered    host=127.0.0.1 node_address=6e2cc640 port=29873                                                                                                                                                                                                                                                             
2018-05-30 16:17:39 [info     ] registered endpoint in discovery host=127.0.0.1 node_address=fcfd1f55 port=29874                                                                                                                                                                                                                                                           
2018-05-30 16:17:39 [info     ] endpoint already registered    host=127.0.0.1 node_address=fcfd1f55 port=29874                                                                                                                                                                                                                                                             
2018-05-30 16:17:41 [info     ] new_netting_channel called     netting_channel=46349e3c peer1=4a62ecca peer2=6e2cc640                                                                                                                                                                                                                                                      
2018-05-30 16:17:42 [info     ] new_netting_channel called     netting_channel=55d4440d peer1=6e2cc640 peer2=fcfd1f55                                                                                                                                                                                                                                                      
2018-05-30 16:17:43 [info     ] deposit called                 amount=200 contract=46349e3c node=4a62ecca                                                                                                                                                                                                                                                                  
2018-05-30 16:17:44 [info     ] deposit called                 amount=200 contract=55d4440d node=6e2cc640                                                                                                                                                                                                                                                                  
2018-05-30 16:17:45 [info     ] deposit successful             amount=200 contract=46349e3c node=4a62ecca                                                                                                                                                                                                                                                                  
2018-05-30 16:17:46 [info     ] deposit successful             amount=200 contract=55d4440d node=6e2cc640                                                                                                                                                                                                                                                                  
2018-05-30 16:17:47 [info     ] deposit called                 amount=200 contract=46349e3c node=6e2cc640                                                                                                                                                                                                                                                                  
2018-05-30 16:17:48 [info     ] deposit called                 amount=200 contract=55d4440d node=fcfd1f55                                                                                                                                                                                                                                                                  
2018-05-30 16:17:49 [info     ] deposit successful             amount=200 contract=46349e3c node=6e2cc640                                                                                                                                                                                                                                                                  
2018-05-30 16:17:50 [info     ] deposit successful             amount=200 contract=55d4440d node=fcfd1f55                                                                                                                                                                                                                                                                  
2018-05-30 16:17:56 [warning  ] No routes available from 4a62ecca to fcfd1f55                                                                                                                                                                                                                                                                                              
2018-05-30 16:17:56 [warning  ] No routes available from 6e2cc640 to fcfd1f55                                                                                                                                                                                                                                                                                              
2018-05-30 16:17:57 [warning  ] No routes available from 4a62ecca to fcfd1f55                                                                                                                                                                                                                                                                                              
2018-05-30 16:17:57 [warning  ] No routes available from 6e2cc640 to fcfd1f55                                                                                                                                                                                                                                                                                              
2018-05-30 16:17:57 [info     ] channel 6e2cc640 - fcfd1f55 doesnt have enough funds [50], ignoring                                                                                                                                                                                                                                                                        
2018-05-30 16:17:57 [warning  ] No routes available from 4a62ecca to fcfd1f55                                                                                                                                                                                                                                                                                              
2018-05-30 16:17:57 [error    ] UnlockFailed!                  reason=route was canceled secrethash=f14c951c                                                                                                                                                                                                                                                               
2018-05-30 16:17:57 [exception] unexpected exception on alarm                                                                                                                                                                                                                                                                                                              
Traceback (most recent call last):
  File "/home/lefteris/ew/raiden/raiden/tasks.py", line 97, in poll_for_new_block
    result = callback(current_block)
  File "/home/lefteris/ew/raiden/raiden/raiden_service.py", line 355, in set_block_number
    self.handle_state_change(state_change, block_number)
  File "/home/lefteris/ew/raiden/raiden/raiden_service.py", line 367, in handle_state_change
    event_list = self.wal.log_and_dispatch(state_change, block_number)
  File "/home/lefteris/ew/raiden/raiden/storage/wal.py", line 52, in log_and_dispatch
    events = self.state_manager.dispatch(state_change)
  File "/home/lefteris/ew/raiden/raiden/transfer/architecture.py", line 134, in dispatch
    state_change,
  File "/home/lefteris/ew/raiden/raiden/transfer/node.py", line 642, in state_transition
    state_change,
  File "/home/lefteris/ew/raiden/raiden/transfer/node.py", line 382, in handle_block
    state_change,
  File "/home/lefteris/ew/raiden/raiden/transfer/node.py", line 98, in subdispatch_to_all_lockedtransfers
    result = subdispatch_to_paymenttask(node_state, state_change, secrethash)
  File "/home/lefteris/ew/raiden/raiden/transfer/node.py", line 128, in subdispatch_to_paymenttask
    block_number,
  File "/home/lefteris/ew/raiden/raiden/transfer/mediated_transfer/initiator_manager.py", line 315, in state_transition
    sanity_check(iteration.new_state)
  File "/home/lefteris/ew/raiden/raiden/transfer/mediated_transfer/initiator_manager.py", line 58, in sanity_check
    ), 'either the task must be finished or there must be an initiator transfer pending'
AssertionError: either the task must be finished or there must be an initiator transfer pending
PASSED                                                                                                                                                                                                                                  [100%]
===Flaky Test Report===
```
