### ISSUE TITLE
Logging-related exception printed in smoketest

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#1436]
When running the smoketest there is a non-fatal exception printed. This should be fixed.

```
[1/5] getting smoketest configuration
[2/5] starting ethereum
[3/5] starting raiden
You are connected to the 'smoketest' network and the DB path is: /var/folders/gz/0f_3f9k96gd1hblwgd1r8h280000gn/T/tmpely5vxih/keystore/netid_627/0x67a5e2/log.db
[4/5] running smoketests...
Traceback (most recent call last):
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/gevent/pywsgi.py", line 1482, in handle
    handler.handle()
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/gevent/pywsgi.py", line 454, in handle
    result = self.handle_one_request()
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/gevent/pywsgi.py", line 671, in handle_one_request
    self.handle_one_response()
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/gevent/pywsgi.py", line 964, in handle_one_response
    self.log_request()
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/gevent/pywsgi.py", line 871, in log_request
    self.server.log.write(self.format_request() + '\n')
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/structlog/_base.py", line 177, in _proxy_to_logger
    return getattr(self._logger, method_name)(*args, **kw)
AttributeError: '_FixedFindCallerLogger' object has no attribute 'write'
Mon May 28 11:15:25 2018 <Greenlet at 0x10fe5de88: _handle_and_close_when_done(<bound method WSGIServer.handle of <WSGIServer at , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed with AttributeError

[5/5] smoketest successful, report was written to /var/folders/gz/0f_3f9k96gd1hblwgd1r8h280000gn/T/tmpdvkkg5pd.log
```

**Comment by pcppcp** [comment]
a wrapper for the log object is required - I'll look into it.

**Comment by pcppcp** [comment]
PR #1442 fixes that
