### ISSUE TITLE
Mysterious Error: 401 Unrecognised Access Token

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/raiden#1573]
## Problem Definition

When running tests with matrix enabled, the test sometimes aborts with a 401 error exception.
This error is usually returned by the synapse server if client attempts to use invalid `access_token`.

From examination of the test logs it seems like the Matrix client used by raiden uses a token that belongs to other raiden app (!). This is related to logouts during the test teardown.

excerpt from the testrun. You can find complete log on a link below
https://travis-ci.org/pcppcp/raiden/jobs/392745502

`2018-06-15 14:45:35,938 - synapse.storage.SQL - 107 - DEBUG - POST-1 - [SQL values] {add_access_token_to_user-18} (u'MDAyMWxvY2F0aW9uIG1hdHJpeC5sb2NhbC5yYWlkZW4KMDAxM2lkZW50aWZpZXIga
 2V5CjAwMTBjaWQgZ2VuID0gMQowMDUyY2lkIHVzZXJfaWQgPSBAMHg2OWU2MjE5NzFlYmM0N2M0ZjZmNWU5YmNhNmEwMjQ5NjRjNWQ2YzVjOm1hdHJpeC5sb2NhbC5yYWlkZW4KMDAxNmNpZCB0eXBlID0gYWNjZXNzCjAwMjFjaWQgbm9uY2UgPSBeQVlHPWFwVXJTcTlvSHYsCjAwMmZzaWduYXR1cmUg3WjRzssNq9PWiV1Q5MMaiZR_Ire1TxqrQKY-AIeYyqcK', '@0x69e621971ebc47c4f6f5e9bca6a024964c5d6c5c:matrix.local.raiden', 3, 'MYSCMLBLCP')`
an user (`0x69..5c` logs in and the token is stored in the database)

... test runs until the teardown...

`2018-06-15 14:46:07,504 - synapse.storage.SQL - 107 - DEBUG - POST-154 - [SQL values] {delete_device-3d7} [u'@0x69e621971ebc47c4f6f5e9bca6a024964c5d6c5c:matrix.local.raiden', u'MYSCMLBLCP']`
Raiden app logouts. The access token is deleted from the DB.

```
2018-06-15 14:46:07,565 - synapse.access.http.8008 - 97 - INFO - POST-157 - ::ffff:127.0.0.1 - 8008 - Received request: POST /_matrix/client/r0/publicRooms?access_token=<redacted>
2018-06-15 14:46:07,567 - synapse.storage.SQL - 107 - DEBUG - POST-157 - [SQL values] {get_user_by_access_token-3dc} ('MDAyMWxvY2F0aW9uIG1hdHJpeC5sb2NhbC5yYWlkZW4KMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDUyY2lkIHVzZXJfaWQgPSBAMHg2OWU2MjE5NzFlYmM0N2M0ZjZmNWU5YmNhNmEwMjQ5NjRjNWQ2YzVjOm1hdHJpeC5sb2NhbC5yYWlkZW4KMDAxNmNpZCB0eXBlID0gYWNjZXNzCjAwMjFjaWQgbm9uY2UgPSBeQVlHPWFwVXJTcTlvSHYsCjAwMmZzaWduYXR1cmUg3WjRzssNq9PWiV1Q5MMaiZR_Ire1TxqrQKY-AIeYyqcK',)
2018-06-15 14:46:07,567 - synapse.api.auth - 491 - WARNING - POST-157 - Unrecognised access token - not in store: MDAyMWxvY2F0aW9uIG1hdHJpeC5sb2NhbC5yYWlkZW4KMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDUyY2lkIHVzZXJfaWQgPSBAMHg2OWU2MjE5NzFlYmM0N2M0ZjZmNWU5YmNhNmEwMjQ5NjRjNWQ2YzVjOm1hdHJpeC5sb2NhbC5yYWlkZW4KMDAxNmNpZCB0eXBlID0gYWNjZXNzCjAwMjFjaWQgbm9uY2UgPSBeQVlHPWFwVXJTcTlvSHYsCjAwMmZzaWduYXR1cmUg3WjRzssNq9PWiV1Q5MMaiZR_Ire1TxqrQKY-AIeYyqcK
2018-06-15 14:46:07,568 - synapse.http.server - 84 - INFO - POST-157 - <SynapseRequest at 0x7fd4857af7e8 method='POST' uri='/_matrix/client/r0/publicRooms?access_token=<redacted>' clientproto='HTTP/1.1' site=8008> SynapseError: 401 - Unrecognised access token.
2018-06-15 14:46:07,569 - synapse.access.http.8008 - 131 - INFO - POST-157 - ::ffff:127.0.0.1 - 8008 - {None} Processed request: 0.004sec (0.004sec, 0.000sec) (0.000sec/0.001sec/1) 82B 401 "POST /_matrix/client/r0/publicRooms?access_token=<redacted> HTTP/1.1" "python-requests/2.19.1"
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/travis/build/pcppcp/raiden/raiden/network/matrixtransport.py", line 535, in _get_room_for_address
    room_candidates = self._client.search_room_directory(room_name)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/raiden_libs/network/matrix/client.py", line 127, in search_room_directory
    **filter_options
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/matrix_client/api.py", line 685, in _send
    code=response.status_code, content=response.text
matrix_client.errors.MatrixRequestError: 401: {"errcode":"M_UNKNOWN_TOKEN","error":"Unrecognised access token."}
2018-06-15T14:46:07Z <Greenlet "Greenlet-0" at 0x7f8c209b9748: <bound method MatrixTransport._get_room_for_address of <raiden.network.matrixtransport.MatrixTransport object at 0x7f8c20c894e0>>(b'\xf4\xc5\xa0\x95&\x17\x16\xde\xc9\xcfS\xc6\x9e\x, allow_missing_peers=True)> failed with MatrixRequestError
```
As seen in the traceback, client that called this POST request  is `b'\xf4\xc5\xa0\x95&\x17\x16\xde\xc9\xcfS\xc6\x9e\x`, but token that belongs to `0x69..` was used

`2018-06-15 14:45:42,262 - synapse.storage.SQL - 107 - DEBUG - POST-28 - [SQL values] {add_access_token_to_user-117} (u'MDAyMWxvY2F0aW9uIG1hdHJpeC5sb2NhbC5yYWlkZW4KMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDUyY2lkIHVzZXJfaWQgPSBAMHhmNGM1YTA5NTI2MTcxNmRlYzljZjUzYzY5ZTEzZDg2NjI2ODg3YjEzOm1hdHJpeC5sb2NhbC5yYWlkZW4KMDAxNmNpZCB0eXBlID0gYWNjZXNzCjAwMjFjaWQgbm9uY2UgPSBvV3F1U0thXkteLmhGd21-CjAwMmZzaWduYXR1cmUgsRjrkZarP3Umj632WGAKy65WO4QOKUOgTNTyXwHxe0AK', '@0xf4c5a095261716dec9cf53c69e13d86626887b13:matrix.local.raiden', 7, 'YYSWMYCUNK')`
this is token that 0xf4c5.. should've used

**Comment by pcppcp** [comment]
probably caused by a dictionary instance being used as default argument in `matrix_client`. The fix has already been merged to `master` branch of `matrix_client`.

https://github.com/matrix-org/matrix-python-sdk/pull/236

@ulope @jomuel @andrevmatos 
Feel free to try if the fix makes the skipped tests introduced in #1528 work again

**Comment by andrevmatos** [comment]
@pcppcp I can confirm the fix worked for matrix also in the skipped tests. Working on unskipping them. Thank you!

**Comment by pcppcp** [comment]
Fixed by
https://github.com/raiden-network/raiden-libs/pull/93

The tests should be un-skipped:
https://github.com/raiden-network/raiden/issues/1575
