### ISSUE TITLE
Refund transfer needs to also be handled by the mediator

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden#1627]
WIP issue, maybe @hackaugusto can give more details.

**Comment by andrevmatos** [comment]
We've been hitting this error:
```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/travis/build/raiden-network/raiden/raiden/network/matrixtransport.py", line 440, in _handle_message
    self._receive_message(message)
  File "/home/travis/build/raiden-network/raiden/raiden/network/matrixtransport.py", line 483, in _receive_message
    if on_udp_message(self._raiden_service, message):
  File "/home/travis/build/raiden-network/raiden/raiden/udp_message_handler.py", line 138, in on_udp_message
    handle_message_refundtransfer(raiden, message)
  File "/home/travis/build/raiden-network/raiden/raiden/udp_message_handler.py", line 97, in handle_message_refundtransfer
    raiden.handle_state_change(state_change)
  File "/home/travis/build/raiden-network/raiden/raiden/raiden_service.py", line 346, in handle_state_change
    event_list = self.wal.log_and_dispatch(state_change, block_number)
  File "/home/travis/build/raiden-network/raiden/raiden/storage/wal.py", line 55, in log_and_dispatch
    events = self.state_manager.dispatch(state_change)
  File "/home/travis/build/raiden-network/raiden/raiden/transfer/architecture.py", line 134, in dispatch
    state_change,
  File "/home/travis/build/raiden-network/raiden/raiden/transfer/node.py", line 748, in state_transition
    state_change,
  File "/home/travis/build/raiden-network/raiden/raiden/transfer/node.py", line 591, in handle_receive_transfer_refund
    state_change.transfer.lock.secrethash,
  File "/home/travis/build/raiden-network/raiden/raiden/transfer/node.py", line 143, in subdispatch_to_paymenttask
    block_number,
  File "/home/travis/build/raiden-network/raiden/raiden/transfer/mediated_transfer/mediator.py", line 1258, in state_transition
    block_number,
  File "/home/travis/build/raiden-network/raiden/raiden/transfer/mediated_transfer/mediator.py", line 1057, in handle_refundtransfer
    mediator_state_change.routes,
AttributeError: 'ReceiveTransferRefund' object has no attribute 'routes'
2018-06-22T08:57:18Z <Greenlet "Greenlet-0" at 0x7fbe9d5df848: <bound method MatrixTransport._handle_message of <raiden.network.matrixtransport.MatrixTransport object at 0x7fbe9d76e7f0>>(<Room id="!CqUXOnzaibhgutDoSm:matrix.local.raiden", {'origin_server_ts': 1529657837813, 'sender': '@0x)> failed with AttributeError
```

**Comment by LefterisJP** [comment]
@andrevmatos That's a nice catch. I looked into our code and indeed that's incorrect and rather funny the tests have not caught it. I am looking into it [here](https://github.com/raiden-network/raiden/pull/1653) but I am not sure if this is the issue @hackaugusto had in mind.

**Comment by LefterisJP** [comment]
Confirmed with @hackaugusto that the issue I am solving in #1653 is what he was talking with @loredanacirstea about.
