### ISSUE TITLE
No _bound_logger in matrix transport

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#1761]
## Problem Definition

When running Raiden with `--transport matrix` I get the following traceback:

```
raiden --keystore-path ~/Library/Ethereum/testnet/keystore --address=0xDf173a5173C3d0Ae5Ba11DAE84470c5d3f1A8123 --network-id ropsten --no-sync-check
Welcome to Raiden, version 0.3.1.dev890+gffa115f0!
WARNING: The Matrix transport is experimental
You are connected to the 'ropsten' network and the DB path is: /Users/paul/.raiden/netid_3/0xdf173a/log.db
Traceback (most recent call last):
  File "/Users/paul/Work/venv-raiden/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/Users/paul/Work/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/paul/Work/raiden/raiden/ui/cli.py", line 941, in run
    app_ = _run_app()
  File "/Users/paul/Work/raiden/raiden/ui/cli.py", line 861, in _run_app
    app_ = ctx.invoke(app, **kwargs)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/paul/Work/raiden/raiden/ui/cli.py", line 679, in app
    transport = MatrixTransport(config['matrix'])
  File "/Users/paul/Work/raiden/raiden/network/transport/matrix.py", line 127, in __init__
    self._server_url: str = self._select_server(config)
  File "/Users/paul/Work/raiden/raiden/network/transport/matrix.py", line 795, in _select_server
    self.log.debug('Matrix homeserver RTT times', rtt_times=sorted_servers)
  File "/Users/paul/Work/raiden/raiden/network/transport/matrix.py", line 265, in log
    if self._bound_logger:
AttributeError: 'MatrixTransport' object has no attribute '_bound_logger'
```

**Comment by palango** [comment]
Now I get:
```
Traceback (most recent call last):
  File "/Users/paul/Work/venv-raiden/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/Users/paul/Work/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/paul/Work/raiden/raiden/ui/cli.py", line 941, in run
    app_ = _run_app()
  File "/Users/paul/Work/raiden/raiden/ui/cli.py", line 861, in _run_app
    app_ = ctx.invoke(app, **kwargs)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/paul/Work/raiden/raiden/ui/cli.py", line 679, in app
    transport = MatrixTransport(config['matrix'])
  File "/Users/paul/Work/raiden/raiden/network/transport/matrix.py", line 128, in __init__
    self._server_url: str = self._select_server(config)
  File "/Users/paul/Work/raiden/raiden/network/transport/matrix.py", line 795, in _select_server
    self.log.debug('Matrix homeserver RTT times', rtt_times=sorted_servers)
  File "/Users/paul/Work/raiden/raiden/network/transport/matrix.py", line 267, in log
    if not getattr(self._client, 'user_id', None):
AttributeError: 'MatrixTransport' object has no attribute '_client'
```

**Comment by andrevmatos** [comment]
@palango this issue is called because of the server selector being called early in init (before some expected variables were set). It wasn't triggered because a specific server is used on tests, instead of selecting one of the availables.
