### ISSUE TITLE
Traceback for web3.net_version at raiden start

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1779]
Getting this traceback when trying to run raiden. Apparently only happens at my machine.

Geth is 1.8.11

```
Welcome to Raiden, version 0.3.1.dev894+ga098658f!
..
..
..,

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lefteris/ew/raiden/raiden/__main__.py", line 15, in <module>
    main()
  File "/home/lefteris/ew/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/lefteris/ew/raiden/raiden/ui/cli.py", line 950, in run
    app_ = _run_app()
  File "/home/lefteris/ew/raiden/raiden/ui/cli.py", line 870, in _run_app
    app_ = ctx.invoke(app, **kwargs)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/lefteris/ew/raiden/raiden/ui/cli.py", line 603, in app
    net_id = blockchain_service.network_id
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/cachetools/func.py", line 58, in wrapper
    v = func(*args, **kwargs)
  File "/home/lefteris/ew/raiden/raiden/network/blockchain_service.py", line 190, in network_id
    return int(self.client.web3.version.network)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/web3/version.py", line 18, in network
    return self.web3.manager.request_blocking("net_version", [])
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/web3/manager.py", line 110, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32601, 'message': 'The method net_version does not exist/is not available'}
```

**Comment by LefterisJP** [comment]
Okay this was easy. We just need to also add the `net` rpc api now when we start geth.

So `--rpcapi eth,net,web3,admin,debug console` should do it
