### ISSUE TITLE
Raiden crashes after some time running

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden#1785]
## Problem Definition

[Using webUI](https://github.com/andrevmatos/raiden/commit/feef5ac6710367d1af4e383f20ace61def1642d5) (rebased on current master 66cd4c1c7f05c4d244ed47e501a58ac025b9311d), after some minutes running, the Raiden app crashes with following traceback.
This happened multiple times (maybe related to webUI polling for events), but can't find the exact cause.
Using `parity v.1.10.8`.

```
2018-07-11 18:12:09 [debug    ] new block                      [raiden.tasks] number=3617465
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/app/raiden/raiden/tasks.py", line 56, in _run
    self.poll_for_new_block()
  File "/app/raiden/raiden/tasks.py", line 95, in poll_for_new_block
    result = callback(current_block, chain_id)
  File "/app/raiden/raiden/raiden_service.py", line 373, in _callback_new_block
    for event in self.blockchain_events.poll_blockchain_events():
  File "/app/raiden/raiden/blockchain/events.py", line 324, in poll_blockchain_events
    for log_event in getattr(event_listener.filter, query_fn)():
  File "/usr/local/lib/python3.6/dist-packages/web3/utils/filters.py", line 105, in get_new_entries
    log_entries = self._filter_valid_entries(self.web3.eth.getFilterChanges(self.filter_id))
  File "/usr/local/lib/python3.6/dist-packages/web3/eth.py", line 344, in getFilterChanges
    "eth_getFilterChanges", [filter_id],
  File "/usr/local/lib/python3.6/dist-packages/web3/manager.py", line 110, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'Filter not found'}
2018-07-11T18:12:09Z <AlarmTask "Greenlet-0" at 0x7f2e30586148: _run> failed with ValueError

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/raiden/raiden/__main__.py", line 15, in <module>
    main()
  File "/app/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/raiden/raiden/ui/cli.py", line 951, in run
    app_ = _run_app()
  File "/app/raiden/raiden/ui/cli.py", line 924, in _run_app
    event.wait()
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
ValueError: {'code': -32000, 'message': 'Filter not found'}
docker_raiden_raiden_1 exited with code 1
```

**Comment by LefterisJP** [comment]
Can you also try with geth? We have had problems with parity events historically.

**Comment by andrevmatos** [comment]
I'm not sure if I've enough disk space to keep both blockchains, but I'll try. Anyway, we should look into handling that exception and re-registering the filter

**Comment by palango** [comment]
I've also got bitten by this.

**Comment by rakanalh** [comment]
In all 3 times i witnessed this exception, i noticed that the alarm triggered for missed blocks. Last time it was 17 blocks. Would that count as a pattern?

**Comment by andrevmatos** [comment]
I think somehow the node's view of the network is lagging behind sometimes, which makes the new blocks not being triggered for more than 60s (as per [this comment](https://github.com/paritytech/parity/issues/9122#issuecomment-405048839)), which then makes the filter timeout.
I'm working in another workaround as the comment above for raiden, making it poll for the filters each N seconds (initially 20s) **even** if no new blocks came. This should at least ensure the filters doesn't expire in these network hangs.

**Comment by andrevmatos** [comment]
@rakanalh iow: the missing blocks is another side effect of the issue which is causing the filters to expire.
