### ISSUE TITLE
Raiden crashed due to MatrixRequestError: 504 Timed out

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1790]
While testing it has only happened once so far. But without doing anything special Raiden just crashed with the following trace:

```
Checking if the ethereum node is synchronized
You are connected to the 'ropsten' network and the DB path is: /home/lefteris/.raiden/netid_3/25511699/log.db
2018-07-12 12:47:09 [info     ] Automatically selecting matrix homeserver based on RTT [raiden.network.transport.matrix] homeserver=https://transport01.raiden.network rtt=0.027562666666666666                                                                                 
2018-07-12 12:47:09 [info     ] Lock 139654262841016 acquired on /home/lefteris/.raiden/netid_3/25511699/.lock [filelock]
2018-07-12 12:47:10 [info     ] REGISTER                       [raiden.network.transport.matrix] current_user=@0x25511699c252eea2678266857c98f459df97b77c:transport01.raiden.network homeserver=transport01.raiden.network server_url=https://transport01.raiden.network username=0x25511699c252eea2678266857c98f459df97b77c
2018-07-12 12:47:10 [warning  ] Member of a room we're not supposed to be a member of - ignoring [raiden.network.transport.matrix] current_user=@0x25511699c252eea2678266857c98f459df97b77c:transport01.raiden.network discovery=#raiden_ropsten_discovery:transport01.raiden.network room=<Room id="!fqQVZEXgokgQhcYpMI:transport01.raiden.network" alias="#test:transport01.raiden.network">
2018-07-12 12:47:10 [info     ] TRANSPORT STARTED              [raiden.network.transport.matrix] current_user=@0x25511699c252eea2678266857c98f459df97b77c:transport01.raiden.network                                                                                            
The Raiden API RPC server is now running at http://127.0.0.1:5001/.

See the Raiden documentation for all available endpoints at
http://raiden-network.readthedocs.io/en/stable/rest_api.html
2018-07-12 12:47:11 [warning  ] Member of a room we're not supposed to be a member of - ignoring [raiden.network.transport.matrix] current_user=@0x25511699c252eea2678266857c98f459df97b77c:transport01.raiden.network discovery=#raiden_ropsten_discovery:transport01.raiden.network room=<Room id="!fqQVZEXgokgQhcYpMI:transport01.raiden.network" alias="#test:transport01.raiden.network">
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/lefteris/ew/raiden/raiden/network/transport/matrix.py", line 671, in _handle_presence_change
    address = self._validate_userid_signature(user)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/cachetools/__init__.py", line 87, in wrapper
    v = method(self, *args, **kwargs)
  File "/home/lefteris/ew/raiden/raiden/network/transport/matrix.py", line 846, in _validate_userid_signature
    decode_hex(user.get_display_name()),
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/matrix_client/user.py", line 36, in get_display_name
    self.displayname = self.api.get_display_name(self.user_id)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/matrix_client/api.py", line 705, in get_display_name
    content = self._send("GET", "/profile/%s/displayname" % user_id)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/matrix_client/api.py", line 691, in _send
    code=response.status_code, content=response.text
matrix_client.errors.MatrixRequestError: 504: {"errcode":"M_UNKNOWN","error":"Timed out"}
2018-07-12T12:47:25Z <Greenlet "Greenlet-0" at 0x7f03cd03ae48: <bound method MatrixTransport._handle_presence_change of <raiden.network.transport.matrix.MatrixTransport object at 0x7f03cabeacc0>>({'content': {'last_active_ago': 1890341395, 'prese)> failed with MatrixRequestError

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lefteris/ew/raiden/raiden/__main__.py", line 15, in <module>
    main()
  File "/home/lefteris/ew/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/lefteris/ew/raiden/raiden/ui/cli.py", line 951, in run
    app_ = _run_app()
  File "/home/lefteris/ew/raiden/raiden/ui/cli.py", line 924, in _run_app
    event.wait()
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
matrix_client.errors.MatrixRequestError: 504: {"errcode":"M_UNKNOWN","error":"Timed out"}
```

**Comment by ulope** [comment]
Will be tracked in #1793
