### ISSUE TITLE
Empty address in message

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#1794]
## Problem Definition

During unavailability of the matrix server the client crashed as described in #1791 

After restarting the client afterwards it crashes with the following stacktrace:
```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/Users/paul/Work/raiden/raiden/network/transport/matrix.py", line 524, in send_queue
    self.send_async('', address, _event_to_message(event, node_address))
  File "/Users/paul/Work/raiden/raiden/network/transport/matrix.py", line 223, in send_async
    receiver_address=to_normalized_address(receiver_address),
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/eth_utils/address.py", line 68, in to_normalized_address
    "Unknown format {}, attempted to normalize to {}".format(address, hex_address)
ValueError: Unknown format , attempted to normalize to 0x
2018-07-12T12:48:59Z <Greenlet "Greenlet-0" at 0x10dea9848: send_queue(b'\xfb9\x8eb\x1c\x15\xe2\xbcZ\xe6\xa5\x08\xd8\xd8\, [<SendSecretRequest msgid:4437787535096995327 paym)> failed with ValueError

Traceback (most recent call last):
  File "/Users/paul/Work/venv-raiden/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/Users/paul/Work/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/paul/Work/raiden/raiden/ui/cli.py", line 951, in run
    app_ = _run_app()
  File "/Users/paul/Work/raiden/raiden/ui/cli.py", line 871, in _run_app
    app_ = ctx.invoke(app, **kwargs)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/paul/Work/raiden/raiden/ui/cli.py", line 692, in app
    discovery,
  File "/Users/paul/Work/raiden/raiden/app.py", line 119, in __init__
    discovery,
  File "/Users/paul/Work/raiden/raiden/raiden_service.py", line 213, in __init__
    self.start()
  File "/Users/paul/Work/raiden/raiden/raiden_service.py", line 277, in start
    self.start_neighbours_healthcheck()
  File "/Users/paul/Work/raiden/raiden/raiden_service.py", line 287, in start_neighbours_healthcheck
    self.start_health_check_for(neighbour)
  File "/Users/paul/Work/raiden/raiden/raiden_service.py", line 346, in start_health_check_for
    self.transport.start_health_check(node_address)
  File "/Users/paul/Work/raiden/raiden/network/transport/matrix.py", line 209, in start_health_check
    room = self._get_room_for_address(node_address, allow_missing_peers=True)
  File "/Users/paul/Work/raiden/raiden/network/transport/matrix.py", line 601, in _get_room_for_address
    room = self._get_unlisted_room(room_name, invitees=[user.user_id for user in peers])
  File "/Users/paul/Work/raiden/raiden/network/transport/matrix.py", line 624, in _get_unlisted_room
    is_public=True,  # FIXME: debug only
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/matrix_client/client.py", line 305, in create_room
    response = self.api.create_room(alias, is_public, invitees)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/matrix_client/api.py", line 182, in create_room
    return self._send("POST", "/createRoom", content)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/matrix_client/api.py", line 670, in _send
    verify=self.validate_cert
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/paul/.pyenv/versions/3.6.5/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/Users/paul/.pyenv/versions/3.6.5/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Users/paul/.pyenv/versions/3.6.5/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/paul/.pyenv/versions/3.6.5/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/gevent/_ssl3.py", line 504, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/gevent/_ssl3.py", line 331, in read
    self._wait(self._read_event, timeout_exc=_SSLErrorReadTimeout)
  File "src/gevent/_hub_primitives.py", line 265, in gevent.__hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 266, in gevent.__hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 252, in gevent.__hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 152, in gevent.__waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
ValueError: Unknown format , attempted to normalize to 0x
```

When debugging the code in question it turns out that the `receiver_address` of a message is empty. My guess is that it got lost on its way to the WAL or is not properly serialized.
```
[1] > /Users/paul/Work/raiden/raiden/network/transport/matrix.py(224)send_async()
-> self.log.info(
(Pdb++) l
219  	        if not self._running:
220  	            return
221  	        print(receiver_address)
222  	        import pdb; pdb.set_trace()
223
224  ->	        self.log.info(
225  	            'SEND ASYNC',
226  	            receiver_address=to_normalized_address(receiver_address),
227  	            message=message,
228  	            queue_name=queue_name,
229  	        )
(Pdb++) receiver_address
''
(Pdb++) message
<SecretRequest [msgid:4437787535096995327 paymentid:42 secrethash:93b54214 amount:200 hash:8070d93b]>
```

**Comment by rakanalh** [comment]
I can consistently reproduce the issue. I'll check this.

**Comment by pcppcp** [comment]
empty string is set here:

https://github.com/raiden-network/raiden/blob/master/raiden/network/transport/matrix.py#L524
