### ISSUE TITLE
Closed channel marked as `waiting_for_close`

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#1807]
## Problem Definition

I closed a channel from the webUI. It properly initiated the closing of the channel, the transaction was send and the event can be seen in the webUI.

However, the channel still displays the status `waiting_for_close` in the webUI and the REST API.

The raiden log:
```
2018-07-13 12:36:44 [info     ] close called                   [raiden.network.proxies.token_network] additional_hash=0x balance_hash=0x node=df173a51 nonce=0 partner=fb398e62 signature=0x token_network=3c158a20
2018-07-13 12:36:49 [info     ] 127.0.0.1 - - [2018-07-13 14:36:49] "GET /api/1/channels HTTP/1.1" 200 522 0.002044 [raiden.api.rest.pywsgi]
2018-07-13 12:36:54 [info     ] 127.0.0.1 - - [2018-07-13 14:36:54] "GET /api/1/channels HTTP/1.1" 200 522 0.001711 [raiden.api.rest.pywsgi]
2018-07-13 12:36:59 [info     ] 127.0.0.1 - - [2018-07-13 14:36:59] "GET /api/1/channels HTTP/1.1" 200 522 0.002863 [raiden.api.rest.pywsgi]
2018-07-13 12:37:04 [info     ] 127.0.0.1 - - [2018-07-13 14:37:04] "GET /api/1/channels HTTP/1.1" 200 522 0.001533 [raiden.api.rest.pywsgi]
2018-07-13 12:37:09 [info     ] 127.0.0.1 - - [2018-07-13 14:37:09] "GET /api/1/channels HTTP/1.1" 200 522 0.001397 [raiden.api.rest.pywsgi]
2018-07-13 12:37:14 [info     ] 127.0.0.1 - - [2018-07-13 14:37:14] "GET /api/1/channels HTTP/1.1" 200 522 0.001957 [raiden.api.rest.pywsgi]
2018-07-13 12:37:20 [info     ] 127.0.0.1 - - [2018-07-13 14:37:20] "GET /api/1/channels HTTP/1.1" 200 522 0.001515 [raiden.api.rest.pywsgi]
2018-07-13 12:37:23 [info     ] close successful               [raiden.network.proxies.token_network] additional_hash=0x balance_hash=0x node=df173a51 nonce=0 partner=fb398e62 signature=0x token_network=3c158a20
```

the channel endpoint returning the wrong status:
```
curl http://localhost:5001/api/1/channels                                                   14:41:14
[{"token_address": "0x2F4Aaa4112E1891cC32b630e167a7179cFbE7b03", "channel_identifier": "0xfb43f382bbdbf209f854e14b74d183970e26ad5c1fd1b74a20f8f6bb653c1617", "reveal_timeout": 10, "token_network_identifier": "0x3C158a20b47d9613DDb9409099Be186fC272421a", "settle_timeout": 500, "balance": 0, "partner_address": "0xfB398E621c15E2BC5Ae6A508D8D89AF1f88c93e8", "state": "waiting_for_close"}]%
```

Screenshot of the `ChannelClosed` event properly shown in the webUI:
![screen shot 2018-07-13 at 14 51 01](https://user-images.githubusercontent.com/90851/42692511-409c9f7a-86ac-11e8-8904-a30f83f14fdc.png)

**Comment by palango** [comment]
After restarting the client I get the following crash. @hackaugusto Can you have a look?

```
2018-07-13 13:46:41 [info     ] Automatically selecting matrix homeserver based on RTT [raiden.network.transport.matrix] homeserver=https://transport03.raiden.network rtt=0.028008666666666668
2018-07-13 13:46:41 [info     ] Lock 4518252952 acquired on /Users/paul/.raiden/netid_3/df173a51/.lock [filelock]
2018-07-13 13:46:43 [info     ] LOGIN                          [raiden.network.transport.matrix] current_user=@0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413.2ea2498f:transport03.raiden.network homeserver=transport03.raiden.network server_url=https://transport03.raiden.network username=0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413.2ea2498f
2018-07-13 13:46:43 [info     ] TRANSPORT STARTED              [raiden.network.transport.matrix] current_user=@0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413.2ea2498f:transport03.raiden.network
2018-07-13 13:46:44 [info     ] close called                   [raiden.network.proxies.token_network] additional_hash=0x balance_hash=0x node=df173a51 nonce=0 partner=fb398e62 signature=0x token_network=3c158a20
2018-07-13 13:47:03 [critical ] close failed                   [raiden.network.proxies.token_network] additional_hash=0x balance_hash=0x node=df173a51 nonce=0 partner=fb398e62 signature=0x token_network=3c158a20
Traceback (most recent call last):
  File "/Users/paul/Work/venv-raiden/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/Users/paul/Work/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/paul/Work/raiden/raiden/ui/cli.py", line 966, in run
    app_ = _run_app()
  File "/Users/paul/Work/raiden/raiden/ui/cli.py", line 887, in _run_app
    app_ = ctx.invoke(app, **kwargs)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/paul/Work/raiden/raiden/ui/cli.py", line 693, in app
    discovery=discovery,
  File "/Users/paul/Work/raiden/raiden/app.py", line 121, in __init__
    discovery=discovery,
  File "/Users/paul/Work/raiden/raiden/raiden_service.py", line 216, in __init__
    self.start()
  File "/Users/paul/Work/raiden/raiden/raiden_service.py", line 283, in start
    on_raiden_event(self, event)
  File "/Users/paul/Work/raiden/raiden/raiden_event_handler.py", line 333, in on_raiden_event
    handle_contract_send_channelclose(raiden, event)
  File "/Users/paul/Work/raiden/raiden/raiden_event_handler.py", line 201, in handle_contract_send_channelclose
    signature,
  File "/Users/paul/Work/raiden/raiden/network/proxies/payment_channel.py", line 112, in close
    signature=signature,
  File "/Users/paul/Work/raiden/raiden/network/proxies/token_network.py", line 573, in close
    'Channel is not in an opened state. It cannot be closed.',
raiden.exceptions.ChannelIncorrectStateError: Channel is not in an opened state. It cannot be closed.
```

**Comment by palango** [comment]
The other participant properly sees the channel as closed.

![screen shot 2018-07-13 at 16 15 58](https://user-images.githubusercontent.com/90851/42696316-1b8e5c26-86b8-11e8-859a-99d7af8251a9.png)

**Comment by rakanalh** [comment]
Same exception happened on my local raiden node. The channel was closed successfully though, which is different from Paul's case.

**Comment by hackaugusto** [comment]
closing in favor of #1561 and #1839
