### ISSUE TITLE
Too big  `from_block` in event endpoint causes exception

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1809]
This query to the API:

`http http://localhost:5001/api/1/events/network?from_block=999999999999999999999999`

causes the following exception:

```
Traceback (most recent call last):
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/webargs/core.py", line 441, in wrapper
    return func(*args, **kwargs)
  File "/home/lefteris/ew/raiden/raiden/api/v1/resources.py", line 106, in get
    to_block=to_block,
  File "/home/lefteris/ew/raiden/raiden/api/rest.py", line 553, in get_network_events
    to_block,
  File "/home/lefteris/ew/raiden/raiden/api/python.py", line 618, in get_network_events
    to_block=to_block,
  File "/home/lefteris/ew/raiden/raiden/blockchain/events.py", line 95, in get_token_network_registry_events
    to_block,
  File "/home/lefteris/ew/raiden/raiden/blockchain/events.py", line 65, in get_contract_events
    to_block=to_block,
  File "/home/lefteris/ew/raiden/raiden/network/rpc/client.py", line 586, in get_filter_events
    'topics': topics,
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/web3/eth.py", line 354, in getLogs
    "eth_getLogs", [filter_params],
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/web3/manager.py", line 110, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32602, 'message': 'invalid argument 0: hex number > 64 bits'}
```

**Comment by palango** [comment]
This also solved a crash when giving negative numbers as parameters.
