### ISSUE TITLE
Crash while trying to trying to join/create room

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#1812]
## Problem Definition

I had to remove my `~/.raiden` directory after some state got corrupted. On startup I got the following output followed by a client crash.

```
2018-07-13 13:57:30 [info     ] Automatically selecting matrix homeserver based on RTT [raiden.network.transport.matrix] homeserver=https://transport03.raiden.network rtt=0.023271
2018-07-13 13:57:30 [info     ] Lock 4485913008 acquired on /Users/paul/.raiden/netid_3/df173a51/.lock [filelock]
2018-07-13 13:57:34 [info     ] LOGIN                          [raiden.network.transport.matrix] current_user=@0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413.2ea2498f:transport03.raiden.network homeserver=transport03.raiden.network server_url=https://transport03.raiden.network username=0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413.2ea2498f
2018-07-13 13:57:34 [info     ] TRANSPORT STARTED              [raiden.network.transport.matrix] current_user=@0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413.2ea2498f:transport03.raiden.network
2018-07-13 13:57:34 [info     ] Room raiden_ropsten_0x25511699c252eea2678266857c98f459df97b77c_0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413 not found, trying to create it. [raiden.network.transport.matrix] current_user=@0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413.2ea2498f:transport03.raiden.network
2018-07-13 13:57:35 [warning  ] Leaving room without canonical alias [raiden.network.transport.matrix] current_user=@0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413.2ea2498f:transport03.raiden.network room=<Room id="!JWLacXvBISOIlFMcCp:transport03.raiden.network" aliases=[]>
2018-07-13 13:57:36 [info     ] Error creating room raiden_ropsten_0x25511699c252eea2678266857c98f459df97b77c_0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413: 403 {"errcode":"M_FORBIDDEN","error":"@0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413.2ea2498f:transport03.raiden.network not in room !JWLacXvBISOIlFMcCp:transport03.raiden.network."}. Retrying to join... [raiden.network.transport.matrix] current_user=@0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413.2ea2498f:transport03.raiden.network
2018-07-13 13:57:36 [info     ] Room raiden_ropsten_0x25511699c252eea2678266857c98f459df97b77c_0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413 not found, trying to create it. [raiden.network.transport.matrix] current_user=@0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413.2ea2498f:transport03.raiden.network
2018-07-13 13:57:37 [info     ] Error creating room raiden_ropsten_0x25511699c252eea2678266857c98f459df97b77c_0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413: 400 {"errcode":"M_UNKNOWN","error":"Room alias already taken"}. Retrying to join... [raiden.network.transport.matrix] current_user=@0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413.2ea2498f:transport03.raiden.network
2018-07-13 13:57:37 [info     ] Room raiden_ropsten_0x25511699c252eea2678266857c98f459df97b77c_0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413 not found, trying to create it. [raiden.network.transport.matrix] current_user=@0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413.2ea2498f:transport03.raiden.network
2018-07-13 13:57:38 [info     ] Error creating room raiden_ropsten_0x25511699c252eea2678266857c98f459df97b77c_0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413: 400 {"errcode":"M_UNKNOWN","error":"Room alias already taken"}. Retrying to join... [raiden.network.transport.matrix] current_user=@0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413.2ea2498f:transport03.raiden.network
2018-07-13 13:57:38 [info     ] Room raiden_ropsten_0x25511699c252eea2678266857c98f459df97b77c_0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413 not found, trying to create it. [raiden.network.transport.matrix] current_user=@0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413.2ea2498f:transport03.raiden.network
2018-07-13 13:57:39 [info     ] Error creating room raiden_ropsten_0x25511699c252eea2678266857c98f459df97b77c_0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413: 400 {"errcode":"M_UNKNOWN","error":"Room alias already taken"}. Retrying to join... [raiden.network.transport.matrix] current_user=@0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413.2ea2498f:transport03.raiden.network
2018-07-13 13:57:39 [info     ] Room raiden_ropsten_0x25511699c252eea2678266857c98f459df97b77c_0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413 not found, trying to create it. [raiden.network.transport.matrix] current_user=@0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413.2ea2498f:transport03.raiden.network
2018-07-13 13:57:40 [info     ] Error creating room raiden_ropsten_0x25511699c252eea2678266857c98f459df97b77c_0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413: 400 {"errcode":"M_UNKNOWN","error":"Room alias already taken"}. Retrying to join... [raiden.network.transport.matrix] current_user=@0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413.2ea2498f:transport03.raiden.network
Traceback (most recent call last):
  File "/Users/paul/Work/venv-raiden/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/Users/paul/Work/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/paul/Work/raiden/raiden/ui/cli.py", line 966, in run
    app_ = _run_app()
  File "/Users/paul/Work/raiden/raiden/ui/cli.py", line 887, in _run_app
    app_ = ctx.invoke(app, **kwargs)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/paul/Work/raiden/raiden/ui/cli.py", line 693, in app
    discovery=discovery,
  File "/Users/paul/Work/raiden/raiden/app.py", line 121, in __init__
    discovery=discovery,
  File "/Users/paul/Work/raiden/raiden/raiden_service.py", line 216, in __init__
    self.start()
  File "/Users/paul/Work/raiden/raiden/raiden_service.py", line 280, in start
    self.start_neighbours_healthcheck()
  File "/Users/paul/Work/raiden/raiden/raiden_service.py", line 290, in start_neighbours_healthcheck
    self.start_health_check_for(neighbour)
  File "/Users/paul/Work/raiden/raiden/raiden_service.py", line 349, in start_health_check_for
    self.transport.start_health_check(node_address)
  File "/Users/paul/Work/raiden/raiden/network/transport/matrix.py", line 209, in start_health_check
    room = self._get_room_for_address(node_address, allow_missing_peers=True)
  File "/Users/paul/Work/raiden/raiden/network/transport/matrix.py", line 601, in _get_room_for_address
    room = self._get_unlisted_room(room_name, invitees=[user.user_id for user in peers])
  File "/Users/paul/Work/raiden/raiden/network/transport/matrix.py", line 652, in _get_unlisted_room
    raise RuntimeError(f'Could not join or create room {room_name}.')
RuntimeError: Could not join or create room raiden_ropsten_0x25511699c252eea2678266857c98f459df97b77c_0xdf173a5173c3d0ae5ba11dae84470c5d3f1a8413.
```

**Comment by ulope** [comment]
Problem vanished on its own. Possibly an aftereffect of #1784.
We'll upgrade the homeservers to the latest version just in case.
