### ISSUE TITLE
Handle situations where node is out of funds (ETH for gas)

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/raiden#1815]
when registering a new token from a node without balance required to pay for the gas the API crashes.

What to do:
- [ ] write tests for api calls performed on a node with low or zero eth balance
- [ ] handle such situation gracefully. Return `HTTPStatus.PAYMENT_REQUIRED`, the same error we return if the user does not have enough tokens for a deposit operation.
- [ ] update API to display meaningful message to the user in this case

example traceback:
```
Traceback (most recent call last):
  File "/home/xoza/.pyenv/versions/360_raiden/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/xoza/.pyenv/versions/360_raiden/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/xoza/.pyenv/versions/360_raiden/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/xoza/.pyenv/versions/360_raiden/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/xoza/.pyenv/versions/360_raiden/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/xoza/src/raiden/raiden/api/v1/resources.py", line 146, in put
    token_address,
  File "/home/xoza/src/raiden/raiden/api/rest.py", line 354, in register_token
    token_address,
  File "/home/xoza/src/raiden/raiden/api/python.py", line 120, in token_network_register
    return registry.add_token(token_address)
  File "/home/xoza/src/raiden/raiden/network/proxies/token_network_registry.py", line 103, in add_token
    token_address,
  File "/home/xoza/src/raiden/raiden/network/rpc/smartcontract_proxy.py", line 40, in transact
    **kargs,
  File "/home/xoza/src/raiden/raiden/network/rpc/client.py", line 496, in send_transaction
    result = self.web3.eth.sendRawTransaction(signed_txn.rawTransaction)
  File "/home/xoza/.pyenv/versions/360_raiden/lib/python3.6/site-packages/web3/eth.py", line 274, in sendRawTransaction
    [raw_transaction],
  File "/home/xoza/.pyenv/versions/360_raiden/lib/python3.6/site-packages/web3/manager.py", line 110, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32010, 'message': 'Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 401482550000000000 and got: 374200502000000000.'}
```

**Comment by LefterisJP** [comment]
Any races caused by this in the same manner described [here](https://github.com/raiden-network/raiden/issues/1839) will also be handled for this issue.
