### ISSUE TITLE
Exception on /api/1/connections/0xaddress [PUT]

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#1819]
## Problem Definition

When trying to join a token network from the WebUI

```
2018-07-13 15:22:48 [error    ] Exception on /api/1/connections/0x2F4Aaa4112E1891cC32b630e167a7179cFbE7b03 [PUT] [flask.app]
Traceback (most recent call last):
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/webargs/core.py", line 441, in wrapper
    return func(*args, **kwargs)
  File "/Users/paul/Work/raiden/raiden/api/v1/resources.py", line 186, in put
    joinable_funds_target=joinable_funds_target,
  File "/Users/paul/Work/raiden/raiden/api/rest.py", line 462, in connect
    joinable_funds_target,
  File "/Users/paul/Work/raiden/raiden/api/python.py", line 164, in token_network_connect
    joinable_funds_target=joinable_funds_target,
  File "/Users/paul/Work/raiden/raiden/connection_manager.py", line 132, in connect
    self._open_channels()
  File "/Users/paul/Work/raiden/raiden/connection_manager.py", line 296, in _open_channels
    partner,
TypeError: channel_open() missing 1 required positional argument: 'partner_address'
```

**Comment by pcppcp** [comment]
This will be fixed by #1739
