### ISSUE TITLE
Runtime error when launching

### ISSUE THREAD

**Issue by anmolshl** [raiden-network/raiden#1830]
## Problem Definition

Runtime error when launching raider:

```RuntimeError: Discovery room #raiden_4555_discovery:transport01.raiden.network not found and can't be created on a federated homeserver 'transport03.raiden.network'.```

### System Description

Debug log by @palango:

```
(venv) ➜  raiden git:(Priv-chain-tut) ✗ raiden --network-id 4555 --keystore-path ../pvnet1/myDataDir/keystore --registry-contract-address "0x1C3ADA8aCeA791127e4469ac55fec4b2A7068523" --discovery-contract-address "0xc6C2A20BFaa1767eDbD275dDc299e928402Af81e" --secret-registry-contract-address "0x6C5AB0d72c6809b5b6b7a22b96E405e02f8990DF" --no-sync-check --log-config "raiden:debug"
Welcome to Raiden, version 0.3.1.dev1006+gb2429b3b!

----------------------------------------------------------------------
| This is an Alpha version of experimental open source software      |
| released under the MIT license and may contain errors and/or bugs. |
| Use of the software is at your own risk and discretion. No         |
| guarantee whatsoever is made regarding its suitability for your    |
| intended purposes and its compliance with applicable law and       |
| regulations. It is up to the user to determine the software´s      |
| quality and suitability and whether its use is compliant with its  |
| respective regulatory regime, especially in the case that you are  |
| operating in a commercial context.                                 |
----------------------------------------------------------------------
The following accounts were found in your machine:

[  0] - 0x85199C90F029D0c8Baa138A4F8f3A3c4a808A4A2

Select one of them by index to continue: 0
Enter the password to unlock 0x85199C90F029D0c8Baa138A4F8f3A3c4a808A4A2:
You are connected to the '4555' network and the DB path is: /Users/anmolsingh/.raiden/netid_4555/85199c90/log.db
2018-07-16 13:27:34 [debug    ] Matrix homeserver RTT times    [raiden.network.transport.matrix] rtt_times=[('https://transport03.raiden.network', 0.027695), ('https://transport01.raiden.network', 0.029353333333333332), ('https://transport02.raiden.network', 0.16406433333333334)]
2018-07-16 13:27:34 [info     ] Automatically selecting matrix homeserver based on RTT [raiden.network.transport.matrix] homeserver=https://transport03.raiden.network rtt=0.027695
2018-07-16 13:27:34 [info     ] Lock 4619556176 acquired on /Users/anmolsingh/.raiden/netid_4555/85199c90/.lock [filelock]
2018-07-16 13:27:35 [debug    ] starting block number          [raiden.tasks] block_number=21499
2018-07-16 13:27:35 [info     ] LOGIN                          [raiden.network.transport.matrix] current_user=@0x85199c90f029d0c8baa138a4f8f3a3c4a808a4a2:transport03.raiden.network homeserver=transport03.raiden.network server_url=https://transport03.raiden.network username=0x85199c90f029d0c8baa138a4f8f3a3c4a808a4a2
Traceback (most recent call last):
  File "/Users/anmolsingh/Documents/raiden/raiden/network/transport/matrix.py", line 333, in _join_discovery_room
    discovery_room = self._client.join_room(self._discovery_room_alias_full)
  File "/Users/anmolsingh/Documents/private_net/venv/lib/python3.6/site-packages/matrix_client/client.py", line 320, in join_room
    response = self.api.join_room(room_id_or_alias)
  File "/Users/anmolsingh/Documents/private_net/venv/lib/python3.6/site-packages/matrix_client/api.py", line 195, in join_room
    return self._send("POST", path)
  File "/Users/anmolsingh/Documents/private_net/venv/lib/python3.6/site-packages/matrix_client/api.py", line 691, in _send
    code=response.status_code, content=response.text
matrix_client.errors.MatrixRequestError: 404: {"errcode":"M_NOT_FOUND","error":"Room alias #raiden_4555_discovery:transport01.raiden.network not found"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anmolsingh/Documents/private_net/venv/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/Users/anmolsingh/Documents/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')
  File "/Users/anmolsingh/Documents/private_net/venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/anmolsingh/Documents/private_net/venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/anmolsingh/Documents/private_net/venv/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/Users/anmolsingh/Documents/private_net/venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/anmolsingh/Documents/private_net/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/anmolsingh/Documents/private_net/venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/anmolsingh/Documents/raiden/raiden/ui/cli.py", line 966, in run
    app_ = _run_app()
  File "/Users/anmolsingh/Documents/raiden/raiden/ui/cli.py", line 887, in _run_app
    app_ = ctx.invoke(app, **kwargs)
  File "/Users/anmolsingh/Documents/private_net/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/anmolsingh/Documents/raiden/raiden/ui/cli.py", line 693, in app
    discovery=discovery,
  File "/Users/anmolsingh/Documents/raiden/raiden/app.py", line 121, in __init__
    discovery=discovery,
  File "/Users/anmolsingh/Documents/raiden/raiden/raiden_service.py", line 216, in __init__
    self.start()
  File "/Users/anmolsingh/Documents/raiden/raiden/raiden_service.py", line 277, in start
    self.transport.start(self, queueids_to_queues)
  File "/Users/anmolsingh/Documents/raiden/raiden/network/transport/matrix.py", line 184, in start
    self._join_discovery_room()
  File "/Users/anmolsingh/Documents/raiden/raiden/network/transport/matrix.py", line 340, in _join_discovery_room
    f"Discovery room {self._discovery_room_alias_full} not found and can't be "
RuntimeError: Discovery room #raiden_4555_discovery:transport01.raiden.network not found and can't be created on a federated homeserver 'transport03.raiden.network'.
```

**Comment by andrevmatos** [comment]
This happens because, as you're using a private blockchain, there's no discovery for it in the main (as in "the one the clients will look for the discovery room) server (`transport01`), and you're on another server (`transport03`).
As the matrix client tries to create it, it fails, because the room can't be created in a server different than the one you're on now.

You have two options for running matrix transport with a private blockchain. Either:
- At least once, run the client specifying the transport01 as the server, with `--matrix-server="http://transport01.raiden.network"`. This will create the room there, and then you can go back to your server, and it'll gladly join this room, as expected (or stay in the 01 server, if you want)
- Specify a different "main" server (changing [this default config](https://github.com/raiden-network/raiden/blob/e7c82a12fcb2db764a47be514c8f3c6dee0f4ecc/raiden/app.py#L76), which isn't exposed through config options yet). You need to do this for all the clients you want connected to this private blockchain, as they need to join the same "discovery" room to be able to find each other.

**Comment by anmolshl** [comment]
@andrevmatos I tried the extra tag you gave me, I'm getting this in the log:
```raiden --network-id 4555 --keystore-path ../pvnet1/myDataDir/keystore --registry-contract-address "0x1C3ADA8aCeA791127e4469ac55fec4b2A7068523" --discovery-contract-address "0xc6C2A20BFaa1767eDbD275dDc299e928402Af81e" --secret-registry-contract-address "0x6C5AB0d72c6809b5b6b7a22b96E405e02f8990DF" --no-sync-check --log-config "raiden:debug" --matrix-server="http://transport01.raiden.network"
Welcome to Raiden, version 0.3.1.dev1006+gb2429b3b!

----------------------------------------------------------------------
| This is an Alpha version of experimental open source software      |
| released under the MIT license and may contain errors and/or bugs. |
| Use of the software is at your own risk and discretion. No         |
| guarantee whatsoever is made regarding its suitability for your    |
| intended purposes and its compliance with applicable law and       |
| regulations. It is up to the user to determine the software´s      |
| quality and suitability and whether its use is compliant with its  |
| respective regulatory regime, especially in the case that you are  |
| operating in a commercial context.                                 |
----------------------------------------------------------------------
The following accounts were found in your machine:

[  0] - 0x85199C90F029D0c8Baa138A4F8f3A3c4a808A4A2

Select one of them by index to continue: 0
Enter the password to unlock 0x85199C90F029D0c8Baa138A4F8f3A3c4a808A4A2:
Incorrect passphrase to unlock the private key. 3 tries remaining. Please try again or kill the process to quit. Usually Ctrl-c.
Enter the password to unlock 0x85199C90F029D0c8Baa138A4F8f3A3c4a808A4A2:
You are connected to the '4555' network and the DB path is: /Users/anmolsingh/.raiden/netid_4555/85199c90/log.db
2018-07-16 14:10:01 [info     ] Lock 4581423704 acquired on /Users/anmolsingh/.raiden/netid_4555/85199c90/.lock [filelock]
2018-07-16 14:10:01 [debug    ] starting block number          [raiden.tasks] block_number=21717
Traceback (most recent call last):
  File "/Users/anmolsingh/Documents/private_net/venv/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/Users/anmolsingh/Documents/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')
  File "/Users/anmolsingh/Documents/private_net/venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/anmolsingh/Documents/private_net/venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/anmolsingh/Documents/private_net/venv/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/Users/anmolsingh/Documents/private_net/venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/anmolsingh/Documents/private_net/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/anmolsingh/Documents/private_net/venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/anmolsingh/Documents/raiden/raiden/ui/cli.py", line 966, in run
    app_ = _run_app()
  File "/Users/anmolsingh/Documents/raiden/raiden/ui/cli.py", line 887, in _run_app
    app_ = ctx.invoke(app, **kwargs)
  File "/Users/anmolsingh/Documents/private_net/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/anmolsingh/Documents/raiden/raiden/ui/cli.py", line 693, in app
    discovery=discovery,
  File "/Users/anmolsingh/Documents/raiden/raiden/app.py", line 121, in __init__
    discovery=discovery,
  File "/Users/anmolsingh/Documents/raiden/raiden/raiden_service.py", line 216, in __init__
    self.start()
  File "/Users/anmolsingh/Documents/raiden/raiden/raiden_service.py", line 277, in start
    self.transport.start(self, queueids_to_queues)
  File "/Users/anmolsingh/Documents/raiden/raiden/network/transport/matrix.py", line 170, in start
    self._login_or_register()
  File "/Users/anmolsingh/Documents/raiden/raiden/network/transport/matrix.py", line 293, in _login_or_register
    self._client.login(username, password)
  File "/Users/anmolsingh/Documents/private_net/venv/lib/python3.6/site-packages/matrix_client/client.py", line 272, in login
    self.user_id = response["user_id"]
KeyError: 'user_id'```

**Comment by andrevmatos** [comment]
@anmolshl is this error consistent everytime you try to start raiden with those parameters?
@ulope do you have any weird logs in the `transport01` server for his user, `0x85199C90F029D0c8Baa138A4F8f3A3c4a808A4A2`? Seems like an unexpected response was sent, when we expected either successful login or `403` status code to proceed to register.

**Comment by palango** [comment]
Reopening until we're sure that's not an issue.
