### ISSUE TITLE
Raiden crashes on ChannelBusyError

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#1840]
## Problem Definition

When Raiden is bootstraping and once of the unapplied states includes a channel operation such as `ContractSendChannelClose`, the raiden node crashes when trying to apply this state because the channel is considered to be busy executing a different operation.

```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/rakan/raiden/raiden/tasks.py", line 56, in _run
    self.poll_for_new_block()
  File "/home/rakan/raiden/raiden/tasks.py", line 95, in poll_for_new_block
    result = callback(current_block, chain_id)
  File "/home/rakan/raiden/raiden/raiden_service.py", line 392, in _callback_new_block
    self.handle_state_change(state_change, current_block_number)
  File "/home/rakan/raiden/raiden/raiden_service.py", line 340, in handle_state_change
    on_raiden_event(self, event)
  File "/home/rakan/raiden/raiden/raiden_event_handler.py", line 339, in on_raiden_event
    handle_contract_send_channelsettle(raiden, event)
  File "/home/rakan/raiden/raiden/raiden_event_handler.py", line 298, in handle_contract_send_channelsettle
    second_locksroot,
  File "/home/rakan/raiden/raiden/network/proxies/payment_channel.py", line 163, in settle
    partner_locksroot=partner_locksroot,
  File "/home/rakan/raiden/raiden/network/proxies/token_network.py", line 782, in settle
    self._check_channel_lock(partner)
  File "/home/rakan/raiden/raiden/network/proxies/token_network.py", line 108, in _check_channel_lock
    f'Channel between {self.node_address} and {partner} is '
raiden.exceptions.ChannelBusyError: Channel between b'[\x97\xac !\xc2\x91\x08\xe4\x1b\x8e\x8f,\xe2\x90qZ\xd2\xb7<' and b'\x8a\x0c\xe8\xbd\xa2\x00\xd6M\x85\x89W\x08\x0b\xf7\xed\xdd3q\x13_' is busy with another ongoing operation.
2018-07-16T19:15:00Z <AlarmTask "Greenlet-0" at 0x7f95bfe38c48: _run> failed with ChannelBusyError

Traceback (most recent call last):
  File "/home/rakan/.pyenv/versions/raiden/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/home/rakan/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/rakan/raiden/raiden/ui/cli.py", line 966, in run
    app_ = _run_app()
  File "/home/rakan/raiden/raiden/ui/cli.py", line 887, in _run_app
    app_ = ctx.invoke(app, **kwargs)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/rakan/raiden/raiden/ui/cli.py", line 693, in app
    discovery=discovery,
  File "/home/rakan/raiden/raiden/app.py", line 121, in __init__
    discovery=discovery,
  File "/home/rakan/raiden/raiden/raiden_service.py", line 216, in __init__
    self.start()
  File "/home/rakan/raiden/raiden/raiden_service.py", line 283, in start
    on_raiden_event(self, event)
  File "/home/rakan/raiden/raiden/raiden_event_handler.py", line 333, in on_raiden_event
    handle_contract_send_channelclose(raiden, event)
  File "/home/rakan/raiden/raiden/raiden_event_handler.py", line 201, in handle_contract_send_channelclose
    signature,
  File "/home/rakan/raiden/raiden/network/proxies/payment_channel.py", line 119, in close
    signature=signature,
  File "/home/rakan/raiden/raiden/network/proxies/token_network.py", line 563, in close
    self.client.poll(unhexlify(transaction_hash))
  File "/home/rakan/raiden/raiden/network/rpc/client.py", line 546, in poll
    gevent.sleep(.5)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/gevent/hub.py", line 155, in sleep
    hub.wait(t)
  File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 152, in gevent.__waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
raiden.exceptions.ChannelBusyError: Channel between b'[\x97\xac !\xc2\x91\x08\xe4\x1b\x8e\x8f,\xe2\x90qZ\xd2\xb7<' and b'\x8a\x0c\xe8\xbd\xa2\x00\xd6M\x85\x89W\x08\x0b\xf7\xed\xdd3q\x13_' is busy with another ongoing operation.
```

### System Description
```
 uname -a
Linux archlinux 4.17.4-1-ARCH #1 SMP PREEMPT Tue Jul 3 15:45:09 UTC 2018 x86_64 GNU/Linux
```
```
 command -v solc && solc --version
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Linux.g++
```
```
command -v geth && geth version
/usr/bin/geth
Geth
Version: 1.8.11-stable
Git Commit: dea1ce052a10cd7d401a5c04f83f371a06fe293c
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.3
Operating System: linux
GOPATH=/home/rakan/Code/Go
GOROOT=/usr/lib/go
```
```
command -v raiden && raiden version
/home/rakan/.pyenv/shims/raiden
{
  "raiden": "0.3.1.dev984+ga662e898",
  "python_implementation": "CPython",
  "python_version": "3.6.5",
  "system": "Linux 64bit_ELF 4.17.4-1-ARCH x86_64"
}
```
```
[ -d .git ] && git rev-parse HEAD
b4bf3813c7064fd4c9ca15e123a410ca8e20e83c
```

**Comment by hackaugusto** [comment]
Related: Race between API calls acquiring the channel lock #1839

**Comment by hackaugusto** [comment]
Closing in favor of #1839
