### ISSUE TITLE
Replacement transaction underpriced error on bootstrap

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#1841]
## Problem Definition

When Raiden is bootstrapping, it tries to restore states from WAL and applies the "unapplied states". If the list of unapplied states include `ContractSendChannelClose` for example, this triggers a transaction to happen on the blockchain and might cause an error.

```
Traceback (most recent call last):
  File "/home/rakan/.pyenv/versions/raiden/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/home/rakan/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/rakan/raiden/raiden/ui/cli.py", line 966, in run
    app_ = _run_app()
  File "/home/rakan/raiden/raiden/ui/cli.py", line 887, in _run_app
    app_ = ctx.invoke(app, **kwargs)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/rakan/raiden/raiden/ui/cli.py", line 693, in app
    discovery=discovery,
  File "/home/rakan/raiden/raiden/app.py", line 121, in __init__
    discovery=discovery,
  File "/home/rakan/raiden/raiden/raiden_service.py", line 216, in __init__
    self.start()
  File "/home/rakan/raiden/raiden/raiden_service.py", line 283, in start
    on_raiden_event(self, event)
  File "/home/rakan/raiden/raiden/raiden_event_handler.py", line 333, in on_raiden_event
    handle_contract_send_channelclose(raiden, event)
  File "/home/rakan/raiden/raiden/raiden_event_handler.py", line 201, in handle_contract_send_channelclose
    signature,
  File "/home/rakan/raiden/raiden/network/proxies/payment_channel.py", line 119, in close
    signature=signature,
  File "/home/rakan/raiden/raiden/network/proxies/token_network.py", line 561, in close
    signature,
  File "/home/rakan/raiden/raiden/network/rpc/smartcontract_proxy.py", line 40, in transact
    **kargs,
  File "/home/rakan/raiden/raiden/network/rpc/client.py", line 497, in send_transaction
    result = self.web3.eth.sendRawTransaction(signed_txn.rawTransaction)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/web3-4.4.1-py3.6.egg/web3/eth.py", line 274, in sendRawTransaction
    [raw_transaction],
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/web3-4.4.1-py3.6.egg/web3/manager.py", line 110, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'replacement transaction underpriced'}
```
### System Description
```
 uname -a
Linux archlinux 4.17.4-1-ARCH #1 SMP PREEMPT Tue Jul 3 15:45:09 UTC 2018 x86_64 GNU/Linux
```
```
 command -v solc && solc --version
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Linux.g++
```
```
command -v geth && geth version
/usr/bin/geth
Geth
Version: 1.8.11-stable
Git Commit: dea1ce052a10cd7d401a5c04f83f371a06fe293c
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.3
Operating System: linux
GOPATH=/home/rakan/Code/Go
GOROOT=/usr/lib/go
```
```
command -v raiden && raiden version
/home/rakan/.pyenv/shims/raiden
{
  "raiden": "0.3.1.dev984+ga662e898",
  "python_implementation": "CPython",
  "python_version": "3.6.5",
  "system": "Linux 64bit_ELF 4.17.4-1-ARCH x86_64"
}
```
```
[ -d .git ] && git rev-parse HEAD
b4bf3813c7064fd4c9ca15e123a410ca8e20e83c
```

**Comment by hackaugusto** [comment]
We assume that Raiden has exclusive access to the account, otherwise we would need to remove the local singing (#1402) and have a way to synchronize the account's nonces (#1400).

/If/ this was caused by multiple nodes running with the same account, one solution is to just quit the node and print a nice warning (#1400).
