### ISSUE TITLE
Raiden crashes after removedb command

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#1866]
## Problem Definition

I open the raiden client after I did `raiden --keystore-path  ~/.ethereum/testnet/keystore removedb`, and I got the following:

```
BLOCKCHAIN EVENT               [raiden.blockchain_events_handler] chain_event=<Event contract: 7692624c event: {'args': AttributeDict({'channel_identifier': b"\xdf\x9b\x86\x10h\xbb\x0b\xe9\xf6'\xf3?\x1a\xb4\x85\x08o\xf1$\xabY\rLT\xbb\xa8\x8dNh\xbe\xff\x12", 'participant1': '0x8A0cE8bDA200D64d858957080bf7eDDD3371135F', 'participant2': '0x25511699C252eeA2678266857C98F459Df97B77c', 'settle_timeout': 600}), 'event': 'ChannelOpened', 'logIndex': 2, 'transactionIndex': 7, 'transactionHash': HexBytes('0xb9618ddaeafeabffc5b83f2b7b461c6a802f4b8b07c302ce6e7030f8f1a0fe1b'), 'address': '0x7692624c0C43285D51c0DdDfb2A6388f5002762E', 'blockHash': HexBytes('0xf43af31a72ff446057107980c4436105ff7881f96b6a05638fa530dcca95b2ca'), 'blockNumber': 3627992, 'block_number': 3627992, 'channel_identifier': b"\xdf\x9b\x86\x10h\xbb\x0b\xe9\xf6'\xf3?\x1a\xb4\x85\x08o\xf1$\xabY\rLT\xbb\xa8\x8dNh\xbe\xff\x12", 'participant1': b'\x8a\x0c\xe8\xbd\xa2\x00\xd6M\x85\x89W\x08\x0b\xf7\xed\xdd3q\x13_', 'participant2': b'%Q\x16\x99\xc2R\xee\xa2g\x82f\x85|\x98\xf4Y\xdf\x97\xb7|', 'settle_timeout': 600}> node=8a0ce8bd
2018-07-18 08:48:01 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=8a0ce8bd state_change=<ContractReceiveChannelNew token_network:7692624c state:<NettingChannelState id:df9b8610 opened:<TransactionExecutionStatus started:None finished:3627992 result:success> closed:None settled:None>>
Traceback (most recent call last):
  File "/home/cosmin/.virtualenvs/raiden/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 961, in run
    app_ = _run_app()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 882, in _run_app
    app_ = ctx.invoke(app, **kwargs)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 688, in app
    discovery=discovery,
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/app.py", line 121, in __init__
    discovery=discovery,
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/raiden_service.py", line 216, in __init__
    self.start()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/raiden_service.py", line 262, in start
    last_log_block_number,
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/raiden_service.py", line 425, in install_and_query_payment_network_filters
    chain_id,
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/blockchain_events_handler.py", line 243, in on_blockchain_event
    handle_channel_new(raiden, event, current_block_number)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/blockchain_events_handler.py", line 106, in handle_channel_new
    from_block=data['blockNumber'],
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/blockchain/events.py", line 411, in add_payment_channel_listener
    from_block=from_block,
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/network/proxies/payment_channel.py", line 215, in all_events_filter
    returned_amount,
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/web3/utils/events.py", line 47, in construct_event_topic_set
    "When passing an argument list, the number of arguments must "
ValueError: When passing an argument list, the number of arguments must match the event constructor.
```
Before removing the db I tried to make a deposit on one of my opened channels.

### System Description

```
Geth
Version: 1.8.12-stable
Git Commit: 37685930d953bcbe023f9bc65b135a8d8b8f1488
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.1
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.10
```

```
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Linux.g++
```

```
{
  "raiden": "0.3.1.dev1043+g84984c35",
  "python_implementation": "CPython",
  "python_version": "3.6.5",
  "system": "Linux 64bit_ELF 4.15.0-24-generic x86_64"
}
```
```
Git comm: 84984c35e7aa7b09ac45686d9d375251c6802391
```

**Comment by hackaugusto** [comment]
This happens when the virtualenv not properly updated, the dependency `raiden-contracts` needs to be outdated for the event abi to mismatch.
