### ISSUE TITLE
matrix: crash on startup when sending message from a queue

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/raiden#1871]
```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/xoza/src/raiden/raiden/network/transport/matrix.py", line 524, in send_queue
    self.send_async('', address, _event_to_message(event, node_address))
  File "/home/xoza/src/raiden/raiden/network/transport/matrix.py", line 223, in send_async
    receiver_address=to_normalized_address(receiver_address),
  File "/home/xoza/.pyenv/versions/360_raiden/lib/python3.6/site-packages/eth_utils/address.py", line 68, in to_normalized_address
    "Unknown format {}, attempted to normalize to {}".format(address, hex_address)
ValueError: Unknown format , attempted to normalize to 0x
2018-07-18T12:17:26Z <Greenlet "Greenlet-0" at 0x7fd2279cd148: send_queue(b'%Q\x16\x99\xc2R\xee\xa2g\x82f\x85|\x98\xf4Y\xdf\, [<SendLockedTransfer msgid:5994485520500595654 tra)> failed with ValueError

Traceback (most recent call last):
  File "/home/xoza/.pyenv/versions/3.6.0/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/xoza/.pyenv/versions/3.6.0/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xoza/src/raiden/raiden/__main__.py", line 15, in <module>
    main()
  File "/home/xoza/src/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')
  File "/home/xoza/.pyenv/versions/360_raiden/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/xoza/.pyenv/versions/360_raiden/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/xoza/.pyenv/versions/360_raiden/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/xoza/.pyenv/versions/360_raiden/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xoza/.pyenv/versions/360_raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/xoza/.pyenv/versions/360_raiden/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/xoza/src/raiden/raiden/ui/cli.py", line 961, in run
    app_ = _run_app()
  File "/home/xoza/src/raiden/raiden/ui/cli.py", line 935, in _run_app
    event.wait()
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
ValueError: Unknown format , attempted to normalize to 0x
```

**Comment by andrevmatos** [comment]
Related to #1794 . 
Raiden, somehow, is trying to send a message to an empty address. It's not matrix transport fault here.

**Comment by pcppcp** [comment]
well the receiver address is explicitly set to an empty string here

https://github.com/raiden-network/raiden/blob/master/raiden/network/transport/matrix.py#L524
