### ISSUE TITLE
Matrix 502: Bad gateway

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#2029]
## Problem Definition

When running Raiden today I experienced what seems to be some Matrix hiccups. So I am just dumping the traceback here to keep track of the errors we encounter.

I ran raiden 0.4.1 exactly in the same way as I usually do. It could have been caused by some network problems, but still Raiden shouldn't crash in this case.

```
FATAL: An unexpected exception occured.A traceback has been written to /tmp/raiden-exception-2018-08-01T10-02qxn7ti1h.txt
502: Bad Gateway
Traceback (most recent call last):
  File "raiden-script.py", line 2, in <module>
  File "site-packages/raiden/__main__.py", line 11, in main
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1043, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "site-packages/click/decorators.py", line 17, in new_func
  File "site-packages/raiden/ui/cli.py", line 969, in run
  File "site-packages/raiden/ui/cli.py", line 829, in run
  File "site-packages/raiden/app.py", line 147, in stop
  File "site-packages/raiden/raiden_service.py", line 301, in stop
  File "site-packages/raiden/network/transport/matrix.py", line 268, in stop_and_wait
  File "site-packages/raiden_libs/network/matrix/client.py", line 204, in set_presence_state
  File "site-packages/raiden_libs/network/matrix/client.py", line 48, in _send
  File "site-packages/matrix_client/api.py", line 670, in _send
  File "site-packages/requests/sessions.py", line 512, in request
  File "site-packages/requests/sessions.py", line 622, in send
  File "site-packages/requests/adapters.py", line 445, in send
  File "site-packages/urllib3/connectionpool.py", line 588, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 239, in _get_conn
  File "site-packages/urllib3/util/connection.py", line 23, in is_connection_dropped
  File "site-packages/urllib3/util/wait.py", line 146, in wait_for_read
  File "site-packages/urllib3/util/wait.py", line 107, in poll_wait_for_socket
  File "site-packages/urllib3/util/wait.py", line 42, in _retry_on_intr
  File "site-packages/urllib3/util/wait.py", line 105, in do_poll
  File "site-packages/gevent/select.py", line 268, in poll
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
matrix_client.errors.MatrixRequestError: 502: Bad Gateway
[6015] Failed to execute script raiden-script
```

**Comment by andrevmatos** [comment]
Fixed by #2062
