### ISSUE TITLE
Internal server error when calling payments rest api

### ISSUE THREAD

**Issue by kelsos** [raiden-network/raiden#2101]
## Problem Definition

Calling the payments api throws an Internal Server error.

```
2018-08-08 11:19:53 [info     ] partner for channel 82641569 - 7a664079 is not reachable, ignoring [raiden.routing] 
2018-08-08 11:19:53 [error    ] Exception on /api/1/payments/0x0f114A1E9Db192502E7856309cc899952b3db1ED/0x7A664079423fa25B87014EB53282F34c7AC7B87E [POST] [flask.app] 
Traceback (most recent call last):
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/webargs/core.py", line 441, in wrapper
    return func(*args, **kwargs)
  File "/home/kelsos/development/github/raiden/raiden/api/v1/resources.py", line 163, in post
    identifier=identifier,
  File "/home/kelsos/development/github/raiden/raiden/api/rest.py", line 671, in initiate_payment
    identifier=identifier,
  File "/home/kelsos/development/github/raiden/raiden/api/python.py", line 589, in transfer_and_wait
    identifier,
  File "/home/kelsos/development/github/raiden/raiden/api/python.py", line 640, in transfer_async
    identifier,
  File "/home/kelsos/development/github/raiden/raiden/raiden_service.py", line 503, in mediated_transfer_async
    identifier,
  File "/home/kelsos/development/github/raiden/raiden/raiden_service.py", line 569, in start_mediated_transfer
    target,
  File "/home/kelsos/development/github/raiden/raiden/raiden_service.py", line 85, in initiator_init
    previous_address,
  File "/home/kelsos/development/github/raiden/raiden/routing.py", line 128, in get_best_routes
    if channel.get_status(channel_state) != CHANNEL_STATE_OPENED:
  File "/home/kelsos/development/github/raiden/raiden/transfer/channel.py", line 878, in get_status
    if channel_state.settle_transaction:
AttributeError: 'NoneType' object has no attribute 'settle_transaction'
2018-08-08 11:19:53 [info     ] 127.0.0.1 - - [2018-08-08 13:19:53] "POST /api/1/payments/0x0f114A1E9Db192502E7856309cc899952b3db1ED/0x7A664079423fa25B87014EB53282F34c7AC7B87E HTTP/1.1" 500 164 0.036295 [raiden.api.rest.pywsgi] 

```

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
Linux thoth 4.17.11-arch1 #1 SMP PREEMPT Sun Jul 29 10:11:16 UTC 2018 x86_64 GNU/Linux
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Linux.g++
/usr/bin/geth
Geth
Version: 1.8.13-stable
Git Commit: 225171a4bfcc16bd12a1906b1e0d43d0b18c353b
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.3
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go
/usr/bin/parity
Parity
  version Parity/v1.11.8-stable-c754a028e0-20180725/x86_64-linux-gnu/rustc1.27.2
Copyright 2015, 2016, 2017, 2018 Parity Technologies (UK) Ltd
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann

25742fda9cb0159a2d311d79c5cef83bd85e19a3

```

**Comment by palango** [comment]
Seems to happen because the partner is not online. But it shouldn't crash...

**Comment by kelsos** [comment]
It didn't crash indeed it just returned a 500 response from the rest API.

**Comment by palango** [comment]
The reason is that `channel_state` is `None` here:
https://github.com/raiden-network/raiden/blob/4a11dd6e136ff42f3a5fd830bc638549df2b4eb7/raiden/routing.py#L118-L128
