### ISSUE TITLE
Raiden crashes if connection to geth couldn't be established.

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#2130]
## Problem Definition

This behavior is correct, Raiden should fail when an ethereum node isn't running. However, we should catch the exception and print a user-friendly error message.

Exception:
```
Traceback (most recent call last):
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/gevent/_socket3.py", line 336, in connect
    raise error(err, strerror(err))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/rakan/.pyenv/versions/3.6.5/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/rakan/.pyenv/versions/3.6.5/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/rakan/.pyenv/versions/3.6.5/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/rakan/.pyenv/versions/3.6.5/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/rakan/.pyenv/versions/3.6.5/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/urllib3/connection.py", line 196, in connect
    conn = self._new_conn()
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f71536e8cc0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f71536e8cc0>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rakan/.pyenv/versions/raiden/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/home/rakan/Brainbot/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/rakan/Brainbot/raiden/raiden/ui/cli.py", line 1049, in run
    NodeRunner(kwargs, ctx).run()
  File "/home/rakan/Brainbot/raiden/raiden/ui/cli.py", line 903, in run
    app = self._run_app()
  File "/home/rakan/Brainbot/raiden/raiden/ui/cli.py", line 921, in _run_app
    app_ = run_app(**self._options)
  File "/home/rakan/Brainbot/raiden/raiden/ui/cli.py", line 607, in run_app
    node_version = web3.version.node  # pylint: disable=no-member
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/web3/version.py", line 14, in node
    return self.web3.manager.request_blocking("web3_clientVersion", [])
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/web3/manager.py", line 107, in request_blocking
    response = self._make_request(method, params)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/web3/manager.py", line 90, in _make_request
    return request_func(method, params)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/web3/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/web3/middleware/exception_retry_request.py", line 87, in middleware
    return make_request(method, params)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/web3/providers/rpc.py", line 68, in make_request
    **self.get_request_kwargs()
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/web3/utils/request.py", line 26, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/requests/sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f71536e8cc0>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

### System Description

```
uname -a
Linux archlinux 4.17.12-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 3 07:16:41 UTC 2018 x86_64 GNU/Linux

command -v solc && solc --version
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Linux.g++

command -v geth && geth version
/usr/bin/geth
Geth
Version: 1.8.13-stable
Git Commit: 225171a4bfcc16bd12a1906b1e0d43d0b18c353b
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.3
Operating System: linux
GOPATH=/home/rakan/Code/Go
GOROOT=/usr/lib/go

 command -v raiden && raiden version
/home/rakan/.pyenv/shims/raiden
{
  "raiden": "0.3.1.dev984+ga662e898",
  "python_implementation": "CPython",
  "python_version": "3.6.5",
  "system": "Linux 64bit_ELF 4.17.12-arch1-1-ARCH x86_64",
  "distribution": "source"
}

[ -d .git ] && git rev-parse HEAD~
4da52abe9d549bee518fc53d6060b3d87f381b01
```

**Comment by LefterisJP** [comment]
>  "raiden": "0.3.1.dev984+ga662e898",

Hmmm ?

> [ -d .git ] && git rev-parse HEAD~
>4da52abe9d549bee518fc53d6060b3d87f381b01

Commit does not exist: https://github.com/raiden-network/raiden/commit/4da52abe9d549bee518fc53d6060b3d87f381b01

**Comment by rakanalh** [comment]
It's basically a commit have on top of master... but it should happen on master as well.

**Comment by hackaugusto** [comment]
fixed by: https://github.com/raiden-network/raiden/pull/2151
