### ISSUE TITLE
Internal server error when joining a token network

### ISSUE THREAD

**Issue by kelsos** [raiden-network/raiden#2138]
## Problem Definition

```
2018-08-10 09:28:16 [debug    ] bootstrapping token network.   [raiden.connection_manager] 
2018-08-10 09:28:17 [error    ] Exception on /api/1/connections/0x0f114A1E9Db192502E7856309cc899952b3db1ED [PUT] [flask.app] 
Traceback (most recent call last):
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/web3/contract.py", line 1363, in call_contract_function
    output_data = decode_abi(output_types, return_data)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/eth_abi/abi.py", line 96, in decode_abi
    return decoder(stream)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/eth_abi/decoding.py", line 118, in __call__
    return self.decode(stream)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/eth_abi/decoding.py", line 164, in decode
    yield decoder(stream)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/eth_abi/decoding.py", line 118, in __call__
    return self.decode(stream)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/eth_abi/decoding.py", line 186, in decode
    raw_data = self.read_data_from_stream(stream)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/eth_abi/decoding.py", line 279, in read_data_from_stream
    len(data),
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/webargs/core.py", line 441, in wrapper
    return func(*args, **kwargs)
  File "/home/kelsos/development/github/raiden-network/1/raiden/api/v1/resources.py", line 169, in put
    joinable_funds_target=joinable_funds_target,
  File "/home/kelsos/development/github/raiden-network/1/raiden/api/rest.py", line 500, in connect
    joinable_funds_target,
  File "/home/kelsos/development/github/raiden-network/1/raiden/api/python.py", line 175, in token_network_connect
    joinable_funds_target=joinable_funds_target,
  File "/home/kelsos/development/github/raiden-network/1/raiden/connection_manager.py", line 143, in connect
    self.BOOTSTRAP_ADDR,
  File "/home/kelsos/development/github/raiden-network/1/raiden/api/python.py", line 274, in channel_open
    settle_timeout,
  File "/home/kelsos/development/github/raiden-network/1/raiden/network/proxies/token_network.py", line 144, in new_netting_channel
    transaction_hash = self._new_netting_channel(partner, settle_timeout)
  File "/home/kelsos/development/github/raiden-network/1/raiden/network/proxies/token_network.py", line 177, in _new_netting_channel
    if self.channel_exists(self.node_address, partner):
  File "/home/kelsos/development/github/raiden-network/1/raiden/network/proxies/token_network.py", line 198, in channel_exists
    channel_data = self.detail_channel(participant1, participant2)
  File "/home/kelsos/development/github/raiden-network/1/raiden/network/proxies/token_network.py", line 231, in detail_channel
    to_checksum_address(participant2),
  File "/home/kelsos/development/github/raiden-network/1/raiden/network/proxies/token_network.py", line 95, in _call_and_check_result
    call_result = fn(*args).call()
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/web3/contract.py", line 1106, in call
    **self.kwargs
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/web3/contract.py", line 1385, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not decode contract function call getChannelInfo return data b'' for output_types ['bytes32', 'uint256', 'uint8']
2018-08-10 09:28:17 [info     ] 127.0.0.1 - - [2018-08-10 11:28:17] "PUT /api/1/connections/0x0f114A1E9Db192502E7856309cc899952b3db1ED HTTP/1.1" 500 164 0.175103 [raiden.api.rest.pywsgi] 

```

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
Linux thoth 4.17.13-arch1-1-ARCH #1 SMP PREEMPT Mon Aug 6 23:06:31 UTC 2018 x86_64 GNU/Linux
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Linux.g++
/usr/bin/geth
Geth
Version: 1.8.13-stable
Git Commit: 225171a4bfcc16bd12a1906b1e0d43d0b18c353b
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.3
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go
/usr/bin/parity
Parity
  version Parity/v1.11.8-stable-c754a028e0-20180725/x86_64-linux-gnu/rustc1.27.2
Copyright 2015, 2016, 2017, 2018 Parity Technologies (UK) Ltd
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann

/home/kelsos/.virtualenvs/raiden/bin/raiden
{
  "raiden": "0.4.2.dev198+g354168e4",
  "python_implementation": "CPython",
  "python_version": "3.6.6",
  "system": "Linux 64bit_ELF 4.17.13-arch1-1-ARCH x86_64",
  "distribution": "source"
}

9f1afe80a59ac676a62c65822d45320a0dc6e9c6

```

**Comment by kelsos** [comment]
All good
