### ISSUE TITLE
Raiden node crashes

### ISSUE THREAD

**Issue by kelsos** [raiden-network/raiden#2139]
## Problem Definition

```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/kelsos/development/github/raiden-network/1/raiden/network/transport/matrix.py", line 578, in _send_queued_messages
    self.send_async(address, queue_identifier, message)
TypeError: send_async() takes 3 positional arguments but 4 were given
2018-08-10T10:40:21Z <RaidenGreenlet "Greenlet-0" at 0x7f7f981f2948: <bound method MatrixTransport._send_queued_messages of <raiden.network.transport.matrix.MatrixTransport object at 0x7f7f9b1e4e80>>({QueueIdentifier(recipient=b'\x02\xf4\xb6\xbceV\x1)> failed with TypeError

FATAL: An unexpected exception occured. A traceback has been written to cat
send_async() takes 3 positional arguments but 4 were given

➜ cat /tmp/raiden-exception-2018-08-10T10-40ymucdzxl.txt
Traceback (most recent call last):
  File "/home/kelsos/development/github/raiden-network/1/raiden/ui/cli.py", line 992, in _run_app
    event.wait()
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
TypeError: send_async() takes 3 positional arguments but 4 were given

```

```
Linux thoth 4.17.13-arch1-1-ARCH #1 SMP PREEMPT Mon Aug 6 23:06:31 UTC 2018 x86_64 GNU/Linux
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Linux.g++
/usr/bin/geth
Geth
Version: 1.8.13-stable
Git Commit: 225171a4bfcc16bd12a1906b1e0d43d0b18c353b
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.3
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go
/usr/bin/parity
Parity
  version Parity/v1.11.8-stable-c754a028e0-20180725/x86_64-linux-gnu/rustc1.27.2
Copyright 2015, 2016, 2017, 2018 Parity Technologies (UK) Ltd
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann

/home/kelsos/.virtualenvs/raiden/bin/raiden
{
  "raiden": "0.4.2.dev227+gff8c58be.d20180810",
  "python_implementation": "CPython",
  "python_version": "3.6.6",
  "system": "Linux 64bit_ELF 4.17.13-arch1-1-ARCH x86_64",
  "distribution": "source"
}
dde8d789a9999f9d407675dd4394b6cbf24566e1

```

**Comment by LefterisJP** [comment]
Looking into it
