### ISSUE TITLE
Raiden node crashes on restart

### ISSUE THREAD

**Issue by kelsos** [raiden-network/raiden#2144]
## Problem Definition

```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/kelsos/development/github/raiden-network/1/raiden/network/transport/matrix.py", line 578, in _send_queued_messages
    self.send_async(queue_identifier, message)
  File "/home/kelsos/development/github/raiden-network/1/raiden/network/transport/matrix.py", line 256, in send_async
    receiver_address = queue_identifier.recipient
AttributeError: 'int' object has no attribute 'recipient'
2018-08-10T13:00:33Z <RaidenGreenlet "Greenlet-0" at 0x7f4b0a9a0c48: <bound method MatrixTransport._send_queued_messages of <raiden.network.transport.matrix.MatrixTransport object at 0x7f4b11909fd0>>({QueueIdentifier(recipient=b'\x02\xf4\xb6\xbceV\x1)> failed with AttributeError


➜ cat /tmp/raiden-exception-2018-08-10T13-00euz4x4j_.txt
Traceback (most recent call last):
  File "/home/kelsos/development/github/raiden-network/1/raiden/ui/cli.py", line 992, in _run_app
    event.wait()
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
AttributeError: 'int' object has no attribute 'recipient'

```

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
Linux thoth 4.17.13-arch1-1-ARCH #1 SMP PREEMPT Mon Aug 6 23:06:31 UTC 2018 x86_64 GNU/Linux
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Linux.g++
/usr/bin/geth
Geth
Version: 1.8.13-stable
Git Commit: 225171a4bfcc16bd12a1906b1e0d43d0b18c353b
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.3
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go
/usr/bin/parity
Parity
  version Parity/v1.11.8-stable-c754a028e0-20180725/x86_64-linux-gnu/rustc1.27.2
Copyright 2015, 2016, 2017, 2018 Parity Technologies (UK) Ltd
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann

/home/kelsos/.virtualenvs/raiden/bin/raiden
{
  "raiden": "0.4.2.dev229+g0229f730",
  "python_implementation": "CPython",
  "python_version": "3.6.6",
  "system": "Linux 64bit_ELF 4.17.13-arch1-1-ARCH x86_64",
  "distribution": "source"
}
bc9987f16530297d37af2090ecb55ed1178f04f4
```

**Comment by LefterisJP** [comment]
On it again.

**Comment by LefterisJP** [comment]
Should be fixed by https://github.com/raiden-network/raiden/pull/2145
