### ISSUE TITLE
local state can not be used to call settle

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2221]
## Problem Definition
When starting my node I get the following exception: 
```
Enter the password to unlock 0x8A0cE8bDA200D64d858957080bf7eDDD3371135F: 
2018-08-21 11:56:44 [debug    ] JSONRPCClient created          [raiden.network.rpc.client] available_nonce=117 sender=8a0ce8bd
Checking if the ethereum node is synchronized

You are connected to the 'ropsten' network and the DB path is: /home/cosmin/.raiden/netid_3/8a0ce8bd/v0_log.db
2018-08-21 11:56:47 [debug    ] Matrix homeserver RTT times    [raiden.network.transport.matrix] rtt_times=[('https://transport03.raiden.network', 0.028123333333333334), ('https://transport01.raiden.network', 0.029653333333333337), ('https://transport02.raiden.network', 0.12500266666666668)]
2018-08-21 11:56:47 [info     ] Automatically selecting matrix homeserver based on RTT [raiden.network.transport.matrix] homeserver=https://transport03.raiden.network rtt=0.028123333333333334
2018-08-21 11:56:47 [info     ] Lock 139765630942624 acquired on /home/cosmin/.raiden/netid_3/8a0ce8bd/.lock [filelock] 
2018-08-21 11:56:48 [debug    ] Restoring from snapshot        [raiden.storage.wal] 
2018-08-21 11:56:48 [debug    ] Replaying state changes        [raiden.storage.wal] num_state_changes=460
2018-08-21 11:56:49 [debug    ] Restored state from WAL        [raiden.raiden_service] last_restored_block=3880883
2018-08-21 11:56:51 [debug    ] starting at block number       [raiden.tasks] current_block=3880886
2018-08-21 11:56:51 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=8a0ce8bd state_change=<Block 3880886>
2018-08-21 11:56:51 [debug    ] Processing pending transactions [raiden.raiden_service] num_pending_transactions=1
2018-08-21 11:56:51 [info     ] settle called                  [raiden.network.proxies.token_network] locked_amount=0 locksroot=0x0000000000000000000000000000000000000000000000000000000000000000 node=8a0ce8bd partner=92746ece partner_locked_amount=0 partner_locksroot=0x0000000000000000000000000000000000000000000000000000000000000000 partner_transferred_amount=0 token_network=9fe1f19d transferred_amount=0
--- Logging error ---
Traceback (most recent call last):
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/raiden_event_handler.py", line 343, in on_raiden_event
    handle_contract_send_channelsettle(raiden, event)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/raiden_event_handler.py", line 307, in handle_contract_send_channelsettle
    second_locksroot,
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/network/proxies/payment_channel.py", line 201, in settle
    partner_locksroot=partner_locksroot,
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/network/proxies/token_network.py", line 912, in settle
    raise RaidenRecoverableError('local state can not be used to call settle')
raiden.exceptions.RaidenRecoverableError: local state can not be used to call settle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/structlog/stdlib.py", line 459, in format
    record.msg = self.processor(logger, meth_name, ed)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/log_config.py", line 24, in wrapper
    result = first_func(*args, **kwargs)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/structlog/dev.py", line 189, in __call__
    event = _pad(event, self._pad_event) + self._styles.reset + " "
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/structlog/dev.py", line 35, in _pad
    missing = l - len(s)
TypeError: object of type 'RaidenRecoverableError' has no len()
Call stack:
  File "/home/cosmin/.virtualenvs/raiden/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 1064, in run
    NodeRunner(kwargs, ctx).run()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 923, in run
    app = self._run_app()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 941, in _run_app
    app_ = run_app(**self._options)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 765, in run_app
    raiden_app.start()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/app.py", line 132, in start
    self.raiden.start()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/raiden_service.py", line 310, in start
    self.start_async().wait()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/raiden_service.py", line 288, in start_async
    on_raiden_event(self, transaction)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/raiden_event_handler.py", line 349, in on_raiden_event
    log.error(e)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/structlog/stdlib.py", line 81, in error
    return self._proxy_to_logger("error", event, *args, **kw)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/structlog/stdlib.py", line 119, in _proxy_to_logger
    **event_kw)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/structlog/_base.py", line 177, in _proxy_to_logger
    return getattr(self._logger, method_name)(*args, **kw)
Message: {'event': RaidenRecoverableError('local state can not be used to call settle',), 'logger': 'raiden.raiden_event_handler', 'level': 'error', 'timestamp': '2018-08-21 11:56:51'}
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/raiden_event_handler.py", line 343, in on_raiden_event
    handle_contract_send_channelsettle(raiden, event)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/raiden_event_handler.py", line 307, in handle_contract_send_channelsettle
    second_locksroot,
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/network/proxies/payment_channel.py", line 201, in settle
    partner_locksroot=partner_locksroot,
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/network/proxies/token_network.py", line 912, in settle
    raise RaidenRecoverableError('local state can not be used to call settle')
raiden.exceptions.RaidenRecoverableError: local state can not be used to call settle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/structlog/stdlib.py", line 459, in format
    record.msg = self.processor(logger, meth_name, ed)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/log_config.py", line 24, in wrapper
    result = first_func(*args, **kwargs)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/structlog/dev.py", line 189, in __call__
    event = _pad(event, self._pad_event) + self._styles.reset + " "
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/structlog/dev.py", line 35, in _pad
    missing = l - len(s)
TypeError: object of type 'RaidenRecoverableError' has no len()
Call stack:
  File "/home/cosmin/.virtualenvs/raiden/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 1064, in run
    NodeRunner(kwargs, ctx).run()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 923, in run
    app = self._run_app()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 941, in _run_app
    app_ = run_app(**self._options)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 765, in run_app
    raiden_app.start()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/app.py", line 132, in start
    self.raiden.start()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/raiden_service.py", line 310, in start
    self.start_async().wait()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/raiden_service.py", line 288, in start_async
    on_raiden_event(self, transaction)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/raiden_event_handler.py", line 349, in on_raiden_event
    log.error(e)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/structlog/stdlib.py", line 81, in error
    return self._proxy_to_logger("error", event, *args, **kw)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/structlog/stdlib.py", line 119, in _proxy_to_logger
    **event_kw)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/structlog/_base.py", line 177, in _proxy_to_logger
    return getattr(self._logger, method_name)(*args, **kw)
Message: {'event': RaidenRecoverableError('local state can not be used to call settle',), 'logger': 'raiden.raiden_event_handler', 'level': 'error', 'timestamp': '2018-08-21 11:56:51'}
Arguments: ()
2018-08-21 11:56:52 [debug    ] new block                      [raiden.tasks] number=3880887
2018-08-21 11:56:52 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=8a0ce8bd state_change=<Block 3880887>
2018-08-21 11:56:53 [info     ] LOGIN                          [raiden.network.transport.matrix] current_user=@0x8a0ce8bda200d64d858957080bf7eddd3371135f:transport03.raiden.network homeserver=transport03.raiden.network server_url=https://transport03.raiden.network username=0x8a0ce8bda200d64d858957080bf7eddd3371135f
2018-08-21 11:56:53 [debug    ] INVITE                         [raiden.network.transport.matrix] current_user=@0x8a0ce8bda200d64d858957080bf7eddd3371135f:transport03.raiden.network room=<Room id="!MQNtgFYZQETmHGWoxU:transport03.raiden.network" alias="#raiden_ropsten_0x82641569b2062b545431cf6d7f0a418582865ba7_0x8a0ce8bda200d64d858957080bf7eddd3371135f:transport03.raiden.network"> user=<User id="@0x82641569b2062b545431cf6d7f0a418582865ba7:transport02.raiden.network">
```
I want to mention that the application works fine afterwards, but we should at least, catch the exception. Also the traceback is not being showed into the log: [log.txt](https://github.com/raiden-network/raiden/files/2306160/log.txt)
 
### System Description
```
Linux cosmin-Lenovo-ideapad-100-15IBD 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Linux.g++
/usr/bin/geth
Geth
Version: 1.8.12-stable
Git Commit: 37685930d953bcbe023f9bc65b135a8d8b8f1488
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.1
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.10

Raiden commit: 9c39699c845833a64bc4dbc8f488fbf4802f9876
```

**Comment by andrevmatos** [comment]
Fixed by #2244
