### ISSUE TITLE
Unhandled exception when handling endpoint request

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2229]
## Problem Definition

When trying to query the endpoints: 
``api/1/raiden_events/networks/<token_address>/channels/``
``api/1/blockchain_events/payment_networks/<token_address>/channels/``
I get the following exception:
```
2018-08-23 08:19:15 [critical ] Unhandled exception when handling endpoint request [raiden.api.rest] 
301 Moved Permanently: None
2018-08-23 08:19:15 [error    ] Exception on /api/1/raiden_events/networks/0x0f114A1E9Db192502E7856309cc899952b3db1ED/channels [GET] [flask.app] 
Traceback (most recent call last):
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/werkzeug/routing.py", line 1538, in match
    rv = rule.match(path, method)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/werkzeug/routing.py", line 776, in match
    raise RequestSlash()
werkzeug.routing.RequestSlash

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/flask/app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/flask/app.py", line 1644, in handle_http_exception
    return handler(e)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/api/rest.py", line 411, in unhandled_exception
    raise exception  # re-raise to crash node
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/api/rest.py", line 380, in run
    self.wsgiserver.serve_forever()
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/gevent/baseserver.py", line 364, in serve_forever
    self._stop_event.wait()
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
werkzeug.routing.RequestRedirect: 301 Moved Permanently: None
2018-08-23 08:19:15 [critical ] Unhandled exception when handling endpoint request [raiden.api.rest] 
```

### Solution
Either remove the ``/`` from the channel endpoints or just add strict_slashes=False, as mentioned [here](http://werkzeug.pocoo.org/docs/0.14/routing/#werkzeug.routing.Rule) and [here](https://stackoverflow.com/questions/21050320/flask-301-response)

I will remove the ``/`` for consistency reasons.
### System Description
```
Linux cosmin-Lenovo-ideapad-100-15IBD 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Linux.g++
/usr/bin/geth
Geth
Version: 1.8.12-stable
Git Commit: 37685930d953bcbe023f9bc65b135a8d8b8f1488
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.1
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.10
/home/cosmin/.virtualenvs/raiden/bin/raiden
{
  "raiden": "0.5.2.dev37+gc18c896c",
  "python_implementation": "CPython",
  "python_version": "3.6.5",
  "system": "Linux 64bit_ELF 4.15.0-32-generic x86_64",
  "distribution": "source"
}
```

**Comment by CosminNechifor** [comment]
Fixed by: #2230
