### ISSUE TITLE
Matrix request error crashes the node

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2231]
## Problem Definition

When i try to open my Raiden node I get the following error which ends up crashing my node:
```
[  1] - 0x8A0cE8bDA200D64d858957080bf7eDDD3371135F

Select one of them by index to continue: 1
Enter the password to unlock 0x8A0cE8bDA200D64d858957080bf7eDDD3371135F: 
2018-08-23 10:05:44 [debug    ] JSONRPCClient created          [raiden.network.rpc.client] available_nonce=131 sender=8a0ce8bd
Checking if the ethereum node is synchronized

You are connected to the 'ropsten' network and the DB path is: /home/cosmin/.raiden/netid_3/8a0ce8bd/v0_log.db
2018-08-23 10:05:48 [debug    ] Matrix homeserver RTT times    [raiden.network.transport.matrix] rtt_times=[('https://transport03.raiden.network', 0.035080999999999994), ('https://transport02.raiden.network', 0.130906)]
2018-08-23 10:05:48 [info     ] Automatically selecting matrix homeserver based on RTT [raiden.network.transport.matrix] homeserver=https://transport03.raiden.network rtt=0.035080999999999994
2018-08-23 10:05:48 [info     ] Lock 140416599023512 acquired on /home/cosmin/.raiden/netid_3/8a0ce8bd/.lock [filelock] 
2018-08-23 10:05:48 [debug    ] Restoring from snapshot        [raiden.storage.wal] 
2018-08-23 10:05:48 [debug    ] Replaying state changes        [raiden.storage.wal] num_state_changes=10505
2018-08-23 10:08:48 [debug    ] Restored state from WAL        [raiden.raiden_service] last_restored_block=3893941
2018-08-23 10:08:49 [debug    ] starting at block number       [raiden.tasks] current_block=3894089
2018-08-23 10:08:49 [debug    ] BLOCKCHAIN EVENT               [raiden.blockchain_events_handler] chain_event=<Event contract: 9fe1f19d event: {'args': AttributeDict({'channel_identifier': 89, 'participant': '0x77799e4f6d29BA3dC4b643A07dFea94D51442c32', 'total_deposit': 15}), 'event': 'ChannelNewDeposit', 'logIndex': 2, 'transactionIndex': 4, 'transactionHash': HexBytes('0x03ce72992bf083a216215f804ff3e198e97d85c12c698b2e67c2296608102da8'), 'address': '0x9FE1f19D8C0d2591Fd01486E575B44f4220eF241', 'blockHash': HexBytes('0xbfac5c7e2abdcce87af69145d02baf360213bcf06db4499d1b45d070471d6680'), 'blockNumber': 3894070, 'block_number': 3894070, 'channel_identifier': 89, 'deposit': 15, 'participant': b'wy\x9eOm)\xba=\xc4\xb6C\xa0}\xfe\xa9MQD,2'}> node=8a0ce8bd
2018-08-23 10:08:49 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=8a0ce8bd state_change=<ContractReceiveChannelNewBalance token_network:9fe1f19d channel:89 transaction:<TransactionChannelNewBalance participant:77799e4f balance:15 at_block:3894070>>
2018-08-23 10:08:50 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=8a0ce8bd state_change=<Block 3894089>
2018-08-23 10:08:50 [debug    ] RAIDEN EVENT                   [raiden.raiden_service] node=8a0ce8bd raiden_event=<ContractSendSecretReveal secrethash:b"\xfc\x82aI\xf1\x01t1\xe2sH\x03w\x0b\x9e6^i\x87z\xe4\xc6'\xf3F19\x06\xf7\x8dsx">
2018-08-23 10:08:50 [info     ] secret 0xfc826149f1017431e2734803770b9e365e69877ae4c627f346313906f78d7378 already registered. [raiden.network.proxies.secret_registry] contract=3de6b821 node=8a0ce8bd secrethash=0xfc826149f1017431e2734803770b9e365e69877ae4c627f346313906f78d7378
2018-08-23 10:08:50 [debug    ] Processing pending transactions [raiden.raiden_service] num_pending_transactions=2
2018-08-23 10:08:50 [info     ] settle called                  [raiden.network.proxies.token_network] locked_amount=0 locksroot=0x0000000000000000000000000000000000000000000000000000000000000000 node=8a0ce8bd partner=92746ece partner_locked_amount=0 partner_locksroot=0x0000000000000000000000000000000000000000000000000000000000000000 partner_transferred_amount=0 token_network=9fe1f19d transferred_amount=0
2018-08-23 10:08:50 [info     ] secret 0xfc826149f1017431e2734803770b9e365e69877ae4c627f346313906f78d7378 already registered. [raiden.network.proxies.secret_registry] contract=3de6b821 node=8a0ce8bd secrethash=0xfc826149f1017431e2734803770b9e365e69877ae4c627f346313906f78d7378
2018-08-23 10:08:53 [info     ] LOGIN                          [raiden.network.transport.matrix] current_user=@0x8a0ce8bda200d64d858957080bf7eddd3371135f:transport03.raiden.network homeserver=transport03.raiden.network server_url=https://transport03.raiden.network username=0x8a0ce8bda200d64d858957080bf7eddd3371135f
2018-08-23 10:09:07 [debug    ] new block                      [raiden.tasks] number=3894090
2018-08-23 10:09:07 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=8a0ce8bd state_change=<Block 3894090>
2018-08-23 10:09:07 [debug    ] RAIDEN EVENT                   [raiden.raiden_service] node=8a0ce8bd raiden_event=<ContractSendSecretReveal secrethash:b"\xfc\x82aI\xf1\x01t1\xe2sH\x03w\x0b\x9e6^i\x87z\xe4\xc6'\xf3F19\x06\xf7\x8dsx">
2018-08-23 10:09:07 [info     ] secret 0xfc826149f1017431e2734803770b9e365e69877ae4c627f346313906f78d7378 already registered. [raiden.network.proxies.secret_registry] contract=3de6b821 node=8a0ce8bd secrethash=0xfc826149f1017431e2734803770b9e365e69877ae4c627f346313906f78d7378
2018-08-23 10:09:09 [debug    ] new block                      [raiden.tasks] number=3894091
2018-08-23 10:09:09 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=8a0ce8bd state_change=<Block 3894091>
2018-08-23 10:09:09 [debug    ] RAIDEN EVENT                   [raiden.raiden_service] node=8a0ce8bd raiden_event=<ContractSendSecretReveal secrethash:b"\xfc\x82aI\xf1\x01t1\xe2sH\x03w\x0b\x9e6^i\x87z\xe4\xc6'\xf3F19\x06\xf7\x8dsx">
2018-08-23 10:09:09 [info     ] secret 0xfc826149f1017431e2734803770b9e365e69877ae4c627f346313906f78d7378 already registered. [raiden.network.proxies.secret_registry] contract=3de6b821 node=8a0ce8bd secrethash=0xfc826149f1017431e2734803770b9e365e69877ae4c627f346313906f78d7378
2018-08-23 10:09:10 [debug    ] new block                      [raiden.tasks] number=3894092
2018-08-23 10:09:10 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=8a0ce8bd state_change=<Block 3894092>
2018-08-23 10:09:10 [debug    ] RAIDEN EVENT                   [raiden.raiden_service] node=8a0ce8bd raiden_event=<ContractSendSecretReveal secrethash:b"\xfc\x82aI\xf1\x01t1\xe2sH\x03w\x0b\x9e6^i\x87z\xe4\xc6'\xf3F19\x06\xf7\x8dsx">
2018-08-23 10:09:10 [info     ] secret 0xfc826149f1017431e2734803770b9e365e69877ae4c627f346313906f78d7378 already registered. [raiden.network.proxies.secret_registry] contract=3de6b821 node=8a0ce8bd secrethash=0xfc826149f1017431e2734803770b9e365e69877ae4c627f346313906f78d7378
2018-08-23 10:09:17 [debug    ] new block                      [raiden.tasks] number=3894093
2018-08-23 10:09:17 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=8a0ce8bd state_change=<Block 3894093>
2018-08-23 10:09:17 [debug    ] RAIDEN EVENT                   [raiden.raiden_service] node=8a0ce8bd raiden_event=<ContractSendSecretReveal secrethash:b"\xfc\x82aI\xf1\x01t1\xe2sH\x03w\x0b\x9e6^i\x87z\xe4\xc6'\xf3F19\x06\xf7\x8dsx">
2018-08-23 10:09:17 [info     ] secret 0xfc826149f1017431e2734803770b9e365e69877ae4c627f346313906f78d7378 already registered. [raiden.network.proxies.secret_registry] contract=3de6b821 node=8a0ce8bd secrethash=0xfc826149f1017431e2734803770b9e365e69877ae4c627f346313906f78d7378
2018-08-23 10:09:43 [debug    ] new block                      [raiden.tasks] number=3894094
2018-08-23 10:09:43 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=8a0ce8bd state_change=<Block 3894094>
2018-08-23 10:09:43 [debug    ] RAIDEN EVENT                   [raiden.raiden_service] node=8a0ce8bd raiden_event=<ContractSendSecretReveal secrethash:b"\xfc\x82aI\xf1\x01t1\xe2sH\x03w\x0b\x9e6^i\x87z\xe4\xc6'\xf3F19\x06\xf7\x8dsx">
2018-08-23 10:09:43 [info     ] secret 0xfc826149f1017431e2734803770b9e365e69877ae4c627f346313906f78d7378 already registered. [raiden.network.proxies.secret_registry] contract=3de6b821 node=8a0ce8bd secrethash=0xfc826149f1017431e2734803770b9e365e69877ae4c627f346313906f78d7378
2018-08-23 10:09:47 [debug    ] new block                      [raiden.tasks] number=3894095
2018-08-23 10:09:47 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=8a0ce8bd state_change=<Block 3894095>
2018-08-23 10:09:47 [debug    ] RAIDEN EVENT                   [raiden.raiden_service] node=8a0ce8bd raiden_event=<ContractSendSecretReveal secrethash:b"\xfc\x82aI\xf1\x01t1\xe2sH\x03w\x0b\x9e6^i\x87z\xe4\xc6'\xf3F19\x06\xf7\x8dsx">
2018-08-23 10:09:47 [info     ] secret 0xfc826149f1017431e2734803770b9e365e69877ae4c627f346313906f78d7378 already registered. [raiden.network.proxies.secret_registry] contract=3de6b821 node=8a0ce8bd secrethash=0xfc826149f1017431e2734803770b9e365e69877ae4c627f346313906f78d7378
2018-08-23 10:10:02 [debug    ] new block                      [raiden.tasks] number=3894096
2018-08-23 10:10:02 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=8a0ce8bd state_change=<Block 3894096>
2018-08-23 10:10:02 [debug    ] RAIDEN EVENT                   [raiden.raiden_service] node=8a0ce8bd raiden_event=<ContractSendSecretReveal secrethash:b"\xfc\x82aI\xf1\x01t1\xe2sH\x03w\x0b\x9e6^i\x87z\xe4\xc6'\xf3F19\x06\xf7\x8dsx">
2018-08-23 10:10:02 [info     ] secret 0xfc826149f1017431e2734803770b9e365e69877ae4c627f346313906f78d7378 already registered. [raiden.network.proxies.secret_registry] contract=3de6b821 node=8a0ce8bd secrethash=0xfc826149f1017431e2734803770b9e365e69877ae4c627f346313906f78d7378
2018-08-23 10:10:05 [debug    ] new block                      [raiden.tasks] number=3894097
2018-08-23 10:10:05 [debug    ] STATE CHANGE                   [raiden.raiden_service] node=8a0ce8bd state_change=<Block 3894097>
2018-08-23 10:10:05 [debug    ] RAIDEN EVENT                   [raiden.raiden_service] node=8a0ce8bd raiden_event=<ContractSendSecretReveal secrethash:b"\xfc\x82aI\xf1\x01t1\xe2sH\x03w\x0b\x9e6^i\x87z\xe4\xc6'\xf3F19\x06\xf7\x8dsx">
2018-08-23 10:10:05 [info     ] secret 0xfc826149f1017431e2734803770b9e365e69877ae4c627f346313906f78d7378 already registered. [raiden.network.proxies.secret_registry] contract=3de6b821 node=8a0ce8bd secrethash=0xfc826149f1017431e2734803770b9e365e69877ae4c627f346313906f78d7378
Traceback (most recent call last):
  File "/home/cosmin/.virtualenvs/raiden/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 1064, in run
    NodeRunner(kwargs, ctx).run()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 923, in run
    app = self._run_app()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 941, in _run_app
    app_ = run_app(**self._options)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 765, in run_app
    raiden_app.start()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/app.py", line 132, in start
    self.raiden.start()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/raiden_service.py", line 310, in start
    self.start_async().wait()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/raiden_service.py", line 293, in start_async
    self.transport.start(self, queueids_to_queues)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/network/transport/matrix.py", line 197, in start
    self._join_discovery_room()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/network/transport/matrix.py", line 361, in _join_discovery_room
    discovery_room = self._client.join_room(discovery_room_alias_full)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/matrix_client/client.py", line 320, in join_room
    response = self.api.join_room(room_id_or_alias)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/matrix_client/api.py", line 195, in join_room
    return self._send("POST", path)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/raiden_libs/network/matrix/client.py", line 72, in _send
    return super()._send(method, path, *args, **kwargs)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/matrix_client/api.py", line 691, in _send
    code=response.status_code, content=response.text
matrix_client.errors.MatrixRequestError: 500: {"errcode":"M_UNKNOWN","error":"Internal server error"}

```
 
Time: 11:40 +- 2min
Username: 0x8A0cE8bDA200D64d858957080bf7eDDD3371135F

### System Description
```
Linux cosmin-Lenovo-ideapad-100-15IBD 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Linux.g++
/usr/bin/geth
Geth
Version: 1.8.12-stable
Git Commit: 37685930d953bcbe023f9bc65b135a8d8b8f1488
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.1
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.10
/home/cosmin/.virtualenvs/raiden/bin/raiden
{
  "raiden": "0.5.2.dev37+gc18c896c",
  "python_implementation": "CPython",
  "python_version": "3.6.5",
  "system": "Linux 64bit_ELF 4.15.0-32-generic x86_64",
  "distribution": "source"
}
c18c896c7b070f4ecbbd09597623836f8a606787
```

**Comment by CosminNechifor** [comment]
Closing this, because in #2234 we have more people implicated, the information seems more explicit.
