### ISSUE TITLE
Exception raised when trying to make a deposit

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2263]
## Problem Definition

After joining the token network I have opened a channel, but when trying to make a deposit, I get an internal server error and the following exception:
``` 
2018-08-24 12:49:04 [debug    ] Depositing to channel          [raiden.api.rest] channel_identifier=113 registry_address=b'D]y\x05%"\xec\x94\x07\x8d\xfc\xcf\x96\xd90\'u\xca[N' total_deposit=7
2018-08-24 12:49:04 [debug    ] send_raw_transaction called    [raiden.network.rpc.client] account=0xa80fAAa7D98A479C304a67e6CDEf92dF8f3435Af gasLimit=3763699 gasPrice=6000000000 nonce=10
2018-08-24 12:49:04 [error    ] Exception on /api/1/channels/0x0f114A1E9Db192502E7856309cc899952b3db1ED/0x008311788dff04E3c0426a3EB19622B2035bA49d [PATCH] [flask.app] 
Traceback (most recent call last):
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/webargs/core.py", line 441, in wrapper
    return func(*args, **kwargs)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/api/v1/resources.py", line 66, in patch
    **kwargs,
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/api/rest.py", line 1127, in patch_channel
    result = self._deposit(registry_address, channel_state, total_deposit)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/api/rest.py", line 1001, in _deposit
    total_deposit,
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/api/python.py", line 388, in set_total_channel_deposit
    channel_proxy.set_total_deposit(total_deposit)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/network/proxies/payment_channel.py", line 137, in set_total_deposit
    partner=self.participant2,
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/network/proxies/token_network.py", line 582, in set_total_deposit
    token.approve(self.address, amount_to_deposit)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/network/proxies/token.py", line 52, in approve
    allowance,
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/network/rpc/smartcontract_proxy.py", line 93, in transact
    raise e
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/network/rpc/smartcontract_proxy.py", line 79, in transact
    **kargs,
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/network/rpc/client.py", line 463, in send_transaction
    tx_hash = self.web3.eth.sendRawTransaction(signed_txn.rawTransaction)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/web3/eth.py", line 274, in sendRawTransaction
    [raw_transaction],
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/web3/manager.py", line 110, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'nonce too low'}
```

Log: 
[raiden-debug.log](https://github.com/raiden-network/raiden/files/2318388/raiden-debug.log)

### System Description
```
Linux cosmin-Lenovo-ideapad-100-15IBD 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Linux.g++
/usr/bin/geth
Geth
Version: 1.8.12-stable
Git Commit: 37685930d953bcbe023f9bc65b135a8d8b8f1488
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.1
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.10
/home/cosmin/.virtualenvs/raiden/bin/raiden
{
  "raiden": "0.5.2.dev69+g39936e5b",
  "python_implementation": "CPython",
  "python_version": "3.6.5",
  "system": "Linux 64bit_ELF 4.15.0-32-generic x86_64",
  "distribution": "source"
}
aef0a87a41858f5d81a40f02b8a1ad4830ab9c8b

```

**Comment by LefterisJP** [comment]
@CosminNechifor  When closing an issue can you please say why this is closed?
