### ISSUE TITLE
Raiden client crashes when replaying state changes

### ISSUE THREAD

**Issue by kelsos** [raiden-network/raiden#2274]
## Problem Definition

```
2018-08-27 09:10:23 [info     ] Lock 140200684920672 acquired on /home/kelsos/.raiden/netid_3/c52952eb/.lock [filelock] 
2018-08-27 09:10:23 [debug    ] Restoring from snapshot        [raiden.storage.wal] 
2018-08-27 09:10:23 [debug    ] Replaying state changes        [raiden.storage.wal] num_state_changes=2217
Traceback (most recent call last):
  File "/home/kelsos/.virtualenvs/raiden/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/home/kelsos/development/github/raiden-network/2/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/kelsos/development/github/raiden-network/2/raiden/ui/cli.py", line 1064, in run
    NodeRunner(kwargs, ctx).run()
  File "/home/kelsos/development/github/raiden-network/2/raiden/ui/cli.py", line 923, in run
    app = self._run_app()
  File "/home/kelsos/development/github/raiden-network/2/raiden/ui/cli.py", line 941, in _run_app
    app_ = run_app(**self._options)
  File "/home/kelsos/development/github/raiden-network/2/raiden/ui/cli.py", line 765, in run_app
    raiden_app.start()
  File "/home/kelsos/development/github/raiden-network/2/raiden/app.py", line 133, in start
    self.raiden.start()
  File "/home/kelsos/development/github/raiden-network/2/raiden/raiden_service.py", line 310, in start
    self.start_async().wait()
  File "/home/kelsos/development/github/raiden-network/2/raiden/raiden_service.py", line 219, in start_async
    storage,
  File "/home/kelsos/development/github/raiden-network/2/raiden/storage/wal.py", line 31, in restore_from_latest_snapshot
    state_manager.dispatch(state_change)
  File "/home/kelsos/development/github/raiden-network/2/raiden/transfer/architecture.py", line 169, in dispatch
    state_change,
  File "/home/kelsos/development/github/raiden-network/2/raiden/transfer/node.py", line 1096, in state_transition
    iteration = handle_state_change(chain_state, state_change)
  File "/home/kelsos/development/github/raiden-network/2/raiden/transfer/node.py", line 835, in handle_state_change
    state_change,
  File "/home/kelsos/development/github/raiden-network/2/raiden/transfer/node.py", line 658, in handle_receive_secret_request
    return subdispatch_to_paymenttask(chain_state, state_change, secrethash)
  File "/home/kelsos/development/github/raiden-network/2/raiden/transfer/node.py", line 163, in subdispatch_to_paymenttask
    block_number,
  File "/home/kelsos/development/github/raiden-network/2/raiden/transfer/mediated_transfer/initiator_manager.py", line 273, in state_transition
    pseudo_random_generator,
  File "/home/kelsos/development/github/raiden-network/2/raiden/transfer/mediated_transfer/initiator.py", line 189, in handle_secretrequest
    state_change.expiration == lock.expiration
AttributeError: 'ReceiveSecretRequest' object has no attribute 'expiration'
2018-08-27 09:10:36 [info     ] Lock 140200684920672 released on /home/kelsos/.raiden/netid_3/c52952eb/.lock [filelock] 

```
### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
Linux forseti 4.18.4-arch1-1-ARCH #1 SMP PREEMPT Wed Aug 22 07:33:26 UTC 2018 x86_64 GNU/Linux
/usr/bin/geth
Geth
Version: 1.8.13-stable
Git Commit: 225171a4bfcc16bd12a1906b1e0d43d0b18c353b
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.3
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go
/home/kelsos/.virtualenvs/raiden/bin/raiden
{
  "raiden": "0.5.1.dev171+ged08f720",
  "python_implementation": "CPython",
  "python_version": "3.6.6",
  "system": "Linux 64bit_ELF 4.18.4-arch1-1-ARCH x86_64",
  "distribution": "source"
}
ed08f7208e4b6a194cd18d11589addf960234e44

```

**Comment by LefterisJP** [comment]
That's interesting: 

```
AttributeError: 'ReceiveSecretRequest' object has no attribute 'expiration'
```

`ReceiveSecretRequest` does have an expiration attribute now. It was added via 4e2c8754a9a7a34e4c9230ea319e92cb7bf166db.

How come you are replaying state changes from an old DB? I guess you are using latest master right? If so you shoudl manually remove the DB and this problem should go away.

**Comment by kelsos** [comment]
Yes it was an old database issue. I am closing the issue.
