### ISSUE TITLE
Raiden client crashes on start

### ISSUE THREAD

**Issue by kelsos** [raiden-network/raiden#2408]
## Problem Definition
I also did try to remove (after backup) the previous database and start with clear state but the same thing happens.

```
2018-09-10 11:23:27 [debug    ] Matrix homeserver RTT times    [raiden.network.transport.matrix] rtt_times=[('https://transport01.raiden.network', 0.032889), ('https://transport03.raiden.network', 0.04940133333333333), ('https://transport02.raiden.network', 0.12749766666666665)]
2018-09-10 11:23:27 [info     ] Automatically selecting matrix homeserver based on RTT [raiden.network.transport.matrix] homeserver=https://transport01.raiden.network rtt=0.032889
2018-09-10 11:23:28 [info     ] Lock 140430136264016 acquired on /home/kelsos/.raiden/node_82641569/netid_3/network_f2a175a5/.lock [filelock] 
2018-09-10 11:23:28 [debug    ] No snapshot found, replaying all state changes [raiden.storage.wal] 
2018-09-10 11:23:28 [debug    ] Replaying state changes        [raiden.storage.wal] num_state_changes=145
Traceback (most recent call last):
  File "/home/kelsos/.virtualenvs/raiden/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/ui/cli.py", line 1104, in run
    NodeRunner(kwargs, ctx).run()
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/ui/cli.py", line 937, in run
    app = self._run_app()
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/ui/cli.py", line 955, in _run_app
    app_ = run_app(**self._options)
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/ui/cli.py", line 774, in run_app
    raiden_app.start()
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/app.py", line 134, in start
    self.raiden.start()
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/raiden_service.py", line 223, in start
    storage,
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/storage/wal.py", line 31, in restore_from_latest_snapshot
    state_manager.dispatch(state_change)
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/transfer/architecture.py", line 285, in dispatch
    state_change,
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/transfer/node.py", line 1127, in state_transition
    iteration = handle_state_change(chain_state, state_change)
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/transfer/node.py", line 732, in handle_state_change
    state_change,
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/transfer/node.py", line 420, in handle_block
    block_number,
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/transfer/node.py", line 123, in subdispatch_to_all_channels
    block_number,
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/transfer/channel.py", line 2101, in state_transition
    block_number,
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/transfer/channel.py", line 1918, in handle_block
    settlement_end = closed_block_number + channel_state.settle_timeout
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
--- Logging error ---
Exception ignored in: <function BaseFileLock.__del__ at 0x7fb878c6a1e0>
Traceback (most recent call last):
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.7/site-packages/filelock.py", line 330, in __del__
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.7/site-packages/filelock.py", line 317, in release
  File "/usr/lib64/python3.7/logging/__init__.py", line 1332, in info
  File "/usr/lib64/python3.7/logging/__init__.py", line 1468, in _log
  File "/usr/lib64/python3.7/logging/__init__.py", line 1478, in handle
  File "/usr/lib64/python3.7/logging/__init__.py", line 1540, in callHandlers
  File "/usr/lib64/python3.7/logging/__init__.py", line 854, in handle
  File "/usr/lib64/python3.7/logging/__init__.py", line 989, in emit
  File "/usr/lib64/python3.7/logging/__init__.py", line 907, in handleError
  File "/usr/lib64/python3.7/traceback.py", line 100, in print_exception
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/log_config.py", line 158, in tracebackexception_format
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/log_config.py", line 143, in processor_wrapper
ImportError: sys.meta_path is None, Python is likely shutting down

```

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
Linux forseti 4.18.5-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 24 12:48:58 UTC 2018 x86_64 GNU/Linux
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Linux.g++
/usr/bin/geth
Geth
Version: 1.8.15-stable
Git Commit: 89451f7c382ad2185987ee369f16416f89c28a7d
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.3
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go
/home/kelsos/.virtualenvs/raiden/bin/raiden
{
  "raiden": "0.7.1.dev153+gfe831802",
  "python_implementation": "CPython",
  "python_version": "3.7.0",
  "system": "Linux 64bit_ELF 4.18.5-arch1-1-ARCH x86_64",
  "distribution": "source"
}
fe8318020ec4878029b3f7f8e89dc85477b8d7b1

```

**Comment by czepluch** [comment]
I can verify that this also happens to me on latest master.

**Comment by czepluch** [comment]
@hackaugusto seems to have worked for me. At least I can start Raiden now.
