### ISSUE TITLE
Unable to install raiden due to "wrong" dependencies

### ISSUE THREAD

**Issue by eorituz** [raiden-network/raiden#2418]
## Problem Definition

The latest Raiden release (v.0.8.0) has some messed up dependencies:

`py-evm 0.2.0a30 has requirement ipython<7.0.0,>=6.2.1, but you'll have ipython 4.2.1 which is incompatible.`
`py-evm 0.2.0a30 has requirement web3==4.4.1, but you'll have web3 4.6.0 which is incompatible.`

It looks like the requirements.txt dependencies are conflicting with the ethereum once.

The pip installation states that the installation of raiden was successfull but when I try to start Raiden it raises a VersionConflict:
```
raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (ipython 4.2.1 (/home/oliver/.virtualenvs/demo/lib/python3.6/site-packages), Requirement.parse('ipython<7.0.0,>=6.2.1'), {'py-evm'})
```

### System Description

Tried to install raiden via the last [pypi release](https://pypi.org/project/raiden/)
New virtualenv, Python3.6, Ubuntu 18.04

Was able to reproduced this issue in a vitualmachine too.

**Comment by pcppcp** [comment]
yep the deps are messed up now. I can't even start the node.

This issue in `web3` is related
https://github.com/ethereum/web3.py/issues/1048

**Comment by eorituz** [comment]
I'm not too sure if it is web3 related. 
I tried to clone the repo and manually install the dev requirements `pip install -r requirements-dev.txt` and still end up with the same ipython VersionConflict

`Traceback (most recent call last):
  File "/home/oliver/.virtualenvs/demo/bin/raiden", line 11, in <module>
    sys.exit(main())
  File "/home/oliver/.virtualenvs/demo/lib/python3.6/site-packages/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/home/oliver/.virtualenvs/demo/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/oliver/.virtualenvs/demo/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/oliver/.virtualenvs/demo/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/oliver/.virtualenvs/demo/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/oliver/.virtualenvs/demo/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/oliver/.virtualenvs/demo/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/oliver/.virtualenvs/demo/lib/python3.6/site-packages/raiden/ui/cli.py", line 1105, in run
    NodeRunner(kwargs, ctx).run()
  File "/home/oliver/.virtualenvs/demo/lib/python3.6/site-packages/raiden/ui/cli.py", line 886, in run
    click.secho(self._welcome_string, fg='green')
  File "/home/oliver/.virtualenvs/demo/lib/python3.6/site-packages/raiden/ui/cli.py", line 875, in _welcome_string
    return f"Welcome to Raiden, version {get_system_spec()['raiden']}!"
  File "/home/oliver/.virtualenvs/demo/lib/python3.6/site-packages/raiden/utils/__init__.py", line 192, in get_system_spec
    raiden=pkg_resources.require(raiden.__name__)[0].version,
  File "/home/oliver/.virtualenvs/demo/lib/python3.6/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/oliver/.virtualenvs/demo/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (ipython 4.2.1 (/home/oliver/.virtualenvs/demo/lib/python3.6/site-packages), Requirement.parse('ipython<7.0.0,>=6.2.1'), {'py-evm'})
`

**Comment by pcppcp** [comment]
it looks like `eth-tester` pulls dependencies that are incompatible with what is specified in Raiden requirements. I'll hopefully fix this tomorrow.

**Comment by ulope** [comment]
@pcppcp AFAIK this will be fixed by a new web3.py release. See the web3 issue you linked.
