### ISSUE TITLE
Raiden client is crashing

### ISSUE THREAD

**Issue by kelsos** [raiden-network/raiden#2431]
## Problem Definition
```
Traceback (most recent call last):
  File "/home/kelsos/.virtualenvs/raiden/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/ui/cli.py", line 1110, in run
    NodeRunner(kwargs, ctx).run()
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/ui/cli.py", line 943, in run
    app = self._run_app()
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/ui/cli.py", line 961, in _run_app
    app_ = run_app(**self._options)
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/ui/cli.py", line 780, in run_app
    raiden_app.start()
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/app.py", line 130, in start
    self.raiden.start()
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/raiden_service.py", line 314, in start
    self.raiden_event_handler.on_raiden_event(self, transaction)
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/raiden_event_handler.py", line 84, in on_raiden_event
    self.handle_contract_send_channelsettle(raiden, event)
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/raiden_event_handler.py", line 364, in handle_contract_send_channelsettle
    second_locksroot,
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/network/proxies/payment_channel.py", line 214, in settle
    partner_locksroot=partner_locksroot,
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/network/proxies/token_network.py", line 920, in settle
    channel_identifier,
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/network/proxies/token_network.py", line 1114, in _check_channel_state_for_settle
    'Channel cannot be settled before closing',
raiden.exceptions.RaidenRecoverableError: Channel cannot be settled before closing
--- Logging error ---
Exception ignored in: <function BaseFileLock.__del__ at 0x7fa0077281e0>
Traceback (most recent call last):
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.7/site-packages/filelock.py", line 330, in __del__
  File "/home/kelsos/.virtualenvs/raiden/lib/python3.7/site-packages/filelock.py", line 317, in release
  File "/usr/lib64/python3.7/logging/__init__.py", line 1332, in info
  File "/usr/lib64/python3.7/logging/__init__.py", line 1468, in _log
  File "/usr/lib64/python3.7/logging/__init__.py", line 1478, in handle
  File "/usr/lib64/python3.7/logging/__init__.py", line 1540, in callHandlers
  File "/usr/lib64/python3.7/logging/__init__.py", line 854, in handle
  File "/usr/lib64/python3.7/logging/__init__.py", line 989, in emit
  File "/usr/lib64/python3.7/logging/__init__.py", line 907, in handleError
  File "/usr/lib64/python3.7/traceback.py", line 100, in print_exception
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/log_config.py", line 158, in tracebackexception_format
  File "/home/kelsos/development/github/raiden-network/raiden/raiden/log_config.py", line 143, in processor_wrapper
ImportError: sys.meta_path is None, Python is likely shutting down
```

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
Linux forseti 4.18.5-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 24 12:48:58 UTC 2018 x86_64 GNU/Linux
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Linux.g++
/usr/bin/geth
Geth
Version: 1.8.15-stable
Git Commit: 89451f7c382ad2185987ee369f16416f89c28a7d
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.3
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go
/home/kelsos/.virtualenvs/raiden/bin/raiden
{
  "raiden": "0.7.1.dev178+g96a771e4",
  "python_implementation": "CPython",
  "python_version": "3.7.0",
  "system": "Linux 64bit_ELF 4.18.5-arch1-1-ARCH x86_64",
  "distribution": "source"
}
96a771e41be8d7413deb695e518b4c5dd08f30d6

```

**Comment by LefterisJP** [comment]
Thanks kelsos. I am looking at it.

**Comment by czepluch** [comment]
I get the same error

**Comment by czepluch** [comment]
I think in order to recreate this problem one must close a channel and then be offline when the settlement period is over. I am pretty sure this is what I did for it to happen. Will try to recreate it with a fresh account.

**Comment by LefterisJP** [comment]
That sounds like it @czepluch.

The problem is that we were not catching RecoverableErrors when we were handle pending transactions during raiden's start. That's what #2432 does.

**Comment by LefterisJP** [comment]
But note that for this to work both you and your partner need to be offline. Or else you would get a different error and Raiden would notice that the channel is settled by the partner before handling the pending transactions.

**Comment by czepluch** [comment]
Yeah, I think that's exactly what happened. Because I forgot that the settle period was on going and I shut down both my nodes.
