### ISSUE TITLE
Node is crashing

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2440]
## Problem Definition

Node crashes when restarted with the following traceback. 
```
Traceback (most recent call last):
  File "/home/cosmin/.virtualenvs/raiden/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 1110, in run
    NodeRunner(kwargs, ctx).run()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 943, in run
    app = self._run_app()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 961, in _run_app
    app_ = run_app(**self._options)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 780, in run_app
    raiden_app.start()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/app.py", line 130, in start
    self.raiden.start()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/raiden_service.py", line 221, in start
    storage,
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/storage/wal.py", line 9, in restore_from_latest_snapshot
    snapshot = storage.get_latest_state_snapshot()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/storage/sqlite.py", line 135, in get_latest_state_snapshot
    snapshot_state = self.serializer.deserialize(serialized[0][1])
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/storage/serialize.py", line 87, in deserialize
    return json.loads(data, cls=RaidenJSONDecoder)
  File "/usr/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/storage/serialize.py", line 53, in object_hook
    obj = klass.from_dict(data)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/transfer/state.py", line 317, in from_dict
    pseudo_random_generator = pseudo_random_generator_from_json(data)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/transfer/utils.py", line 28, in pseudo_random_generator_from_json
    state = list(data['pseudo_random_generator'])  # copy
KeyError: 'pseudo_random_generator'
--- Logging error ---
Exception ignored in: <bound method BaseFileLock.__del__ of <filelock.UnixFileLock object at 0x7fc14c39df98>>
Traceback (most recent call last):
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/filelock.py", line 330, in __del__
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/filelock.py", line 317, in release
  File "/usr/lib/python3.6/logging/__init__.py", line 1306, in info
  File "/usr/lib/python3.6/logging/__init__.py", line 1442, in _log
  File "/usr/lib/python3.6/logging/__init__.py", line 1452, in handle
  File "/usr/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
  File "/usr/lib/python3.6/logging/__init__.py", line 863, in handle
  File "/usr/lib/python3.6/logging/__init__.py", line 998, in emit
  File "/usr/lib/python3.6/logging/__init__.py", line 916, in handleError
  File "/usr/lib/python3.6/traceback.py", line 100, in print_exception
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/log_config.py", line 158, in tracebackexception_format
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/log_config.py", line 143, in processor_wrapper
ImportError: sys.meta_path is None, Python is likely shutting down
```
### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
Linux  4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Linux.g++
/usr/bin/geth
Geth
Version: 1.8.12-stable
Git Commit: 37685930d953bcbe023f9bc65b135a8d8b8f1488
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.1
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.10
2f6a55243a9a32c58d710d3cf2bda0ba741c6a9b
```

**Comment by LefterisJP** [comment]
After https://github.com/raiden-network/raiden/pull/2399 you need a new DB. We have not upgraded the DB version since there may be more breaking changes until next release.
