### ISSUE TITLE
Greenlet that fails with MatrixHttpLibError should stop the node

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2447]
## Problem Definition

While testing out the raiden client I have experienced the following error. The weird part is that my node continue running, when it should have crashed. 

```
Traceback (most recent call last):
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/gevent/_ssl3.py", line 503, in recv_into
    return self.read(nbytes, buffer)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/gevent/_ssl3.py", line 327, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/gevent/_ssl3.py", line 503, in recv_into
    return self.read(nbytes, buffer)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/gevent/_ssl3.py", line 327, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/matrix_client/api.py", line 670, in _send
    verify=self.validate_cert
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/network/transport/matrix.py", line 700, in retry
    self._send_raw(receiver_address, data)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/network/transport/matrix.py", line 747, in _send_raw
    room.send_text(data)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/matrix_client/room.py", line 105, in send_text
    return self.client.api.send_message(self.room_id, text)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/matrix_client/api.py", line 336, in send_message
    timestamp=timestamp
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/matrix_client/api.py", line 256, in send_message_event
    return self._send("PUT", path, content, query_params=params)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/raiden_libs/network/matrix/client.py", line 75, in _send
    return super()._send(method, path, *args, **kwargs)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/matrix_client/api.py", line 673, in _send
    raise MatrixHttpLibError(e, method, endpoint)
matrix_client.errors.MatrixHttpLibError: Something went wrong in PUT requesting https://transport01.raiden.network/_matrix/client/r0/rooms/%21czfGhAfMplUeElSqCi%3Atransport01.raiden.network/send/m.room.message/431536744119688: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2018-09-12T09:23:02Z <Greenlet "Greenlet-4" at 0x7f3dae8d8548: retry> failed with MatrixHttpLibError
```

Log: https://gist.github.com/CosminNechifor/c6fbabc265bd53605fd4c0bd796009c4

### System Description

```
Linux cosmin-Lenovo-ideapad-100-15IBD 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Linux.g++
/usr/bin/geth
Geth
Version: 1.8.12-stable
Git Commit: 37685930d953bcbe023f9bc65b135a8d8b8f1488
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.1
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.10
cdefd83c90980dd6a41e9fc1d15b16ca4160e869
```

**Comment by andrevmatos** [comment]
@ulope that `retry` function is explictly being `link_exception`ed to the `MatrixTransport`, which should kill the `Runnable` and bubble up the exception, but it's not happening.. any chance of `gevent.spawn` running the function before the [link_exception](https://github.com/raiden-network/raiden/blob/7facbf3f9ce025c8fcbaa76983deb2bab045540a/raiden/network/transport/matrix.py#L248) is called?

**Comment by CosminNechifor** [comment]
I will close it since I could not reproduce it.
