### ISSUE TITLE
handle_request_parsing_error expects only 1 parameter, webargs>=4 calls it with 3

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden#2489]
## Problem Definition

After #2469, rest tests that tests for invalid parameters are failing with following traceback:
```
2018-09-14 12:50:59 [error    ] Exception on /api/1/channels/0xdE363F6c2AE831bF7e56ff58D17adDb31F73f95F/0x61C808D82A3Ac53231750daDc13c777b59310bD9 [PATCH] [flask.app]
Traceback (most recent call last):
  File "/sec/Dev/BrainBot/raiden/venv/lib/python3.7/site-packages/webargs/core.py", line 392, in parse
    result = schema.load(parsed)
  File "/sec/Dev/BrainBot/raiden/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 576, in load
    result, errors = self._do_load(data, many, partial=partial, postprocess=True)
  File "/sec/Dev/BrainBot/raiden/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 699, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'state': ['Not a valid choice.']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sec/Dev/BrainBot/raiden/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/sec/Dev/BrainBot/raiden/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/sec/Dev/BrainBot/raiden/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/sec/Dev/BrainBot/raiden/venv/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/sec/Dev/BrainBot/raiden/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/sec/Dev/BrainBot/raiden/venv/lib/python3.7/site-packages/webargs/core.py", line 474, in wrapper
    force_all=force_all,
  File "/sec/Dev/BrainBot/raiden/venv/lib/python3.7/site-packages/webargs/core.py", line 396, in parse
    self._on_validation_error(error, req, schema)
  File "/sec/Dev/BrainBot/raiden/venv/lib/python3.7/site-packages/webargs/core.py", line 334, in _on_validation_error
    self.error_callback(error, req, schema)
TypeError: handle_request_parsing_error() takes 1 positional argument but 3 were given
```

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
Linux galaaz 4.18.7-arch1-1-ARCH #1 SMP PREEMPT Sun Sep 9 11:27:58 UTC 2018 x86_64 GNU/Linux
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Linux.g++
/usr/bin/geth
Geth
Version: 1.8.15-stable
Git Commit: 89451f7c382ad2185987ee369f16416f89c28a7d
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.3
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go
/sec/Dev/BrainBot/raiden/venv/bin/raiden
{
  "raiden": "0.8.1.dev118+g98d20d11",
  "python_implementation": "CPython",
  "python_version": "3.7.0",
  "system": "Linux 64bit_ 4.18.7-arch1-1-ARCH x86_64",
  "distribution": "source"
}
39a2f547b7dfc9b201dfca6b12ebd80d9dc5d932
```

**Comment by LefterisJP** [comment]
Argh ... we should really make [ci integration] the default.
