### ISSUE TITLE
crash on restart

### ISSUE THREAD

**Issue by alemhnan** [raiden-network/raiden#2495]
Hello,

I'm trying to run raiden in my local computer. The first run is fine, but after a while it crash and it seems I cannot run anymore. 

I'm using the ropsten network.
I'm with a friend and we both experienced the same timing on crash. I tried with my mobile as hotspot to rule out router problem but is I still cannot make it work. 

I tried with v0.9.0 and also the latest master. On a Mac with 10.13.6 and python 3.7.

```bash
You are connected to the 'ropsten' network and the DB path is: /Users/alemhnan/.raiden/node_8f2e9381/netid_3/network_f2a175a5/v3_log.db
2018-09-15 16:12:06 [info     ] Automatically selecting matrix homeserver based on RTT [raiden.network.transport.matrix] homeserver=https://transport03.raiden.network rtt=0.01689033333333333
2018-09-15 16:12:06 [info     ] Lock 4600751496 acquired on /Users/alemhnan/.raiden/node_8f2e9381/netid_3/network_f2a175a5/.lock [filelock] 
2018-09-15 16:12:11 [info     ] LOGIN                          [raiden.network.transport.matrix] current_user=@0x8f2e93813e2cc930230bd5493f67b48308268a5b:transport03.raiden.network homeserver=transport03.raiden.network node=8f2e9381 server_url=https://transport03.raiden.network username=0x8f2e93813e2cc930230bd5493f67b48308268a5b
2018-09-15 16:12:16 [info     ] TRANSPORT STARTED              [raiden.network.transport.matrix] config={'available_servers': ['https://transport01.raiden.network', 'https://transport02.raiden.network', 'https://transport03.raiden.network'], 'discovery_room': 'discovery', 'retries_before_backoff': 5, 'retry_interval': 5.0, 'server': 'auto'} current_user=@0x8f2e93813e2cc930230bd5493f67b48308268a5b:transport03.raiden.network node=8f2e9381
Traceback (most recent call last):
  File "/Users/alemhnan/Projects/Raiden/raiden/venv-raiden/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/Users/alemhnan/Projects/Raiden/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/Users/alemhnan/Projects/Raiden/raiden/venv-raiden/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/alemhnan/Projects/Raiden/raiden/venv-raiden/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/alemhnan/Projects/Raiden/raiden/venv-raiden/lib/python3.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/Users/alemhnan/Projects/Raiden/raiden/venv-raiden/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/alemhnan/Projects/Raiden/raiden/venv-raiden/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/alemhnan/Projects/Raiden/raiden/venv-raiden/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/alemhnan/Projects/Raiden/raiden/raiden/ui/cli.py", line 1119, in run
    NodeRunner(kwargs, ctx).run()
  File "/Users/alemhnan/Projects/Raiden/raiden/raiden/ui/cli.py", line 950, in run
    app = self._run_app()
  File "/Users/alemhnan/Projects/Raiden/raiden/raiden/ui/cli.py", line 968, in _run_app
    app_ = run_app(**self._options)
  File "/Users/alemhnan/Projects/Raiden/raiden/raiden/ui/cli.py", line 787, in run_app
    raiden_app.start()
  File "/Users/alemhnan/Projects/Raiden/raiden/raiden/app.py", line 127, in start
    self.raiden.start()
  File "/Users/alemhnan/Projects/Raiden/raiden/raiden/raiden_service.py", line 303, in start
    self.alarm.first_run()
  File "/Users/alemhnan/Projects/Raiden/raiden/raiden/tasks.py", line 163, in first_run
    self._run_callbacks(current_block)
  File "/Users/alemhnan/Projects/Raiden/raiden/raiden/tasks.py", line 169, in _run_callbacks
    result = callback(current_block)
  File "/Users/alemhnan/Projects/Raiden/raiden/raiden/raiden_service.py", line 469, in _callback_new_block
    for event in self.blockchain_events.poll_blockchain_events(current_block_number):
  File "/Users/alemhnan/Projects/Raiden/raiden/raiden/blockchain/events.py", line 338, in poll_blockchain_events
    log_event,
  File "/Users/alemhnan/Projects/Raiden/raiden/raiden/utils/filters.py", line 93, in decode_event
    event_abi = topic_to_event_abi[event_id]
KeyError: HexBytes('0x5fe3d4a343010393184843ef4873386b572e844e89f6b41c9f60f5ab912fbdfe')`

**Comment by alemhnan** [comment]
Hello @andrevmatos ,

thanks for the prompt reply. 

I'm following this [guide](https://raiden-network.readthedocs.io/en/stable/macos_install_guide.html#macos-development-setup) (mac os x setup )and [this](https://raiden-network.readthedocs.io/en/stable/webui_tutorial.html) one (web ui tutorial). 

I'm using the infura ropsten network. I'm bit confused about what you say about the contracts. 
Does the web ui assume that I deploy ex novo the raiden contracts or there are some test contracts out there used by the web ui in the tutorial?

I'm digging out info in those past days so I apologies if questions are maybe a bit silly.

**Comment by andrevmatos** [comment]
@alemhnan No need to re-deploy the contracts, they're deployed in Ropsten and the addresses are in the `constants.py` file. But Raiden needs the contracts source codes to get the ABI to interact with it, therefore, it needs a split package called `raiden-contracts` (you can see it in the [requirements.txt](https://github.com/raiden-network/raiden/blob/f68cc1ec358d7ec4b0a95f4465462d889901afe4/requirements.txt#L25) file). Your error means you're using an incompatible `raiden-contracts` version, probably some leftover from an old virtualenv, and also, the 8-9 steps from the guide you linked were recently updated (readthedocs should be updated shortly).
So, after creating a new virtualenv, try the [guide from github](https://github.com/raiden-network/raiden/blob/master/docs/macos_install_guide.rst#development-setup-on-macos)

**Comment by LefterisJP** [comment]
@alemhnan This is probably related to https://github.com/raiden-network/raiden-contracts/issues/266.

The last `raiden-contracts` package seems to have had old precompiled contracts. Once the above issue is fixed (in the next release) everything should be fine.

You can also have `solc` locally and make sure that you compile the contracts yourself instead of using the precompiled ones as a temporary solution.

**Comment by pcppcp** [comment]
Should be fixed by
https://github.com/raiden-network/raiden-contracts/pull/268

If you still experience the problem, feel free to reopen this issue ;)

**Comment by alemhnan** [comment]
Thanks a lot guys.
I will check again soon and re-open if needed.
