### ISSUE TITLE
Raiden crashes when trying to update the non closing balance proof 

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2566]
## Problem Definition
```
2018-09-24 09:35:42 [debug    ] send_raw_transaction called    [raiden.network.rpc.client] account=0x2BA1B53C174f6F917CFBe64220646BB38860F870 gasLimit=6388398 gasPrice=2932788091 nonce=15
2018-09-24 09:35:42 [debug    ] send_raw_transaction returned  [raiden.network.rpc.client] account=0x2BA1B53C174f6F917CFBe64220646BB38860F870 gasLimit=6388398 gasPrice=2932788091 nonce=15 tx_hash=HexBytes('0x70a3fd9194938c8c001c2c9551f322d26d099c8e31ca6b3d0bf865e2be075309')
2018-09-24 09:35:53 [critical ] updateNonClosingBalanceProof failed [raiden.network.proxies.token_network] additional_hash=0xe70357733ed35fd133e38b03ab88d9172e99b4ae87cd62362cf4d80966ad64ab balance_hash=0xef662a629ce07c9ed715124d8141a6e430d0a3065f8ce8074a7ea95e8751f184 closing_signature=0xc823019b096d146bdae00b0423376cb8ecccdfe83761293cc4e5197d63af5d3a755dd852feab1e40911bb770758be6c5616d6c797e668e2c91ab0a523baf3c6b1b node=2ba1b53c non_closing_signature=0x137af9c2f29feaaa226cfdb8ff3c9091bca7ec72976fd4f346f66e5b07bf884f73b4f42f17edcd149446e72bcbfb4ca6dae98b7a6f5d2eb1832a9a1028637ae11c nonce=4 partner=22d8f4db token_network=6cb21c7d
Traceback (most recent call last):
  File "/home/cosmin/.virtualenvs/raiden/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 1120, in run
    NodeRunner(kwargs, ctx).run()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 951, in run
    app = self._run_app()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 969, in _run_app
    app_ = run_app(**self._options)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/ui/cli.py", line 787, in run_app
    raiden_app.start()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/app.py", line 127, in start
    self.raiden.start()
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/raiden_service.py", line 318, in start
    self.raiden_event_handler.on_raiden_event(self, transaction)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/raiden_event_handler.py", line 80, in on_raiden_event
    self.handle_contract_send_channelupdate(raiden, event)
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/raiden_event_handler.py", line 288, in handle_contract_send_channelupdate
    our_signature,
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/network/proxies/payment_channel.py", line 186, in update_transfer
    non_closing_signature=signature,
  File "/home/cosmin/Documents/WORK/GITHUB/raiden/raiden/network/proxies/token_network.py", line 734, in update_transfer
    raise TransactionThrew('Update NonClosing balance proof', receipt_or_none)
raiden.exceptions.TransactionThrew: Update NonClosing balance proof transaction threw. Receipt=AttributeDict({'blockHash': HexBytes('0xed93377c5d15ca628fac433b3020d4f6a63fcb64073239503bcd34f4faeee7cc'), 'blockNumber': 4103863, 'contractAddress': None, 'cumulativeGasUsed': 513459, 'from': '0x2ba1b53c174f6f917cfbe64220646bb38860f870', 'gasUsed': 56362, 'logs': [], 'logsBloom': HexBytes('0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'), 'status': 0, 'to': '0x6cb21c7d6a56d16d22c5f4ee2f2a9515b3d9607b', 'transactionHash': HexBytes('0x70a3fd9194938c8c001c2c9551f322d26d099c8e31ca6b3d0bf865e2be075309'), 'transactionIndex': 6})
```

Full log: https://gist.github.com/CosminNechifor/5b6b935b8ab6d6c77c25db7f92b5eb30

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.25+commit.59dbf8f1.Linux.g++
/usr/bin/geth
Geth
Version: 1.8.15-stable
Git Commit: 89451f7c382ad2185987ee369f16416f89c28a7d
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.1
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.10
/home/cosmin/.virtualenvs/raiden/bin/raiden
{
  "raiden": "0.10.1.dev2+g6aefe331",
  "python_implementation": "CPython",
  "python_version": "3.6.5",
  "system": "Linux 64bit_ELF 4.15.0-34-generic x86_64",
  "distribution": "source"
}
6aefe331fb46ff9584f307a46cc1e256ab76a965
```

**Comment by CosminNechifor** [comment]
Both nodes after the restart crash with the following: https://gist.github.com/CosminNechifor/52f5bf31b5abad2f40349db1e287813d

**Comment by rakanalh** [comment]
@CosminNechifor, @hackaugusto and I figured that the node was unable to find the proper balance proof because the channel data exist in an older DB file and only data from after the upgrade was found in the newer DB.
This will be apparent to you when you execute `tree ~/.raiden` and find that some account folders have 2 DB files instead of just 1.
So in short, you need to reset your state since it's distributed between 2 incompatible DB files.

**Comment by rakanalh** [comment]
I am going to close this issue as the PR linked above doesn't directly resolve this issue but warns about it's potential.
