### ISSUE TITLE
Matrix: https://travis-ci.org/raiden-network/raiden/jobs/432942640#L2149

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#2594]
## Problem Definition

In a run of the integration tests the following Traceback appeared (https://travis-ci.org/raiden-network/raiden/jobs/432942640#L2149):
```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/raiden_libs/network/matrix/client.py", line 328, in _handle_response
    self.call(listener, room_id, invite_room['invite_state'])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/raiden_libs/network/matrix/client.py", line 307, in call
    return callback(*args, **kwargs)
  File "/home/travis/build/raiden-network/raiden/raiden/network/transport/matrix.py", line 546, in _handle_invite
    room = self._client.join_room(room_id)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/matrix_client/client.py", line 320, in join_room
    response = self.api.join_room(room_id_or_alias)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/matrix_client/api.py", line 195, in join_room
    return self._send("POST", path)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/raiden_libs/network/matrix/client.py", line 75, in _send
    return super()._send(method, path, *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/matrix_client/api.py", line 691, in _send
    code=response.status_code, content=response.text
matrix_client.errors.MatrixRequestError: 404: {"errcode":"M_UNKNOWN","error":"No known servers"}
2018-09-25T13:45:06Z <Greenlet "Greenlet-39" at 0x7f5b6c0b5d48: <bound method GMatrixClient._handle_response of <raiden_libs.network.matrix.client.GMatrixClient object at 0x7f5b6c336908>>({'next_batch': 's60_8_0_1_10_1_1_7_1', 'device_one)> failed with MatrixRequestError
```

**Comment by andrevmatos** [comment]
@ulope the job was restarted, but I could see the `Inviting` line before, in which both the inviter and invited users belonged to the `raiden.local.network` server (from tests). Any idea what could cause it?

**Comment by palango** [comment]
Ah sorry, thought the log would stay available. Will download it next time.

**Comment by andrevmatos** [comment]
No problem, that info should be enough, this error shouldn't happen and seems internal and specific to test synapse, not reported with real servers

**Comment by palango** [comment]
Happened again: https://travis-ci.org/raiden-network/raiden/jobs/433023132#L3499

**Comment by andrevmatos** [comment]
My debugging of this have show it is caused by a race condition on matrix's `_get_room_for_address` method. This method have the following workflow:
1. Get current room for that user
2. If there's any, return it, or else:
3. Get candidates
4. Get candidate's displayname and validate it
5. Create a room for that address, and invite the valid peers/partner's users
6. Set the crated room as the one to use for this address
6.1 Clear old (>2) rooms for this address

Well, obviously between 1 and 6, there's a lot of matrix http requests, io and context switches. This wasn't a problem before 6.1 was added, as all rooms would be valid for this user, but as we're eventually leaving these (not so) old rooms, the rooms ended up empty before the partner got all invites, triggering synapse to try to clean the room, but still inviting the partner to it, which made it fail due to a bug where empty rooms goes to limbo: they're queued for clean up, but are not yet, and users trying to join or access it after may get some weird results.
Solution is to not create rooms we'll leave before the partner has the opportunity to join, and this is done ensuring these races doesn't occur (so one and only one room is created for each partner). Serializing access to this method will do. I'm preparing a PR.
