### ISSUE TITLE
Raiden crashes with AddressWithoutCode exception on handling of TokenNetworkCreated

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden#2658]
## Problem Definition

[raiden-debug.log](https://gist.github.com/andrevmatos/fe5eb9d7f1f501b7c46e6e12f16ff893)

```
raiden_1   | 2018-10-02 13:38:16 [debug    ] Blockchain event               [raiden.blockchain_events_handler] chain_event=<Event contract: f2a175a5 event: {'args': AttributeDict({'token_address': '0xB6dD8cE977aa2853B5c6783a344B172C02b049BC', 'token_network_address': '0xa7e8C0462374Eaf2641e1a5F7c47f926eA6F6B3e'}), 'event': 'TokenNetworkCreated', 'logIndex': 1, 'transactionIndex': 2, 'transactionHash': HexBytes('0x1eb4e1b77aafb433674f15cdf052a04f1888a270315b77afda6ac32ec7af2c18'), 'address': '0xf2a175A52Bd3c815eD7500c765bA19652AB89B30', 'blockHash': HexBytes('0x181f21f7e06d23366cf0444db6a8ca8a3f44815cc9ef278b9c852dde465bbf3c'), 'blockNumber': 4156658, 'block_number': 4156658, 'token_network_address': b'\xa7\xe8\xc0F#t\xea\xf2d\x1e\x1a_|G\xf9&\xeaok>', 'token_address': b'\xb6\xdd\x8c\xe9w\xaa(S\xb5\xc6x:4K\x17,\x02\xb0I\xbc'}> contract=f2a175a5 node=008135fa
raiden_1   | Traceback (most recent call last):
raiden_1   |   File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
raiden_1   |   File "/app/raiden/raiden/tasks.py", line 98, in _run
raiden_1   |     self.loop_until_stop()
raiden_1   |   File "/app/raiden/raiden/tasks.py", line 159, in loop_until_stop
raiden_1   |     self._run_callbacks(latest_block)
raiden_1   |   File "/app/raiden/raiden/tasks.py", line 181, in _run_callbacks
raiden_1   |     result = callback(latest_block)
raiden_1   |   File "/app/raiden/raiden/raiden_service.py", line 517, in _callback_new_block
raiden_1   |     on_blockchain_event(self, event)
raiden_1   |   File "/app/raiden/raiden/blockchain_events_handler.py", line 306, in on_blockchain_event
raiden_1   |     handle_tokennetwork_new(raiden, event)
raiden_1   |   File "/app/raiden/raiden/blockchain_events_handler.py", line 37, in handle_tokennetwork_new
raiden_1   |     token_network_proxy = raiden.chain.token_network(token_network_address)
raiden_1   |   File "/app/raiden/raiden/network/blockchain_service.py", line 151, in token_network
raiden_1   |     address,
raiden_1   |   File "/app/raiden/raiden/network/proxies/token_network.py", line 81, in __init__
raiden_1   |     check_address_has_code(jsonrpc_client, manager_address, CONTRACT_TOKEN_NETWORK)
raiden_1   |   File "/app/raiden/raiden/network/rpc/client.py", line 79, in check_address_has_code
raiden_1   |     to_checksum_address(address),
raiden_1   | raiden.exceptions.AddressWithoutCode: [TokenNetwork]: Address 0xa7e8C0462374Eaf2641e1a5F7c47f926eA6F6B3e does not contain code
raiden_1   | 2018-10-02T13:38:16Z <Greenlet "AlarmTask|Greenlet-2" at 0x7faee8eab268: <bound method AlarmTask._run of <raiden.tasks.AlarmTask object at 0x7faee8ebc208>>> failed with AddressWithoutCode
raiden_1   |
raiden_1   | 2018-10-02 13:38:16 [error    ] Runnable subtask died!         [raiden.utils.runnable] exc=AddressWithoutCode('[TokenNetwork]: Address 0xa7e8C0462374Eaf2641e1a5F7c47f926eA6F6B3e does not contain code') running=True subtask=<Greenlet "AlarmTask|Greenlet-2" at 0x7faee8eab268: <bound method AlarmTask._run of <raiden.tasks.AlarmTask object at 0x7faee8ebc208>>> this=<RaidenService 008135fa>
```

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
Linux galaaz 4.18.11-arch1-1-ARCH #1 SMP PREEMPT Sat Sep 29 21:01:35 UTC 2018 x86_64 GNU/Linux
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.25+commit.59dbf8f1.Linux.g++
/sec/Dev/BrainBot/raiden/venv/bin/geth
Geth
Version: 1.8.15-stable
Git Commit: 89451f7c382ad2185987ee369f16416f89c28a7d
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.3
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go
/sec/Dev/BrainBot/raiden/venv/bin/raiden
{
  "raiden": "0.11.1.dev6+g34e4bdbd",
  "python_implementation": "CPython",
  "python_version": "3.7.0",
  "system": "Linux 64bit_ 4.18.11-arch1-1-ARCH x86_64",
  "distribution": "source"
}
de291393bcbc8372a3d3e9b2cbe2bfd4effc6993
```

**Comment by LefterisJP** [comment]
So what happens here is interesting.

`2018-10-02 13:38:08 [debug    ] Received new block             [raiden.tasks] block_hash=0x9090933603286c60852d309b596a387c9e90a5518d6bc452d848cabe6f9a15c6 gas_limit=7992442 number=4156656`

From the logs we can see that the last block we know is `4156656`. 

```
2018-10-02 13:38:16 [debug    ] Received new block             [raiden.tasks] block_hash=0x181f21f7e06d23366cf0444db6a8ca8a3f44815cc9ef278b9c852dde465bbf3c gas_limit=7992189 number=4156658
2018-10-02 13:38:16 [info     ] Missed block(s)                [raiden.tasks] latest_block=AttributeDict({'difficulty': 4436406617, 'proofOfAuthorityData': HexBytes('0xd583010702846765746885676f312e39856c696e7578'), 'gasLimit': 7992189, 'gasUsed': 3893704, 'hash': HexBytes('0x181f21f7e06d23366cf0444db6a8ca8a3f44815cc9ef278b9c852dde465bbf3c'), 'logsBloom': HexBytes('0x00004000000000000000000000000000000000000000000000000003000000000000000000440000000000000010000000000000000000000000000000000000080000000000000000000000000008000000000000000000000000000000000000000002000040000002000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000081000000000000000000000002000000000000000000002000000000000000000100000000800000000000000080000000400000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000'), 'miner': '0x7bF98C124ea83ca3E71A0AF2daead4DD2F025285', 'mixHash': HexBytes('0xc4f33cddc166e045b4f30a8d960b41af3ff3171a4a555d26142f87ca9893c864'), 'nonce': HexBytes('0xf24ee71981137733'), 'number': 4156658, 'parentHash': HexBytes('0xd68d44749e88efae96cb6c2e8ee18ccab09aeed643cec6ac3e4ecbae1f1ebaea'), 'receiptsRoot': HexBytes('0xd6f18a62d6ccd0ea0dc3730cd8b75f5d661916d9d3966e2b6e584921f4cb7628'), 'sha3Uncles': HexBytes('0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347'), 'size': 932, 'stateRoot': HexBytes('0xf788c94d0d472c98086618af761cfcda602a974e4177a24db001c995c4063122'), 'timestamp': 1538487490, 'totalDifficulty': 11846788973346807, 'transactions': [HexBytes('0x1f9ab629534f81fad114bbabaed86b8da6845ff3068e222a3b078e1ddfa102ae'), HexBytes('0xa0bfdf84b3b2bebe396f8196dfaebe9b59d59ea9feaa256ce25e3821dd6e6d31'), HexBytes('0x1eb4e1b77aafb433674f15cdf052a04f1888a270315b77afda6ac32ec7af2c18')], 'transactionsRoot': HexBytes('0x48c240ac878d744ca19526ae63a21a72ae902eadba9c8537e970d46481629265'), 'uncles': []}) missed_blocks=1
```

Then we get block `4156658` but we miss the previous block `4156657`.

Incidentally the TokenNetwork in question is indeed [created by a transaction in that block](https://ropsten.etherscan.io/tx/0x1eb4e1b77aafb433674f15cdf052a04f1888a270315b77afda6ac32ec7af2c18).

```
2018-10-02 13:38:16 [debug    ] Blockchain event               [raiden.blockchain_events_handler] chain_event=<Event contract: f2a175a5 event: {'args': AttributeDict({'token_address': '0xB6dD8cE977aa2853B5c6783a344B172C02b049BC', 'token_network_address': '0xa7e8C0462374Eaf2641e1a5F7c47f926eA6F6B3e'}), 'event': 'TokenNetworkCreated', 'logIndex': 1, 'transactionIndex': 2, 'transactionHash': HexBytes('0x1eb4e1b77aafb433674f15cdf052a04f1888a270315b77afda6ac32ec7af2c18'), 'address': '0xf2a175A52Bd3c815eD7500c765bA19652AB89B30', 'blockHash': HexBytes('0x181f21f7e06d23366cf0444db6a8ca8a3f44815cc9ef278b9c852dde465bbf3c'), 'blockNumber': 4156658, 'block_number': 4156658, 'token_network_address': b'\xa7\xe8\xc0F#t\xea\xf2d\x1e\x1a_|G\xf9&\xeaok>', 'token_address': b'\xb6\xdd\x8c\xe9w\xaa(S\xb5\xc6x:4K\x17,\x02\xb0I\xbc'}> contract=f2a175a5 node=008135fa
```

But then the moment we get block `4156658` we try to process the `TokenNetworkCreation` event and during that process the ethereum node looks at it internal state due to our call [here](https://github.com/raiden-network/raiden/blob/beebf8be1d77540eb35932332d3c41e07f91a1f9/raiden/network/rpc/client.py#L69):

 `client.web3.eth.getCode(to_checksum_address(address), 'latest')`

sees no code there and we crash.

---

Now the big question, why does that happen? We just got the block so perhaps the client (geth in your case) still has the data in the pending state? So according to the [JSON RPC wiki](https://github.com/ethereum/wiki/wiki/JSON-RPC#the-default-block-parameter) we could also use `'pending'` but I am not yet sure if this is a proper solution.

And testing it might be really hard.

**Comment by hackaugusto** [comment]
It seems the block [0x181f21](https://ropsten.etherscan.io/block/0x181f21f7e06d23366cf0444db6a8ca8a3f44815cc9ef278b9c852dde465bbf3c) was removed, so I guess this was a reorg and the block didn't become an uncle.

**Comment by LefterisJP** [comment]
Indeed, so even though that block did not contain anything related to the token network which causes the crash, the client may have just been in the middle of the reorg and we do not handle reorgs at all in our code.

Anyway though, adding the confirmations on the blockchain events polling will most probably fix this issue, right @hackaugusto ?

**Comment by LefterisJP** [comment]
Assuming this was a reorg closing this issue in favour of: https://github.com/raiden-network/raiden/issues/2711
