### ISSUE TITLE
[SP] 404 when sending transfer to invalid address

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#2706]
## Problem definition
When trying to make a transfer with an invalid address (non EIP55 fx), there SP gets a 404 error code. This is not expected behavior, and it should return 400 according to the documentation.

```
2018-10-08 10:13:37 [error    ] Exception while running scenario [scenario_player.main] 
Traceback (most recent call last):
  File "/home/jacob/tempRaiden/raiden/tools/scenario-player/scenario_player/main.py", line 123, in main
    assert_errors = runner.run_scenario()
  File "/home/jacob/tempRaiden/raiden/tools/scenario-player/scenario_player/runner.py", line 137, in run_scenario
    self.root_task()
  File "/home/jacob/tempRaiden/raiden/tools/scenario-player/scenario_player/tasks/base.py", line 62, in __call__
    return self._run(*args, **kwargs)
  File "/home/jacob/tempRaiden/raiden/tools/scenario-player/scenario_player/tasks/execution.py", line 43, in _run
    task()
  File "/home/jacob/tempRaiden/raiden/tools/scenario-player/scenario_player/tasks/base.py", line 62, in __call__
    return self._run(*args, **kwargs)
  File "/home/jacob/tempRaiden/raiden/tools/scenario-player/scenario_player/tasks/execution.py", line 43, in _run
    task()
  File "/home/jacob/tempRaiden/raiden/tools/scenario-player/scenario_player/tasks/base.py", line 62, in __call__
    return self._run(*args, **kwargs)
  File "/home/jacob/tempRaiden/raiden/tools/scenario-player/scenario_player/tasks/raiden_api.py", line 57, in _run
    f'HTTP status code "{resp.status_code}" while fetching {url}. '
scenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code "404" while fetching https://raiden-0001.testnet.raiden.network/api/1/payments/0x304064E4E8FD6e47e872AF4CEb76927Be566829B/0x02f4b6bc65561a792836212ebc54434db0ab759a. Expected 400: {"errors": ["invalid endpoint", "Not a valid EIP55 encoded address."]}
```

**Comment by palango** [comment]
@czepluch Can we get the node logs as well? And do you know what version these nodes run?

**Comment by LefterisJP** [comment]
The docs are wrong. URL errors should be a `404`

**Comment by czepluch** [comment]
@LefterisJP Currently if you provide a faulty address the API return a `400` with the message that the address might be invalid. That's what I would expect to happen too, since it helps debug the problem from a user's perspective. It's only when using the SP that it returns 404, the API return 400

**Comment by palango** [comment]
From how I understand the code it should always return 404 when a `InvalidEndpoint` error is thrown, do you have an example where this isn't the case?

btw. what does SP stand for?

**Comment by LefterisJP** [comment]
>  SP stand for?

I guess scenario player. But no need to double label an issue.

**Comment by czepluch** [comment]
@palango It stands for Scenario Player. 

And also it seems you guys are right. I just tested it out and it does indeed return 404 through the API also. My bad. Should we add the 404 error in the docs then?

**Comment by ulope** [comment]
I think we’re inconsistent here. I distinctly remember that there are endpoints that return 400 for invalid addresses.

**Comment by LefterisJP** [comment]
Yes we are incosistent. The task here is to re-untroduce consistency in the docs, and if needed in the API itself.

Rules:

- If there is an error in the URL return `404`
- If there is malformed request data return `400`
- If there are other errors in the values of the request then we just have `409` as a catch all.

**Comment by czepluch** [comment]
Closing this in favor of https://github.com/raiden-network/raiden/issues/2710
