### ISSUE TITLE
upnpsock exception when starting Raiden

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#2747]
Get the following when starting Raiden on latest master (version 0.12.1.dev30+g29a94164)

```
Have you read and acknowledged the above disclaimer? [y/N]: y
Traceback (most recent call last):
  File "/home/jacob/tempRaiden/raiden/.venv/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/home/jacob/tempRaiden/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/home/jacob/tempRaiden/raiden/.venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/jacob/tempRaiden/raiden/.venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/jacob/tempRaiden/raiden/.venv/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/jacob/tempRaiden/raiden/.venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jacob/tempRaiden/raiden/.venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jacob/tempRaiden/raiden/.venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jacob/tempRaiden/raiden/raiden/ui/cli.py", line 390, in run
    app = runner.run()
  File "/home/jacob/tempRaiden/raiden/raiden/ui/runners.py", line 207, in run
    listen_host, listen_port, strategy=self._options['nat'],
  File "/home/jacob/tempRaiden/raiden/raiden/network/sockfactory.py", line 76, in __enter__
    mapped_socket = getattr(self, 'map_{}'.format(method))()
  File "/home/jacob/tempRaiden/raiden/raiden/network/sockfactory.py", line 117, in map_upnp
    self.source_port,
  File "/home/jacob/tempRaiden/raiden/raiden/network/upnpsock.py", line 146, in open_port
    success = register(internal_port, external_port)
  File "/home/jacob/tempRaiden/raiden/raiden/network/upnpsock.py", line 142, in register
    '',
Exception: Action Failed
```

**Comment by ulope** [comment]
Probably caused by #2715
