### ISSUE TITLE
Inconsistent balance on my scenario

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2812]
## Problem Definition

When I run the scenario I created in PR [2673](https://github.com/raiden-network/raiden/pull/2763), it fails at one specific assertion, more exactly [here](https://github.com/raiden-network/raiden/pull/2763/files#diff-d3fc08ecac713941a3bed200a17e8930R216), and that's because node ``1`` thinks it has a balance of ``110`` instead of ``160``. It would be really helpful in the first steps of this issue if someone could take a look at my code and check if I did something wrong. 

One weird thing is that the channel has not been used since the last time I asserted for the balance [here](https://github.com/raiden-network/raiden/pull/2763/files#diff-d3fc08ecac713941a3bed200a17e8930R150), because I [shutdown](https://github.com/raiden-network/raiden/pull/2763/files#diff-d3fc08ecac713941a3bed200a17e8930R163) the node, and it was never used till the moment I restarted it [here](https://github.com/raiden-network/raiden/pull/2763/files#diff-d3fc08ecac713941a3bed200a17e8930R188) and assert for the balance.

The scenario code as said before can be found here: #2763 

This problem is reproducible every time, but in case you don't want to run it and wait ~30', I will provide the log of all 5 nodes in the network here and also the error that was shown in the scenario player. 

[logs.zip](https://github.com/raiden-network/raiden/files/2487299/logs.zip)

One more thing that I have to mention is that I have used a remote a remote parity node set on Kovan for testing my scenario.

### System Description

```
Linux noname 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux                                                                                        
/usr/bin/solc                                                                                                                                                                                    
solc, the solidity compiler commandline interface                                                                                                                                                
Version: 0.4.25+commit.59dbf8f1.Linux.g++                                                                                                                                                        
/usr/bin/geth                                                                                                                                                                                    
Geth                                                                                                                                                                                             
Version: 1.8.15-stable                                                                                                                                                                           
Git Commit: 89451f7c382ad2185987ee369f16416f89c28a7d                                                                                                                                             
Architecture: amd64                                                                                                                                                                              
Protocol Versions: [63 62]                                                                                                                                                                       
Network Id: 1                                                                                                                                                                                    
Go Version: go1.10.1                                                                                                                                                                             
Operating System: linux                                                                                                                                                                          
GOPATH=                                                                                                                                                                                          
GOROOT=/usr/lib/go-1.10                                                                                                                                                                          
/home/cosmin/.virtualenvs/raiden/bin/raiden 

{                                                                                                                                                                                                
  "raiden": "0.13.2.dev13+g777f6760",                                                                                                                                                            
  "python_implementation": "CPython",                                                                                                                                                            
  "python_version": "3.6.5",                                                                                                                                                                     
  "system": "Linux 64bit_ELF 4.15.0-36-generic x86_64",                                                                                                                                          
  "distribution": "source"                                                                                                                                                                       
}   

```

**Comment by LefterisJP** [comment]
@CosminNechifor At [this](https://github.com/raiden-network/raiden/pull/2763/files#diff-d3fc08ecac713941a3bed200a17e8930R121) line of your scenario you assert that `0` has transferred 50 tokens to `1`.

But where did this transfer happen? I see no such transfer before that line.

**Comment by CosminNechifor** [comment]
@LefterisJP Above [here](https://github.com/raiden-network/raiden/pull/2763/files#diff-d3fc08ecac713941a3bed200a17e8930R119). That's because it's a multi hop.

**Comment by LefterisJP** [comment]
Ah good did not see that. Thanks.

**Comment by LefterisJP** [comment]
Please run this with a geth client to see if it still happens. i run through the scenario code carefully and the balances add up until the point you said there is a failure.

**Comment by LefterisJP** [comment]
Also can you make another assert on the balance of channel `1` to `0` right after restart? It could be something related to the node's restart.

**Comment by CosminNechifor** [comment]
@LefterisJP will do it right now.

**Comment by CosminNechifor** [comment]
This is getting really weird: 

The assertion that I've done [here](https://github.com/raiden-network/raiden/pull/2763/files#diff-d3fc08ecac713941a3bed200a17e8930R203) fails:

```
- [✗] Assert (0:00:00.043478): {'from': 1, 'to': 0, 'total_deposit': 100, 'balance': 160, 'state': 'opened'} 
```

Fails with the following message: 

```
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                                                                                                              │
│  File "/home/cosmin/Documents/WORK/GITHUB/raiden/tools/scenario-player/scenario_player/tasks/base.py", line 70, in __call__                                                                                                                                                                                                                                                                                                                                    │
│    return self._run(*args, **kwargs)                                                                                                                                                                                                                                                                                                                                                                                                                           │
│  File "/home/cosmin/Documents/WORK/GITHUB/raiden/tools/scenario-player/scenario_player/tasks/execution.py", line 40, in _run                                                                                                                                                                                                                                                                                                                                   │
│    task()                                                                                                                                                                                                                                                                                                                                                                                                                                                      │
│  File "/home/cosmin/Documents/WORK/GITHUB/raiden/tools/scenario-player/scenario_player/tasks/base.py", line 70, in __call__                                                                                                                                                                                                                                                                                                                                    │
│    return self._run(*args, **kwargs)                                                                                                                                                                                                                                                                                                                                                                                                                           │
│  File "/home/cosmin/Documents/WORK/GITHUB/raiden/tools/scenario-player/scenario_player/tasks/execution.py", line 67, in _run                                                                                                                                                                                                                                                                                                                                   │
│    group.join(raise_error=True)                                                                                                                                                                                                                                                                                                                                                                                                                                │
│  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/gevent/pool.py", line 428, in join                                                                                                                                                                                                                                                                                                                                                         │
│    greenlet._raise_exception()                                                                                                                                                                                                                                                                                                                                                                                                                                 │
│  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception                                                                                                                                                                                                                                                                                                                                                                        │
│  File "/home/cosmin/.virtualenvs/raiden/lib/python3.6/site-packages/gevent/_compat.py", line 47, in reraise                                                                                                                                                                                                                                                                                                                                                    │
│    raise value.with_traceback(tb)                                                                                                                                                                                                                                                                                                                                                                                                                              │
│  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run                                                                                                                                                                                                                                                                                                                                                                                     │
│  File "/home/cosmin/Documents/WORK/GITHUB/raiden/tools/scenario-player/scenario_player/tasks/base.py", line 70, in __call__                                                                                                                                                                                                                                                                                                                                    │
│    return self._run(*args, **kwargs)                                                                                                                                                                                                                                                                                                                                                                                                                           │
│  File "/home/cosmin/Documents/WORK/GITHUB/raiden/tools/scenario-player/scenario_player/tasks/raiden_api.py", line 70, in _run                                                                                                                                                                                                                                                                                                                                  │
│    return self._process_response(response_dict)                                                                                                                                                                                                                                                                                                                                                                                                                │
│  File "/home/cosmin/Documents/WORK/GITHUB/raiden/tools/scenario-player/scenario_player/tasks/channels.py", line 93, in _process_response                                                                                                                                                                                                                                                                                                                       │
│    f'Value mismatch for "{field}". '                                                                                                                                                                                                                                                                                                                                                                                                                           │
│scenario_player.exceptions.ScenarioAssertionError: Value mismatch for "balance". Should: "160" Is: "110" Channel: {'reveal_timeout': 50, 'token_network_identifier': '0x9492b75FEC92616BC8E7073fE1f6610D6f07E1aA', 'partner_address': '0x05925D888c04C3a30493bC6cBea920eB5c3435ae', 'token_address': '0x42a2147397616e4980eA9A4b2E1e8357545cF9cb', 'balance': 110, 'channel_identifier': 3, 'state': 'opened', 'settle_timeout': 500, 'total_deposit': 100}  
```

And If I start the node manually and query the rest endpoint that checks for the balance I get the following.
```
│scenario_player.exceptions.ScenarioAssertionError: Value mismatch for "balance". Should: "160" Is: "110" Channel: {'reveal_timeout': 50, 'token_network_identifier': '0x9492b75FEC92616BC8E7073fE1f6610D6f07E1aA', 'partner_address': '0x05925D888c04C3a30493bC6cBea920eB5c3435ae', 'token_address': '0x42a2147397616e4980eA9A4b2E1e8357545cF9cb', 'balance': 110, 'channel_identifier': 3, 'state': 'opened', 'settle_timeout': 500, 'total_deposit': 100} 
```
| token_network_identifier | "0x9492b75FEC92616BC8E7073fE1f6610D6f07E1aA" |
| -- | -- |
| settle_timeout | 500 | 
| channel_identifier | 3|
| state | "opened"| 
| total_deposit | 100 |
| token_address | "0x42a2147397616e4980eA9A4b2E1e8357545cF9cb" |
| balance | 100 |
| partner_address | "0x05925D888c04C3a30493bC6cBea920eB5c3435ae" |
| reveal_timeout | 50 |

**Comment by palango** [comment]
@czepluch Can you check if this scenario still makes problems?

**Comment by czepluch** [comment]
Was not able to recreate this
