### ISSUE TITLE
Raiden crashes when starting on Kovan/Rinkeby with `--network-type test`

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#2836]
Stack trace on latest master:

```
Traceback (most recent call last):
  File "/home/lefteris/ew/raiden/raiden/ui/app.py", line 326, in run_app
    contracts[CONTRACT_TOKEN_NETWORK_REGISTRY]['address'],
  File "/home/lefteris/ew/raiden/raiden/network/blockchain_service.py", line 147, in token_network_registry
    contract_manager=self.contract_manager,
  File "/home/lefteris/ew/raiden/raiden/network/proxies/token_network_registry.py", line 59, in __init__
    raise ContractVersionMismatch('Incompatible ABI for TokenNetworkRegistry')
raiden.exceptions.ContractVersionMismatch: Incompatible ABI for TokenNetworkRegistry

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lefteris/ew/raiden/raiden/__main__.py", line 15, in <module>
    main()
  File "/home/lefteris/ew/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/lefteris/ew/raiden/raiden/ui/cli.py", line 397, in run
    app = runner.run()
  File "/home/lefteris/ew/raiden/raiden/ui/runners.py", line 243, in run
    return self._start_services()
  File "/home/lefteris/ew/raiden/raiden/ui/runners.py", line 97, in _start_services
    app_ = run_app(**self._options)
  File "/home/lefteris/ew/raiden/raiden/ui/app.py", line 330, in run_app
    handle_contract_version_mismatch('token network registry', registry_contract_address)
  File "/home/lefteris/ew/raiden/raiden/ui/app.py", line 55, in handle_contract_version_mismatch
    hex_addr = to_checksum_address(address)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/eth_utils/address.py", line 129, in to_checksum_address
    norm_address = to_normalized_address(value)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/eth_utils/address.py", line 75, in to_normalized_address
    hex_address = hexstr_if_str(to_hex, value).lower()
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/eth_utils/conversions.py", line 157, in hexstr_if_str
    return to_type(primitive, hexstr=hexstr)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/eth_utils/decorators.py", line 73, in wrapper
    _assert_one_val(*args, **kwargs)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/eth_utils/decorators.py", line 39, in _assert_one_val
    "Instead, values were: %r, %r" % (args, kwargs)
TypeError: Exactly one of the passed values can be specified. Instead, values were: (None,), {'hexstr': None}

```

**Comment by LefterisJP** [comment]
So as we found out it was the version check that was wrong, so it's temporarilly commented out [here](https://github.com/raiden-network/raiden/pull/2837) until the new test network contracts are deployed.

Let's keep this issue open until this is done and then re-instate the check and close the issue.

**Comment by LefterisJP** [comment]
With further investigation turns out that the problem was in the version check. Since we got multiple deployed versions can't always expect the same version. So now the version check extracts the expected version from the deployed data taken from the contract manager. Implemented by: https://github.com/raiden-network/raiden/pull/2841
