### ISSUE TITLE
Fix python2 synapse bundling html import error

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden#2906]
## Problem Definition

All of sudden, `install_synapse.sh`, which generates the `.synapse/synapse` bundle which is used in test suite stopped working. It was not possible to reproduce the issue locally, as even in a pristine `python:2.7.12` (version reported by Travis) the script worked normally.
The traceback reported was:
```
+/home/travis/.bin/synapse.12fa0f9 --server-name=matrix.local.raiden --config-path=/home/travis/.bin/synapse-config.yaml --generate-keys
Traceback (most recent call last):
  File "site-packages/synapse/app/homeserver.py", line 60, in <module>
  File "/tmp/pip-install-Ee8m2B/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/synapse/rest/__init__.py", line 21, in <module>
  File "/tmp/pip-install-Ee8m2B/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/synapse/rest/client/v1/login.py", line 22, in <module>
  File "/tmp/pip-install-Ee8m2B/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/saml2/config.py", line 21, in <module>
  File "/tmp/pip-install-Ee8m2B/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/saml2/mdstore.py", line 26, in <module>
  File "/tmp/pip-install-Ee8m2B/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/saml2/httpbase.py", line 13, in <module>
  File "/tmp/pip-install-Ee8m2B/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/saml2/pack.py", line 11, in <module>
ImportError: No module named html
[5354] Failed to execute script homeserver
```

Notice `html` is a python3 module, provided in python2 through the `future` pypi package, which was installed, but `html` somehow was not available in the temporary python2 virtualenv in Travis.
But `html` is only needed as a simple import from `pysaml2`, a package required by `synapse` but never used, as we don't do `saml2` authentication in raiden, only plain login/password.
Therefore, the solution in #2904 was to trigger `pyinstaller` to install [html.py](https://pypi.org/project/HTML.py), which I'm not sure is compatible with the future's `html` module, but as it's a import-time only issue, this should never be a problem, as long as we don't use effectively `pysaml2` authentication in test suite. 
- Plan B would be to compile the package locally and provide it somewhere for download by the test suite.
- Plan C and eventually definitive fix for these synapse bundling issues is to move to Python3 synapse dist directly in our `requirements-dev.txt` and use it with all its dependencies under same virtualenv as Raiden.

**Comment by ulope** [comment]
Will be obsolete once #3172 is merged.
