### ISSUE TITLE
Parallel payment requests crashed the nodes - Logs from Storj

### ISSUE THREAD

**Issue by super3** [raiden-network/raiden#2947]
We took part in the workshop. 

1) Parallel payment requests crashed the nodes
2) Had lots of insufficient funds errors

```
#!/bin/bash
for i in `seq 1 10`;
do
	curl -i -X POST http://localhost:5001/api/1/payments/0x396764f15ed1467883A9a5B7D42AcFb788CD1826/0x3D5d0339f90A6eeE02F6a3e5553508CdcCd56A2f -H 'Content-Type: application/json' --data-raw '{"amount": 1000}' &

done
```

[raiden-logs-workshop-storj.tar.gz](https://github.com/raiden-network/raiden/files/2538742/raiden-logs-workshop-storj.tar.gz)

**Comment by palango** [comment]
I'll look into these.

**Comment by palango** [comment]
One of the exception is during matrix sync. @andrevmatos @ulope Can one of you give it a look? If it's something to investigate further I can create a separate issue.
```
2018-11-01 13:32:28 [debug    ] Send                           [raiden.network.transport.matrix] current_user=@0xfd28faba46f280a94a0c24a224a137ba0f7e34de:transport01.raiden.network data={"type": "Delivered", "delivered_message_identifier": 16180446441536027691, "signature": "0x14f11d3f716d2a7ad3dfafc429cb30bcd812bdf241f6eadf2ccfe56d7babc34e48b7fd58a2d969de646820d77218c25bef7bcfab23fc20279f5a5c45f579e1e31c", "_type": "raiden.messages.Delivered", "_version": 0} node=fd28faba receiver=3d5d0339 room=<Room id="!UEvXBVJcZKaXnkGhwh:transport01.raiden.network" alias="#raiden_kovan_0x3d5d0339f90a6eee02f6a3e5553508cdccd56a2f_0xfd28faba46f280a94a0c24a224a137ba0f7e34de:transport01.raiden.network">
2018-11-01 13:32:28 [debug    ] Send                           [raiden.network.transport.matrix] current_user=@0xfd28faba46f280a94a0c24a224a137ba0f7e34de:transport01.raiden.network data={"type": "Secret", "chain_id": 42, "message_identifier": 17790865803400406718, "payment_identifier": 2449813038021206359, "secret": "0x96a03e75fc1d654e96e1fffaf2a6bb97024828a9edcfa4422d38e51a08b854a5", "nonce": 713, "token_network_address": "0x6d609bf189060cba0ff794168c2cc3bea496031a", "channel_identifier": 195, "transferred_amount": 211000034507000, "locked_amount": 10000000000000, "locksroot": "0xbf546b66dc7d12fa3e4c8d641c8a5d43c2a82270d4af14cc9f60e44a5eaff013", "signature": "0x3e567f333cc88b6ab5b5e61d3abf4afa26695deb40d1e396d9f8b7d8085e3a0255047a430367d647dd9619e604b11cee8dc79b4cb82bc5557c8920b64a3be74d1b"} node=fd28faba receiver=3d5d0339 room=<Room id="!UEvXBVJcZKaXnkGhwh:transport01.raiden.network" alias="#raiden_kovan_0x3d5d0339f90a6eee02f6a3e5553508cdccd56a2f_0xfd28faba46f280a94a0c24a224a137ba0f7e34de:transport01.raiden.network">
2018-11-01 13:32:28 [error    ] Exception thrown during sync   [raiden_libs.network.matrix.client] 
Traceback (most recent call last):
  File "site-packages/raiden_libs/network/matrix/client.py", line 151, in listen_forever
  File "site-packages/raiden_libs/network/matrix/client.py", line 311, in _sync
  File "site-packages/matrix_client/api.py", line 105, in sync
  File "site-packages/raiden_libs/network/matrix/client.py", line 70, in _send
  File "site-packages/matrix_client/api.py", line 670, in _send
  File "site-packages/requests/sessions.py", line 512, in request
  File "site-packages/requests/sessions.py", line 622, in send
  File "site-packages/requests/adapters.py", line 445, in send
  File "site-packages/urllib3/connectionpool.py", line 588, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 239, in _get_conn
  File "site-packages/urllib3/util/connection.py", line 23, in is_connection_dropped
  File "site-packages/urllib3/util/wait.py", line 146, in wait_for_read
  File "site-packages/urllib3/util/wait.py", line 107, in poll_wait_for_socket
  File "site-packages/urllib3/util/wait.py", line 42, in _retry_on_intr
  File "site-packages/urllib3/util/wait.py", line 105, in do_poll
  File "site-packages/gevent/select.py", line 268, in poll
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
AssertionError
```

**Comment by palango** [comment]
@super3 Thanks for the report.

* For 1) I found the crashes in the log and some colleagues will look into it.
* For 2) How did these error show themselves? Were the payments not going through or did you get some error popups in the webUI?

**Comment by super3** [comment]
2) I was attempting to send out a large volume of payments via the script above when the crashes occurred.

**Comment by ulope** [comment]
This one is a bit weird. Since this is an AssertionError without a message it's likely it was caused by a bare assert (without message). Due to the way exception re-raising works in gevent it's quite difficult to tell where the error originated. 

Unfortunately we do have quite a few bare `assert`s in our code:
```
± ggrep -r --include '*.py' --exclude-dir tests --exclude-dir node_modules -P '^\s*assert [^,]+$' . | wc -l
      57
```

Needs more investigation.

**Comment by super3** [comment]
@andrevmatos I'm having trouble running the latest (although I can run the hackathon binary):

Running:
```
./raiden-binary \
    --keystore-path keystore \
    --network-id kovan \
    --environment-type development \
    --gas-price 20000000000 \
    --eth-rpc-endpoint https://kovan.infura.io/v3/xxx
```

Getting:
```
...
Select one of them by index to continue: 0
Enter the password to unlock: 
Traceback (most recent call last):
  File "raiden-script.py", line 2, in <module>
  File "site-packages/raiden/__main__.py", line 11, in main
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1043, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "site-packages/click/decorators.py", line 17, in new_func
  File "site-packages/raiden/ui/cli.py", line 425, in run
  File "site-packages/raiden/ui/runners.py", line 245, in run
  File "site-packages/raiden/ui/runners.py", line 99, in _start_services
  File "site-packages/raiden/ui/app.py", line 236, in run_app
  File "site-packages/raiden/network/rpc/client.py", line 209, in __init__
  File "site-packages/raiden/network/rpc/client.py", line 45, in discover_next_available_nonce
  File "site-packages/web3/manager.py", line 109, in request_blocking
  File "site-packages/web3/manager.py", line 92, in _make_request
  File "site-packages/web3/middleware/cache.py", line 105, in middleware
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
  File "site-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
  File "site-packages/web3/middleware/attrdict.py", line 18, in middleware
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
  File "site-packages/web3/middleware/normalize_errors.py", line 9, in middleware
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
  File "site-packages/web3/middleware/exception_retry_request.py", line 87, in middleware
  File "site-packages/web3/providers/rpc.py", line 68, in make_request
  File "site-packages/web3/utils/request.py", line 27, in make_post_request
  File "site-packages/requests/models.py", line 939, in raise_for_status
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://kovan.infura.io/v3/xxx
[2972] Failed to execute script raiden-script
```

Replaced my infuria key with xxx in the logs.

**Comment by BOR4** [comment]
@super3  I think you need to pull latest version of master or nightly release. Issue you are having is same as one from https://github.com/raiden-network/raiden/issues/2951 and fix for that was merged after the latest release

PS you can try get answer to your technical question in official gitter created for this purpose. Link: https://gitter.im/raiden-network/raiden

**Comment by LefterisJP** [comment]
@super3 Infura does not expose some APIs that we use for the nonce counting. With https://github.com/raiden-network/raiden/commit/927a23a94add8521ed3cafd424b8637c35ebb287 Infura should now work again but there can still be nonce problems since we can't check the pending transaction nonces of an infura node.

**Comment by rakanalh** [comment]
@super3 I tried your script on Raiden version: 0.5.1
```
#!/bin/bash
for i in `seq 1 10`;
do
	curl -i -X POST http://localhost:5001/api/1/payments/0x396764f15ed1467883A9a5B7D42AcFb788CD1826/0x3D5d0339f90A6eeE02F6a3e5553508CdcCd56A2f -H 'Content-Type: application/json' --data-raw '{"amount": 1000}' &

done
```
Given that i changed the partner address and the network ID on Kovan to WETH.
With the following scenario:
1. Open a channel with a different node
2. Waited until the channel is open + Funds are deposited.
3. Sent 10, 20 and kept increasing the number.

At a small number of parallel transfers (ex: 10 or 20), what i noticed is that no issue happened while processing the payments. As soon as i increased the number to my "Open files" limit, that's when i noticed that we have a problem related to that limit. However, i could not reproduce the exception you were facing.

So, to move forward, i would need your help:
1. Providing the last number (the second param to `seq`) of parallel payments you were doing before the crash happened. i suspect the number original script which is 10 is the one that caused the issue.
2. See if you can reproduce the issue again by repeating your previous steps on a later version of Raiden, which is as of now: https://github.com/raiden-network/raiden/releases/tag/v0.16.0

Awaiting your response.

**Comment by super3** [comment]
Not able to reproduce the error with the new releases. Thanks for your assistance.
