### ISSUE TITLE
Transaction execution error get erroneously propagated.

### ISSUE THREAD

**Issue by kelsos** [raiden-network/raiden#3005]
## Problem Definition

This happens on the following line:
https://github.com/raiden-network/raiden/blob/c22a189589c66f767fdc7d992d4d1cdb1963d3bd/raiden/network/rpc/smartcontract_proxy.py#L32

The message from parity contains double quotes in the message, so when the single quotes of the response are replaced with single quotes at 

```python
json_response = str(val_err).replace("'", '"')
```
We end up with an invalid JSON that causes the parse to fail and just propagates the previous error
```json
{
	"code": -32015,
	"message": "Transaction execution error.",
	"data": "Internal("
	Requires higher than upper limit of 80000000 ")"
}
```
This is the traceback:
```
Traceback (most recent call last):
  File "raiden-script.py", line 2, in <module>
  File "site-packages/raiden/__main__.py", line 11, in main
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1043, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "site-packages/click/decorators.py", line 17, in new_func
  File "site-packages/raiden/ui/cli.py", line 425, in run
  File "site-packages/raiden/ui/runners.py", line 245, in run
  File "site-packages/raiden/ui/runners.py", line 96, in _start_services
  File "site-packages/raiden/ui/app.py", line 418, in run_app
  File "site-packages/raiden/app.py", line 143, in start
  File "site-packages/raiden/raiden_service.py", line 366, in start
  File "site-packages/raiden/raiden_service.py", line 593, in _initialize_transactions_queues
  File "site-packages/raiden/raiden_event_handler.py", line 103, in on_raiden_event
  File "site-packages/raiden/raiden_event_handler.py", line 484, in handle_contract_send_channelsettle
  File "site-packages/raiden/network/proxies/payment_channel.py", line 228, in settle
  File "site-packages/raiden/network/proxies/token_network.py", line 988, in settle
  File "site-packages/raiden/network/rpc/smartcontract_proxy.py", line 168, in estimate_gas
  File "site-packages/raiden/network/rpc/smartcontract_proxy.py", line 157, in estimate_gas
  File "site-packages/web3/contract.py", line 1194, in estimateGas
  File "site-packages/web3/contract.py", line 1488, in estimate_gas_for_function
  File "site-packages/web3/eth.py", line 304, in estimateGas
  File "site-packages/web3/manager.py", line 112, in request_blocking
ValueError: {'code': -32015, 'message': 'Transaction execution error.', 'data': 'Internal("Requires higher than upper limit of 80000000")'}
[15890] Failed to execute script raiden-script
--- Logging error ---
Exception ignored in: <bound method BaseFileLock.__del__ of <filelock.UnixFileLock object at 0x7fc8306f3f28>>
Traceback (most recent call last):
  File "site-packages/filelock.py", line 333, in __del__
  File "site-packages/filelock.py", line 320, in release
  File "logging/__init__.py", line 1308, in info
  File "logging/__init__.py", line 1444, in _log
  File "logging/__init__.py", line 1454, in handle
  File "logging/__init__.py", line 1516, in callHandlers
  File "logging/__init__.py", line 865, in handle
  File "logging/handlers.py", line 75, in emit
  File "logging/__init__.py", line 918, in handleError
  File "/usr/local/lib/python3.6/traceback.py", line 104, in print_exception
  File "site-packages/raiden/log_config.py", line 127, in tracebackexception_format
  File "site-packages/raiden/log_config.py", line 112, in processor_wrapper
ImportError: sys.meta_path is None, Python is likely shutting down
```

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
Linux forseti 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.25+commit.59dbf8f1.Linux.g++
/usr/bin/geth
Geth
Version: 1.8.17-stable
Git Commit: 8bbe72075e4e16442c4e28d999edee12e294329e
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.11.1
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go
/usr/bin/parity
Parity
  version Parity-Ethereum/v2.0.9-stable-09f77575d6-20181028/x86_64-linux-gnu/rustc1.30.0
Copyright 2015, 2016, 2017, 2018 Parity Technologies (UK) Ltd
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann

/home/kelsos/.virtualenvs/raiden/bin/raiden
{
  "raiden": "0.16.1.dev2+g50328762.d20181112",
  "python_implementation": "CPython",
  "python_version": "3.7.1",
  "system": "Linux 64bit_ 4.18.16-arch1-1-ARCH x86_64",
  "distribution": "source"
}
50328762e0cf09f5ea6daad05b70f33cadd11c47

```

**Comment by LefterisJP** [comment]
Thanks for finding this out @kelsos  :)

**Comment by kelsos** [comment]
@LefterisJP you are welcome, though I accidentally pressed to create the issue before adding all the information.
