### ISSUE TITLE
Matrix should create discovery room if it doesn't find one for a private chain

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#3081]
### Problem

When running a private chain, Raiden will fail in case the `discovery` room wasn't found.

Log:
```
2018-11-27 13:18:55 [debug    ] JSONRPCClient created          [raiden.network.rpc.client] available_nonce=0 client=Parity-Ethereum//v2.1.6-stable-491f17f149-20181114/x86_64-linux-gnu/rustc1.30.1 node=7dfc0dd6
Raiden is running in production mode

You are connected to the '17' network and the DB path is: /home/rakan/development/raiden/local/production/0x00a329c0648769A73afAc7F9381E08FB43dBEA72/data/node_7dfc0dd6/netid_17/network_acd2ed44/v14_log.db
2018-11-27 13:18:55 [debug    ] Fetching available matrix servers [raiden.ui.app] available_servers=['https://raidentransport.exchangeunion.com', 'https://persephone.raidentransport.digitalvirtues.com', 'https://raidentransport.ki-decentralized.com', 'https://raidentransport.mycryptoapi.com']
2018-11-27 13:18:59 [debug    ] Matrix homeserver RTT times    [raiden.network.transport.matrix] rtt_times=[('https://raidentransport.ki-decentralized.com', 0.03457166666666667), ('https://persephone.raidentransport.digitalvirtues.com', 0.03535733333333333), ('https://raidentransport.mycryptoapi.com', 0.11807066666666666), ('https://raidentransport.exchangeunion.com', 0.12680833333333333)]
2018-11-27 13:18:59 [info     ] Automatically selecting matrix homeserver based on RTT [raiden.network.transport.matrix] homeserver=https://raidentransport.ki-decentralized.com rtt=0.03457166666666667
2018-11-27 13:18:59 [debug    ] No snapshot found, replaying all state changes [raiden.storage.wal] to_state_change_id=latest
2018-11-27 13:18:59 [debug    ] Replaying state changes        [raiden.storage.wal] num_state_changes=0
2018-11-27 13:18:59 [debug    ] No recoverable state available, created inital state [raiden.raiden_service] node=7dfc0dd6
2018-11-27 13:18:59 [debug    ] State change                   [raiden.raiden_service] node=7dfc0dd6 state_change={"block_number": "0", "our_address": "0x7DfC0dd6C0a36Eb6C7cEc4a5209E7C9599Bc8121", "chain_id": 17, "pseudo_random_generator": [3, [2147483648, 4165509572, 3202308653, 1209319807, 1651631594, 3562002240, 4243921012, 2800593485, 4000303513, 2634826776, 3339044470, 667681882, 2861228514, 2603253608, 839181180, 2059910287, 3355078338, 4206631235, 1286828571, 3710718420, 3367198339, 3110925466, 1471071295, 3359951463, 3597702798, 651972330, 2037186159, 680347790, 3591882321, 942917409, 3663651208, 1412680355, 1764274399, 3832062179, 619565381, 3486855326, 2294876939, 3543980920, 856164224, 2764739763, 3753354983, 421082705, 34370883, 531776433, 115002926, 432304548, 3081014019, 4036222131, 111919089, 1097802917, 3732136609, 1730704502, 2260761190, 2270292165, 3521362365, 2725476409, 378084673, 2408726154, 3110596608, 241883960, 480660588, 1138595777, 810627554, 3584516610, 1216071585, 3338936148, 4063046159, 2555317938, 2516318359, 4000056942, 3634631758, 3722538259, 3489519173, 1918535067, 43379828, 706954723, 420005946, 1312485792, 2880020442, 4230902974, 2600788388, 195687503, 1421881290, 1810940809, 902707996, 2927989608, 1311503078, 3561159448, 1416163551, 2006329605, 2453988869, 274746482, 2687289597, 928073300, 1275576440, 2451900739, 3128095191, 64493366, 3982047007, 1465970715, 3379322118, 63423726, 4077623300, 3791477765, 1537342220, 3051310188, 1594973787, 2675781296, 4125617648, 1941565344, 236417919, 4032932925, 366766986, 2273334037, 92905305, 231593275, 2272390229, 1500010108, 316929417, 4098479218, 2284501959, 2286750989, 2181734953, 562815338, 1423670773, 1993615121, 3750964344, 3214200911, 3255577620, 284180752, 2775877631, 3855059073, 2159435643, 2165762834, 586163264, 1993799839, 3120975405, 1477270474, 2582826592, 2182682720, 960235081, 4229479879, 2588591292, 2818165715, 1510356573, 2686435646, 803690021, 229554990, 1806917635, 2228131717, 2819452523, 3094935581, 1527745196, 589863222, 2213450811, 1231774680, 965225032, 3431513424, 620287149, 1273294339, 1556470995, 3762758910, 3758601574, 2568498001, 1138587283, 4047343008, 901054390, 1541660762, 2991594815, 2726216786, 2519821783, 946916935, 2379317836, 2544146281, 551665945, 3142014836, 1844554301, 4281199570, 3121406696, 3710765989, 1065980666, 3850139232, 193213045, 2466895431, 3576981524, 4176909363, 2439175638, 3400798009, 335104411, 723223472, 2141031551, 1486400183, 4283924739, 422446627, 1156700244, 183488345, 3093213473, 2321678976, 824814206, 1397218177, 1024179670, 3271602470, 2269846485, 1458114765, 2436411029, 3150362006, 3990612589, 3337408420, 647184849, 2843417549, 4001823090, 857060604, 728877069, 2040577122, 3250653884, 3837342671, 1148937962, 1406650776, 4098181096, 1650052264, 3805629785, 1917710092, 2221249492, 36737600, 1038810608, 1003484084, 2792429032, 3972044585, 112874442, 1314455724, 3209823026, 4195507162, 846991273, 1560671285, 3693175327, 2035654363, 781225154, 1655593253, 1265430028, 4174818485, 870578757, 1966900464, 1440752465, 1141271472, 2920382771, 722217432, 2088549800, 1647504019, 3782646884, 1835118884, 3174456526, 1172351130, 3557884094, 1522794824, 3978236722, 2238854868, 3394714000, 2003911054, 3567394036, 4044719383, 2096771547, 3414195074, 194120766, 2236131953, 342623982, 2008646809, 962665578, 639508605, 1733613437, 3243851261, 1672153136, 4027356270, 513310288, 2338392764, 408496450, 3695091018, 3254965121, 1927383681, 915268112, 2085219380, 2242300884, 3164302795, 1690145531, 270135779, 3877911181, 2508599317, 1523822713, 2779957121, 31074828, 1983108545, 3946540841, 1140798757, 3934848983, 3367223568, 2556749426, 3265186720, 1281785702, 187458244, 2818754625, 2119982249, 3059150771, 1904814007, 2397500433, 3428644385, 4165380601, 3912508786, 4123756174, 2302014926, 601944375, 2776660246, 1332850675, 3511089191, 3988469167, 961386057, 2305115046, 280036426, 3310230335, 675109293, 1322252226, 3551343339, 3094340078, 2568454207, 2875917965, 490880594, 8822646, 1830022989, 1268141106, 1776086412, 1658670471, 381580753, 4042045584, 1989968775, 585200375, 3041443860, 284103356, 2379285362, 611695708, 3102769759, 2953259927, 764906171, 1390757395, 1783754724, 3295437862, 2975686415, 1574828945, 1859612188, 36766364, 2383274860, 3919722584, 3295496913, 856868953, 1160273200, 373108201, 2175814200, 310101159, 4002630366, 3749378570, 2120364872, 289541810, 2209861905, 563448895, 2992854160, 1899226178, 3142295716, 2185795393, 2970183737, 1694076684, 1072656727, 750461196, 2654463372, 2783841367, 4262215073, 307760781, 2109098315, 2272150599, 15872347, 87668968, 2693885498, 1414825686, 2016990292, 1421701413, 3021822616, 4102493051, 3256645381, 924948305, 4060173449, 961291590, 1848108799, 2276319737, 3035877879, 2579669224, 1409017249, 2925972359, 4259589223, 2413037349, 3997776908, 895684990, 1849387340, 471450066, 1942985253, 2139915999, 774422550, 501883238, 3215122041, 1878080732, 3734784466, 2516078454, 3469831607, 414824553, 1814394904, 1945343210, 1055167947, 935778479, 3215582491, 4228874163, 2165176420, 3350713976, 181540285, 2630721915, 4052476878, 841671266, 3831288528, 1055256087, 852611074, 383027810, 2562935924, 3616081384, 2384736144, 3150896791, 3411008777, 3265541590, 1504242592, 2453684475, 1330563762, 4266724221, 547306966, 2713722428, 716031211, 2109870798, 798401003, 2118087050, 104129788, 1568578315, 537520574, 3261522682, 1727743695, 2167980038, 3058121445, 3448662331, 2529762500, 2272468848, 1124529112, 2114133324, 1085525561, 2868023872, 624274701, 870715830, 2463417221, 1476120365, 1321942739, 4030994832, 764875179, 2258111745, 985434913, 3562775730, 3302835908, 378448214, 330109124, 2692872735, 1726134345, 2777240363, 746425788, 3540749287, 1414439825, 3377552167, 3563809717, 3821965899, 1043818119, 3489163846, 483537294, 57125736, 2156162597, 2230095590, 2487435662, 4043962654, 372864810, 232973571, 4169553212, 1941409481, 1279617879, 296917829, 3900752776, 139490225, 4232162587, 1367337876, 2566593291, 3341236607, 1917245342, 192761083, 1251390494, 1641297777, 1271594385, 3965436297, 1521715671, 1696190838, 3117665975, 829746523, 3738692750, 76620808, 1102232756, 3991776399, 4199161226, 3063258261, 2734264770, 3387916009, 3392548246, 1757462684, 363562182, 3059769013, 2302698070, 3063302433, 3759972299, 2100522160, 2313653924, 934871384, 615619902, 1761382836, 1839999708, 1059110943, 2563342446, 3101094298, 2060968451, 1387815382, 2737601209, 1434106961, 2638706691, 2928779348, 1354455958, 4060037270, 1882225884, 2146666010, 3223942361, 3743369052, 912507030, 3847853371, 1931529659, 4158282521, 1401399717, 2078142192, 3204295184, 1401312601, 3155890585, 1047452245, 3477140387, 583322645, 2728081971, 3910575654, 1714849107, 2343458049, 3241490938, 3302158143, 2573246615, 1171046439, 3477205970, 636395858, 230318155, 1050970434, 1284252141, 4120029163, 2771704490, 3780069896, 3925850139, 375250168, 2474110994, 3109842005, 1797344614, 3294851137, 3718567894, 671307013, 468188224, 547351584, 1607667239, 1378223176, 626247657, 1134946440, 3249817038, 3284558626, 325905210, 1638557282, 3188934884, 1669613809, 1296481037, 2133018331, 3006340496, 1901498579, 1050267110, 1162958311, 2571797911, 511858924, 3822864542, 738017461, 1231975094, 3585661265, 1959457241, 151430921, 3460928529, 2004188792, 374630295, 3137408481, 1231447196, 1216252454, 2491670579, 2266122219, 1729276379, 130748336, 199291059, 2248425076, 1257518949, 500337825, 2180678419, 2952213068, 2508071662, 84415850, 1308327764, 624], null], "_type": "raiden.transfer.state_change.ActionInitChain", "_version": 0}
2018-11-27 13:18:59 [debug    ] State change                   [raiden.raiden_service] node=7dfc0dd6 state_change={"transaction_hash": "0x0000000000000000000000000000000000000000000000000000000000000000", "payment_network": {"address": "0xACD2Ed44a0c2b0B13b488dD8f47B3a2f01033133", "tokennetworks": [], "_type": "raiden.transfer.state.PaymentNetworkState", "_version": 0}, "block_number": "0", "_type": "raiden.transfer.state_change.ContractReceiveNewPaymentNetwork", "_version": 0}
2018-11-27 13:18:59 [debug    ] Alarm task first run           [raiden.tasks] known_block_number=0 latest_block_hash=0x670be07edf04de745b68643ca8304fdaa4d88b4b8e361b86992dd088a0fc8ead latest_block_number=7530 latest_gas_limit=8000000
2018-11-27 13:18:59 [debug    ] Received new block             [raiden.tasks] known_block_number=0 latest_block_gas_limit=8000000 latest_block_hash=0x670be07edf04de745b68643ca8304fdaa4d88b4b8e361b86992dd088a0fc8ead latest_block_number=7530 num_missed_blocks=7529
2018-11-27 13:18:59 [debug    ] Blockchain event               [raiden.blockchain_events_handler] chain_event=<Event contract: acd2ed44 event: {'args': AttributeDict({'token_address': '0x5816511D8329393aa87B1d784d5D09c08D87e44F', 'token_network_address': '0xB0b1B8Be5039A31778B82d2EE9357b29Ea048612'}), 'event': 'TokenNetworkCreated', 'logIndex': 0, 'transactionIndex': 0, 'transactionHash': HexBytes('0x1f67b806f7500784043440ba9a0cf6249e3d078551368990a7a8045e96161e9a'), 'address': '0xACD2Ed44a0c2b0B13b488dD8f47B3a2f01033133', 'blockHash': HexBytes('0x9676b7bca06031dbf1c7cd05ab5185b44bf5918ceb46a19633cf1d4dddab01c7'), 'blockNumber': 6677, 'block_number': 6677, 'token_network_address': b'\xb0\xb1\xb8\xbeP9\xa3\x17x\xb8-.\xe95{)\xea\x04\x86\x12', 'token_address': b'X\x16Q\x1d\x83)9:\xa8{\x1dxM]\t\xc0\x8d\x87\xe4O'}> contract=acd2ed44 node=7dfc0dd6
2018-11-27 13:18:59 [debug    ] State change                   [raiden.raiden_service] node=7dfc0dd6 state_change={"transaction_hash": "0x1f67b806f7500784043440ba9a0cf6249e3d078551368990a7a8045e96161e9a", "payment_network_identifier": "0xACD2Ed44a0c2b0B13b488dD8f47B3a2f01033133", "token_network": {"address": "0xB0b1B8Be5039A31778B82d2EE9357b29Ea048612", "token_address": "0x5816511D8329393aa87B1d784d5D09c08D87e44F", "network_graph": {"token_network_id": "0xB0b1B8Be5039A31778B82d2EE9357b29Ea048612", "network": "[]", "channel_identifier_to_participants": {}, "_type": "raiden.transfer.state.TokenNetworkGraphState", "_version": 0}, "channelidentifiers_to_channels": {}, "partneraddresses_to_channelidentifiers": {}, "_type": "raiden.transfer.state.TokenNetworkState", "_version": 0}, "block_number": "6677", "_type": "raiden.transfer.state_change.ContractReceiveNewTokenNetwork", "_version": 0}
2018-11-27 13:18:59 [debug    ] State change                   [raiden.raiden_service] node=7dfc0dd6 state_change={"block_number": "7525", "gas_limit": 8000000, "block_hash": "0x352c0614f34d297e8a99a9d422873dfb502b44229f40e7877ac8bb2066eb0d5e", "_type": "raiden.transfer.state_change.Block", "_version": 0}
2018-11-27 13:18:59 [debug    ] Processing pending transactions [raiden.raiden_service] node=7dfc0dd6 num_pending_transactions=0
2018-11-27 13:18:59 [debug    ] Login                          [raiden.network.transport.matrix] homeserver=raidentransport.ki-decentralized.com server_url=https://raidentransport.ki-decentralized.com username=0x7dfc0dd6c0a36eb6c7cec4a5209e7c9599bc8121
2018-11-27 13:18:59 [debug    ] Could not join discovery room  [raiden.network.transport.matrix] _exception=MatrixRequestError('404: {"errcode":"M_NOT_FOUND","error":"Room alias #raiden_17_discovery:raidentransport.ki-decentralized.com not found"}',) current_user=@0x7dfc0dd6c0a36eb6c7cec4a5209e7c9599bc8121:raidentransport.ki-decentralized.com node=7dfc0dd6 room_alias_full=#raiden_17_discovery:raidentransport.ki-decentralized.com
2018-11-27 13:19:00 [debug    ] Could not join discovery room  [raiden.network.transport.matrix] _exception=MatrixRequestError('404: {"errcode":"M_NOT_FOUND","error":"Room alias #raiden_17_discovery:persephone.raidentransport.digitalvirtues.com not found"}',) current_user=@0x7dfc0dd6c0a36eb6c7cec4a5209e7c9599bc8121:raidentransport.ki-decentralized.com node=7dfc0dd6 room_alias_full=#raiden_17_discovery:persephone.raidentransport.digitalvirtues.com
Traceback (most recent call last):
  File "/home/rakan/.pyenv/versions/raiden/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/home/rakan/Brainbot/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/rakan/Brainbot/raiden/raiden/ui/cli.py", line 425, in run
    app = runner.run()
  File "/home/rakan/Brainbot/raiden/raiden/ui/runners.py", line 247, in run
    return self._start_services()
  File "/home/rakan/Brainbot/raiden/raiden/ui/runners.py", line 96, in _start_services
    app_ = run_app(**self._options)
  File "/home/rakan/Brainbot/raiden/raiden/ui/app.py", line 418, in run_app
    raiden_app.start()
  File "/home/rakan/Brainbot/raiden/raiden/app.py", line 152, in start
    self.raiden.start()
  File "/home/rakan/Brainbot/raiden/raiden/raiden_service.py", line 380, in start
    self.transport.start(self, self.message_handler)
  File "/home/rakan/Brainbot/raiden/raiden/network/transport/matrix.py", line 349, in start
    self._join_discovery_room()
  File "/home/rakan/Brainbot/raiden/raiden/network/transport/matrix.py", line 574, in _join_discovery_room
    discovery_room = self._client.join_room(discovery_room_alias_full)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/matrix_client/client.py", line 320, in join_room
    response = self.api.join_room(room_id_or_alias)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/matrix_client/api.py", line 195, in join_room
    return self._send("POST", path)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/raiden_libs/network/matrix/client.py", line 75, in _send
    return super()._send(method, path, *args, **kwargs)
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/matrix_client/api.py", line 691, in _send
    code=response.status_code, content=response.text
matrix_client.errors.MatrixRequestError: 500: {"errcode":"M_UNKNOWN","error":"Internal server error"}
--- Logging error ---
Exception ignored in: <bound method BaseFileLock.__del__ of <filelock.UnixFileLock object at 0x7f815f0f7470>>
Traceback (most recent call last):
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/filelock.py", line 333, in __del__
  File "/home/rakan/.pyenv/versions/3.6.5/envs/raiden/lib/python3.6/site-packages/filelock.py", line 320, in release
  File "/home/rakan/.pyenv/versions/3.6.5/lib/python3.6/logging/__init__.py", line 1306, in info
  File "/home/rakan/.pyenv/versions/3.6.5/lib/python3.6/logging/__init__.py", line 1442, in _log
  File "/home/rakan/.pyenv/versions/3.6.5/lib/python3.6/logging/__init__.py", line 1452, in handle
  File "/home/rakan/.pyenv/versions/3.6.5/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
  File "/home/rakan/.pyenv/versions/3.6.5/lib/python3.6/logging/__init__.py", line 863, in handle
  File "/home/rakan/.pyenv/versions/3.6.5/lib/python3.6/logging/handlers.py", line 75, in emit
  File "/home/rakan/.pyenv/versions/3.6.5/lib/python3.6/logging/__init__.py", line 916, in handleError
  File "/home/rakan/.pyenv/versions/3.6.5/lib/python3.6/traceback.py", line 100, in print_exception
  File "/home/rakan/Brainbot/raiden/raiden/log_config.py", line 126, in tracebackexception_format
  File "/home/rakan/Brainbot/raiden/raiden/log_config.py", line 111, in processor_wrapper
ImportError: sys.meta_path is None, Python is likely shutting down
```

### Proposed solution:
1. Prevent crashing Raiden in this case.
2. Force the creation of the discovery room

**Comment by ulope** [comment]
There is already code to create and link a discovery room if it's missing. 
This seems to break under some conditions. 

@rakanalh Can you add the command line you used?

**Comment by rakanalh** [comment]
It's mostly the same command i shared earlier:
```
/home/rakan/.pyenv/versions/raiden/bin/raiden --keystore-path /home/rakan/.local/share/io.parity.ethereum/keys/DevelopmentChain/ --log-config raiden:DEBUG --api-address localhost:5502 --eth-rpc-endpoint http://localhost:8545 --accept-disclaimer --network-id 17 --environment-type production --matrix-server=https://transport01.raiden.network --no-sync-check --tokennetwork-registry-contract-address=0x7098b0393aDC815B42a046628AB5fFa378Eb7cA4 --secret-registry-contract-address=0x21a50f9D0c9B2709dfaD8da91344E90943FfD83E --endpoint-registry-contract-address=0xe0fb6C6119ee7777E7208A9fDF2B85Ae97BF3fdb
```

However, the discovery room's name is determined based on the chain ID. The code block at which the room is checked is here: https://github.com/raiden-network/raiden/blob/master/raiden/network/transport/matrix.py#L571 
It seems like the force-create only happens if `servers` is an empty list which triggers the `else` block.

**Comment by ulope** [comment]
Hm unless it's a copy paste error this still sets the server name to one of the test servers and environment-type defaults to `production`.

**Comment by andrevmatos** [comment]
The algorithm goes as:
1. try to join discovery room on own server
2. if there's none, try to join discovery room on each listed server
3. if still can't, create one on own server

The problem is that, in 2., something is weird with the server federation API (possibly some server with full disk or some other issue), which is raising a `500` on join discovery room on a different server if the room doesn't exist.
So, to fix it, we need to both:
1. Verify the logs why the join room is failing and giving an `E500` and fix it
2. Ensure this `MatrixRequestError` doesn't crash the client and continue, trying the other servers or finally creating the room

**Comment by ulope** [comment]
Asked for the logs of KI-Decentralized's server via email.

**Comment by rakanalh** [comment]
@ulope yup... seems like a copy-paste error... seems i like i went back too far in the CLI history

**Comment by LefterisJP** [comment]
should be done by #3180
