### ISSUE TITLE
Payment failure - & Precise Message for Payment failure Suggestion 

### ISSUE THREAD

**Issue by junaidev** [raiden-network/raiden#3114]
## Problem Definition

Transfer via hub fails some time with message that 'Payment couldn't be completed (insufficient funds, no route to target or target offline)'.  All three nodes are 'online' and have 'funds' I verified, but still payment is failing.  Is there any route finding issue? how end user can mitigate that? 
Also the error message should be precise. 

I found #2358 and #2379 are similar and I found this issue many times in last few releases (around 8) , I am reopening issue so we have proper response at least for payment failure.

HTTP/1.1 409 CONFLICT
mimetype: application/json
Content-Type: application/json
Content-Length: 103
...

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
uname -a
Linux c922bfc647d5 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 GNU/Linux

command -v solc && solc --version
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.23+commit.124ca40d.Linux.g++

command -v raiden && raiden version
/usr/local/bin/raiden
{
  "raiden": "0.18.1.dev19+gacc5ada0.d20181204",
  "python_implementation": "CPython",
  "python_version": "3.6.7",
  "system": "Linux 64bit_ 4.15.0-39-generic x86_64",
  "distribution": "source"
}

[ -d .git ] && git rev-parse HEAD
acc5ada02edbac41749c5a173f5c83c67eae1c5e
```

**Comment by LefterisJP** [comment]
@junaidev As I mentioned in https://github.com/raiden-network/raiden/issues/3094#issuecomment-443770420 after the fix introduced by https://github.com/raiden-network/raiden/pull/3111 instead of the payments getting stuck forever they now will get properly expired and fail.

But as I also mentioned in that post the root cause of not finding a route to target lies with the Matrix transport and if tracked by https://github.com/raiden-network/raiden/issues/2779.

Assuming this is the reason I suppose as soon as we fix #2779 your problem will also go away.

**Comment by junaidev** [comment]
Tested today with Raiden 18.2 (following system):
```
root@11b5601fde77:/raiden# uname -a
Linux 11b5601fde77 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 GNU/Linux
root@11b5601fde77:/raiden# command -v solc && solc --version
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.4.23+commit.124ca40d.Linux.g++
root@11b5601fde77:/raiden# command -v raiden && raiden version
/usr/local/bin/raiden
{
  "raiden": "0.18.2.dev6+gb0491199.d20181211",
  "python_implementation": "CPython",
  "python_version": "3.6.7",
  "system": "Linux 64bit_ 4.15.0-42-generic x86_64",
  "distribution": "source"
}
root@11b5601fde77:/raiden# [ -d .git ] && git rev-parse HEAD
b04911997198f1baa43c1ef985438fc53f531192
root@11b5601fde77:/raiden#
```
and output is after 391 successful individual transfers in 1 to 1 channel all transfers are failing with message that "{"errors": "Payment couldn't be completed (insufficient funds, no route to target or target offline)."}" 

more importantly I **observed funds loss**. Node-A deposited 5k in channel and when issue occurred node A have 4605 and node B have 391 tokens, seems 4 tokens disappeared, and no more transfers are possible in this state with error mentioned above.

**Comment by LefterisJP** [comment]
@junaidev can you please provide logs and database?

**Comment by junaidev** [comment]
[sharelodb.zip](https://github.com/raiden-network/raiden/files/2668249/sharelodb.zip)

**Comment by junaidev** [comment]
```2018-12-12 09:04:02.800378 [warning  ] Message already in queue - ignoring [raiden.network.transport.matrix] current_user=@0x003c01eabf4ef499227281be7d9013cc36f227fd:transport01.raiden.network greenlet_name=sync_handle_response-s767339_378976_0_1_2059_1_1_8698_1 message=<Delivered [delivered_msgid:17801552402024465718]> node=003c01ea queue=<QueueIdentifier recipient:00ac8b50 channel_identifier:0> receiver=00ac8b50```

**Comment by junaidev** [comment]
After long time now payments in channel are equal to total deposit, seems these were in queue.

**Comment by junaidev** [comment]
after channel close and settlement 2nd node always crashes on restart:
```
 based on RTT [raiden.network.transport.matrix] homeserver=https://transport03.raiden.network rtt=0.03958866666666667
Traceback (most recent call last):
  File "raiden-script.py", line 2, in <module>
  File "site-packages/raiden/__main__.py", line 11, in main
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1043, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "site-packages/click/decorators.py", line 17, in new_func
  File "site-packages/raiden/ui/cli.py", line 425, in run
  File "site-packages/raiden/ui/runners.py", line 247, in run
  File "site-packages/raiden/ui/runners.py", line 96, in _start_services
  File "site-packages/raiden/ui/app.py", line 426, in run_app
  File "site-packages/raiden/app.py", line 152, in start
  File "site-packages/raiden/raiden_service.py", line 366, in start
  File "site-packages/raiden/raiden_service.py", line 597, in _initialize_transactions_queues
  File "site-packages/raiden/raiden_event_handler.py", line 92, in on_raiden_event
  File "site-packages/raiden/raiden_event_handler.py", line 364, in handle_contract_send_channelunlock
raiden.exceptions.RaidenUnrecoverableError: Failed to find state/event that match current channel locksroots. token:0x4650D8E298C53948B60B05d56830E92a47480259 token_network:0x6E205E367b018C7bFDd6e41a5b1475b4588001e4 channel:44 participant:0x003C01eabF4ef499227281be7D9013CC36f227FD our_locksroot:0x0000000000000000000000000000000000000000000000000000000000000000 partner_locksroot:0x0000000000000000000000000000000000000000000000000000000000000000 
[9] Failed to execute script raiden-script

```

**Comment by LefterisJP** [comment]
Thank you @junaidev. Seems very similar to what was experienced in https://github.com/raiden-network/raiden/issues/3139

**Comment by rakanalh** [comment]
@LefterisJP this seems to have the same issue. Although the provided logs don't have this error message due to them being shared before the error happened. But it's obvious from the stacktrace provided above that the values of locksroots returned by the contracts are zeros 
```
our_locksroot:0x0000000000000000000000000000000000000000000000000000000000000000 partner_locksroot:0x0000000000000000000000000000000000000000000000000000000000000000 
```
Which means that we're experiencing an attempt to batch unlock an expired lock by the failing node while the closing node closed/settled the channels with the empty locksroots. So as agreed, the PR https://github.com/raiden-network/raiden/pull/3154 should resolve the issue.

**Comment by rakanalh** [comment]
Tried to confirm the existence of the expired lock in the channel for participant `0x003C01eabF4ef499227281be7D9013CC36f227FD` but couldn't due to the absence of the database for that specific node.

**Comment by junaidev** [comment]
@rakanalh  you can check DB in https://github.com/raiden-network/raiden/files/2668249/sharelodb.zip

**Comment by karlb** [comment]
The PFS will report proper errors for many cases. This is good enough for now.
