### ISSUE TITLE
Raiden crashes with "Deposit amount decreased"

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3135]
## Problem Definition

This was seen only once by @czepluch during trying out latest [nightly](https://raiden-nightlies.ams3.digitaloceanspaces.com/raiden-nightly-2018-12-06T17-58-34-v0.18.1.dev57%2Bg786347b2-linux.tar.gz).

Network was Kovan.
Logs are [here](https://gist.github.com/czepluch/5c99d1eaf3715d9ce338152af9244551)
The failing `setTotalDeposit()` transaction is [here](https://kovan.etherscan.io/tx/0xd7ff4c4f5ab7120f2cdd17be692a6c130b6ac9a3882b2c0a59c3976e9cbb6010)

## Task

Investigate to see why this can be happening and fix it.

**Comment by arsenyjin** [comment]
I had the same issue at the ETHSingapore hackathon

**Comment by LefterisJP** [comment]
>  Happened on a newly registered token network,

Thank you @arsenyjin -- this gives a hint as to what the reason for the bug may be. Do you by any chance have any logs?

**Comment by czepluch** [comment]
Weird thing here is, that for me it only happened the first time I opened a channel in a newly registered token network. In this case the crash kept happening over and over again.

**Comment by arsenyjin** [comment]
I guess I posted the logs in the issue #3139

**Comment by LefterisJP** [comment]
@arsenyjin you posted 43 logs in that zip. Can you by any chance help us narrow it down by telling us which are relevant?

**Comment by LefterisJP** [comment]
Relevant log from #3139 for `setTotalDepositFailed` is [here](https://gist.github.com/LefterisJP/9cead7e9a899c50d6db7b762817b4d10)

**Comment by hackaugusto** [comment]
This is the stacktrace:

```
Traceback (most recent call last):
  File "site-packages/flask/app.py", line 1813, in full_dispatch_request
  File "site-packages/flask/app.py", line 1799, in dispatch_request
  File "site-packages/flask_restful/__init__.py", line 480, in wrapper
  File "site-packages/flask/views.py", line 88, in view
  File "site-packages/flask_restful/__init__.py", line 595, in dispatch_request
  File "site-packages/webargs/core.py", line 478, in wrapper
  File "site-packages/raiden/api/v1/resources.py", line 52, in put
  File "site-packages/raiden/api/rest.py", line 608, in open
  File "site-packages/raiden/api/python.py", line 423, in set_total_channel_deposit
  File "site-packages/raiden/network/proxies/payment_channel.py", line 164, in set_total_deposit
  File "site-packages/raiden/network/proxies/token_network.py", line 652, in set_total_deposit
  File "site-packages/raiden/network/proxies/token_network.py", line 1150, in _check_channel_state_for_deposit
raiden.exceptions.RaidenUnrecoverableError: Deposit amount decreased
```

This is the code at that time:

https://github.com/raiden-network/raiden/blob/786347b23316c517770a87c7a7169fb243cd6867/raiden/network/proxies/token_network.py#L1149-L1150
