### ISSUE TITLE
Error when running Raiden with Infura

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#3201]
## Intro
I am running Raiden v0.100.1 (Red eyes) version with an Infura `eth-rpc-endpoint`.

## Problem Definition
At some random moments, Raiden crashes with the following error:

```
2018-12-22 10:42:23.980709 [info     ] 95.91.241.178 - - [2018-12-22 10:42:23] "GET /api/v1/channels HTTP/1.1" 200 859 0.003017 [raiden.api.rest.pywsgi]
2018-12-22 10:42:29.052544 [info     ] 95.91.241.178 - - [2018-12-22 10:42:29] "GET /api/v1/channels HTTP/1.1" 200 859 0.002782 [raiden.api.rest.pywsgi]
2018-12-22 10:42:34.122722 [info     ] 95.91.241.178 - - [2018-12-22 10:42:34] "GET /api/v1/channels HTTP/1.1" 200 859 0.002983 [raiden.api.rest.pywsgi]
2018-12-22 10:42:39.209457 [info     ] 95.91.241.178 - - [2018-12-22 10:42:39] "GET /api/v1/channels HTTP/1.1" 200 859 0.005030 [raiden.api.rest.pywsgi]
2018-12-22 10:42:40.847361 [debug    ] State change                   [raiden.raiden_service] greenlet_name=AlarmTask|Greenlet-2 node=4252ccc2 state_change={"block_number": "6932038", "gas_limit": 8000029, "block_hash": "0x5cac19e341474e1f
4b7810a58f3612f5f9181e714c9a75ad53ee7563fae248d0", "_type": "raiden.transfer.state_change.Block", "_version": 0}
2018-12-22 10:42:44.282228 [info     ] 95.91.241.178 - - [2018-12-22 10:42:44] "GET /api/v1/channels HTTP/1.1" 200 859 0.002962 [raiden.api.rest.pywsgi]
2018-12-22 10:42:49.357799 [info     ] 95.91.241.178 - - [2018-12-22 10:42:49] "GET /api/v1/channels HTTP/1.1" 200 859 0.002921 [raiden.api.rest.pywsgi]
2018-12-22 10:42:52.712692 [debug    ] State change                   [raiden.raiden_service] greenlet_name=AlarmTask|Greenlet-2 node=4252ccc2 state_change={"block_number": "6932039", "gas_limit": 8000029, "block_hash": "0xe098aebca3acf5db
2cca706a59e75812715f6ba505e9b50429f5bb07663d5d6b", "_type": "raiden.transfer.state_change.Block", "_version": 0}
2018-12-22 10:42:54.464009 [info     ] 95.91.241.178 - - [2018-12-22 10:42:54] "GET /api/v1/channels HTTP/1.1" 200 859 0.003239 [raiden.api.rest.pywsgi]
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "site-packages/raiden/tasks.py", line 73, in check_gas_reserve
  File "site-packages/raiden/utils/gas_reserve.py", line 144, in has_enough_gas_reserve
  File "site-packages/raiden/utils/gas_reserve.py", line 120, in get_reserve_estimate
  File "site-packages/raiden/network/rpc/client.py", line 346, in gas_price
  File "site-packages/web3/eth.py", line 385, in generateGasPrice
  File "site-packages/web3/gas_strategies/time_based.py", line 165, in time_based_gas_price_strategy
  File "site-packages/eth_utils/functional.py", line 22, in inner
  File "site-packages/web3/gas_strategies/time_based.py", line 84, in _compute_probabilities
  File "site-packages/web3/gas_strategies/time_based.py", line 60, in _aggregate_miner_data
  File "cytoolz/itertoolz.pyx", line 118, in cytoolz.itertoolz.groupby
  File "cytoolz/itertoolz.pyx", line 160, in cytoolz.itertoolz.groupby
  File "site-packages/web3/gas_strategies/time_based.py", line 54, in _get_raw_miner_data
  File "site-packages/web3/eth.py", line 141, in getBlock
  File "site-packages/web3/manager.py", line 109, in request_blocking
  File "site-packages/web3/manager.py", line 92, in _make_request
  File "site-packages/web3/middleware/cache.py", line 99, in middleware
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
  File "site-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
  File "site-packages/web3/middleware/attrdict.py", line 18, in middleware
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
  File "site-packages/web3/middleware/normalize_errors.py", line 9, in middleware
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "site-packages/web3/middleware/formatting.py", line 57, in apply_formatters
  File "cytoolz/functoolz.pyx", line 491, in cytoolz.functoolz.Compose.__call__
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "site-packages/eth_utils/functional.py", line 22, in inner
  File "site-packages/eth_utils/applicators.py", line 121, in apply_key_map
AttributeError: 'NoneType' object has no attribute 'keys'
2018-12-22T10:42:55Z <Greenlet "Greenlet-4" at 0x7fd268d25b48: check_gas_reserve(<RaidenService 4252ccc2>)> failed with AttributeError
```
Restarting Raiden could sometimes result in the same crash or it could continue to run normally without any issues until this happens again.

This is probably something wrong with Infra nodes? will have to investigate this further to figure things out.

**Comment by LefterisJP** [comment]
This seems like  a problem with Infura and the web3.py gas price strategy module. If you can recreate it and go in with pdb or put some more logs to see what we send down to web3.py we can confirm this.

**Comment by rakanalh** [comment]
That's the issue, we don't send anything to web3 when calling for gas price.
https://github.com/raiden-network/raiden/blob/a26fd70a035083100bc143c90060e5dc6239671d/raiden/network/rpc/client.py#L341-L346

**Comment by karlb** [comment]
I just got an error which looks like this again with infura on the current develop:
```
Traceback (most recent call last):                                                                                                                                                            
  File "/home/karl/scenario-player/scenario_player/main.py", line 320, in run_                                                                                                                
    environment=environment,                                                                                                                                                                  
  File "/home/karl/scenario-player/scenario_player/main.py", line 395, in orchestrate                                                                                                         
    scenario_runner.run_scenario()                                                                                                                                                            
  File "/home/karl/scenario-player/scenario_player/runner.py", line 347, in run_scenario                                                                                                      
    gevent.joinall(greenlets, raise_error=True, count=1)                                                                                                                                      
  File "src/gevent/greenlet.py", line 1002, in gevent._greenlet.joinall                                                                                                                       
  File "src/gevent/greenlet.py", line 1018, in gevent._greenlet.joinall                                                                                                                       
  File "src/gevent/greenlet.py", line 364, in gevent._greenlet.Greenlet._raise_exception                                                                                                      
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/gevent/_compat.py", line 62, in reraise                                                                                   
    raise value.with_traceback(tb)                                                                                                                                                            
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run                                                                                                                   
  File "/home/karl/scenario-player/scenario_player/runner.py", line 427, in setup_environment_and_run_main_task
    pool.join(raise_error=True)                                              
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/gevent/pool.py", line 435, in join                                                                                       
    greenlet._raise_exception()   
  File "src/gevent/greenlet.py", line 364, in gevent._greenlet.Greenlet._raise_exception
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/gevent/_compat.py", line 62, in reraise
    raise value.with_traceback(tb)                                                                                                                                                           
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "/home/karl/scenario-player/scenario_player/utils/token.py", line 128, in userdeposit_maybe_deposit                                                                                   
    target_address, new_total_deposit, userdeposit_proxy.client.get_confirmed_blockhash()
  File "/home/karl/raiden/raiden/network/rpc/client.py", line 959, in get_confirmed_blockhash
    return self.blockhash_from_blocknumber(confirmed_block_number)
  File "/home/karl/raiden/raiden/network/rpc/client.py", line 963, in blockhash_from_blocknumber
    block = self.get_block(block_number)
  File "/home/karl/raiden/raiden/network/rpc/client.py", line 949, in get_block
    return self.web3.eth.getBlock(block_identifier)
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/eth.py", line 217, in getBlock                                                                                       
    [block_identifier, full_transactions],                                                                                                                                                    
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/manager.py", line 149, in request_blocking                                                                           
    response = self._make_request(method, params)                                                                                                                                             
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/manager.py", line 128, in _make_request                                                                              
    return request_func(method, params)                                                                                                                                                       
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/middleware/cache.py", line 134, in middleware                                                                        
    return make_request(method, params)                                                                                                                                                       
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__                                                                                                                 
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters                                                              
    response = make_request(method, params)                                                                                                                                                   
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware                                                            
    return make_request(method, params)                                                                                                                                                       
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__                                                                                                                 
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters                                                              
    response = make_request(method, params)                                                                                                                                                   
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/middleware/attrdict.py", line 33, in middleware                                                                      
    response = make_request(method, params)                                                                                                                                                   
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__                                                                                                                 
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/middleware/formatting.py", line 73, in apply_formatters                                                              
    response = make_request(method, formatted_params)                                                                                                                                         
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/middleware/normalize_errors.py", line 25, in middleware                                                              
    result = make_request(method, params)                                                                                                                                                     
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__                                                                                                                 
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters                                                              
    response = make_request(method, params)                                                                                                                                                   
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__                                                                                                                 
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters                                                              
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/middleware/formatting.py", line 82, in apply_formatters                                                             
    formatter(response["result"]),
  File "cytoolz/functoolz.pyx", line 503, in cytoolz.functoolz.Compose.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/eth_utils/functional.py", line 45, in inner                                                                              
    return callback(fn(*args, **kwargs))
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/eth_utils/applicators.py", line 119, in apply_key_map                                                                    
    set(value.keys())
AttributeError: 'NoneType' object has no attribute 'keys'
```

Is this a regression or is something else happening?

**Comment by konradkonrad** [comment]
- error seems to happen due to a non-expected `response` in web3
- we should log request and response, maybe use `DEBUG` log settings for `web3` or `requests`, otherwise in `get_block`
- if we can't see a way for an upstream fix, we could wrap in a retry logic

**Comment by Dominik1999** [comment]
got the same
```
```
2020-05-07 08:17:34.876376 [debug    ] Registering token to create the network [scenario_player.runner] greenlet_name=orchestration
2020-05-07 08:17:38.343801 [error    ] Exception while running scenario [scenario_player.main] 
Traceback (most recent call last):
  File "/home/pirate/PycharmProjects/ScenarioPlayer/scenario-player/scenario_player/main.py", line 321, in run_
    environment=environment,
  File "/home/pirate/PycharmProjects/ScenarioPlayer/scenario-player/scenario_player/main.py", line 396, in orchestrate
    scenario_runner.run_scenario()
  File "/home/pirate/PycharmProjects/ScenarioPlayer/scenario-player/scenario_player/runner.py", line 347, in run_scenario
    gevent.joinall(greenlets, raise_error=True, count=1)
  File "src/gevent/greenlet.py", line 1002, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 1018, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 364, in gevent._greenlet.Greenlet._raise_exception
  File "/home/pirate/PycharmProjects/ScenarioPlayer/venv/ScenarioPlayer/lib/python3.7/site-packages/gevent/_compat.py", line 62, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "/home/pirate/PycharmProjects/ScenarioPlayer/scenario-player/scenario_player/runner.py", line 431, in setup_environment_and_run_main_task
    token_network_registry_proxy, token_proxy
  File "/home/pirate/PycharmProjects/ScenarioPlayer/scenario-player/scenario_player/runner.py", line 209, in maybe_create_token_network
    block_identifier = token_network_proxy.rpc_client.get_confirmed_blockhash()
  File "/home/pirate/raiden/raiden/network/rpc/client.py", line 970, in get_confirmed_blockhash
    return self.blockhash_from_blocknumber(confirmed_block_number)
  File "/home/pirate/raiden/raiden/network/rpc/client.py", line 974, in blockhash_from_blocknumber
    block = self.get_block(block_number)
  File "/home/pirate/raiden/raiden/network/rpc/client.py", line 960, in get_block
    return self.web3.eth.getBlock(block_identifier)
  File "/home/pirate/PycharmProjects/ScenarioPlayer/venv/ScenarioPlayer/lib/python3.7/site-packages/web3/eth.py", line 217, in getBlock
    [block_identifier, full_transactions],
  File "/home/pirate/PycharmProjects/ScenarioPlayer/venv/ScenarioPlayer/lib/python3.7/site-packages/web3/manager.py", line 149, in request_blocking
    response = self._make_request(method, params)
  File "/home/pirate/PycharmProjects/ScenarioPlayer/venv/ScenarioPlayer/lib/python3.7/site-packages/web3/manager.py", line 128, in _make_request
    return request_func(method, params)
  File "/home/pirate/PycharmProjects/ScenarioPlayer/venv/ScenarioPlayer/lib/python3.7/site-packages/web3/middleware/cache.py", line 134, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/pirate/PycharmProjects/ScenarioPlayer/venv/ScenarioPlayer/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
    response = make_request(method, params)
  File "/home/pirate/PycharmProjects/ScenarioPlayer/venv/ScenarioPlayer/lib/python3.7/site-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/pirate/PycharmProjects/ScenarioPlayer/venv/ScenarioPlayer/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
    response = make_request(method, params)
  File "/home/pirate/PycharmProjects/ScenarioPlayer/venv/ScenarioPlayer/lib/python3.7/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/pirate/PycharmProjects/ScenarioPlayer/venv/ScenarioPlayer/lib/python3.7/site-packages/web3/middleware/formatting.py", line 73, in apply_formatters
    response = make_request(method, formatted_params)
  File "/home/pirate/PycharmProjects/ScenarioPlayer/venv/ScenarioPlayer/lib/python3.7/site-packages/web3/middleware/normalize_errors.py", line 25, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/pirate/PycharmProjects/ScenarioPlayer/venv/ScenarioPlayer/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/pirate/PycharmProjects/ScenarioPlayer/venv/ScenarioPlayer/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/pirate/PycharmProjects/ScenarioPlayer/venv/ScenarioPlayer/lib/python3.7/site-packages/web3/middleware/formatting.py", line 82, in apply_formatters
    formatter(response["result"]),
  File "cytoolz/functoolz.pyx", line 503, in cytoolz.functoolz.Compose.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/pirate/PycharmProjects/ScenarioPlayer/venv/ScenarioPlayer/lib/python3.7/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/home/pirate/PycharmProjects/ScenarioPlayer/venv/ScenarioPlayer/lib/python3.7/site-packages/eth_utils/applicators.py", line 119, in apply_key_map
    set(value.keys())
AttributeError: 'NoneType' object has no attribute 'keys'
``` 
here are the logs

[Fail-Infura-Run.zip](https://github.com/raiden-network/raiden/files/4591670/Fail-Infura-Run.zip)

**Comment by Dominik1999** [comment]
@ulope can you link your PR to that issue?

**Comment by ulope** [comment]
I was finally able to track down what causes this issue. 
In some cases Infura seems to return an invalid JSONRPC:
```
'{"jsonrpc": "2.0", "id": 1239, "result": null}
```

Infura issue (unfortunately closed without proper reason): https://github.com/INFURA/infura/issues/43
