### ISSUE TITLE
Exception: invalid transaction, check gas price

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden#3204]
[raiden-debug_2018-12-23T23:31:26.980277.log](https://github.com/raiden-network/raiden/files/2706415/raiden-debug_2018-12-23T23.31.26.980277.log)
## Problem Definition

Running Raiden `v0.100.1` in production, with an Infura `eth-rpc-endpoint` (not currently supported, but I'm not sure at the moment if it is an Infura issue or a general gas price strategy issue).

Successfully opened 1 channel, transaction for the second channel failed with the following error:

```
2018-12-23 23:36:54.792329 [critical ] new_netting_channel failed     [raiden.network.proxies.token_network] peer1=223fd1e3 peer2=d8da6bf2
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "raiden/connection_manager.py", line 342, in _join_partner
  File "raiden/api/python.py", line 310, in channel_open
  File "raiden/network/proxies/token_network.py", line 178, in new_netting_channel
  File "raiden/network/proxies/token_network.py", line 228, in _new_netting_channel
  File "raiden/network/rpc/client.py", line 588, in poll
Exception: invalid transaction, check gas price
2018-12-23T23:36:54Z <Greenlet "Greenlet-8" at 0x10c71c848: <bound method ConnectionManager._join_partner of ConnectionManager(target=3 channels=1:[<NettingChannelState id:127 opened:<TransactionExecutionStatus started:None finished:6941082 result:success> closed:None settled:None updated:None>])>(b'\xd8\xdak\xf2id\xaf\x9d~\xed\x9e\x03\xe54\x15\xd)> failed with Exception

2018-12-23 23:36:54.804766 [critical ] Unhandled exception when processing endpoint request [raiden.api.rest] node=223fd1e3
Traceback (most recent call last):
  File "flask/app.py", line 1813, in full_dispatch_request
  File "flask/app.py", line 1799, in dispatch_request
  File "flask_restful/__init__.py", line 480, in wrapper
  File "flask/views.py", line 88, in view
  File "flask_restful/__init__.py", line 595, in dispatch_request
  File "webargs/core.py", line 478, in wrapper
  File "raiden/api/v1/resources.py", line 194, in put
  File "raiden/api/rest.py", line 663, in connect
  File "raiden/api/python.py", line 214, in token_network_connect
  File "raiden/connection_manager.py", line 167, in connect
  File "raiden/connection_manager.py", line 437, in _open_channels
  File "src/gevent/greenlet.py", line 849, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 865, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "gevent/_compat.py", line 47, in reraise
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "raiden/connection_manager.py", line 342, in _join_partner
  File "raiden/api/python.py", line 310, in channel_open
  File "raiden/network/proxies/token_network.py", line 178, in new_netting_channel
  File "raiden/network/proxies/token_network.py", line 228, in _new_netting_channel
  File "raiden/network/rpc/client.py", line 588, in poll
Exception: invalid transaction, check gas price
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "raiden/api/rest.py", line 430, in _run
  File "gevent/baseserver.py", line 364, in serve_forever
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
Exception: invalid transaction, check gas price
2018-12-23T23:36:54Z <Greenlet "APIServer|Greenlet-3" at 0x10a20ca48: <bound method APIServer._run of <raiden.api.rest.APIServer object at 0x10bd74f60>>> failed with Exception

2018-12-23 23:36:54.815022 [info     ] 127.0.0.1 - - [2018-12-24 00:36:54] "PUT /api/v1/connections/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2 HTTP/1.1" 500 273 178.992948 [raiden.api.rest.pywsgi] 
FATAL: An unexpected exception occured. A traceback has been written to /var/folders/s_/_xpjyq_j0l7bs262tw_8flcw0000gn/T/raiden-exception-2018-12-23T23-363hthv2j8.txt
invalid transaction, check gas price
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "raiden/ui/runners.py", line 209, in stop_task
  File "src/gevent/greenlet.py", line 633, in gevent._greenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "gevent/_compat.py", line 47, in reraise
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "raiden/api/rest.py", line 430, in _run
  File "gevent/baseserver.py", line 364, in serve_forever
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
Exception: invalid transaction, check gas price
2018-12-23T23:36:54Z <Greenlet "Greenlet-8" at 0x10a20c848: stop_task(<raiden.api.rest.APIServer object at 0x10bd74f60>)> failed with Exception

Traceback (most recent call last):
  File "build/raiden/raiden-script.py", line 2, in <module>
  File "raiden/__main__.py", line 11, in main
  File "click/core.py", line 722, in __call__
  File "click/core.py", line 697, in main
  File "click/core.py", line 1043, in invoke
  File "click/core.py", line 895, in invoke
  File "click/core.py", line 535, in invoke
  File "click/decorators.py", line 17, in new_func
  File "raiden/ui/cli.py", line 425, in run
  File "raiden/ui/runners.py", line 247, in run
  File "raiden/ui/runners.py", line 214, in _start_services
  File "src/gevent/greenlet.py", line 849, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 865, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "gevent/_compat.py", line 47, in reraise
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "raiden/ui/runners.py", line 209, in stop_task
  File "src/gevent/greenlet.py", line 633, in gevent._greenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "gevent/_compat.py", line 47, in reraise
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "raiden/api/rest.py", line 430, in _run
  File "gevent/baseserver.py", line 364, in serve_forever
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
Exception: invalid transaction, check gas price
[34250] Failed to execute script raiden-script
```

**Comment by loredanacirstea** [comment]
Correct, I did not set the gas price flag, so the node used the default strategy.

**Comment by LefterisJP** [comment]
So the reason this can happen is if the gas price returned by the Infura node with the web3.py gas strategy is too low. For very low gas prices it can also be removed from the txpool [here](https://github.com/raiden-network/raiden/blob/9975d8ba9ddd3926d1fe8d9f89ee5c60089449e0/raiden/network/rpc/client.py#L588).

Until we figure out why web3.py does not reliably return a gas price with the "fast strategy" and with Infura (as with #3201) the quick solution to this is to set a specific gas price with the `--gas-price` argument.

**Comment by palango** [comment]
@LefterisJP : @manuelwedler tested last week with infura and didn't run into this issue. As it is quite old I'm in favour of closing it. Do you agree?

**Comment by LefterisJP** [comment]
Sure. If this has been tested and does not come up again I would close it.
