### ISSUE TITLE
Infura endpoint - HTTPSConnectionPool: Read timed out

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden#3205]
## Issue checklist

To help us more easily debug your issue please check the boxes for which requirements for safe usage or Raiden were followed:

- [ ] The Ethereum node was always up to date with the chain tip and never stopped running.
- [ ] No Ethereum transaction was sent for the account that Raiden manages by another app.
- [X] The Ethereum account used by Raiden always had sufficient ETH.
- [X] The Raiden DB that exists by default at ~/.raiden was never altered or deleted.
- [ ] The Raiden node was never restarted. If yes please provide more info.
- [ ] The ethereum node was not switched while Raiden was running.
- [X] The Raiden REST API is protected from public access.

## Problem Definition

I could not start the Raiden node (ver. `0.100.1`) at all with the following command: 
```
raiden-v0.100.1 --accept-disclaimer --eth-rpc-endpoint https://mainnet.infura.io/v3/[APIKEY]--log-config "raiden:info" --keystore-path ~/Library/Ethereum/keystore --rpc --rpccorsdomain http://[SOME_IP]:*/*,http://localhost:*/* --api-address http://localhost:5001 --address 0xbC682A384c48D3bBF6e25Cb10F448F73601B6259 --datadir /Users/loredana/.raiden100_1
```

It kept crashing with the same error:
```
2018-12-24 09:06:40.262374 [info     ] Starting Raiden                [raiden.ui.runners] distribution=bundled python_implementation=CPython python_version=3.6.5 raiden=0.100.1 system=macOS 10.14.2 64bit
Enter the password to unlock 0xbC682A384c48D3bBF6e25Cb10F448F73601B6259:
/var/folders/fk/p5q37dk97gd1bmbxtv3m45dr0000gp/T/_MEIkmIpYx/raiden/network/rpc/client.py:285: UserWarning: Infura does not provide an API to recover the latest used nonce. This may cause the Raiden node to error on restarts.
The error will manifest while there is a pending transaction from a previous execution in the Ethereum's client pool. When Raiden restarts the same transaction with the same nonce will be retried and *rejected*, because the nonce is already used.
Raiden is running in production mode
Checking if the ethereum node is synchronized

You are connected to the 'mainnet' network and the DB path is: /Users/loredana/.raiden100_1/node_bc682a38/netid_1/network_b9633dd9/v16_log.db
2018-12-24 09:06:50.836460 [info     ] Automatically selecting matrix homeserver based on RTT [raiden.network.transport.matrix] homeserver=https://raidentransport.ki-decentralized.com rtt=0.032819999999999995
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 384, in _make_request
  File "<string>", line 2, in raise_from
  File "urllib3/connectionpool.py", line 380, in _make_request
  File "http/client.py", line 1331, in getresponse
  File "http/client.py", line 297, in begin
  File "http/client.py", line 258, in _read_status
  File "socket.py", line 586, in readinto
  File "gevent/_ssl3.py", line 503, in recv_into
  File "gevent/_ssl3.py", line 332, in read
  File "src/gevent/_hub_primitives.py", line 265, in gevent.__hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 266, in gevent.__hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 261, in gevent.__hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 262, in gevent.__hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 151, in gevent.__waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 638, in urlopen
  File "urllib3/util/retry.py", line 367, in increment
  File "urllib3/packages/six.py", line 686, in reraise
  File "urllib3/connectionpool.py", line 600, in urlopen
  File "urllib3/connectionpool.py", line 386, in _make_request
  File "urllib3/connectionpool.py", line 306, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='mainnet.infura.io', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build/raiden/raiden-script.py", line 2, in <module>
  File "raiden/__main__.py", line 11, in main
  File "click/core.py", line 722, in __call__
  File "click/core.py", line 697, in main
  File "click/core.py", line 1043, in invoke
  File "click/core.py", line 895, in invoke
  File "click/core.py", line 535, in invoke
  File "click/decorators.py", line 17, in new_func
  File "raiden/ui/cli.py", line 425, in run
  File "raiden/ui/runners.py", line 247, in run
  File "raiden/ui/runners.py", line 96, in _start_services
  File "raiden/ui/app.py", line 416, in run_app
  File "raiden/app.py", line 152, in start
  File "raiden/raiden_service.py", line 362, in start
  File "raiden/tasks.py", line 176, in first_run
  File "raiden/tasks.py", line 216, in _maybe_run_callbacks
  File "raiden/raiden_service.py", line 548, in _callback_new_block
  File "raiden/blockchain/events.py", line 238, in poll_blockchain_events
  File "raiden/utils/filters.py", line 117, in get_new_entries
  File "web3/eth.py", line 354, in getLogs
  File "web3/manager.py", line 109, in request_blocking
  File "web3/manager.py", line 92, in _make_request
  File "web3/middleware/cache.py", line 105, in middleware
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "web3/middleware/formatting.py", line 48, in apply_formatters
  File "web3/middleware/gas_price_strategy.py", line 18, in middleware
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "web3/middleware/formatting.py", line 48, in apply_formatters
  File "web3/middleware/attrdict.py", line 18, in middleware
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "web3/middleware/formatting.py", line 48, in apply_formatters
  File "web3/middleware/normalize_errors.py", line 9, in middleware
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "web3/middleware/formatting.py", line 50, in apply_formatters
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "web3/middleware/formatting.py", line 48, in apply_formatters
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "web3/middleware/formatting.py", line 50, in apply_formatters
  File "web3/middleware/exception_retry_request.py", line 80, in middleware
  File "web3/providers/rpc.py", line 68, in make_request
  File "web3/utils/request.py", line 26, in make_post_request
  File "requests/sessions.py", line 572, in post
  File "requests/sessions.py", line 524, in request
  File "requests/sessions.py", line 637, in send
  File "requests/adapters.py", line 529, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='mainnet.infura.io', port=443): Read timed out. (read timeout=10)
[4934] Failed to execute script raiden-script
--- Logging error ---
Exception ignored in: <bound method BaseFileLock.__del__ of <filelock.UnixFileLock object at 0x113098eb8>>
Traceback (most recent call last):
  File "filelock.py", line 333, in __del__
  File "filelock.py", line 320, in release
  File "logging/__init__.py", line 1306, in info
  File "logging/__init__.py", line 1442, in _log
  File "logging/__init__.py", line 1452, in handle
  File "logging/__init__.py", line 1514, in callHandlers
  File "logging/__init__.py", line 863, in handle
  File "logging/handlers.py", line 75, in emit
  File "logging/__init__.py", line 916, in handleError
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/traceback.py", line 100, in print_exception
  File "raiden/log_config.py", line 138, in tracebackexception_format
  File "raiden/log_config.py", line 123, in processor_wrapper
ImportError: sys.meta_path is None, Python is likely shutting down
```

I tried the exact same Infura endpoint with Remix and I could successfully connect and read from a mainnet contract. 
I am using the exact same endpoint on another Raiden node, running on Digital Ocean and it works there.

I wanted to restart the node with one of our mainnet remote nodes, but seems they are offline (`Could not contact the ethereum node through JSON-RPC.`), so I cannot test wether it restarts properly or not at the moment.
 
Logs for the first 3 times I tried to start the node, crashing with the above error:

[raiden-debug_2018-12-24T03:39:02.324699.log](https://github.com/raiden-network/raiden/files/2706968/raiden-debug_2018-12-24T03.39.02.324699.log)
[raiden-debug_2018-12-24T03:40:35.475741.log](https://github.com/raiden-network/raiden/files/2706969/raiden-debug_2018-12-24T03.40.35.475741.log)
[raiden-debug_2018-12-24T07:50:24.424759.log](https://github.com/raiden-network/raiden/files/2706970/raiden-debug_2018-12-24T07.50.24.424759.log)

**Comment by LefterisJP** [comment]
@loredanacirstea Our mainnet nodes should be up. I just tested running raiden with them and it works fine. Could you be having some funny network trouble?

**Comment by andrevmatos** [comment]
Hi, @loredanacirstea . It may be related to 10s timeout being too short for infura on the bigish `getLogs` call. Maybe increasing the timeout [here](https://github.com/raiden-network/raiden/blob/9975d8ba9ddd3926d1fe8d9f89ee5c60089449e0/raiden/ui/app.py#L87) with, e.g. `web3 = Web3(HTTPProvider(eth_rpc_endpoint, request_kwarg={'timeout': 60}))` will show if that's actually the problem. Could you try it?

**Comment by loredanacirstea** [comment]
Ok, so I restarted my computer, tried again with the macos binary - same issue.
I then tried the latest master at https://github.com/raiden-network/raiden/tree/9975d8ba9ddd3926d1fe8d9f89ee5c60089449e0 - same issue.

@andrevmatos tried setting `web3 = Web3(HTTPProvider(eth_rpc_endpoint, request_kwarg={'timeout': 60}))` as suggested above with latest master and I got:
```
__init__() got an unexpected keyword argument 'request_kwarg'
```
I don't have time at the moment to look into where I should put the `timeout` argument, but if you give me another suggestion, I can try it.

**Comment by loredanacirstea** [comment]
Oh, didn't notice the typo either. Ok, so with `web3 = Web3(HTTPProvider(eth_rpc_endpoint, request_kwargs={'timeout': 60}))` I get:

```
2018-12-24 12:25:18.056796 [info     ] Starting Raiden                [raiden.ui.runners] distribution=source python_implementation=CPython python_version=3.6.0 raiden=0.100.2.dev13+g9975d8ba.d20181224 system=macOS 10.14.2 64bit
Enter the password to unlock 0xbC682A384c48D3bBF6e25Cb10F448F73601B6259:
/Users/loredana/ETH/raiden/raiden/network/rpc/client.py:285: UserWarning: Infura does not provide an API to recover the latest used nonce. This may cause the Raiden node to error on restarts.
The error will manifest while there is a pending transaction from a previous execution in the Ethereum's client pool. When Raiden restarts the same transaction with the same nonce will be retried and *rejected*, because the nonce is already used.
  'Infura does not provide an API to '
Raiden is running in production mode
Checking if the ethereum node is synchronized

You are connected to the 'mainnet' network and the DB path is: /Users/loredana/.raiden100_1/node_bc682a38/netid_1/network_b9633dd9/v16_log.db
2018-12-24 12:25:26.101915 [info     ] Automatically selecting matrix homeserver based on RTT [raiden.network.transport.matrix] homeserver=https://persephone.raidentransport.digitalvirtues.com rtt=0.032504
Traceback (most recent call last):
  File "/Users/loredana/ETH/raiden/env/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/Users/loredana/ETH/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/loredana/ETH/raiden/raiden/ui/cli.py", line 425, in run
    app = runner.run()
  File "/Users/loredana/ETH/raiden/raiden/ui/runners.py", line 247, in run
    return self._start_services()
  File "/Users/loredana/ETH/raiden/raiden/ui/runners.py", line 96, in _start_services
    app_ = run_app(**self._options)
  File "/Users/loredana/ETH/raiden/raiden/ui/app.py", line 416, in run_app
    raiden_app.start()
  File "/Users/loredana/ETH/raiden/raiden/app.py", line 152, in start
    self.raiden.start()
  File "/Users/loredana/ETH/raiden/raiden/raiden_service.py", line 362, in start
    self.alarm.first_run(last_log_block_number)
  File "/Users/loredana/ETH/raiden/raiden/tasks.py", line 176, in first_run
    self._maybe_run_callbacks(latest_block)
  File "/Users/loredana/ETH/raiden/raiden/tasks.py", line 216, in _maybe_run_callbacks
    result = callback(latest_block)
  File "/Users/loredana/ETH/raiden/raiden/raiden_service.py", line 548, in _callback_new_block
    for event in self.blockchain_events.poll_blockchain_events(confirmed_block_number):
  File "/Users/loredana/ETH/raiden/raiden/blockchain/events.py", line 238, in poll_blockchain_events
    for log_event in event_listener.filter.get_new_entries(block_number):
  File "/Users/loredana/ETH/raiden/raiden/utils/filters.py", line 117, in get_new_entries
    result = self.web3.eth.getLogs(filter_params)
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/web3/eth.py", line 354, in getLogs
    "eth_getLogs", [filter_params],
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/web3/manager.py", line 109, in request_blocking
    response = self._make_request(method, params)
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/web3/manager.py", line 92, in _make_request
    return request_func(method, params)
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/web3/middleware/cache.py", line 105, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/web3/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/web3/middleware/exception_retry_request.py", line 80, in middleware
    return make_request(method, params)
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/web3/providers/rpc.py", line 68, in make_request
    **self.get_request_kwargs()
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/web3/utils/request.py", line 27, in make_post_request
    response.raise_for_status()
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://mainnet.infura.io/v3/ebca4c2a0f4b4cf9ba4669ac26d3dde2
Exception ignored in: <bound method BaseFileLock.__del__ of <filelock.UnixFileLock object at 0x10bdad198>>
Traceback (most recent call last):
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/filelock.py", line 333, in __del__
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/filelock.py", line 320, in release
  File "/Users/loredana/.pyenv/versions/3.6.0/lib/python3.6/logging/__init__.py", line 1301, in info
  File "/Users/loredana/.pyenv/versions/3.6.0/lib/python3.6/logging/__init__.py", line 1436, in _log
  File "/Users/loredana/.pyenv/versions/3.6.0/lib/python3.6/logging/__init__.py", line 1406, in makeRecord
  File "/Users/loredana/.pyenv/versions/3.6.0/lib/python3.6/logging/__init__.py", line 295, in __init__
  File "/Users/loredana/.pyenv/versions/3.6.0/lib/python3.6/threading.py", line 1236, in current_thread
  File "/Users/loredana/ETH/raiden/env/lib/python3.6/site-packages/gevent/threading.py", line 131, in __init__
ImportError: sys.meta_path is None, Python is likely shutting down
```

Probably a network issue, but it is weird because I have 3 nodes `raiden-v0.18.1.dev57+g786347b2-macOS` that work well with Infura on Kovan on the same personal computer.

**Comment by andrevmatos** [comment]
Hmm, `500 Internal Server Error` is something else. Don't think it's a network error on your side, as it'd give another timeout or some connection refused error. `E500` means the remote host was successfuly contacted, but some weird thing happened inside. Needs further investigation.

**Comment by loredanacirstea** [comment]
Logs from the restart with the above `500 Server Error`:

[raiden-debug_2018-12-24T12:25:17.727708.log](https://github.com/raiden-network/raiden/files/2707297/raiden-debug_2018-12-24T12.25.17.727708.log)

So, indeed - it gets chain data from Infura.

**Comment by andrevmatos** [comment]
Maybe Infura's showing of #3187 (1000 blocks size limit error)? It may be on server side, but certainly is triggered by our request.

**Comment by LefterisJP** [comment]
The block size limit should only apply for light client nodes and I hope infura has full nodes :)

**Comment by loredanacirstea** [comment]
Short note:
Since this issue popped up, I started another node on the same computer, using the same Infura endpoint, just on another Ethereum address and I did not get the above issues anymore - the node started successfully.

So, they only appear with my `0xbC682A384c48D3bBF6e25Cb10F448F73601B6259` Raiden account (which is also a new one).

**Comment by err508** [comment]
I'm also seeing this with `0x0e5215997B8232ace7cC0DEb04dFeB60a4C0beB1` locally and remotely ([0x0e52(1).log](https://github.com/raiden-network/raiden/files/2714756/0x0e52.1.log)). I used the address with earlier releases already. The client works with a fresh address.

**Comment by rakanalh** [comment]
Closing this because it hasn't popped up recently.
