### ISSUE TITLE
Can't start raiden, raiden.exceptions.AddressWithoutCode: [TokenNetworkRegistry]: Address 0x4a6E1fe3dB979e600712E269b26207c49FEe116E does not contain code

### ISSUE THREAD

**Issue by narcis2007** [raiden-network/raiden#3306]
- [x] The Ethereum node was always up to date with the chain tip and never stopped running.
- [x] No Ethereum transaction was sent for the account that Raiden manages by another app.
- [ ] The Ethereum account used by Raiden always had sufficient ETH.
- [x] The Raiden DB that exists by default at ~/.raiden was never altered or deleted.
- [ ] The Raiden node was never restarted. If yes please provide more info. -> just closing the process and rerunning the command again
- [x] The ethereum node was not switched while Raiden was running.
- [x] The Raiden REST API is protected from public access.

## Problem Definition

I can't start raiden properly, I have a geth node synchronized on ropsten and I get this error: 

Traceback (most recent call last):
  File "site-packages/raiden/ui/app.py", line 335, in run_app
  File "site-packages/raiden/network/blockchain_service.py", line 147, in token_network_registry
  File "site-packages/raiden/network/proxies/token_network_registry.py", line 40, in __init__
  File "site-packages/raiden/network/rpc/client.py", line 166, in check_address_has_code
raiden.exceptions.AddressWithoutCode: [TokenNetworkRegistry]: Address 0x4a6E1fe3dB979e600712E269b26207c49FEe116E does not contain code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "raiden-script.py", line 2, in <module>
  File "site-packages/raiden/__main__.py", line 11, in main
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1043, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "site-packages/click/decorators.py", line 17, in new_func
  File "site-packages/raiden/ui/cli.py", line 425, in run
  File "site-packages/raiden/ui/runners.py", line 247, in run
  File "site-packages/raiden/ui/runners.py", line 96, in _start_services
  File "site-packages/raiden/ui/app.py", line 341, in run_app
  File "site-packages/raiden/ui/app.py", line 63, in handle_contract_no_code
  File "site-packages/eth_utils/address.py", line 129, in to_checksum_address
  File "site-packages/eth_utils/address.py", line 75, in to_normalized_address
  File "site-packages/eth_utils/conversions.py", line 157, in hexstr_if_str
  File "site-packages/eth_utils/decorators.py", line 73, in wrapper
  File "site-packages/eth_utils/decorators.py", line 39, in _assert_one_val
TypeError: Exactly one of the passed values can be specified. Instead, values were: (None,), {'hexstr': None}
[12660] Failed to execute script raiden-script

This is how I start raiden and geth: 

geth --syncmode fast --rpc --rpcapi eth,net,web3,txpool --testnet

./raiden --keystore-path  ~/.ethereum/keystore --network-id ropsten --no-sync-check --environment-type development

I've used the red eyes raiden and also the latest release(rc2) but I have the same problem
I'm using ubuntu

**Comment by LefterisJP** [comment]
Can you remove `--no-sync-check`? The most probable cause of what you are seeing is that geth has not synchronized fully. You can also see it if you add `console` at the end of the geth command and when geth starts type: `eth.blockNumber` to see the current blockNumer and compare it to etherscan's highest block for ropsten [here](https://ropsten.etherscan.io/)
