### ISSUE TITLE
Exception when starting Raiden

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3448]
## Problem Definition

Trying to start raiden this morning I got the following traceback:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lefteris/ew/raiden/raiden/__main__.py", line 15, in <module>
    main()
  File "/home/lefteris/ew/raiden/raiden/__main__.py", line 7, in main
    from raiden.ui.cli import run
  File "/home/lefteris/ew/raiden/raiden/ui/cli.py", line 44, in <module>
    from .app import run_app
  File "/home/lefteris/ew/raiden/raiden/ui/app.py", line 26, in <module>
    from raiden.network.transport import MatrixTransport, UDPTransport
  File "/home/lefteris/ew/raiden/raiden/network/transport/__init__.py", line 1, in <module>
    from raiden.network.transport.matrix import MatrixTransport  # NOQA
  File "/home/lefteris/ew/raiden/raiden/network/transport/matrix/__init__.py", line 1, in <module>
    from raiden.network.transport.matrix.transport import (  # noqa
  File "/home/lefteris/ew/raiden/raiden/network/transport/matrix/transport.py", line 39, in <module>
    from raiden.network.transport.udp import udp_utils
  File "/home/lefteris/ew/raiden/raiden/network/transport/udp/__init__.py", line 1, in <module>
    from raiden.network.transport.udp.udp_transport import UDPTransport  # NOQA
  File "/home/lefteris/ew/raiden/raiden/network/transport/udp/udp_transport.py", line 15, in <module>
    from raiden.network.transport.udp import healthcheck
  File "/home/lefteris/ew/raiden/raiden/network/transport/udp/healthcheck.py", line 8, in <module>
    from raiden.network.transport.udp import udp_utils
  File "/home/lefteris/ew/raiden/raiden/network/transport/udp/udp_utils.py", line 5, in <module>
    from gevent.event import Event, _AbstractLinkable
ImportError: cannot import name '_AbstractLinkable' from 'gevent._event' (/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/gevent/_event.cpython-37m-x86_64-linux-gnu.so)
```

This is a clean venv made from scratch. It seems that `gevent` was upgraded somehow to `1.4.0` even though in the constraints we got it pinned to `1.3.6`.

**Comment by LefterisJP** [comment]
Duh -.-; my bad
