### ISSUE TITLE
Respect max event size when sending batched Matrix messages

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#3512]
## Problem definition

@agatsoh experienced the following exception when (re-)starting Raiden:
```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "site-packages/raiden/network/transport/matrix.py", line 263, in _run
  File "site-packages/raiden/network/transport/matrix.py", line 254, in _check_and_send
  File "site-packages/raiden/network/transport/matrix.py", line 1023, in _send_raw
  File "site-packages/matrix_client/room.py", line 105, in send_text
  File "site-packages/matrix_client/api.py", line 336, in send_message
  File "site-packages/matrix_client/api.py", line 256, in send_message_event
  File "site-packages/raiden_libs/network/matrix/client.py", line 75, in _send
  File "site-packages/matrix_client/api.py", line 691, in _send
matrix_client.errors.MatrixRequestError: 413: {"errcode":"M_TOO_LARGE","error":"event too large"}
2019-02-19T12:10:29Z <Greenlet "RetryQueue:b2c94bba" at 0x7f077d3a9158: <bound method _RetryQueue._run of <_RetryQueue for 0xb2c94bbaf307c6dfbf70cc2537385553385a345b>>> failed with MatrixRequestError
```

The reason is most likely the message batching inside the `_RetryQueue`.
According to the [Matrix Spec](https://matrix.org/docs/spec/client_server/r0.4.0.html#size-limits) events may not exceed 65,536 bytes when encoded in canonical-json.

## Tasks

- [ ] Implement size limit on batched messages, so the event doesn't exceed 65536 bytes

**Comment by konradkonrad** [comment]
Ah, this also applies to the `send_global` queue worker, as it batches messages. On startup/recovery, this can potentially lead to a largish number of monitoring requests being sent.

**Comment by marcosmartinez7** [comment]
Having the same problem here.
