### ISSUE TITLE
Fix filelock usage, it must not try to log from `__del__`

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#3559]
## Problem Definition

In recent user reports we've seen a lot of exception shutdowns contain an additional logging error at the end.

Example:
```
--- Logging error ---
Exception ignored in: <function BaseFileLock.__del__ at 0x10ae878c8>
Traceback (most recent call last):
  File "filelock.py", line 333, in __del__
  File "filelock.py", line 320, in release
  File "logging/__init__.py", line 1332, in info
  File "logging/__init__.py", line 1468, in _log
  File "logging/__init__.py", line 1478, in handle
  File "logging/__init__.py", line 1540, in callHandlers
  File "logging/__init__.py", line 854, in handle
  File "logging/handlers.py", line 72, in emit
  File "logging/__init__.py", line 907, in handleError
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/traceback.py", line 100, in print_exception
  File "raiden/log_config.py", line 138, in tracebackexception_format
  File "raiden/log_config.py", line 123, in processor_wrapper
ImportError: sys.meta_path is None, Python is likely shutting down
```

The superficial cause seems to be related to `filelock` perfoming a logging call from within its `__del__` method (which isn't a good idea). However we didn't used to have this error in the past.

Investigation needed.

**Comment by hackaugusto** [comment]
This was analyzed as part of https://github.com/raiden-network/raiden/issues/4639 . The solution is to either use a context manager for the logger. Or fork the library and apply the PR https://github.com/benediktschmitt/py-filelock/pull/55

**Comment by Dominik1999** [comment]
handle exception instead of using context managers

**Comment by Dominik1999** [comment]
> handle exception instead of using context managers

haha those are just notes from a dialogue with Augusto. I just wanted that this does not get lost.

**Comment by karlb** [comment]
We don't use `__del__`, anymore. This is checked by https://github.com/raiden-network/raiden/pull/5568.
