### ISSUE TITLE
Don't query chain state for blocks 128 block numbers in the past and more

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3566]
## Problem Definition

As pointed out by @offerm [here](https://github.com/raiden-network/raiden/issues/3555#issuecomment-468074337) since we now started to query old state in the proxies we can have a problem with older blocks.

If we query the chain state at a block 128 blocks older than the current one then an ethereum client with state pruning activated (should be both geth and parity by default, unless they are an archive node) will throw an error.

Example error from geth is:

```
`{'code': -32000, 'message': 'missing trie node d74423b54378a6d49546847401bb01798f2ac01f8f0a9ba47ed8a5b26c20ef4c (path )'}`
```

from parity:

```
Error: This request is not supported because your node is running with state pruning. Run with --pruning=archive
```

## Task

Identify the places where chain state is queried with a `block_number` or `block_hash` and figure out a strategy that safely avoids performing such queries with a block_hash/block_number that's older than 128 blocks.

Or perhaps the better option here is to handle the errors thrown by the clients and if such an error is thrown then use the latest block (if that makes sense for the respective query).

**Comment by offerm** [comment]
@LefterisJP This is not solved. #3555 is still with us.

**Comment by LefterisJP** [comment]
@offerm What do you mean? Where did you get the error again? Can be a part we missed. Can you give more info?

**Comment by offerm** [comment]
@LefterisJP 
With latest master (just rebased) and an empty raiden dir

```
/Users/admin/.virtualenvs/raiden/bin/python -m raiden --datadir exchange-a --keystore-path /Users/admin/xud-eth/blkchain1/keystore/ --network-id 4321 --accept-disclaimer --address 0x4F6799E2341379eA52213919622B9bEc80a1b655 --rpc --api-address 0.0.0.0:5001 --web-ui --environment-type development --password-file passwd_file --console --no-sync-check --accept-disclaimer --tokennetwork-registry-contract-address 0xaa1c9586BbCF5795828A09d705d41B7fF65dD90A --secret-registry-contract-address 0x6DC70232E11b5b5C4A5f2DEbe7DfE83752b24de9 --endpoint-registry-contract-address 0x147fa2035beB2a5e6613b232213e6962B6bD1C47 --gas-price 10000000000
Welcome to Raiden, version 0.100.2rc5.dev548+g50e6f3ff.d20190325!
----------------------------------------------------------------------
| This is an Alpha version of experimental open source software      |
| released as a test version under an MIT license and may contain    |
| errors and/or bugs. No guarantee or representations whatsoever is  |
| made regarding its suitability (or its use) for any purpose or     |
| regarding its compliance with any applicable laws and regulations. |
| Use of the software is at your own risk and discretion and by      |
| using the software you acknowledge that you have read this         |
| disclaimer, understand its contents, assume all risk related       |
| thereto and hereby release, waive, discharge and covenant not to   |
| sue Brainbot Labs Establishment or any officers, employees or      |
| affiliates from and for any direct or indirect liability resulting |
| from the use of the software as permissible by applicable laws and |
| regulations.                                                       |
|                                                                    |
| Privacy Warning: Please be aware, that by using the Raiden Client, |
| among others, your Ethereum address, channels, channel deposits,   |
| settlements and the Ethereum address of your channel counterparty  |
| will be stored on the Ethereum chain, i.e. on servers of Ethereum  |
| node operators and ergo are to a certain extent publicly available.|
| The same might also be stored on systems of parties running Raiden |
| nodes connected to the same token network. Data present in the     |
| Ethereum chain is very unlikely to be able to be changed, removed  |
| or deleted from the public arena.                                  |
|                                                                    |
| Also be aware, that data on individual Raiden token transfers will |
| be made available via the Matrix protocol to the recipient,        |
| intermediating nodes of a specific transfer as well as to the      |
| Matrix server operators.                                           |
----------------------------------------------------------------------
2019-03-26 16:05:50.572206 [info     ] Starting Raiden                [raiden.ui.runners] architecture=x86_64 distribution=source python_implementation=CPython python_version=3.7.2 raiden=0.100.2rc5.dev548+g50e6f3ff.d20190325 system=macOS 10.14 64bit
Raiden is running in development mode

You are connected to the '4321' network and the DB path is: /Users/admin/xud-eth/exchange-a/node_4f6799e2/netid_4321/network_aa1c9586/v19_log.db
2019-03-26 16:05:56.479066 [info     ] Automatically selecting matrix homeserver based on RTT [raiden.network.transport.matrix.utils] sorted_servers=['https://transport01.raiden.network', 'https://transport03.raiden.network', 'https://transport02.raiden.network']
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/admin/raiden/raiden/__main__.py", line 15, in <module>
    main()
  File "/Users/admin/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/admin/raiden/raiden/ui/cli.py", line 508, in run
    app = runner.run()
  File "/Users/admin/raiden/raiden/ui/runners.py", line 276, in run
    return self._start_services()
  File "/Users/admin/raiden/raiden/ui/runners.py", line 95, in _start_services
    app_ = run_app(**self._options)
  File "/Users/admin/raiden/raiden/ui/app.py", line 503, in run_app
    raiden_app.start()
  File "/Users/admin/raiden/raiden/app.py", line 152, in start
    self.raiden.start()
  File "/Users/admin/raiden/raiden/raiden_service.py", line 487, in start
    self.alarm.first_run(last_log_block_number)
  File "/Users/admin/raiden/raiden/tasks.py", line 221, in first_run
    self._maybe_run_callbacks(latest_block)
  File "/Users/admin/raiden/raiden/tasks.py", line 261, in _maybe_run_callbacks
    result = callback(latest_block)
  File "/Users/admin/raiden/raiden/raiden_service.py", line 772, in _callback_new_block
    on_blockchain_event(self, event)
  File "/Users/admin/raiden/raiden/blockchain_events_handler.py", line 366, in on_blockchain_event
    handle_channel_new(raiden, event)
  File "/Users/admin/raiden/raiden/blockchain_events_handler.py", line 100, in handle_channel_new
    opened_block_hash=block_hash,
  File "/Users/admin/raiden/raiden/blockchain/state.py", line 26, in get_channel_state
    channel_details = payment_channel_proxy.detail(opened_block_hash)
  File "/Users/admin/raiden/raiden/network/proxies/payment_channel.py", line 77, in detail
    channel_identifier=self.channel_identifier,
  File "/Users/admin/raiden/raiden/network/proxies/token_network.py", line 467, in detail
    channel_identifier=channel_identifier,
  File "/Users/admin/raiden/raiden/network/proxies/token_network.py", line 394, in detail_channel
    to_checksum_address(participant2),
  File "/Users/admin/raiden/raiden/network/proxies/token_network.py", line 144, in _call_and_check_result
    call_result = fn(*args).call(block_identifier=block_identifier)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/web3/contract.py", line 1120, in call
    **self.kwargs
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/web3/contract.py", line 1369, in call_contract_function
    return_data = web3.eth.call(call_transaction, block_identifier=block_id)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/web3/eth.py", line 294, in call
    [transaction, block_identifier],
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/web3/manager.py", line 112, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'missing trie node fbbec0d45e7f9cc79dee0e6f72ab46c2c7a681003547651e1926a6b3aadcf0a4 (path )'}
--- Logging error ---

```


If I change raiden.blockchain.state.py:26 from opened_block_hash to `latest` it is working.

**Comment by LefterisJP** [comment]
@offerm The stack trace looks wrong. You are not on latest master. You have probably not rebased properly.

The lines and functions they point to look wrong. Especially the offending one:

```
File "/Users/admin/raiden/raiden/blockchain/state.py", line 26, in get_channel_state
    channel_details = payment_channel_proxy.detail(opened_block_hash)
```

[Here](https://github.com/raiden-network/raiden/blob/9edd2ab3cdd5ba472dcf295900793fb39a7c0bb1/raiden/blockchain/state.py#L27) is a link to the same place in latest master.

There we use latest hash:

```python
    # Here we have to query the latest state because if we query with an older block
    # state (e.g. opened_block_number) the state may have been pruned which will
    # lead to an error.
    latest_block_hash = payment_channel_proxy.client.blockhash_from_blocknumber('latest')
    channel_details = payment_channel_proxy.detail(latest_block_hash)
```

**Comment by offerm** [comment]
yes you are right. Thanks.

Will be happy to check and confirm but blocked by #3687
