### ISSUE TITLE
Raiden crashes on startup in "Received new balance proof, creating message for Monitoring Service."

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#3656]
The Raiden client reproducably crashes on startup with the error
```
2019-03-21 16:07:08.594480 [info     ] Received new balance proof, creating message for Monitoring Service. [raiden.raiden_service] balance_proof=<BalanceProofSignedState nonce:12 transferred_amount:11 locked_amount:0 locksroot:00000000 token_network:cb7fc984 channel_identifier:1 message_hash:61ecf9fe signature:8caace70 sender:062c12c0 chain_id:42>
Traceback (most recent call last):
  File "/home/karl/tools/venv/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/home/karl/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/home/karl/tools/venv/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/karl/raiden/raiden/ui/cli.py", line 474, in run
    app = runner.run()
  File "/home/karl/raiden/raiden/ui/runners.py", line 276, in run
    return self._start_services()
  File "/home/karl/raiden/raiden/ui/runners.py", line 95, in _start_services
    app_ = run_app(**self._options)
  File "/home/karl/raiden/raiden/ui/app.py", line 491, in run_app
    raiden_app.start()
  File "/home/karl/raiden/raiden/app.py", line 144, in start
    self.raiden.start()
  File "/home/karl/raiden/raiden/raiden_service.py", line 442, in start
    self._initialize_monitoring_services_queue(chain_state)
  File "/home/karl/raiden/raiden/raiden_service.py", line 849, in _initialize_monitoring_services_queue
    update_monitoring_service_from_balance_proof(self, balance_proof)
  File "/home/karl/raiden/raiden/raiden_service.py", line 227, in update_monitoring_service_from_balance_proof
    monitoring_message,
  File "/home/karl/raiden/raiden/network/transport/matrix/transport.py", line 554, in send_global
    room_name = make_room_alias(self.network_id, room)
  File "/home/karl/raiden/raiden/utils/runnable.py", line 80, in __getattribute__
    return super().__getattribute__(name)
  File "/home/karl/raiden/raiden/network/transport/matrix/transport.py", line 606, in network_id
    assert self._raiden_service is not None
AssertionError
--- Logging error ---
Exception ignored in: <function BaseFileLock.__del__ at 0x7f1cd98d3158>
Traceback (most recent call last):
  File "/home/karl/tools/venv/lib/python3.7/site-packages/filelock.py", line 333, in __del__
  File "/home/karl/tools/venv/lib/python3.7/site-packages/filelock.py", line 320, in release
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1383, in info
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1519, in _log
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1529, in handle
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
  File "/usr/local/lib/python3.7/logging/__init__.py", line 905, in handle
  File "/usr/local/lib/python3.7/logging/handlers.py", line 72, in emit
  File "/usr/local/lib/python3.7/logging/__init__.py", line 958, in handleError
  File "/usr/local/lib/python3.7/traceback.py", line 104, in print_exception
  File "/home/karl/raiden/raiden/log_config.py", line 145, in tracebackexception_format
  File "/home/karl/raiden/raiden/log_config.py", line 126, in processor_wrapper
ImportError: sys.meta_path is None, Python is likely shutting down
```

This happens with the current Raiden master branch. The account was out of funds shortly before, which might have helped bringing it into a bad state.

The client has been started with
```
raiden --environment-type development --keystore-path /home/karl/.ethereum/keystore/ --network-id kovan --eth-rpc-endpoint http://kovan.ethnodes.brainbot.com:8545 --gas-price fast --accept-disclaimer --enable-monitoring --pathfinding-service-address http://localhost:6003 --log-config :info --api-address localhost:5002
```

**Comment by hackaugusto** [comment]
Huuumm, we need a test that:

- Has monitoring service enabled
- A node *receives a transfer* and is **restarted**

Now, the bug is that `_initialize_monitoring_services_queue` expected the transport *to not be started*:

Original: https://github.com/raiden-network/raiden/commit/ab7abab8bb09066f767ca4479fa36d600180a6c9#diff-72b8041548bf416a299ac073c02e24e5R403

However the transport expects itself to be started.

We have a problem here:

- We **must** initialize the message queue before starting the transport. Otherwise the queued messages may be queued out-of-order, because pushing the queue and processing new messages will race.
- We **must** send the balance proofs before sending unlocks, so the monitoring service queue **has to be processed** before the **message queue**. This is for safety, because otherwise the node could crash after the locked transfer is sent and before the MS is updated.

So, from the above I think this is a bug in the transport and not in the service initialization. I think we have two options:

1. Initialize the transport, and then have calls to:
  - update the monitoring service
  - update the outgoing queue
  - start processing incoming messages
2. Add a queue for the monitoring service initialization, and change the transport code to do things in the above order

I prefer number 2 because it's less function calls / overall states for the transport.
