### ISSUE TITLE
Crash when starting with empty datadir

### ISSUE THREAD

**Issue by offerm** [raiden-network/raiden#3673]
I'm using latest `master` **with an empty datadir**.

When starting raiden I'm getting an exception:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/admin/raiden/raiden/__main__.py", line 15, in <module>
    main()
  File "/Users/admin/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/admin/raiden/raiden/ui/cli.py", line 508, in run
    app = runner.run()
  File "/Users/admin/raiden/raiden/ui/runners.py", line 276, in run
    return self._start_services()
  File "/Users/admin/raiden/raiden/ui/runners.py", line 95, in _start_services
    app_ = run_app(**self._options)
  File "/Users/admin/raiden/raiden/ui/app.py", line 503, in run_app
    raiden_app.start()
  File "/Users/admin/raiden/raiden/app.py", line 152, in start
    self.raiden.start()
  File "/Users/admin/raiden/raiden/raiden_service.py", line 487, in start
    self.alarm.first_run(last_log_block_number)
  File "/Users/admin/raiden/raiden/tasks.py", line 221, in first_run
    self._maybe_run_callbacks(latest_block)
  File "/Users/admin/raiden/raiden/tasks.py", line 261, in _maybe_run_callbacks
    result = callback(latest_block)
  File "/Users/admin/raiden/raiden/raiden_service.py", line 771, in _callback_new_block
    for event in self.blockchain_events.poll_blockchain_events(confirmed_block_number):
  File "/Users/admin/raiden/raiden/blockchain/events.py", line 221, in poll_blockchain_events
    for log_event in event_listener.filter.get_new_entries(block_number):
  File "/Users/admin/raiden/raiden/utils/filters.py", line 153, in get_new_entries
    self._do_get_new_entries(from_block=from_block, to_block=to_block),
  File "/Users/admin/raiden/raiden/utils/filters.py", line 125, in _do_get_new_entries
    result = self.web3.eth.getLogs(filter_params)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/web3/eth.py", line 354, in getLogs
    "eth_getLogs", [filter_params],
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/web3/manager.py", line 112, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'leveldb: not found'}
--- Logging error ---
Exception ignored in: <function BaseFileLock.__del__ at 0x109bf7488>
Traceback (most recent call last):
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/filelock.py", line 333, in __del__
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/filelock.py", line 320, in release
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1383, in info
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/handlers.py", line 72, in emit
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 958, in handleError
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/traceback.py", line 104, in print_exception
  File "/Users/admin/raiden/raiden/log_config.py", line 145, in tracebackexception_format
  File "/Users/admin/raiden/raiden/log_config.py", line 126, in processor_wrapper
ImportError: sys.meta_path is None, Python is likely shutting down

```

changing `FILTER_MAX_BLOCK_RANGE` at raiden.utils.filters.py from 100,000 to 800 solves the problem. 900 still gives that error.

**Comment by offerm** [comment]
@LefterisJP This looks to be related to https://github.com/raiden-network/raiden/pull/3617

**Comment by LefterisJP** [comment]
@offerm That's very strange.

What do you mean empty dir? Empty raiden directory I guess?

Can you give the exact command you start raiden with? What's the ethereum client and how has it started? What system is this, e.t.c.?

The error is this:

> ValueError: {'code': -32000, 'message': 'leveldb: not found'}

Your ethereum client can't find its database.

**Comment by offerm** [comment]
Sorry, looks like the problem is still here even with 800.

**Comment by offerm** [comment]
@LefterisJP can this be related to **pruning**?

I can `get_new_entries (getLogs)` for blocks 0-4095 and for the last 1005 blocks. But if I try to query on any block in between I get the error `ValueError: {'code': -32000, 'message': 'leveldb: not found'}`

**Comment by LefterisJP** [comment]
I can't say for sure. Can you please answer the question I asked above:

> Can you give the exact command you start raiden with? What's the ethereum client and how has it started? What system is this, e.t.c.?

With a focus on the ethereum client command and settings.

**Comment by offerm** [comment]
Sure:
Darwin admins-MacBook-Pro-2.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

geth:
```
geth version
Geth
Version: 1.8.20-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.11.2
Operating System: darwin
GOPATH=/Users/admin/gocode
GOROOT=/usr/local/Cellar/go/1.11.2/libexec
```

geth start command:
```
bootnode=enode://f6f325c6c02d55b42b04dfee41f2afc66bc28636dcfa5140440dd657620fbbd3ffd3c0b7a5673029c13820f4c5ee84cb6760bb030dd58dbfd24404ad70af411d@127.0.0.1:30303
geth --rpc --datadir blkchain1 --bootnodes $bootnode  --networkid 4321 --rpcapi "eth,net,web3,txpool" console
```

raiden start command:
```
python -m raiden --datadir
exchange-a
--keystore-path
/Users/admin/xud-eth/blkchain1/keystore/
--network-id
4321
--accept-disclaimer
--address
0x4F6799E2341379eA52213919622B9bEc80a1b655
--rpc
--api-address
0.0.0.0:5001
--web-ui
--environment-type
development
--password-file
passwd_file
--console
--no-sync-check
--accept-disclaimer
--tokennetwork-registry-contract-address
0xCfeB5326dbe0D157f026e1d3f65F9Ae099BeC81F
--secret-registry-contract-address
0x3bCb5955a4551767617f1d74B0Ab0501e2065357
--endpoint-registry-contract-address
0x278A5390c50015feF404F21277748D17ED77dAdC
--gas-price
10000000000
```

**Comment by offerm** [comment]
Managed to simulate the problem with curl:
can query block 0 - 4095
```
(raiden) admins-MacBook-Pro-2:xud-eth admin$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"topics":["0x000000000000000000000000a94f5374fce5edbc8e2a8697c15331677e6ebf0b"], "fromBlock":"0x0", "toBlock":"0xfff"}],"id":74}' -H "Content-Type: application/json" localhost:8545
{"jsonrpc":"2.0","id":74,"result":[]}
```
can't query any block between 4096 - 8191
```
(raiden) admins-MacBook-Pro-2:xud-eth admin$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"topics":["0x000000000000000000000000a94f5374fce5edbc8e2a8697c15331677e6ebf0b"], "fromBlock":"0x0", "toBlock":"0x1000"}],"id":74}' -H "Content-Type: application/json" localhost:8545
{"jsonrpc":"2.0","id":74,"error":{"code":-32000,"message":"leveldb: not found"}}
```
can query blocks > 8192
```
(raiden) admins-MacBook-Pro-2:xud-eth admin$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"topics":["0x000000000000000000000000a94f5374fce5edbc8e2a8697c15331677e6ebf0b"], "fromBlock":"0x2000", "toBlock":"0x2001"}],"id":74}' -H "Content-Type: application/json" localhost:8545
{"jsonrpc":"2.0","id":74,"result":[]}
```

Should I open an Issue with go ethereum?

**Comment by LefterisJP** [comment]
@offerm Probably. I really don't know why this would happen with geth.

**Comment by offerm** [comment]
Looks like geth related issue.

Open an issue at https://github.com/ethereum/go-ethereum/issues/19336

Thanks

**Comment by offerm** [comment]
@LefterisJP I need you help here.

After I open the issue with ethereum/go-ethereum#19336 I recreated the private chain and redeployed the contacts. I now have a private chain with about 10500 blocks. The chain is used by 5 raiden nodes. Everything worked fine until this morning.

Today I created another raiden node and I'm facing this problem again.

Looks like that the existing 5 raiden nodes are synced with the chain and does not need to query historical logs. Yet. when I start a new raiden node, It queries from block x0 and is getting this error. 

I don't know what I should do now. Recreating everything will take a lot of time and I guess I will face the problem again also with the new chain. 

You can see the problem yourself with:
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"topics":["0x000000000000000000000000a94f5374fce5edbc8e2a8697c15331677e6ebf0b"], "fromBlock":"0x0", "toBlock":"latest"}],"id":74}' -H "Content-Type: application/json" 35.231.222.142:8547
```

while this does not have a problem
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"topics":["0x000000000000000000000000a94f5374fce5edbc8e2a8697c15331677e6ebf0b"], "fromBlock":"0x2000", "toBlock":"latest"}],"id":74}' -H "Content-Type: application/json" 35.231.222.142:8547
```

I'm getting this exception:
```
You are connected to the '4321' network and the DB path is: /home/offer/xud-simnet/raiden-wd/exchange/node_eb69db89/netid_4321/network_81e09b9b/v21_log.db
2019-04-14 11:22:45.407613 [info     ] Automatically selecting matrix homeserver based on RTT [raiden.network.transport.matrix.utils] sorted_servers=['https://persephone.raidentransport.digitalvirtues.com', 'https://raidentransport.ki-decentralized.com', 'https://raidentransport.mycryptoapi.com', 'https://raidentransport.exchangeunion.com']
Traceback (most recent call last):
  File "/home/offer/xud-simnet/raiden-wd/venv/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/home/offer/xud-simnet/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/home/offer/xud-simnet/raiden-wd/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/offer/xud-simnet/raiden-wd/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/offer/xud-simnet/raiden-wd/venv/lib/python3.7/site-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/home/offer/xud-simnet/raiden-wd/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/offer/xud-simnet/raiden-wd/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/offer/xud-simnet/raiden-wd/venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/offer/xud-simnet/raiden/raiden/ui/cli.py", line 539, in run
    app = runner.run()
  File "/home/offer/xud-simnet/raiden/raiden/ui/runners.py", line 276, in run
    return self._start_services()
  File "/home/offer/xud-simnet/raiden/raiden/ui/runners.py", line 95, in _start_services
    app_ = run_app(**self._options)
  File "/home/offer/xud-simnet/raiden/raiden/ui/app.py", line 277, in run_app
    raiden_app.start()
  File "/home/offer/xud-simnet/raiden/raiden/app.py", line 150, in start
    self.raiden.start()
  File "/home/offer/xud-simnet/raiden/raiden/raiden_service.py", line 538, in start
    self.alarm.first_run(last_log_block_number)
  File "/home/offer/xud-simnet/raiden/raiden/tasks.py", line 222, in first_run
    self._maybe_run_callbacks(latest_block)
  File "/home/offer/xud-simnet/raiden/raiden/tasks.py", line 262, in _maybe_run_callbacks
    result = callback(latest_block)
  File "/home/offer/xud-simnet/raiden/raiden/raiden_service.py", line 822, in _callback_new_block
    for event in self.blockchain_events.poll_blockchain_events(confirmed_block_number):
  File "/home/offer/xud-simnet/raiden/raiden/blockchain/events.py", line 221, in poll_blockchain_events
    for log_event in event_listener.filter.get_new_entries(block_number):
  File "/home/offer/xud-simnet/raiden/raiden/utils/filters.py", line 153, in get_new_entries
    self._do_get_new_entries(from_block=from_block, to_block=to_block),
  File "/home/offer/xud-simnet/raiden/raiden/utils/filters.py", line 125, in _do_get_new_entries
    result = self.web3.eth.getLogs(filter_params)
  File "/home/offer/xud-simnet/raiden-wd/venv/lib/python3.7/site-packages/web3/eth.py", line 355, in getLogs
    "eth_getLogs", [filter_params],
  File "/home/offer/xud-simnet/raiden-wd/venv/lib/python3.7/site-packages/web3/manager.py", line 112, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'context canceled'}
--- Logging error ---
Exception ignored in: <function BaseFileLock.__del__ at 0x7faf237020d0>
Traceback (most recent call last):
  File "/home/offer/xud-simnet/raiden-wd/venv/lib/python3.7/site-packages/filelock.py", line 333, in __del__
  File "/home/offer/xud-simnet/raiden-wd/venv/lib/python3.7/site-packages/filelock.py", line 320, in release
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1383, in info
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1519, in _log
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1529, in handle
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
  File "/usr/local/lib/python3.7/logging/__init__.py", line 905, in handle
  File "/usr/local/lib/python3.7/logging/handlers.py", line 72, in emit
  File "/usr/local/lib/python3.7/logging/__init__.py", line 958, in handleError
  File "/usr/local/lib/python3.7/traceback.py", line 104, in print_exception
  File "/home/offer/xud-simnet/raiden/raiden/log_config.py", line 145, in tracebackexception_format
  File "/home/offer/xud-simnet/raiden/raiden/log_config.py", line 126, in processor_wrapper
ImportError: sys.meta_path is None, Python is likely shutting down
```

I can share the raiden start script if you like.

BTW - I'm running geth with `--gcmode=archive`

I have 2 geth nodes in the network and both give the same error.

**Comment by LefterisJP** [comment]
I will take a look and try to see if I can recreate this.

**Comment by LefterisJP** [comment]
@offerm So it seems that in your case geth returns an error I have never seen before. `context canceled`. There seems to be an issue opened very recently for this in geth: https://github.com/ethereum/go-ethereum/issues/19146

**Comment by karalabe** [comment]
Context cancelled was a bug introduced in 1.9.0 a few weeks ago, and hopefully fixed a week ago. If it still persists on latest master please send us a repro. However, it should not be present on stable (that this bug report was opened against).

**Comment by LefterisJP** [comment]
Thank you for the input @karalabe 

So @offerm did you change version in the meantime? Where did you see the context not found error?

**Comment by karalabe** [comment]
`leveldb: not found` is returned when you request something from the database that doesn't exist but it should. Would be nice to know what the request was, or a repro even better.

**Comment by offerm** [comment]
@LefterisJP @karalabe  Looks good!!!!

I pulled the latest master and the problem gone.  Many thanks!!!!

A question - where can I find the 1.9.0-stable version?  Is there a tag for it? Latest tag that I see is `v1.8.9`

**Comment by karalabe** [comment]
@offerm The latest stable is actually v1.8.26 https://github.com/ethereum/go-ethereum/releases (that should be the latest tag too). v1.9.0 is not yet released (hence why `master` might be occasionally hiccup-y). We're working on finalizing the 1.9 release in a couple weeks.

**Comment by offerm** [comment]
@karalabe Many thanks!

Here are the tags that I see:
```
xud@btcd-simnet:~/gocode/src/github.com/ethereum/go-ethereum$ pwd
/home/xud/gocode/src/github.com/ethereum/go-ethereum
xud@btcd-simnet:~/gocode/src/github.com/ethereum/go-ethereum$ git tag|tail -5
v1.8.6
v1.8.7
v1.8.8
v1.8.9
vv0.7.10
```

**Comment by offerm** [comment]
Many thanks @karalabe and @LefterisJP 

Closing this issue.
