### ISSUE TITLE
`KeyError: 'pathfinding_eth_address'` when using PFS with payments

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#3676]
When running Raiden with
```
raiden --environment-type development --keystore-path /home/karl/.ethereum/keystore/ --network-id kovan --eth-rpc-endpoint http://kovan.ethnodes.brainbot.com:8545 --gas-price fast --accept-disclaimer --enable-monitoring --pathfinding-service-address http://localhost:6003 --log-config :info --routing-mode pfs
```
and I initiate a payment, I get the following traceback:
```
Traceback (most recent call last):                              
  File "/home/karl/tools/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()                                                                           
  File "/home/karl/tools/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)     
  File "/home/karl/tools/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)                                                 
  File "/home/karl/tools/venv/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)                                                                     
  File "/home/karl/tools/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 595, in dispatch_request   
    resp = meth(*args, **kwargs)                                                                                      
  File "/home/karl/tools/venv/lib/python3.7/site-packages/webargs/core.py", line 464, in wrapper        
    return func(*args, **kwargs)   
  File "/home/karl/raiden/raiden/api/v1/resources.py", line 258, in post                                                                          
    secret_hash=secret_hash,
  File "/home/karl/raiden/raiden/api/rest.py", line 1107, in initiate_payment
    secret_hash=secret_hash,                                   
  File "/home/karl/raiden/raiden/api/python.py", line 721, in transfer_and_wait
    secret_hash=secret_hash,                                   
  File "/home/karl/raiden/raiden/api/python.py", line 805, in transfer_async  
    secret_hash=secret_hash,                                                                   
  File "/home/karl/raiden/raiden/raiden_service.py", line 1070, in mediated_transfer_async
    secret_hash,                                                                           
  File "/home/karl/raiden/raiden/raiden_service.py", line 1142, in start_mediated_transfer_with_secret
    target_address=target,                                                                    
  File "/home/karl/raiden/raiden/raiden_service.py", line 144, in initiator_init
    privkey=raiden.privkey,                                                                  
  File "/home/karl/raiden/raiden/routing.py", line 40, in get_best_routes
    privkey=privkey,                                                                         
  File "/home/karl/raiden/raiden/routing.py", line 172, in get_best_routes_pfs
    value=amount,                                                                                   
  File "/home/karl/raiden/raiden/network/pathfinding.py", line 206, in query_paths
    block_number=current_block_number,                       
  File "/home/karl/raiden/raiden/network/pathfinding.py", line 180, in create_current_iou
    block_number=block_number,                                   
  File "/home/karl/raiden/raiden/network/pathfinding.py", line 132, in make_iou
    receiver=config['pathfinding_eth_address'],        
KeyError: 'pathfinding_eth_address'
```

With multiple bugs in the happy case implementation, it looks the me like the Raiden client PFS payment implementation is insufficiently tested.

**Comment by LefterisJP** [comment]
@jomuel This also needs unit tests. It seems that there is no`pathfinding_eth_address`. Did you mean to write `pathfinding_service_address` ?
