### ISSUE TITLE
Crash in DB update v18_to_v19

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#3681]
## Problem Definition

I was running tests with the scenario player when nodes stopped starting (with reusing the token enabled).

During investigating I found the following log:
```
--------- Starting ---------
Traceback (most recent call last):
  File "/Users/paul/Projects/brainbot/raiden/venv/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/Users/paul/Projects/brainbot/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/paul/Projects/brainbot/raiden/raiden/ui/cli.py", line 494, in run
    app = runner.run()
  File "/Users/paul/Projects/brainbot/raiden/raiden/ui/runners.py", line 276, in run
    return self._start_services()
  File "/Users/paul/Projects/brainbot/raiden/raiden/ui/runners.py", line 95, in _start_services
    app_ = run_app(**self._options)
  File "/Users/paul/Projects/brainbot/raiden/raiden/ui/app.py", line 510, in run_app
    raiden_app.start()
  File "/Users/paul/Projects/brainbot/raiden/raiden/app.py", line 152, in start
    self.raiden.start()
  File "/Users/paul/Projects/brainbot/raiden/raiden/raiden_service.py", line 429, in start
    self.maybe_upgrade_db()
  File "/Users/paul/Projects/brainbot/raiden/raiden/raiden_service.py", line 1165, in maybe_upgrade_db
    manager.run()
  File "/Users/paul/Projects/brainbot/raiden/raiden/utils/upgrades.py", line 186, in run
    **self._kwargs,
  File "/Users/paul/Projects/brainbot/raiden/raiden/utils/upgrades.py", line 79, in _run_upgrade_func
    new_version = func(cursor, version, RAIDEN_DB_VERSION, **kwargs)
  File "/Users/paul/Projects/brainbot/raiden/raiden/storage/migrations/v18_to_v19.py", line 213, in upgrade_v18_to_v19
    _add_blockhash_to_state_changes(storage, cache)
  File "/Users/paul/Projects/brainbot/raiden/raiden/storage/migrations/v18_to_v19.py", line 70, in _add_blockhash_to_state_changes
    assert 'block_hash' not in data, 'v18 state changes cant contain blockhash'
AssertionError: v18 state changes cant contain blockhash
--------- Stopped ---------
```

And the logs:
```
{"raiden": "0.100.2rc5.dev610+g1a32bbd8.d20190326", "python_implementation": "CPython", "python_version": "3.7.2", "system": "macOS 10.14.4 64bit", "architecture": "x86_64", "distribution": "source", "event": "Starting Raiden", "logger": "raiden.ui.runners", "level": "info", "timestamp": "2019-03-26 13:55:11.719987"}
{"node": "1c6d403e", "available_nonce": 1, "client": "Geth/v1.8.22-stable/linux-amd64/go1.11.5", "event": "JSONRPCClient created", "logger": "raiden.network.rpc.client", "level": "debug", "timestamp": "2019-03-26 13:55:13.739154"}
{"available_servers": ["https://transport01.raiden.network", "https://transport02.raiden.network", "https://transport03.raiden.network"], "event": "Fetching available matrix servers", "logger": "raiden.ui.app", "level": "debug", "timestamp": "2019-03-26 13:55:14.733211"}
{"rtt_times": [["https://transport03.raiden.network", 0.020486666666666667], ["https://transport01.raiden.network", 0.02957966666666667], ["https://transport02.raiden.network", 0.10980899999999999]], "event": "Matrix homeserver RTT times", "logger": "raiden.network.transport.matrix.utils", "level": "debug", "timestamp": "2019-03-26 13:55:17.278880"}
{"sorted_servers": ["https://transport03.raiden.network", "https://transport01.raiden.network", "https://transport02.raiden.network"], "event": "Automatically selecting matrix homeserver based on RTT", "logger": "raiden.network.transport.matrix.utils", "level": "info", "timestamp": "2019-03-26 13:55:17.279289"}
{"event": "Upgrading database from 19 to v20", "logger": "raiden.utils.upgrades", "level": "debug", "timestamp": "2019-03-26 13:55:17.450880"}
{"event": "Failed to upgrade database: v18 state changes cant contain blockhash", "logger": "raiden.utils.upgrades", "level": "error", "timestamp": "2019-03-26 13:55:17.451883"}

``` 

### System Description

```
Darwin Pauls-MacBook-Pro-2.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
/usr/local/bin/solc
solc, the solidity compiler commandline interface
Version: 0.5.6+commit.b259423e.Darwin.appleclang
/usr/local/bin/geth
Geth
Version: 1.8.22-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.11.5
Operating System: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.11.5/libexec
/Users/paul/Projects/brainbot/raiden/venv/bin/raiden
{
  "raiden": "0.100.2rc5.dev610+g1a32bbd8.d20190326",
  "python_implementation": "CPython",
  "python_version": "3.7.2",
  "system": "macOS 10.14.4 64bit",
  "architecture": "x86_64",
  "distribution": "source"
}
```

**Comment by LefterisJP** [comment]
@palango Were you running those tests also earlier this week? And also last week and it was all fine with master?

**Comment by palango** [comment]
The DB was created yesterday evening with version 19, so it's strange that the `v18_to_v19`  gets run at all.

**Comment by LefterisJP** [comment]
@palango Thanks man. So it has to be something wrong with the v19 to v20 DB upgrades changes that happened in the PR merged today.

**Comment by palango** [comment]
The database(s) in questions [network_57e670be.zip](https://github.com/raiden-network/raiden/files/3009153/network_57e670be.zip)
