### ISSUE TITLE
Crash when opening new channel

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#3729]
## Problem Definition

When testing the PFS I created a new token and registered it. Afterwards I tried to open a new channel, which failed with the following stacktrace.
```
2019-04-02 14:37:36.202086 [critical ] new_netting_channel failed     [raiden.network.proxies.token_network] peer1=2645bcf9 peer2=5fbf2dd2
2019-04-02 14:37:36.206025 [critical ] Unhandled exception when processing endpoint request [raiden.api.rest] node=2645bcf9
Traceback (most recent call last):
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/webargs/core.py", line 464, in wrapper
    return func(*args, **kwargs)
  File "/Users/paul/Projects/brainbot/raiden/raiden/api/v1/resources.py", line 52, in put
    **kwargs,
  File "/Users/paul/Projects/brainbot/raiden/raiden/api/rest.py", line 655, in open
    settle_timeout,
  File "/Users/paul/Projects/brainbot/raiden/raiden/api/python.py", line 396, in channel_open
    given_block_identifier=views.state_from_raiden(self.raiden).block_hash,
  File "/Users/paul/Projects/brainbot/raiden/raiden/network/proxies/token_network.py", line 269, in new_netting_channel
    settle_timeout=settle_timeout,
  File "/Users/paul/Projects/brainbot/raiden/raiden/network/rpc/smartcontract_proxy.py", line 135, in transact
    raise e
  File "/Users/paul/Projects/brainbot/raiden/raiden/network/rpc/smartcontract_proxy.py", line 97, in transact
    data=decode_hex(data),
  File "/Users/paul/Projects/brainbot/raiden/raiden/network/rpc/client.py", line 807, in send_transaction
    tx_hash = self.web3.eth.sendRawTransaction(signed_txn.rawTransaction)
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/web3/eth.py", line 275, in sendRawTransaction
    [raw_transaction],
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/web3/manager.py", line 112, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'nonce too low'}
2019-04-02 14:37:36.538715 [info     ] 127.0.0.1 - - [2019-04-02 16:37:36] "GET /api/v1/channels HTTP/1.1" 200 137 0.002118 [raiden.api.rest.pywsgi]
2019-04-02 14:37:37.228914 [info     ] 127.0.0.1 - - [2019-04-02 16:37:37] "PUT /api/v1/channels HTTP/1.1" 500 161 2.130686 [raiden.api.rest.pywsgi]
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/Users/paul/Projects/brainbot/raiden/raiden/api/rest.py", line 471, in _run
    self.wsgiserver.serve_forever()
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/gevent/baseserver.py", line 364, in serve_forever
    self._stop_event.wait()
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
ValueError: {'code': -32000, 'message': 'nonce too low'}
2019-04-02T14:37:37Z <Greenlet "APIServer|Greenlet-3" at 0x111f59048: <bound method APIServer._run of <raiden.api.rest.APIServer object at 0x111f53828>>> failed with ValueError

FATAL: An unexpected exception occured. A traceback has been written to /var/folders/g4/rq2cz9m969x4zy_9x04bdv9r0000gn/T/raiden-exception-2019-04-02T14-37lcyi7b8i.txt
{'code': -32000, 'message': 'nonce too low'}
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/Users/paul/Projects/brainbot/raiden/raiden/ui/runners.py", line 235, in stop_task
    task.get()  # re-raise
  File "src/gevent/greenlet.py", line 633, in gevent._greenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/Users/paul/Projects/brainbot/raiden/raiden/api/rest.py", line 471, in _run
    self.wsgiserver.serve_forever()
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/gevent/baseserver.py", line 364, in serve_forever
    self._stop_event.wait()
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
ValueError: {'code': -32000, 'message': 'nonce too low'}
2019-04-02T14:37:37Z <Greenlet "Greenlet-4" at 0x111f598c8: stop_task(<raiden.api.rest.APIServer object at 0x111f53828>)> failed with ValueError

Traceback (most recent call last):
  File "/Users/paul/Projects/brainbot/raiden/venv/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/Users/paul/Projects/brainbot/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/paul/Projects/brainbot/raiden/raiden/ui/cli.py", line 494, in run
    app = runner.run()
  File "/Users/paul/Projects/brainbot/raiden/raiden/ui/runners.py", line 276, in run
    return self._start_services()
  File "/Users/paul/Projects/brainbot/raiden/raiden/ui/runners.py", line 240, in _start_services
    raise_error=True,
  File "src/gevent/greenlet.py", line 849, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 865, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/Users/paul/Projects/brainbot/raiden/raiden/ui/runners.py", line 235, in stop_task
    task.get()  # re-raise
  File "src/gevent/greenlet.py", line 633, in gevent._greenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/Users/paul/Projects/brainbot/raiden/raiden/api/rest.py", line 471, in _run
    self.wsgiserver.serve_forever()
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/gevent/baseserver.py", line 364, in serve_forever
    self._stop_event.wait()
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
ValueError: {'code': -32000, 'message': 'nonce too low'}
```

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
git commit e8cb79007622319dec593966b502529b888b02be and BB eth node for rinkeby.
```

**Comment by LefterisJP** [comment]
you mention rinkeby so I suppose it's geth. Since this is an ethereum client error can you also include the version of geth you tried with?

**Comment by czepluch** [comment]
Did you perform any onchain transactions outside of Raiden after you started your node?

**Comment by palango** [comment]
> Did you perform any onchain transactions outside of Raiden after you started your node?

Yes, seems like it. I thought I used the same node for registering the token I deployed before, but it seems it was another one. Sorry for the noise 🙈

**Comment by LefterisJP** [comment]
@palango This reminds me we should probably somehow handle this error better since the only reason this can happen is using the same account that manages Raiden outside of the Raiden app.

**Comment by palango** [comment]
Yeah, seems like we can catch this and shutdown properly.

**Comment by offerm** [comment]
I faced the same problem.  Best to handle in a way that allows L1 operations form the account.
