### ISSUE TITLE
raiden.user_deposit is `None`

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#3731]
## Problem Definition

I'm testing the PFS integration. I have an open channel and sent a payment from node A to node B. When B received the payment, the nodes crashed with the traceback below.

It seems like the `user_deposit` is not properly initialized.

```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/Users/paul/Projects/brainbot/raiden/raiden/network/transport/matrix/client.py", line 438, in _handle_response
    self.call(room._put_event, event)
  File "/Users/paul/Projects/brainbot/raiden/raiden/network/transport/matrix/client.py", line 386, in call
    return callback(*args, **kwargs)
  File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/matrix_client/room.py", line 308, in _put_event
    listener['callback'](self, event)
  File "/Users/paul/Projects/brainbot/raiden/raiden/network/transport/matrix/transport.py", line 914, in _handle_message
    self._receive_message(message)
  File "/Users/paul/Projects/brainbot/raiden/raiden/network/transport/matrix/transport.py", line 947, in _receive_message
    self._raiden_service.on_message(message)
  File "/Users/paul/Projects/brainbot/raiden/raiden/raiden_service.py", line 665, in on_message
    self.message_handler.on_message(self, message)
  File "/Users/paul/Projects/brainbot/raiden/raiden/message_handler.py", line 49, in on_message
    self.handle_message_unlock(raiden, message)
  File "/Users/paul/Projects/brainbot/raiden/raiden/message_handler.py", line 100, in handle_message_unlock
    raiden.handle_and_track_state_change(state_change)
  File "/Users/paul/Projects/brainbot/raiden/raiden/raiden_service.py", line 673, in handle_and_track_state_change
    for greenlet in self.handle_state_change(state_change):
  File "/Users/paul/Projects/brainbot/raiden/raiden/raiden_service.py", line 695, in handle_state_change
    update_services_from_balance_proof(self, current_state, changed_balance_proof)
  File "/Users/paul/Projects/brainbot/raiden/raiden/raiden_service.py", line 229, in update_services_from_balance_proof
    new_balance_proof=changed_balance_proof.balance_proof,
  File "/Users/paul/Projects/brainbot/raiden/raiden/raiden_service.py", line 296, in update_monitoring_service_from_balance_proof
    rei_balance = raiden.user_deposit.effective_balance(raiden.address, 'latest')
AttributeError: 'NoneType' object has no attribute 'effective_balance'
```

### System Description

Here add a detailed description of your system, e.g. output of the following script:

- Raiden git commit e8cb79007622319dec593966b502529b888b02be
- BB rinkeby geth node

**Comment by LefterisJP** [comment]
I believe this is one of these errors during the startup of the raiden application which https://github.com/raiden-network/raiden/issues/3677 is going to try to improve.

I will probably address this issue as part of my work on 3677.

**Comment by LefterisJP** [comment]
Yes it is. This line is the offender: https://github.com/raiden-network/raiden/blob/e8cb79007622319dec593966b502529b888b02be/raiden/ui/app.py#L406

Mixup between `contracts` and `services_contracts` dictionary. With raiden-contracts v0.17.1 and the work I am doing for 3677 this will be fixed.
