### ISSUE TITLE
Strange matrix behaviour

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#3765]
This is a grab bag of strange behavior I see in the PFS integration tests after https://github.com/raiden-network/raiden/pull/3732 has been merged.

### Raiden client received `UpdatePFS` messages

Suddenly I get warnings in the client about received `UpdatePFS` messages that it cannot decode:
```
2019-04-08 12:29:05.566288 [warning  ] Message data JSON are not a valid message [raiden.network.transport.matrix.transport] _exc=InvalidProtocolMessage('Invalid message type (data["type"] = UpdatePFS)') current_user=@0x2645bcf95d1c3fe89db435be8aaefb887832803b:transport03.raiden.network greenlet_name=GMatrixClient._sync user_id:@0x2645bcf95d1c3fe89db435be8aaefb887832803b:transport03.raiden.network sync_token:s737732_814746_0_1_1285_1_1_19431_1 message_data={"type": "UpdatePFS", "canonical_identifier": {"chain_identifier": "4", "token_network_address": "0xcbd57fdfaafe05e993c13270bcc578d003bdf88f", "channel_identifier": "1"}, "updating_participant": "0x5fbf2dd2032c2b32cbd5909401b610ba3fc8fbde", "other_participant": "0x2645bcf95d1c3fe89db435be8aaefb887832803b", "updating_nonce": 0, "other_nonce": 4, "updating_capacity": "1000000000000000000", "other_capacity": "999000000000000000000", "reveal_timeout": 50, "mediation_fee": "0", "signature": "0x14620a70b66a797e9b323952a0bd606c0b69507de6e16b2b7c5f3ffe1c658e945ddcca43b1ab61022be9b3db68639ce74249bce99fcd00da7e7b058014bc57951c"} node=2645bcf9 peer_address=5fbf2dd2
``` 

### `Processed` and `Delivered` messages in PFS

In the PFS I suddenly get `Processed` and `Delivered` messages, which shouldn't happen (from my understanding)

```
2019-04-08 12:29:05.708512 [warning  ] Message data JSON is not a valid message [raiden_libs.matrix] _exc=InvalidProtocolMessage('Invalid message type (data["type"] = Processed)') message_data={"type": "Processed", "message_identifier": 2839214514195715947, "signature": "0xf0f5119ff72fc013a3a506f2f768f3406fcaec5a498778d32ed5e88e71bf720734ec5e5cdc0ead982653863baa007dc65aa10441375bb201a872640d8c1856c91b"} peer_address=0x5fBf2dd2032C2b32CBD5909401b610ba3fC8FBDE
2019-04-08 12:29:05.792673 [warning  ] Message data JSON is not a valid message [raiden_libs.matrix] _exc=InvalidProtocolMessage('Invalid message type (data["type"] = Delivered)') message_data={"type": "Delivered", "delivered_message_identifier": 2839214514195715947, "signature": "0xfc0ae186e3baec0aa5a349a46384939b80aed0a555322eca9fee5f69f307538f7b7f4f866bd39ad9d009ed6c73c2a4582e098694510c541de64aae2da6b2e2a01b"} peer_address=0x2645bcF95d1c3fE89dB435be8AaEFb887832803b
2019-04-08 12:29:10.700468 [warning  ] Message data JSON is not a valid message [raiden_libs.matrix] _exc=InvalidProtocolMessage('Invalid message type (data["type"] = Processed)') message_data={"type": "Processed", "message_identifier": 11267664782919563632, "signature": "0xa05c739aa2c69b2a2e701639ed4d0c8b71fe08b3a4a75d17058f3705146a01be6a8fa8bd9b6b1c48a8957a45675ab59b661b49b0f9879f4a723a0cf4dee9e2d31c"} peer_address=0x5fBf2dd2032C2b32CBD5909401b610ba3fC8FBDE
2019-04-08 12:29:10.700757 [warning  ] Message data JSON is not a valid message [raiden_libs.matrix] _exc=InvalidProtocolMessage('Invalid message type (data["type"] = Processed)') message_data={"type": "Processed", "message_identifier": 10649996304047253148, "signature": "0x43319854cd4654cab76191f659665ff3d01615c71f1c42337f3d0c9a9986663757f8ed699dcdf8d2aaf4e478a645cd59239b1ca9df25e014194eed569cbbca641b"} peer_address=0x5fBf2dd2032C2b32CBD5909401b610ba3fC8FBDE
2019-04-08 12:29:10.701091 [warning  ] Message data JSON is not a valid message [raiden_libs.matrix] _exc=InvalidProtocolMessage('Invalid message type (data["type"] = Processed)') message_data={"type": "Processed", "message_identifier": 2839214514195715947, "signature": "0xf0f5119ff72fc013a3a506f2f768f3406fcaec5a498778d32ed5e88e71bf720734ec5e5cdc0ead982653863baa007dc65aa10441375bb201a872640d8c1856c91b"} peer_address=0x5fBf2dd2032C2b32CBD5909401b610ba3fC8FBDE
2019-04-08 12:29:10.822646 [warning  ] A MatrixRequestError occured during sync. [raiden.network.transport.matrix.client]
2019-04-08 12:29:10.823063 [warning  ] Problem occured serverside. Waiting [raiden.network.transport.matrix.client] wait_for=5
2019-04-08 12:29:15.901696 [warning  ] Message data JSON is not a valid message [raiden_libs.matrix] _exc=InvalidProtocolMessage('Invalid message type (data["type"] = Delivered)') message_data={"type": "Delivered", "delivered_message_identifier": 11267664782919563632, "signature": "0x455295d4aeda5977504af71340a9801e6a73581bc28aa3dad12e41a380f81e8f45f200c5680dc5d54183aee21ee0b632eddca16995661945ab5e72a864aa48cc1b"} peer_address=0x2645bcF95d1c3fE89dB435be8AaEFb887832803b
2019-04-08 12:29:15.902166 [warning  ] Message data JSON is not a valid message [raiden_libs.matrix] _exc=InvalidProtocolMessage('Invalid message type (data["type"] = Delivered)') message_data={"type": "Delivered", "delivered_message_identifier": 10649996304047253148, "signature": "0xbb2b7895ee5564565bc02a3496577ff1e3f72a41df12a01bfd427f6aef73b6876c03d6f070b712484c3db84047cbe0c064863f887553f8690d79fe39c7223f081c"} peer_address=0x2645bcF95d1c3fE89dB435be8AaEFb887832803b
2019-04-08 12:29:15.902604 [warning  ] Message data JSON is not a valid message [raiden_libs.matrix] _exc=InvalidProtocolMessage('Invalid message type (data["type"] = Delivered)') message_data={"type": "Delivered", "delivered_message_identifier": 2839214514195715947, "signature": "0xfc0ae186e3baec0aa5a349a46384939b80aed0a555322eca9fee5f69f307538f7b7f4f866bd39ad9d009ed6c73c2a4582e098694510c541de64aae2da6b2e2a01b"} peer_address=0x2645bcF95d1c3fE89dB435be8AaEFb887832803b

```

Update:
I also saw this `AttributeError` in the logs:
```
2019-04-08 12:29:03.400255 [warning  ] Message already in queue - ignoring [raiden.network.transport.matrix.transport] message=<Processed [msgid:11267664782919563632]> queue=<QueueIdentifier recipient:2645bcf9 channel_identifier:0> receiver=2645bcf9
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/Users/paul/Projects/brainbot/raiden/raiden/network/transport/matrix/transport.py", line 265, in _run
    f'RetryQueue '
AttributeError: 'NoneType' object has no attribute 'address'
2019-04-08T12:29:03Z <Greenlet "RetryQueue recipient:2645bcf9" at 0x105357488: <bound method _RetryQueue._run of <_RetryQueue for 0x2645bcf95d1c3fe89db435be8aaefb887832803b>>> failed with AttributeError

```

**Comment by Dominik1999** [comment]
Same happend to me 
```
ifier": 11364516363267432682, "payment_identifier": 11905133611982124379, "nonce": 1, "token_network_address": "0x490da088fbd97127a2eb7a848b41ee7f03c9b6a0", "token": "0x13c5b7abcfcaff755b5650bffd194233312374c2", "channel_identifier": 4, "transferred_amount": 0, "locked_amount": 500, "recipient": "0x9bf40cbc2b90fc743d45f37d9a3cae8a6fee0544", "locksroot": "0xcbfb0a2a5b400843ffaa09ccdc9e7c5beaa2c83cae1e37ea0154c07e8d1035eb", "lock": {"type": "Lock", "amount": 500, "expiration": 10762194, "secrethash": "0xa619d11d2efb001848da1273ba24acba27e07b85b503344753cb83ac6840a86b"}, "target": "0x9bf40cbc2b90fc743d45f37d9a3cae8a6fee0544", "initiator": "0xb124256e69207a7e82d64938d42d39ed41e7fdfe", "fee": 0, "signature": "0x858cc90ea384bf2117b219f33a4fd951a153a69f0181513cea3e019dccfd5d1c4a4e09d4b4666bfaca77c9e0deef08fbed4386fb4fa7f9b5383e6995ea2412fb1b"} peer_address=0xb124256e69207A7e82d64938d42D39ED41e7FDfe

```

**Comment by ulope** [comment]
Ok, this has a pretty interesting cause

Both the PFS and MS use global broadcast rooms to receive their respective updates.
The Raiden MatrixTransport doesn't install a listener for those global rooms since it's not interested in the messages and can't do anything with them.

After a node restart all known rooms are checked if they need to be listened on. This is where the "don't listen on global broadcast rooms" mechanism failed for (at least) the PFS room because of two bugs:
- Contrary to the MS broadcast room, the PFS one wasn't being added to the list of global rooms: https://github.com/raiden-network/raiden/blob/21d5c9bff6908caae130999ed8a0b6cd0ce47db2/raiden/ui/app.py#L93
- The check if a room should be listened on erroneously used the actual list of joined global rooms, not the list of the global rooms names (this could have caused issues with server roaming): https://github.com/raiden-network/raiden/blob/21d5c9bff6908caae130999ed8a0b6cd0ce47db2/raiden/network/transport/matrix/transport.py#L626-L630

With this failure to not listen on the PFS broadcast room in place the next phase comes into play.

- To prevent a race condition when two clients mutually try to establish communications with each other at nearly the same time the transport contains a special case handling that updates its internal channel -> matrix room mapping whenever a message is received form a known peer in an 'unexpected' room to continue communication in that room. 
- Since the previous bug caused the PFS room not to be recognized as a global room, the `UpdatePFS` messages are also received by the peer nodes triggering the above described room change [1].
- From this point onwards both nodes assume the `path_finding` room to be the correct room to communicate. This in turn then leads to the PFS receiving the unexpected node protocol messages.

While it's an unfortunate bug it shouldn't have caused any failing / hanging transfers. If you observed any of those there has to be another reason.

PR with fixes and added asserts incoming.

The AttributeError appears to be unrelated. I'll make a separate issue for it.


[1] The reason this switchover happens despite the `UpdatePFS` messages being not valid from a Raiden node's point of view is that the channel handling happens before individual messages are extracted from the batched room messages. We're working on reworking the whole channel <-> room mapping and invitation system.
