### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#389]
TODO

**Comment by LefterisJP** [comment]
Adding
`raiden/tests/unit/test_transfer.py::test_transfer_from_outdated[30-1-2-tester] FAILED`
to the flaky tests list.

This is the error:
```
=================================== FAILURES ===================================

__________________ test_transfer_from_outdated[30-1-2-tester] __________________

raiden_network = [<App f0ef4707>, <App a3c19cc4>], settle_timeout = 30

    @pytest.mark.parametrize('blockchain_type', ['tester'])

    @pytest.mark.parametrize('number_of_nodes', [2])

    @pytest.mark.parametrize('channels_per_node', [1])

    @pytest.mark.parametrize('settle_timeout', [30])

    def test_transfer_from_outdated(raiden_network, settle_timeout):

        app0, app1 = raiden_network  # pylint: disable=unbalanced-tuple-unpacking

        tester_state = app0.raiden.chain.tester_state

    

        token_manager0 = app0.raiden.managers_by_token_address.values()[0]

        token_manager1 = app1.raiden.managers_by_token_address.values()[0]

    

        channel0 = token_manager0.partneraddress_channel[app1.raiden.address]

        channel1 = token_manager1.partneraddress_channel[app0.raiden.address]

    

        balance0 = channel0.balance

        balance1 = channel1.balance

    

        assert token_manager0.token_address == token_manager1.token_address

        assert app1.raiden.address in token_manager0.partneraddress_channel

    

        amount = 10

        app0.raiden.api.transfer(

            token_manager0.token_address,

            amount,

            target=app1.raiden.address,

        )

        gevent.sleep(1)

    

        assert_synched_channels(

            channel0, balance0 - amount, [],

            channel1, balance1 + amount, []

        )

    

        app1.raiden.api.close(token_manager0.token_address, app0.raiden.address)

        tester_state.mine(1)

        gevent.sleep(.5)

        tester_state.mine(number_of_blocks=settle_timeout + 1)

>       app0.raiden.api.settle(token_manager0.token_address, app1.raiden.address)

raiden/tests/unit/test_transfer.py:754: 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <raiden.raiden_service.RaidenAPI object at 0x7f7bca8eb090>

token_address = 'q\xea\xc5d%\xe23z\xb1\r\xddQU\x1c\xf6\x8b\x1b\x84\xa0\xb5'

partner_address = '\xa3\xc1\x9c\xc4v\xbe\x1e\x90a\xde\xeb\xa4\x8bq\xde\x00"\x95%\x15'

    def settle(self, token_address, partner_address):

        """ Settle a closed channel with `partner_address` for the given `token_address`. """

        token_address_bin = safe_address_decode(token_address)

        partner_address_bin = safe_address_decode(partner_address)

    

        if not isaddress(token_address_bin) or token_address_bin not in self.tokens:

            raise InvalidAddress('token address is not valid.')

    

        if not isaddress(partner_address_bin):

            raise InvalidAddress('partner_address is not valid.')

    

        manager = self.raiden.get_manager_by_token_address(token_address_bin)

        channel = manager.get_channel_by_partner_address(partner_address_bin)

    

        if channel.isopen:

>           raise InvalidState('channel is still open.')

E           InvalidState: channel is still open.
```

You can find the entire raw log here: https://gist.github.com/LefterisJP/c2eb630735589619e5557ce99da23d0c

**Comment by konradkonrad** [comment]
This test failed eventually _after_ #412 was merged: https://gist.github.com/konradkonrad/42a8ce8fd45baa913c73d4857995c380

**Comment by konradkonrad** [comment]
`raiden/tests/integration/test_endpointregistry.py::test_endpointregistry` fails flaky:

https://gist.github.com/konradkonrad/ba357d8350b8ac8b5a9eae0aa8660d02

**Comment by hackaugusto** [comment]
https://gist.github.com/hackaugusto/16941c2338491c036fe6868eac749c30

**Comment by hackaugusto** [comment]
https://gist.github.com/hackaugusto/65bcfee9b48c729f7b8174b45cf14dec

**Comment by konradkonrad** [comment]
`raiden/tests/integration/test_events.py::test_event_new_channel` fails flaky
https://gist.github.com/konradkonrad/efae999bd6ebe6a82799e0bbcdabcd8d

**Comment by konradkonrad** [comment]
#459 seems to have fixed one class of issues where we had `Known transaction` exceptions.

**Comment by hackaugusto** [comment]
`test_mediated_transfer[10-2-mock]` failed because the socket was already bound.
https://gist.github.com/hackaugusto/1c975e08c7b09ec0f5f6be079632efd7

PR #526 introduced a test to get only unused ports (does not work on mac), hopefully this won't happen again.

**Comment by hackaugusto** [comment]
`test_settlement[2-settlement:{}]` failed with the wrong netted balances
https://gist.github.com/hackaugusto/ec6005921908bee7d82a835ae4a5b6ed

**Comment by LefterisJP** [comment]
`test_token_swap[19-2-2-geth] ` failed due to 160 seconds timeout being hit
https://gist.github.com/LefterisJP/7a1ac31b6a538ac7c895bffc0948fa47

**Comment by hackaugusto** [comment]
`test_payload_with_address_invalid_length` request failed without a status code
https://gist.github.com/hackaugusto/be4cccdef43403593e2ac912ea4a9153

**Comment by hackaugusto** [comment]
The error on the test `test_payload_with_address_invalid_length` above is due to a race with the flask server:
```
(Pdb++) request.exception
ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=29881): Max retries exceeded with url: /api/1/channels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9956e34890>: Failed to establish a new connection: [Errno 111] Connection refused',))",),)
(Pdb++) print(request.traceback)
Traceback (most recent call last):
  File "/home/hack/.pyenv/versions/2.7.13/envs/raiden/lib/python2.7/site-packages/grequests.py", line 72, in send
    self.url, **merged_kwargs)
  File "/home/hack/.pyenv/versions/2.7.13/envs/raiden/lib/python2.7/site-packages/requests/sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/hack/.pyenv/versions/2.7.13/envs/raiden/lib/python2.7/site-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/home/hack/.pyenv/versions/2.7.13/envs/raiden/lib/python2.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=29881): Max retries exceeded with url: /api/1/channels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9956e34890>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by LefterisJP** [comment]
There is a flaky test in the newly added `long_running` tests.

The test: `raiden/tests/long_running/test_token_networks.py::test_participant_selection` fails in a flaky non deterministic way.

Full travis log [here](https://gist.github.com/LefterisJP/7f04edebf86c90ed3849b67dbfca86ec)

**Comment by hackaugusto** [comment]
`raiden/tests/long_running/test_token_networks.py::test_participant_selection[3-6-False-False-0-6] FAILED` seems to have a race.
https://gist.github.com/hackaugusto/5c1ed645099d518ba13be1e28eb5ba70

**Comment by LefterisJP** [comment]
I got another instance of the same failing test. https://gist.github.com/LefterisJP/d7f5cdfd862d56e2b25bc48276820737

So in both augusto's comment and my comment from 17 days ago (2 comments above) it is a race in the `test_participant_selection` test with these specific arguments: 
```
raiden/tests/long_running/test_token_networks.py::test_participant_selection[3-6-False-False-0-6] 
```
**number_of_nodes**: 3
**channels_per_node**: 6
**cached_genesis**: False
**register_tokens**: False
**settle_timeout**: 0
**reveal_timeout**: 6

**Comment by konradkonrad** [comment]
I believe it is rather
```
number_of_nodes = 6                                                   
channels_per_node = 0                                                 
cached_genesis = False                                                
register_tokens = False                                         
settle_timeout = 6                                                    
reveal_timeout = 3  
```

because `settle_timeout: 0` would raise errors in all instances, no?
no?

**Comment by LefterisJP** [comment]
Yes, quite possible. I assumed the order at which the naming appears is the same as it is written in the tests but with settle_timeout 0 we would fail every time.

**Comment by LefterisJP** [comment]
Another flaky `test_settlement` run.

Log is [here](https://gist.github.com/LefterisJP/e160a077368b4f2e37c68580c55b3169).

When doing the `channel.close()` geth returns a `JSONRPCClientReplyError: replacement transaction underpriced[` error.

**Comment by hackaugusto** [comment]
Tets started failling after the `RaidenShuttingDown` exception was introduced.

https://gist.github.com/hackaugusto/691c822d57d965374eccf6c620b79537

**Comment by hackaugusto** [comment]
RaidenShuttingDown: https://gist.github.com/hackaugusto/ae51232a865ef1ddca04fb8f061c5cb0

**Comment by LefterisJP** [comment]
From commit 566eb1c98c7ebf84b1f44556296055b35a6286f1 and on I got a new flaky error at the `raiden/tests/integration/test_events.py::test_event_new_channel ` test.

Log is [here](https://gist.githubusercontent.com/LefterisJP/e22980cfbf7ef615b42760a08176b6ba/raw/01f16e1ba5b3a80b58bcf12054aab5aa94a53148/test_event_new_channel.log)
