### ISSUE TITLE
SP not working with latest keystore changes

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#3902]
It seems that the latest keystore changes broke the scenario player:

```
--------- Starting ---------
Traceback (most recent call last):
  File "/home/pirate/raiden/venv/RaidenClient/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/home/pirate/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/home/pirate/raiden/venv/RaidenClient/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/pirate/raiden/venv/RaidenClient/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/pirate/raiden/venv/RaidenClient/lib/python3.7/site-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/home/pirate/raiden/venv/RaidenClient/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pirate/raiden/venv/RaidenClient/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/pirate/raiden/venv/RaidenClient/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pirate/raiden/raiden/ui/cli.py", line 522, in run
    app = runner.run()
  File "/home/pirate/raiden/raiden/ui/runners.py", line 276, in run
    return self._start_services()
  File "/home/pirate/raiden/raiden/ui/runners.py", line 95, in _start_services
    app_ = run_app(**self._options)
  File "/home/pirate/raiden/raiden/ui/app.py", line 164, in run_app
    password_file=password_file,
  File "/home/pirate/raiden/raiden/ui/prompt.py", line 58, in unlock_account_with_passwordfile
    password = password_file.read().splitlines()[0]
IndexError: list index out of range
```

**Comment by ulope** [comment]
The SP generated keystores use the empty string as password. 
But `.splitlines()` returns an empty list when called on an empty string.

I'll open a PR that retains the 'ignore newline' functionality but doesn't break in this case.
