### ISSUE TITLE
KeyError 'canonical_identifier' during state restore

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#3960]
## Problem Definition

With latest master (`v0.100.3-rc4-193-g1b357340`) I get the following exception immediately after starting the node:

```

You are connected to the 'kovan' network and the DB path is: /Users/ulo/.raiden/node_00a33749/netid_42/network_edd02d50/v22_log.db
2019-04-29 16:07:32.304139 [debug    ] Fetching available matrix servers [raiden.ui.app] available_servers=['https://transport01.raiden.network', 'https://transport02.raiden.network', 'https://transport03.raiden.network']
2019-04-29 16:07:34.909167 [debug    ] Matrix homeserver RTT times    [raiden.network.transport.matrix.utils] rtt_times=[('https://transport01.raiden.network', 0.02257366666666667), ('https://transport03.raiden.network', 0.030878666666666665), ('https://transport02.raiden.network', 0.116672)]
2019-04-29 16:07:34.910248 [info     ] Automatically selecting matrix homeserver based on RTT [raiden.network.transport.matrix.utils] sorted_servers=['https://transport01.raiden.network', 'https://transport03.raiden.network', 'https://transport02.raiden.network']
Traceback (most recent call last):
  File "/Users/ulo/Envs/raiden/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/Users/ulo/Dropbox/devel/brainbot/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/Users/ulo/Envs/raiden/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ulo/Envs/raiden/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/ulo/Envs/raiden/lib/python3.7/site-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/Users/ulo/Envs/raiden/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ulo/Envs/raiden/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/ulo/Envs/raiden/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/ulo/Dropbox/devel/brainbot/raiden/raiden/ui/cli.py", line 536, in run
    app = runner.run()
  File "/Users/ulo/Dropbox/devel/brainbot/raiden/raiden/ui/runners.py", line 276, in run
    return self._start_services()
  File "/Users/ulo/Dropbox/devel/brainbot/raiden/raiden/ui/runners.py", line 95, in _start_services
    app_ = run_app(**self._options)
  File "/Users/ulo/Dropbox/devel/brainbot/raiden/raiden/ui/app.py", line 304, in run_app
    raiden_app.start()
  File "/Users/ulo/Dropbox/devel/brainbot/raiden/raiden/app.py", line 153, in start
    self.raiden.start()
  File "/Users/ulo/Dropbox/devel/brainbot/raiden/raiden/raiden_service.py", line 457, in start
    state_change_identifier='latest',
  File "/Users/ulo/Dropbox/devel/brainbot/raiden/raiden/storage/wal.py", line 22, in restore_to_state_change
    state_change_identifier=state_change_identifier,
  File "/Users/ulo/Dropbox/devel/brainbot/raiden/raiden/storage/sqlite.py", line 649, in get_snapshot_closest_to_state_change
    snapshot_state = self.serializer.deserialize(row[1])
  File "/Users/ulo/Dropbox/devel/brainbot/raiden/raiden/storage/serialize.py", line 107, in deserialize
    return json.loads(data, object_hook=from_dict_hook)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/Users/ulo/Dropbox/devel/brainbot/raiden/raiden/storage/serialize.py", line 47, in from_dict_hook
    return klass.from_dict(data)
  File "/Users/ulo/Dropbox/devel/brainbot/raiden/raiden/transfer/state.py", line 1684, in from_dict
    canonical_identifier=CanonicalIdentifier.from_dict(data['canonical_identifier']),
KeyError: 'canonical_identifier'
```

Databases for this node:
[network_edd02d50.zip](https://github.com/raiden-network/raiden/files/3128334/network_edd02d50.zip)

**Comment by konradkonrad** [comment]
I found the issue and opened #3962 -- I am not entirely sure, what needs to be done if you're database got corrupted because you already ran a recent `master`. Probably:
- backing up the entire database directory
- removing the `v22` database
- starting raiden with a version that includes this PR
should do the trick.

**Comment by ulope** [comment]
Nice catch :)

Sounds like a good time to re-visit the “explicitly specify migration modules” vs. “auto-import from well known location” discussion.

**Comment by rakanalh** [comment]
In this case, the "v21_log.backup" file should be renamed back to "v21_log.db" and the most recent master after the fix can be ran again.
