### ISSUE TITLE
RaidenUnrecoverableError: setTotalDeposit call will fail. and crashes

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#4178]
## Issue checklist

To help us more easily debug your issue please check the boxes for which requirements for safe usage or Raiden were followed:

- [x ] The Ethereum node was always up to date with the chain tip and never stopped running.
- [x ] No Ethereum transaction was sent for the account that Raiden manages by another app.
- [x ] The Ethereum account used by Raiden always had sufficient ETH.
- [x ] The Raiden DB that exists by default at ~/.raiden was never altered or deleted.
- [x ] The Raiden node was never restarted. If yes please provide more info.
- [x ] The Ethereum node was not switched while Raiden was running.
- [x ] The Raiden REST API is protected from public access.

-->

## Problem Definition

Using the latest stable version v0.100.3 - Rosemary binaries for our TU Berlin workshop Raiden crashed when I tried to deposit tokens via the WebUI to an existing channel. That happened twice, wheras I only have the logs of one of these crashes. 

I used an Infura Endpoint on Goerli.

What happened in my own words:
- ran Raiden binaries and everything worked
- used join network functionality 
- laptop went to sleeping mode
- opened laptop again
- tried to deposit tokens manually via the webUI, since it didn't deposit yet
- Raiden crashed
[raiden-debug_2019-06-05T09:40:01.664420.log](https://github.com/raiden-network/raiden/files/3260403/raiden-debug_2019-06-05T09.40.01.664420.log)

```
2019-06-05 10:03:51.876171 [info     ] 127.0.0.1 - - [2019-06-05 12:03:51] "PATCH /api/v1/channels/0x9B740B496dea54d747680e941921aD28BDA5789C/0x32dAA921C25480aA8f3803c33869be95Df1B06b0 HTTP/1.1" 500 140 594.833549 [raiden.api.rest.pywsgi] 
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "site-packages/raiden/api/rest.py", line 400, in _run
  File "site-packages/gevent/baseserver.py", line 364, in serve_forever
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
raiden.exceptions.RaidenUnrecoverableError: setTotalDeposit call will fail. 
2019-06-05T10:03:51Z <Greenlet "APIServer|Greenlet-3" at 0x7f30eda66ae8: <bound method APIServer._run of <raiden.api.rest.APIServer object at 0x7f30e70e7240>>> failed with RaidenUnrecoverableError

FATAL: setTotalDeposit call will fail. 
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "site-packages/raiden/ui/runners.py", line 226, in stop_task
  File "src/gevent/greenlet.py", line 633, in gevent._greenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "site-packages/gevent/_compat.py", line 47, in reraise
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "site-packages/raiden/api/rest.py", line 400, in _run
  File "site-packages/gevent/baseserver.py", line 364, in serve_forever
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
raiden.exceptions.RaidenUnrecoverableError: setTotalDeposit call will fail. 
2019-06-05T10:03:51Z <Greenlet "Greenlet-4" at 0x7f30e708a9d8: stop_task(<raiden.api.rest.APIServer object at 0x7f30e70e724)> failed with RaidenUnrecoverableError

Traceback (most recent call last):
  File "raiden-script.py", line 2, in <module>
  File "site-packages/raiden/__main__.py", line 13, in main
  File "site-packages/click/core.py", line 764, in __call__
  File "site-packages/click/core.py", line 717, in main
  File "site-packages/click/core.py", line 1114, in invoke
  File "site-packages/click/core.py", line 956, in invoke
  File "site-packages/click/core.py", line 555, in invoke
  File "site-packages/click/decorators.py", line 17, in new_func
  File "site-packages/raiden/ui/cli.py", line 512, in run
  File "site-packages/raiden/ui/runners.py", line 263, in run
  File "site-packages/raiden/ui/runners.py", line 231, in _start_services
  File "src/gevent/greenlet.py", line 849, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 865, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "site-packages/gevent/_compat.py", line 47, in reraise
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "site-packages/raiden/ui/runners.py", line 226, in stop_task
  File "src/gevent/greenlet.py", line 633, in gevent._greenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "site-packages/gevent/_compat.py", line 47, in reraise
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "site-packages/raiden/api/rest.py", line 400, in _run
  File "site-packages/gevent/baseserver.py", line 364, in serve_forever
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
raiden.exceptions.RaidenUnrecoverableError: setTotalDeposit call will fail. 
[20688] Failed to execute script raiden-script
```

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
uname -a 
Linux pirate-ThinkPad-T480s 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

command -v solc && solc --version
/usr/bin/solc
solc, the solidity compiler commandline interface
Version: 0.5.9+commit.c68bc34e.Linux.g++

command -v geth && geth version

command -v parity && parity --version

command -v raiden && raiden version

[ -d .git ] && git rev-parse HEAD
```

**Comment by czepluch** [comment]
When you have time can you then please add info about which version you're using etc.?
