### ISSUE TITLE
Import cycle with CanonicalIdentifier

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#4247]
## Problem Definition

We have an import cycle in the `raiden.constants`  and `raiden.trasnfer.identifiers` modules.
```
Traceback (most recent call last):
  File "raiden/test.py", line 3, in <module>
    from raiden.storage.serialization import DictSerializer
  File "/Users/paul/Projects/brainbot/raiden/raiden/storage/serialization/__init__.py", line 1, in <module>
    from .serializer import DictSerializer, JSONSerializer, SerializationBase  # noqa
  File "/Users/paul/Projects/brainbot/raiden/raiden/storage/serialization/serializer.py", line 13, in <module>
    from raiden.storage.serialization.types import SchemaCache
  File "/Users/paul/Projects/brainbot/raiden/raiden/storage/serialization/types.py", line 8, in <module>
    from raiden.storage.serialization.fields import (
  File "/Users/paul/Projects/brainbot/raiden/raiden/storage/serialization/fields.py", line 9, in <module>
    from raiden.transfer.identifiers import CanonicalIdentifier, QueueIdentifier
  File "/Users/paul/Projects/brainbot/raiden/raiden/transfer/identifiers.py", line 3, in <module>
    from raiden import constants
  File "/Users/paul/Projects/brainbot/raiden/raiden/constants.py", line 7, in <module>
    from raiden.transfer.identifiers import CanonicalIdentifier
ImportError: cannot import name 'CanonicalIdentifier' from 'raiden.transfer.identifiers' (/Users/paul/Projects/brainbot/raiden/raiden/transfer/identifiers.py)
```

**Comment by rakanalh** [comment]
Can reproduce:
```
Python 3.7.0 (default, Jan 20 2019, 18:10:09)
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from raiden.transfer.identifiers import CanonicalIdentifier
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rakan/Brainbot/raiden/raiden/transfer/identifiers.py", line 3, in <module>
    from raiden import constants
  File "/home/rakan/Brainbot/raiden/raiden/constants.py", line 7, in <module>
    from raiden.transfer.identifiers import CanonicalIdentifier
ImportError: cannot import name 'CanonicalIdentifier' from 'raiden.transfer.identifiers' (/home/rakan/Brainbot/raiden/raiden/transfer/identifiers.py)
```
