### ISSUE TITLE
Database connection not closed during (matrix) tests

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#4346]
## Problem Definition

The following message is printed multiple times during a test run. It appears to be triggered by the tests in `integration/network/transport/test_matrix_transport.py`:

```
Exception ignored in: <function SQLiteStorage.__del__ at 0x109425730>
Traceback (most recent call last):
  File "/Users/ulo/Dropbox/devel/brainbot/raiden/raiden/storage/sqlite.py", line 719, in __del__
    raise RuntimeError("The database connection was not closed.")
RuntimeError: The database connection was not closed.
```

**Comment by eorituz** [comment]
Running into the same issue, while trying to run an echonode.
``` 
File "/opt/venv/lib/python3.7/site-packages/raiden/transfer/mediated_transfer/mediation_fee.py", line 110, in calculate_imbalance_fees
    x_values = linspace(TokenAmount(0), channel_capacity, num_base_points)
  File "/opt/venv/lib/python3.7/site-packages/raiden/transfer/mediated_transfer/mediation_fee.py", line 84, in linspace
    assert num > 1
AssertionError
Exception ignored in: <function SQLiteStorage.__del__ at 0x7fd6f126cb00>
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/raiden/storage/sqlite.py", line 719, in __del__
    raise RuntimeError("The database connection was not closed.")
RuntimeError: The database connection was not closed.
```

**Comment by manuelwedler** [comment]
Also having the same issue when running raiden version 0.100.4 after closing it once. Deleting the database file helps to be able to restart raiden again.
```
Exception ignored in: <function BaseFileLock.__del__ at 0x7feb41a62c80>
Traceback (most recent call last):
  File "filelock.py", line 331, in __del__
  File "filelock.py", line 318, in release
  File "logging/__init__.py", line 1383, in info
  File "logging/__init__.py", line 1519, in _log
  File "logging/__init__.py", line 1529, in handle
  File "logging/__init__.py", line 1591, in callHandlers
  File "logging/__init__.py", line 905, in handle
  File "logging/handlers.py", line 72, in emit
  File "logging/__init__.py", line 958, in handleError
  File "/usr/local/lib/python3.7/traceback.py", line 104, in print_exception
  File "raiden/log_config.py", line 143, in tracebackexception_format
  File "raiden/log_config.py", line 123, in processor_wrapper
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function SQLiteStorage.__del__ at 0x7feb41400488>
Traceback (most recent call last):
  File "raiden/storage/sqlite.py", line 719, in __del__
RuntimeError: The database connection was not closed.
```

**Comment by ulope** [comment]
> Deleting the database file helps to be able to restart raiden again.

@manuelwedler *never* delete the database please!

What was the actual issue? This is only about the database not being closed at the right moment. It shouldn't have anything to do with Raiden not being able to start.

**Comment by manuelwedler** [comment]
Here is the full error: 
```
Traceback (most recent call last):
  File "/home/manuel/.virtualenvs/webui-verify/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/home/manuel/Projects/raiden/raiden/raiden/__main__.py", line 13, in main
    run(auto_envvar_prefix="RAIDEN")  # pylint: disable=no-value-for-parameter
  File "/home/manuel/.virtualenvs/webui-verify/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/manuel/.virtualenvs/webui-verify/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/manuel/.virtualenvs/webui-verify/lib/python3.7/site-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/home/manuel/.virtualenvs/webui-verify/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/manuel/.virtualenvs/webui-verify/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/manuel/.virtualenvs/webui-verify/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/manuel/Projects/raiden/raiden/raiden/ui/cli.py", line 507, in run
    app = runner.run()
  File "/home/manuel/Projects/raiden/raiden/raiden/ui/runners.py", line 244, in run
    return self._start_services()
  File "/home/manuel/Projects/raiden/raiden/raiden/ui/runners.py", line 95, in _start_services
    app_ = run_app(**self._options)
  File "/home/manuel/Projects/raiden/raiden/raiden/ui/app.py", line 282, in run_app
    raiden_app.start()
  File "/home/manuel/Projects/raiden/raiden/raiden/app.py", line 125, in start
    self.raiden.start()
  File "/home/manuel/Projects/raiden/raiden/raiden/raiden_service.py", line 432, in start
    self._initialize_channel_fees(self.config.get("use_imbalance_penalty", False))
  File "/home/manuel/Projects/raiden/raiden/raiden/raiden_service.py", line 983, in _initialize_channel_fees
    self.handle_and_track_state_changes([state_change])
  File "/home/manuel/Projects/raiden/raiden/raiden/raiden_service.py", line 569, in handle_and_track_state_changes
    for greenlet in self.handle_state_changes(state_changes):
  File "/home/manuel/Projects/raiden/raiden/raiden/raiden_service.py", line 589, in handle_state_changes
    new_state, raiden_event_list = self.wal.log_and_dispatch(state_changes)
  File "/home/manuel/Projects/raiden/raiden/raiden/storage/wal.py", line 87, in log_and_dispatch
    latest_state, all_events = self.state_manager.dispatch(state_changes)
  File "/home/manuel/Projects/raiden/raiden/raiden/transfer/architecture.py", line 261, in dispatch
    iteration = self.state_transition(next_state, state_change)
  File "/home/manuel/Projects/raiden/raiden/raiden/transfer/node.py", line 1143, in state_transition
    iteration = handle_state_change(chain_state, state_change)
  File "/home/manuel/Projects/raiden/raiden/raiden/transfer/node.py", line 795, in handle_state_change
    state_change=state_change,
  File "/home/manuel/Projects/raiden/raiden/raiden/transfer/node.py", line 156, in subdispatch_by_canonical_id
    pseudo_random_generator=chain_state.pseudo_random_generator,
  File "/home/manuel/Projects/raiden/raiden/raiden/transfer/token_network.py", line 374, in state_transition
    pseudo_random_generator=pseudo_random_generator,
  File "/home/manuel/Projects/raiden/raiden/raiden/transfer/token_network.py", line 61, in subdispatch_to_channel_by_id
    pseudo_random_generator=pseudo_random_generator,
  File "/home/manuel/Projects/raiden/raiden/raiden/transfer/channel.py", line 2508, in state_transition
    iteration = handle_action_update_fee(channel_state=channel_state, update_fee=state_change)
  File "/home/manuel/Projects/raiden/raiden/raiden/transfer/channel.py", line 1939, in handle_action_update_fee
    channel_capacity=get_capacity(channel_state)
  File "/home/manuel/Projects/raiden/raiden/raiden/transfer/mediated_transfer/mediation_fee.py", line 110, in calculate_imbalance_fees
    x_values = linspace(TokenAmount(0), channel_capacity, num_base_points)
  File "/home/manuel/Projects/raiden/raiden/raiden/transfer/mediated_transfer/mediation_fee.py", line 84, in linspace
    assert num > 1
AssertionError
--- Logging error ---
Exception ignored in: <function BaseFileLock.__del__ at 0x7f3e44583158>
Traceback (most recent call last):
  File "/home/manuel/.virtualenvs/webui-verify/lib/python3.7/site-packages/filelock.py", line 331, in __del__
  File "/home/manuel/.virtualenvs/webui-verify/lib/python3.7/site-packages/filelock.py", line 318, in release
  File "/usr/lib/python3.7/logging/__init__.py", line 1383, in info
  File "/usr/lib/python3.7/logging/__init__.py", line 1519, in _log
  File "/usr/lib/python3.7/logging/__init__.py", line 1529, in handle
  File "/usr/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
  File "/usr/lib/python3.7/logging/__init__.py", line 905, in handle
  File "/usr/lib/python3.7/logging/handlers.py", line 72, in emit
  File "/usr/lib/python3.7/logging/__init__.py", line 958, in handleError
  File "/usr/lib/python3.7/traceback.py", line 104, in print_exception
  File "/home/manuel/Projects/raiden/raiden/raiden/log_config.py", line 143, in tracebackexception_format
  File "/home/manuel/Projects/raiden/raiden/raiden/log_config.py", line 123, in processor_wrapper
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function SQLiteStorage.__del__ at 0x7f3e43ad5598>
Traceback (most recent call last):
  File "/home/manuel/Projects/raiden/raiden/raiden/storage/sqlite.py", line 719, in __del__
RuntimeError: The database connection was not closed.
```

**Comment by palango** [comment]
Oh,m that's a different error. I'll create an issue for it.

**Comment by karlb** [comment]
I assume this is solved since https://github.com/raiden-network/raiden/pull/5568.
