### ISSUE TITLE
Simplejson Decode Error

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#4378]
During a scenario run on 11th of July below error occurred. It should have been fixed with https://github.com/raiden-network/raiden/pull/4349, but according to @rakanalh a couple of places could have been missed. 

Link to scenario run in case it's needed: http://scenario-player.ci.raiden.network/Scenario_player_Logs-pfs7_simple_path_rewards-1-latest-2019-07-11.tar.gz

```
--------- Starting ---------
Traceback (most recent call last):
  File "/usr/local/bin/raiden", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/raiden/__main__.py", line 13, in main
    run(auto_envvar_prefix="RAIDEN")  # pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/raiden/ui/cli.py", line 506, in run
    app = runner.run()
  File "/usr/local/lib/python3.7/site-packages/raiden/ui/runners.py", line 239, in run
    return self._start_services()
  File "/usr/local/lib/python3.7/site-packages/raiden/ui/runners.py", line 94, in _start_services
    app_ = run_app(**self._options)
  File "/usr/local/lib/python3.7/site-packages/raiden/ui/app.py", line 205, in run_app
    pathfinding_service_address=pathfinding_service_address,
  File "/usr/local/lib/python3.7/site-packages/raiden/ui/startup.py", line 223, in setup_proxies_or_exit
    token_network_registry_address=Address(token_network_registry.address),
  File "/usr/local/lib/python3.7/site-packages/raiden/network/pathfinding.py", line 218, in configure_pfs_or_exit
    pathfinding_service_info = get_pfs_info(pfs_url)
  File "/usr/local/lib/python3.7/site-packages/raiden/network/pathfinding.py", line 142, in get_pfs_info
    infos = response.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 373, in decode
    raise JSONDecodeError("Extra data", s, end, len(s))
simplejson.errors.JSONDecodeError: Extra data: line 1 column 5 - line 2 column 1 (char 4 - 19)
--------- Stopped ---------
```

**Comment by hackaugusto** [comment]
This happened because `request` switches the json library at runtime, the consequence is that our code catched one exception type, while requests raised another (the switch happened because a downstream library depended on `simplejson`)
