### ISSUE TITLE
RuntimeError: The database connection was not closed

### ISSUE THREAD

**Issue by eorituz** [raiden-network/raiden#4449]
## Problem Definition

Whenever my Raiden node crashes (for whatever reason) or I close it and restart it. I run into `RuntimeError: The database connection was not closed.` which causes raiden to crash.

## Reproduction
Start raiden using Infura rpc and try to access the WebUi. (This will cause a crash due to a "missing port issue" which is according to @ulope already fixed in the latest development branch.)
Nonetheless, I'd expect raiden to close the connection to the DB properly.

### Error message

```
Traceback (most recent call last):
  File "raiden-script.py", line 2, in <module>
  File "raiden/__main__.py", line 13, in main
  File "click/core.py", line 764, in __call__
  File "click/core.py", line 717, in main
  File "click/core.py", line 1114, in invoke
  File "click/core.py", line 956, in invoke
  File "click/core.py", line 555, in invoke
  File "click/decorators.py", line 17, in new_func
  File "raiden/ui/cli.py", line 506, in run
  File "raiden/ui/runners.py", line 239, in run
  File "raiden/ui/runners.py", line 94, in _start_services
  File "raiden/ui/app.py", line 266, in run_app
  File "raiden/app.py", line 125, in start
  File "raiden/raiden_service.py", line 431, in start
  File "raiden/raiden_service.py", line 984, in _initialize_channel_fees
  File "raiden/raiden_service.py", line 568, in handle_and_track_state_changes
  File "raiden/raiden_service.py", line 588, in handle_state_changes
  File "raiden/storage/wal.py", line 87, in log_and_dispatch
  File "raiden/transfer/architecture.py", line 261, in dispatch
  File "raiden/transfer/node.py", line 1141, in state_transition
  File "raiden/transfer/node.py", line 794, in handle_state_change
  File "raiden/transfer/node.py", line 156, in subdispatch_by_canonical_id
  File "raiden/transfer/token_network.py", line 374, in state_transition
  File "raiden/transfer/token_network.py", line 61, in subdispatch_to_channel_by_id
  File "raiden/transfer/channel.py", line 2520, in state_transition
  File "raiden/transfer/channel.py", line 1951, in handle_action_update_fee
  File "raiden/transfer/mediated_transfer/mediation_fee.py", line 110, in calculate_imbalance_fees
  File "raiden/transfer/mediated_transfer/mediation_fee.py", line 84, in linspace
AssertionError
[5077] Failed to execute script raiden-script
--- Logging error ---
Exception ignored in: <function BaseFileLock.__del__ at 0x7fac0ffa7c80>
Traceback (most recent call last):
  File "filelock.py", line 331, in __del__
  File "filelock.py", line 318, in release
  File "logging/__init__.py", line 1383, in info
  File "logging/__init__.py", line 1519, in _log
  File "logging/__init__.py", line 1529, in handle
  File "logging/__init__.py", line 1591, in callHandlers
  File "logging/__init__.py", line 905, in handle
  File "logging/handlers.py", line 72, in emit
  File "logging/__init__.py", line 958, in handleError
  File "/usr/local/lib/python3.7/traceback.py", line 104, in print_exception
  File "raiden/log_config.py", line 143, in tracebackexception_format
  File "raiden/log_config.py", line 123, in processor_wrapper
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function SQLiteStorage.__del__ at 0x7fac0f946488>
Traceback (most recent call last):
  File "raiden/storage/sqlite.py", line 719, in __del__
RuntimeError: The database connection was not closed.
```

### System Description

Using release version `raiden-v0.100.4-linux-x86_64`.
This issue seems to be related to what Manuel posted in #4346

**Comment by palango** [comment]
But this crash is related to the `AssertionError` higher in the stacktrace. This should be fixed with https://github.com/raiden-network/raiden/issues/4446

Can you test if this happens on latest `develop`?

**Comment by hackaugusto** [comment]
This is not a problem. The database engine, sqlite, is ACID, which guarantees durability and consistency of the data.

Not closing the connection is only a problem if it will be opened again, because that is forbidden by the current settings, that could either lead to a deadlock or a crash. In this particular case the node is crashing already, so there is not much to do. We should only find a way to silence this particular error, because it may appear as a bad thing to the user.

**Comment by eorituz** [comment]
@palango yeah it seems like it's fixed in develop.
@hackaugusto yeah it would be good to hide the information, it's pretty misleading...

**Comment by LefterisJP** [comment]
So closing this then. Thanks guys!
