### ISSUE TITLE
Silence `RuntimeError: The database connection was not closed.` during irregural shutdowns

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#4463]
## Problem Definition

As can be seen in #4449 there is an error message about the Database that can be misleading and cause users to panic:

```
Exception ignored in: <function BaseFileLock.__del__ at 0x7fac0ffa7c80>
Traceback (most recent call last):
  File "filelock.py", line 331, in __del__
  File "filelock.py", line 318, in release
  File "logging/__init__.py", line 1383, in info
  File "logging/__init__.py", line 1519, in _log
  File "logging/__init__.py", line 1529, in handle
  File "logging/__init__.py", line 1591, in callHandlers
  File "logging/__init__.py", line 905, in handle
  File "logging/handlers.py", line 72, in emit
  File "logging/__init__.py", line 958, in handleError
  File "/usr/local/lib/python3.7/traceback.py", line 104, in print_exception
  File "raiden/log_config.py", line 143, in tracebackexception_format
  File "raiden/log_config.py", line 123, in processor_wrapper
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function SQLiteStorage.__del__ at 0x7fac0f946488>
Traceback (most recent call last):
  File "raiden/storage/sqlite.py", line 719, in __del__
RuntimeError: The database connection was not closed.
```

## Task

Find a way to silence that error so that the user does not see it.

**Comment by hackaugusto** [comment]
The problem here is that the node was crashing and `RaidenService.stop` was not called, therefore the database connection was not closed. We need a way of always closing the database around [here](https://github.com/raiden-network/raiden/blob/53dc61c9d86e30cf6f0389e194575c0825bbee4f/raiden/ui/app.py#L252-L293).

This could be done by changing the App to be a context manager, or by injecting the database connection to the App (this would move the upgrading logic up).

**Comment by hackaugusto** [comment]
duplicate #4346
