### ISSUE TITLE
Logging is broken during test execution

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#4465]
Currently, pytest does not capture logs as usual and won't display then on test failure. Executing `pytest -s` will show the following logging errors:

```
raiden/tests/unit/test_accounts.py --- Logging error ---
Traceback (most recent call last):
  File "/home/karl/raiden/raiden/accounts.py", line 73, in __init__
    data = json.load(data_file)
  File "/usr/local/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1036, in emit
    stream.write(msg)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/colorama/ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/colorama/ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/colorama/ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
ValueError: I/O operation on closed file.
Call stack:
  File "/home/karl/tools/venv/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/home/karl/tools/venv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 82, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/karl/tools/venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/_pytest/main.py", line 243, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/_pytest/main.py", line 206, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/home/karl/tools/venv/lib/python3.7/site-packages/_pytest/main.py", line 250, in _main
    config.hook.pytest_runtestloop(session=session)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/karl/tools/venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/_pytest/main.py", line 271, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/karl/tools/venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/flaky/flaky_pytest_plugin.py", line 92, in pytest_runtest_protocol
    self.runner.pytest_runtest_protocol(item, nextitem)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/_pytest/runner.py", line 78, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/_pytest/runner.py", line 93, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "/home/karl/tools/venv/lib/python3.7/site-packages/flaky/flaky_pytest_plugin.py", line 129, in call_and_report
    call = self.call_runtest_hook(item, when, **kwds)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/flaky/flaky_pytest_plugin.py", line 307, in call_runtest_hook
    when=when,
  File "/home/karl/tools/venv/lib/python3.7/site-packages/_pytest/runner.py", line 226, in from_call
    result = func()
  File "/home/karl/tools/venv/lib/python3.7/site-packages/flaky/flaky_pytest_plugin.py", line 306, in <lambda>
    lambda: ihook(item=item, **kwds),
  File "/home/karl/tools/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/karl/tools/venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/_pytest/runner.py", line 123, in pytest_runtest_call
    item.runtest()
  File "/home/karl/tools/venv/lib/python3.7/site-packages/_pytest/python.py", line 1464, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/karl/tools/venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/_pytest/python.py", line 174, in pytest_pyfunc_call
    testfunction(**testargs)
  File "/home/karl/raiden/raiden/tests/unit/test_accounts.py", line 62, in test_get_privkey
    account_manager = AccountManager(keystore_mock)
  File "/home/karl/raiden/raiden/accounts.py", line 95, in __init__
    log.warning(msg, path=fullpath, ex=ex)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/structlog/stdlib.py", line 75, in warning
    return self._proxy_to_logger("warning", event, *args, **kw)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/structlog/stdlib.py", line 119, in _proxy_to_logger
    method_name, event=event, **event_kw
  File "/home/karl/tools/venv/lib/python3.7/site-packages/structlog/_base.py", line 192, in _proxy_to_logger
    return getattr(self._logger, method_name)(*args, **kw)
Message: {'path': '/home/karl/raiden/raiden/tests/test_files/UTC--2017-06-20T16-06-00.000000000Z--invalid', 'ex': JSONDecodeError('Expecting value: line 1 column 1 (char 0)'), 'event': 'The account file is not valid JSON format', 'logger': 'raiden.accounts', 'level': 'warning', 'timestamp': '2019-07-26 14:42:26.008485'}
Arguments: ()
```

**Comment by karlb** [comment]
Things seem to behave as intended. I'll just have to understand the intended behavior better.
