### ISSUE TITLE
ModuleNotFoundError: No module named 'typing_extensions

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#4473]
Getting this when trying to start Raiden from a fresh clone and `make install` today.

```
Traceback (most recent call last):
  File "/home/jacob/venvs/.venvRaiden/bin/raiden", line 10, in <module>
    sys.exit(main())
  File "/home/jacob/venvs/.venvRaiden/lib/python3.7/site-packages/raiden/__main__.py", line 8, in main
    from raiden.ui.cli import run
  File "/home/jacob/venvs/.venvRaiden/lib/python3.7/site-packages/raiden/ui/cli.py", line 19, in <module>
    from raiden.app import App
  File "/home/jacob/venvs/.venvRaiden/lib/python3.7/site-packages/raiden/app.py", line 11, in <module>
    from raiden.raiden_service import RaidenService
  File "/home/jacob/venvs/.venvRaiden/lib/python3.7/site-packages/raiden/raiden_service.py", line 17, in <module>
    from raiden.blockchain.decode import (
  File "/home/jacob/venvs/.venvRaiden/lib/python3.7/site-packages/raiden/blockchain/decode.py", line 7, in <module>
    from raiden.blockchain.state import (
  File "/home/jacob/venvs/.venvRaiden/lib/python3.7/site-packages/raiden/blockchain/state.py", line 8, in <module>
    from raiden.storage.restore import (
  File "/home/jacob/venvs/.venvRaiden/lib/python3.7/site-packages/raiden/storage/restore.py", line 4, in <module>
    from raiden.storage.sqlite import (
  File "/home/jacob/venvs/.venvRaiden/lib/python3.7/site-packages/raiden/storage/sqlite.py", line 8, in <module>
    from typing_extensions import Literal
ModuleNotFoundError: No module named 'typing_extensions'
```

**Comment by LefterisJP** [comment]
Yeah let me handle it. Typing extensions is only in the dev requirements.

**Comment by LefterisJP** [comment]
Fixed by https://github.com/raiden-network/raiden/pull/4474
