### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#4497]
```
2019-07-31 13:56:19.109921 [error    ] Exception while running scenario [scenario_player.main]
Traceback (most recent call last):
  File "/Users/paul/Projects/brainbot/scenario-player/scenario_player/main.py", line 181, in run
    runner.run_scenario()
  File "/Users/paul/Projects/brainbot/scenario-player/scenario_player/runner.py", line 184, in run_scenario
    gas_limit=mint_gas,
  File "/Users/paul/Projects/brainbot/scenario-player/scenario_player/runner.py", line 248, in _initialize_scenario_token
    token_ctr, token_block = get_or_deploy_token(self)
  File "/Users/paul/Projects/brainbot/scenario-player/scenario_player/utils/legacy.py", line 245, in get_or_deploy_token
    constructor_parameters=(0, decimals, name, symbol),
  File "/Users/paul/Projects/brainbot/scenario-player/venv/lib/python3.7/site-packages/raiden/network/rpc/client.py", line 584, in deploy_single_contract
    contract_address = receipt["contractAddress"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by palango** [comment]
Quoting @ulope 👍 

Yeah I think this is a bug in `JSONRPCClient.poll()`

It does `transaction = self.web3.eth.getTransaction(transaction_hash)` and then checks the `blockNumber`. But that can be set before the tx is actually confirmed. We had the same bug in `wait_for_tx`. The solution was to use `getTransactionReceipt` which will only return if the tx is actually confirmed.

I’m wondering why that’s not causing more problems in raiden itself.

**Comment by LefterisJP** [comment]
I will take a look at this one today since it's unassigned.

**Comment by palango** [comment]
As far as I understand the problem it can happen with every scenario. I got it in roughly 30% of all runs of the scenario player

**Comment by LefterisJP** [comment]
Okay so we will close this issue by switching to `getTransactionReceipt()` instead of waiting for a non null `block_number` at `getTransaction()` since reportedly both geth and parity do not respect that even though it is defined like that in the [spec](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionbyhash).

At the same time we should probably open an issue to track this question and open two issues one in parity and one in geth to ask why this behaviour is happening and why are they not following the spec.

> I’m wondering why that’s not causing more problems in raiden itself.

The only reason we have not seen this problem in raiden is that we start with a `5` blocks confirmation number as opposed to the `0` used by the scenario player and rpclient.poll() [checks](https://github.com/raiden-network/raiden/blob/0256523f7d8d3fa54bcc5633918e30e1b79884f5/raiden/network/rpc/client.py#L687) for block confirmations.
