### ISSUE TITLE
Network interruptions cause crash in Matrix transport

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/raiden#4610]
## Problem Definition

What looks like intermittent network connectivity issues cause a node crash:

```
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 387, in _make_request
  File "<string>", line 2, in raise_from
  File "urllib3/connectionpool.py", line 383, in _make_request
  File "http/client.py", line 1336, in getresponse
  File "http/client.py", line 306, in begin
  File "http/client.py", line 267, in _read_status
  File "socket.py", line 589, in readinto
  File "gevent/_ssl3.py", line 503, in recv_into
  File "gevent/_ssl3.py", line 327, in read
TimeoutError: [Errno 110] Connection timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 641, in urlopen
  File "urllib3/util/retry.py", line 368, in increment
  File "urllib3/packages/six.py", line 686, in reraise
  File "urllib3/connectionpool.py", line 603, in urlopen
  File "urllib3/connectionpool.py", line 389, in _make_request
  File "urllib3/connectionpool.py", line 318, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='transport03.raiden.network', port=443): Read timed out. (read timeout=None)
```

Tested with v0.100.5a0, reported by @agatsoh.

[SP 1]

**Comment by Dominik1999** [comment]
not a bug, but we have to fix the message.

**Comment by Dominik1999** [comment]
@christianbrb there is the rest of the stack trace missing. We can not debug this without the full stack trace. Do you have, by any chance, the rest of the stack trace?

**Comment by christianbrb** [comment]
@Dominik1999 This issue is very old
@agatsoh Do you still have got the logs available?

**Comment by Dominik1999** [comment]
> @Dominik1999 This issue is very old

I know. Better late than never

**Comment by agatsoh** [comment]
@Dominik1999 @christianbrb Unfortunately I dont have the logs from that time as I had to migrate the machine to a new OS

**Comment by Dominik1999** [comment]
> @Dominik1999 @christianbrb Unfortunately I dont have the logs from that time as I had to migrate the machine to a new OS

thank you for looking for it @agatsoh

**Comment by Dominik1999** [comment]
We can add a better message to the user but Raiden should crash. Catch in runner
