### ISSUE TITLE
`cannot call setTotalWithdraw on a channel that is not open.` causes crash on start

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/raiden#4639]
## Problem Definition
Raiden crashes when starting with the following error:
```
2019-08-19 11:56:39.555885 [critical ] Failed                         [raiden.network.proxies.token_network] contract=0x0dd490B5bDBDF218Fa42E5272dd83628c54889c9 description=set_total_withdraw node=0x06292d52101159d4db5195F043FaD81Fc2F0bc50 participant=0x06292d52101159d4db5195F043FaD81Fc2F0bc50 partner=0xf5eAE6E37B2873D32E11C88E310956D3C9c712f0 total_withdraw=6000000000000000
2019-08-19 11:56:39.558816 [error    ] Failed because of              [raiden.network.proxies.token_network] 
Traceback (most recent call last):
  File "raiden/network/proxies/utils.py", line 121, in log_transaction
  File "raiden/network/proxies/token_network.py", line 1282, in set_total_withdraw
  File "raiden/network/proxies/token_network.py", line 1409, in _set_total_withdraw
raiden.exceptions.RaidenUnrecoverableError: cannot call setTotalWithdraw on a channel that is not open. current_state=2
Traceback (most recent call last):
  File "raiden-script.py", line 2, in <module>
  File "raiden/__main__.py", line 13, in main
  File "click/core.py", line 764, in __call__
  File "click/core.py", line 717, in main
  File "click/core.py", line 1114, in invoke
  File "click/core.py", line 956, in invoke
  File "click/core.py", line 555, in invoke
  File "click/decorators.py", line 17, in new_func
  File "raiden/ui/cli.py", line 511, in run
  File "raiden/ui/runners.py", line 244, in run
  File "raiden/ui/runners.py", line 95, in _start_services
  File "raiden/ui/app.py", line 290, in run_app
  File "raiden/app.py", line 127, in start
  File "raiden/raiden_service.py", line 424, in start
  File "raiden/raiden_service.py", line 822, in _initialize_transactions_queues
  File "raiden/raiden_event_handler.py", line 694, in on_raiden_event
  File "raiden/raiden_event_handler.py", line 178, in on_raiden_event
  File "raiden/raiden_event_handler.py", line 344, in handle_contract_send_channelwithdraw
  File "raiden/network/proxies/payment_channel.py", line 183, in set_total_withdraw
  File "raiden/network/proxies/token_network.py", line 1282, in set_total_withdraw
  File "raiden/network/proxies/token_network.py", line 1409, in _set_total_withdraw
raiden.exceptions.RaidenUnrecoverableError: cannot call setTotalWithdraw on a channel that is not open. current_state=2
[16070] Failed to execute script raiden-script
--- Logging error ---
Exception ignored in: <function BaseFileLock.__del__ at 0x7fdf76eee8c0>
Traceback (most recent call last):
  File "filelock.py", line 331, in __del__
  File "filelock.py", line 318, in release
  File "logging/__init__.py", line 1378, in info
  File "logging/__init__.py", line 1514, in _log
  File "logging/__init__.py", line 1524, in handle
  File "logging/__init__.py", line 1586, in callHandlers
  File "logging/__init__.py", line 894, in handle
  File "logging/handlers.py", line 73, in emit
  File "logging/__init__.py", line 947, in handleError
  File "/usr/local/lib/python3.7/traceback.py", line 104, in print_exception
  File "raiden/log_config.py", line 143, in tracebackexception_format
  File "raiden/log_config.py", line 123, in processor_wrapper
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function SQLiteStorage.__del__ at 0x7fdf763e4050>
Traceback (most recent call last):
  File "raiden/storage/sqlite.py", line 717, in __del__
RuntimeError: The database connection was not closed.
```

### System Description

Raiden v0.100.5a0

**Comment by palango** [comment]
@manuelwedler Can you please attach the complete logs and the DB?

**Comment by manuelwedler** [comment]
Yes, here they are:
[log-and-db.zip](https://github.com/raiden-network/raiden/files/3516014/log-and-db.zip)

**Comment by hackaugusto** [comment]
something is very weird with this stack trace:

```
Traceback (most recent call last):
  File "filelock.py", line 331, in __del__
  File "filelock.py", line 318, in release
  File "logging/__init__.py", line 1378, in info
  File "logging/__init__.py", line 1514, in _log
  File "logging/__init__.py", line 1524, in handle
  File "logging/__init__.py", line 1586, in callHandlers
  File "logging/__init__.py", line 894, in handle
  File "logging/handlers.py", line 73, in emit
  File "logging/__init__.py", line 947, in handleError
  File "/usr/local/lib/python3.7/traceback.py", line 104, in print_exception
  File "raiden/log_config.py", line 143, in tracebackexception_format
  File "raiden/log_config.py", line 123, in processor_wrapper
ImportError: sys.meta_path is None, Python is likely shutting down
```

The above error is raised if the import machinery is called while the node is shutting down. The exceptions is raised [here](https://github.com/python/cpython/blob/3.7/Lib/importlib/_bootstrap.py#L885-L888), but the function in the top of the stack is `processor_wrapper` and not `_find_spec`

**Comment by hackaugusto** [comment]
@manuelwedler how did you ran Raiden?

**Comment by hackaugusto** [comment]
Hummm, something interesting happened. While the interpreter was cleaning up and calling the destructors, `filelock` tried to log this line [`Lock %s released on %s`](https://github.com/benediktschmitt/py-filelock/blob/v3.0.12/filelock.py#L318), however, while that log was being written another exception [was raised and handled](https://github.com/python/cpython/blob/3.7/Lib/logging/handlers.py#L68-L73). The line `--- Logging error ---` is not saying `The process is logging an error`, it is saying `An error occurred in the logging system while writing the log`.

**Comment by ulope** [comment]
The reason for the logging error is that the log call is being preformed in the `__del__` method of filelock. Doing complex things (including IO) is a big no-no in `__del__` methods since they may be called during interpreter shutdown when it may not be fully functional anymore. 

We have the same problem with exceptions in the storage `__del__` method: #4346, #4463

**Comment by manuelwedler** [comment]
@hackaugusto I started Raiden using the internal BB geth node and with these options: 
`--keystore-path ~/.ethereum/testnet/keystore --network-id "rinkeby" --environment-type "development" --pathfinding-service-address=https://pfs-rinkeby.services-dev.raiden.network --api-address "127.0.0.1:5004"`

**Comment by hackaugusto** [comment]
The error is not caused exclusively by the use of the logger in the constructor, the following works:

```python
from logging import getLogger
log = getLogger(__name__)
class A:
  def __del__(self): log.critical("log")
A()
```

The above stack trace at least requires an exception to be thrown from the formatter (I assume the monkey patched for `tracebackexception_format`). Tested with:

```python
from logging import Formatter, getLogger
from logging.config import dictConfig

class RaiseOnFormat(Formatter):
    def format(self, record):
        raise ValueError("error")

log_config = {
    "version": 1,
    "formatters": {"default": {"()": RaiseOnFormat}},
    "handlers": {
        "file": {
            "class": "logging.StreamHandler",
            "formatter": "default",
        }
    },
    "loggers": {"": {"handlers": ["file"]}},
}
dictConfig(log_config)
log = getLogger(__name__)

class A:
    def __del__(self):
        log.critical("log")

A()
```

**Comment by hackaugusto** [comment]
The reason why the trace does not include the line of code is because of the pyinstaller which only distributes the bytecode. The above will print the following if executed from the source:

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "t_log.py", line 7, in format
    raise ValueError("error")
ValueError: error
Call stack:
  File "t_log.py", line 30, in <module>
    A()
  File "t_log.py", line 27, in __del__
    log.critical("log")
Message: 'log'
Arguments: ()
```
And the following if executed from the pyinstaller binary:
```
--- Logging error ---
Traceback (most recent call last):
  File "logging/__init__.py", line 1025, in emit
  File "logging/__init__.py", line 869, in format
  File "t_log.py", line 7, in format
    raise ValueError("error")
ValueError: error
Call stack:
  File "t_log.py", line 30, in <module>
    A()
  File "t_log.py", line 27, in __del__
    log.critical("log")
  File "logging/__init__.py", line 1425, in critical
  File "logging/__init__.py", line 1514, in _log
  File "logging/__init__.py", line 1524, in handle
  File "logging/__init__.py", line 1586, in callHandlers
  File "logging/__init__.py", line 894, in handle
  File "logging/__init__.py", line 1033, in emit
Message: 'log'
Arguments: ()
```

**Comment by hackaugusto** [comment]
This is the minimum example to reproduce the problem:

```
import sys
from logging import Formatter, getLogger
from logging.config import dictConfig
from traceback import TracebackException

class RaiseOnFormat(Formatter):
    def format(self, record):
        raise Exception("error")

def late_import(*args, **kwargs):
    import os

TracebackException.format = late_import

log_config = {
    "version": 1,
    "formatters": {"default": {"()": RaiseOnFormat}},
    "handlers": {"file": {"class": "logging.StreamHandler", "formatter": "default"}},
    "loggers": {"": {"handlers": ["file"]}},
}
dictConfig(log_config)
log = getLogger(__name__)

class A:
    def __del__(self):
        log.critical("log")

sys.modules["a"] = A()
```

**Comment by rakanalh** [comment]
I am able to reproduce this issue in a test... PR incoming
