### ISSUE TITLE
Docs build is broken after last release

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#4689]
## Problem Definition

Docs no longer build either in readthedocs or locally.

```
Traceback (most recent call last):
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/sphinx/application.py", line 331, in build
    self.builder.build_update()
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 342, in build_update
    'out of date' % len(to_build))
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 355, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/sphinx/environment/__init__.py", line 568, in update
    self._read_serial(docnames, self.app)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/sphinx/environment/__init__.py", line 587, in _read_serial
    self.read_doc(docname, app)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/sphinx/environment/__init__.py", line 670, in read_doc
    app.emit('doctree-read', doctree)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/sphinx/application.py", line 444, in emit
    return self.events.emit(event, self, *args)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/releases/__init__.py", line 612, in generate_changelog
    doctree.walk(changelog_visitor)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/docutils/nodes.py", line 138, in walk
    if child.walk(visitor):
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/docutils/nodes.py", line 138, in walk
    if child.walk(visitor):
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/docutils/nodes.py", line 130, in walk
    visitor.dispatch_visit(self)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/releases/__init__.py", line 595, in visit_bullet_list
    releases, _ = construct_releases(node.children, self.app)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/releases/__init__.py", line 502, in construct_releases
    stripped_entries[index + 1:], manager
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/releases/__init__.py", line 429, in handle_upcoming_major_release
    version = Version(obj.number)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/releases/models.py", line 14, in __init__
    super(Version, self).__init__(version_string, partial)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/semantic_version/base.py", line 77, in __init__
    major, minor, patch, prerelease, build = self.parse(version_string, partial)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/semantic_version/base.py", line 205, in parse
    raise ValueError('Invalid version string: %r' % version_string)
ValueError: Invalid version string: '0.100.5a0'
```

The problem lies with the [semantic-version](https://github.com/rbarrois/python-semanticversion) package which is a dependency of [releases](https://github.com/bitprophet/releases) which we use for our changelog.

It does not parse the new version string we adapted for Testnet releases.

Adding a `-` to separate suffix from main version string seems to fix it. 

```python
>>> from semantic_version import Version
>>> Version('0.100.5a0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/semantic_version/base.py", line 77, in __init__
    major, minor, patch, prerelease, build = self.parse(version_string, partial)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/semantic_version/base.py", line 205, in parse
    raise ValueError('Invalid version string: %r' % version_string)
ValueError: Invalid version string: '0.100.5a0'
>>> Version('0.100.5-a0')
Version('0.100.5-a0')
```

@ulope That would still be pep compatible?

If yes we can just wait till next release and it would hopefully go away then.

**Comment by ulope** [comment]
Hm that's annoying.

[The version with the dash is still valid PEP440](https://www.python.org/dev/peps/pep-0440/#pre-release-separators) although those alternate spellings will still get normalized to the form we currently use. But it should avoid the error we see here.

**Comment by palango** [comment]
This is
