### ISSUE TITLE
`AssertPFSHistory` failes in PFS7 scenario

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#4810]
The nodes seem to behave correctly, but the asert expects that there are exactly two routes, while there are two routes per response. Here's the output from the debug endpoint:

```json
{
  "request_count": 10,
  "responses": [
    {
      "source": "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
      "target": "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b",
      "routes": [
        {
          "path": [
            "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
            "0xfED2e042aBB26EbaBD0a11843Caf26922994a8dE",
            "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b"
          ],
          "estimated_fee": 0
        },
        {
          "path": [
            "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
            "0x41b6f82A50AdDB2ff6A17d85Ce32f7a83f6e1B5c",
            "0x6A1CE7838824989331cf29C143d9E74fAB53C990",
            "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b"
          ],
          "estimated_fee": 0
        }
      ]
    },
    {
      "source": "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
      "target": "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b",
      "routes": [
        {
          "path": [
            "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
            "0xfED2e042aBB26EbaBD0a11843Caf26922994a8dE",
            "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b"
          ],
          "estimated_fee": 0
        },
        {
          "path": [
            "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
            "0x41b6f82A50AdDB2ff6A17d85Ce32f7a83f6e1B5c",
            "0x6A1CE7838824989331cf29C143d9E74fAB53C990",
            "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b"
          ],
          "estimated_fee": 0
        }
      ]
    },
    {
      "source": "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
      "target": "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b",
      "routes": [
        {
          "path": [
            "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
            "0xfED2e042aBB26EbaBD0a11843Caf26922994a8dE",
            "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b"
          ],
          "estimated_fee": 0
        },
        {
          "path": [
            "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
            "0x41b6f82A50AdDB2ff6A17d85Ce32f7a83f6e1B5c",
            "0x6A1CE7838824989331cf29C143d9E74fAB53C990",
            "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b"
          ],
          "estimated_fee": 0
        }
      ]
    },
    {
      "source": "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
      "target": "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b",
      "routes": [
        {
          "path": [
            "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
            "0xfED2e042aBB26EbaBD0a11843Caf26922994a8dE",
            "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b"
          ],
          "estimated_fee": 0
        },
        {
          "path": [
            "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
            "0x41b6f82A50AdDB2ff6A17d85Ce32f7a83f6e1B5c",
            "0x6A1CE7838824989331cf29C143d9E74fAB53C990",
            "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b"
          ],
          "estimated_fee": 0
        }
      ]
    },
    {
      "source": "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
      "target": "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b",
      "routes": [
        {
          "path": [
            "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
            "0xfED2e042aBB26EbaBD0a11843Caf26922994a8dE",
            "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b"
          ],
          "estimated_fee": 0
        },
        {
          "path": [
            "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
            "0x41b6f82A50AdDB2ff6A17d85Ce32f7a83f6e1B5c",
            "0x6A1CE7838824989331cf29C143d9E74fAB53C990",
            "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b"
          ],
          "estimated_fee": 0
        }
      ]
    },
    {
      "source": "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
      "target": "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b",
      "routes": [
        {
          "path": [
            "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
            "0xfED2e042aBB26EbaBD0a11843Caf26922994a8dE",
            "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b"
          ],
          "estimated_fee": 0
        },
        {
          "path": [
            "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
            "0x41b6f82A50AdDB2ff6A17d85Ce32f7a83f6e1B5c",
            "0x6A1CE7838824989331cf29C143d9E74fAB53C990",
            "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b"
          ],
          "estimated_fee": 0
        }
      ]
    },
    {
      "source": "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
      "target": "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b",
      "routes": [
        {
          "path": [
            "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
            "0xfED2e042aBB26EbaBD0a11843Caf26922994a8dE",
            "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b"
          ],
          "estimated_fee": 0
        },
        {
          "path": [
            "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
            "0x41b6f82A50AdDB2ff6A17d85Ce32f7a83f6e1B5c",
            "0x6A1CE7838824989331cf29C143d9E74fAB53C990",
            "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b"
          ],
          "estimated_fee": 0
        }
      ]
    },
    {
      "source": "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
      "target": "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b",
      "routes": [
        {
          "path": [
            "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
            "0xfED2e042aBB26EbaBD0a11843Caf26922994a8dE",
            "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b"
          ],
          "estimated_fee": 0
        },
        {
          "path": [
            "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
            "0x41b6f82A50AdDB2ff6A17d85Ce32f7a83f6e1B5c",
            "0x6A1CE7838824989331cf29C143d9E74fAB53C990",
            "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b"
          ],
          "estimated_fee": 0
        }
      ]
    },
    {
      "source": "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
      "target": "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b",
      "routes": [
        {
          "path": [
            "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
            "0xfED2e042aBB26EbaBD0a11843Caf26922994a8dE",
            "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b"
          ],
          "estimated_fee": 0
        },
        {
          "path": [
            "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
            "0x41b6f82A50AdDB2ff6A17d85Ce32f7a83f6e1B5c",
            "0x6A1CE7838824989331cf29C143d9E74fAB53C990",
            "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b"
          ],
          "estimated_fee": 0
        }
      ]
    },
    {
      "source": "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
      "target": "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b",
      "routes": [
        {
          "path": [
            "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
            "0xfED2e042aBB26EbaBD0a11843Caf26922994a8dE",
            "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b"
          ],
          "estimated_fee": 0
        },
        {
          "path": [
            "0xc6b8CBfa3b233cc5787Ff14D1457e8F42545B68e",
            "0x41b6f82A50AdDB2ff6A17d85Ce32f7a83f6e1B5c",
            "0x6A1CE7838824989331cf29C143d9E74fAB53C990",
            "0x4113E650E5474A2EAa8942D9d5f72B5664C9D97b"
          ],
          "estimated_fee": 0
        }
      ]
    }
  ]
}
```

**Comment by czepluch** [comment]
@karlb which assert is it exactly that fails and what response does it give?

**Comment by karlb** [comment]
It's the last assertion in the scenario:
```
Traceback (most recent call last):
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/scenario_player/tasks/base.py", line 74, in __call__
    return self._run(*args, **kwargs)
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/scenario_player/tasks/execution.py", line 41, in _run
    task()
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/scenario_player/tasks/base.py", line 74, in __call__
    return self._run(*args, **kwargs)
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/scenario_player/tasks/execution.py", line 41, in _run
    task()
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/scenario_player/tasks/base.py", line 74, in __call__
    return self._run(*args, **kwargs)
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/scenario_player/tasks/api_base.py", line 70, in _run
    return self._process_response(response_dict)
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/scenario_player/tasks/services.py", line 205, in _process_response
    f"Expected {len(exp_routes)} routes but got {len(actual_routes)}."
scenario_player.exceptions.legacy.ScenarioAssertionError: Expected 2 routes but got 166.
```

**Comment by czepluch** [comment]
Ah. Alright. So we should either change the assert it self to only assert on the set of distinct routes or just remove that line of the `expected_routes` part of the `assert_pfs_history` in this specific scenario.

**Comment by ulope** [comment]
Hm, sometimes it may be useful to assert on the exact set of returned routes but I can see how that is a problem here. 

@czepluch 
How about adding an option `distinct_routes_only` which can be set to true to de-duplicate the routes?

@karlb What I don't understand is where the `166` is coming from in  `Expected 2 routes but got 166.`. The response you posted above has only 10 routes. Was that just part of the full response?
