### ISSUE TITLE
UndefinedMediationFee thrown and not caught from inside the state machine

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#4835]
Discovered while working on https://github.com/raiden-network/raiden/pull/4802.

Having non-zero imbalance penalty fee can throw the `UndefinedMediationFee` exception from inside the state machine and it's not caught anywhere.

**Comment by palango** [comment]
How did you get this? If the fees are set via the CLI and for all channels this cannot happen.

**Comment by LefterisJP** [comment]
> If the fees are set via the CLI and for all channels this cannot happen.

This is also thrown if the channel does not have enough capacity to satisfy the imbalance penalty fee and can't mediate the payment. It mentions that also in the docstring of the exception: https://github.com/raiden-network/raiden/blob/develop/raiden/exceptions.py#L286

Now that you mention it the name is also misleading.

As for how I saw it, it was in a test that was trying to send more than its capacity when imbalance penalty is not zero in #4802. Will see if I can push changes up to that point to make it reproducible for you too.

**Comment by LefterisJP** [comment]
@palango So pushed the current state of #4802 in the PR.

If you run

`pytest -xs --pdb raiden/tests/integration/transfer/test_mediatedtransfer.py::test_mediated_transfer_with_entire_deposit `

With this commit eef974812328f89ef336ca40ba4d5f3cb337a051 (at the time of writing this should be last commit of the PR) then the test fails with that exact error.

This is the trace:

```
Traceback (most recent call last):
  File "/home/lefteris/ew/raiden/raiden/transfer/mediated_transfer/mediation_fee.py", line 66, in fee
    imbalance_fee = self._penalty_func(balance + amount) - self._penalty_func(balance)
  File "/home/lefteris/ew/raiden/raiden/transfer/mediated_transfer/mediation_fee.py", line 34, in __call__
    raise ValueError("x out of bounds!")
ValueError: x out of bounds!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/lefteris/ew/raiden/raiden/network/transport/matrix/client.py", line 470, in _handle_response
    self.call(room._put_event, event)
  File "/home/lefteris/ew/raiden/raiden/network/transport/matrix/client.py", line 401, in call
    return callback(*args, **kwargs)
  File "/home/lefteris/.virtualenvs/raiden/lib/python3.7/site-packages/matrix_client/room.py", line 308, in _put_event
    listener['callback'](self, event)
  File "/home/lefteris/ew/raiden/raiden/network/transport/matrix/transport.py", line 887, in _handle_message
    self._receive_message(message)
  File "/home/lefteris/ew/raiden/raiden/network/transport/matrix/transport.py", line 925, in _receive_message
    self._raiden_service.on_message(message)
  File "/home/lefteris/ew/raiden/raiden/raiden_service.py", line 575, in on_message
    self.message_handler.on_message(self, message)
  File "/home/lefteris/ew/raiden/raiden/tests/utils/protocol.py", line 56, in on_message
    super().on_message(raiden, message)
  File "/home/lefteris/ew/raiden/raiden/message_handler.py", line 73, in on_message
    self.handle_message_lockedtransfer(raiden, message)
  File "/home/lefteris/ew/raiden/raiden/message_handler.py", line 269, in handle_message_lockedtransfer
    raiden.mediate_mediated_transfer(message)
  File "/home/lefteris/ew/raiden/raiden/raiden_service.py", line 1198, in mediate_mediated_transfer
    self.handle_and_track_state_changes([init_mediator_statechange])
  File "/home/lefteris/ew/raiden/raiden/raiden_service.py", line 586, in handle_and_track_state_changes
    for greenlet in self.handle_state_changes(state_changes):
  File "/home/lefteris/ew/raiden/raiden/raiden_service.py", line 606, in handle_state_changes
    new_state, raiden_event_list = self.wal.log_and_dispatch(state_changes)
  File "/home/lefteris/ew/raiden/raiden/storage/wal.py", line 122, in log_and_dispatch
    latest_state, all_events = self.state_manager.dispatch(state_changes)
  File "/home/lefteris/ew/raiden/raiden/transfer/architecture.py", line 260, in dispatch
    iteration = self.state_transition(next_state, state_change)
  File "/home/lefteris/ew/raiden/raiden/transfer/node.py", line 1182, in state_transition
    iteration = handle_state_change(chain_state, state_change)
  File "/home/lefteris/ew/raiden/raiden/transfer/node.py", line 837, in handle_state_change
    iteration = handle_init_mediator(chain_state, state_change)
  File "/home/lefteris/ew/raiden/raiden/transfer/node.py", line 676, in handle_init_mediator
    return subdispatch_mediatortask(chain_state, state_change, token_network_address, secrethash)
  File "/home/lefteris/ew/raiden/raiden/transfer/node.py", line 348, in subdispatch_mediatortask
    block_hash=block_hash,
  File "/home/lefteris/ew/raiden/raiden/transfer/mediated_transfer/mediator.py", line 1469, in state_transition
    block_number=block_number,
  File "/home/lefteris/ew/raiden/raiden/transfer/mediated_transfer/mediator.py", line 1110, in handle_init
    block_number=block_number,
  File "/home/lefteris/ew/raiden/raiden/transfer/mediated_transfer/mediator.py", line 1041, in mediate_transfer
    route_state_table=candidate_route_states,
  File "/home/lefteris/ew/raiden/raiden/transfer/mediated_transfer/mediator.py", line 385, in forward_transfer_pair
    payer_transfer.lock, payer_channel, payee_channel
  File "/home/lefteris/ew/raiden/raiden/transfer/mediated_transfer/mediator.py", line 241, in get_lock_amount_after_fees
    fee_in = _fee_for_channel(payer_channel, PaymentAmount(lock.amount))
  File "/home/lefteris/ew/raiden/raiden/transfer/mediated_transfer/mediator.py", line 229, in _fee_for_channel
    return channel.fee_schedule.fee(amount, balance)
  File "/home/lefteris/ew/raiden/raiden/transfer/mediated_transfer/mediation_fee.py", line 68, in fee
    raise UndefinedMediationFee()
raiden.exceptions.UndefinedMediationFee
```
