### ISSUE TITLE
Broken documentation build

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#4958]
## Problem Definition

The docs build from readthedocs is broken:

```
Running Sphinx v1.7.9
loading translations [en]... done
making output directory...
Initiated sphinxcontrib-images backend: `sphinxcontrib_images_lightbox2.lightbox2:LightBox2`
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 23 source files that are out of date
updating environment: 23 added, 0 changed, 0 removed
reading sources... [  4%] adr/0002-testing-strategy
reading sources... [  8%] adr/0003-git-workflow
reading sources... [ 13%] adr/0004-python-dependency-management
reading sources... [ 17%] adr/0005-withdraw-expiry
reading sources... [ 21%] adr/overview
reading sources... [ 26%] adr/template
reading sources... [ 30%] api_walkthrough
reading sources... [ 34%] changelog
/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/checkouts/latest/docs/adr/0002-testing-strategy.rst:2: WARNING: Title underline too short.

Better testing framework for the entire Raiden suite (client, MS and PFS)
*********************************************************************
/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/checkouts/latest/docs/adr/0002-testing-strategy.rst:16: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/checkouts/latest/docs/adr/0002-testing-strategy.rst:37: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/checkouts/latest/docs/adr/0005-withdraw-expiry.rst:71: WARNING: Bullet list ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/checkouts/latest/docs/adr/0005-withdraw-expiry.rst:73: WARNING: Unexpected indentation.
/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/checkouts/latest/docs/adr/0005-withdraw-expiry.rst:71: WARNING: Inline literal start-string without end-string.
/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/checkouts/latest/docs/adr/0005-withdraw-expiry.rst:75: WARNING: Definition list ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/checkouts/latest/docs/adr/0005-withdraw-expiry.rst:77: WARNING: Unexpected indentation.
/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/checkouts/latest/docs/adr/0005-withdraw-expiry.rst:78: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/checkouts/latest/docs/adr/0005-withdraw-expiry.rst:79: WARNING: Unexpected section title.

}
{
/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/checkouts/latest/docs/adr/0005-withdraw-expiry.rst:81: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/checkouts/latest/docs/adr/0005-withdraw-expiry.rst:82: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/checkouts/latest/docs/adr/template.rst:16: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/checkouts/latest/docs/adr/template.rst:37: WARNING: Title underline too short.

Positive Consequences <!-- optional -->
~~~~~~~~~~~~~~~~~~~~~
/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/checkouts/latest/docs/adr/template.rst:43: WARNING: Title underline too short.

Negative Consequences <!-- optional -->
~~~~~~~~~~~~~~~~~~~~~~~~~
/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/checkouts/latest/docs/adr/template.rst:43: WARNING: Title underline too short.

Negative Consequences <!-- optional -->
~~~~~~~~~~~~~~~~~~~~~~~~~
/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/checkouts/latest/docs/adr/template.rst:49: WARNING: Title underline too short.

Pros and Cons of the Options <!-- optional -->
-------------------------------
/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/checkouts/latest/docs/adr/template.rst:49: WARNING: Title underline too short.

Pros and Cons of the Options <!-- optional -->
-------------------------------
/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/checkouts/latest/docs/adr/template.rst:82: WARNING: Title underline too short.

Links <!-- optional -->
----------------------
/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/checkouts/latest/docs/adr/template.rst:82: WARNING: Title underline too short.

Links <!-- optional -->
----------------------

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/envs/latest/lib/python3.6/site-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/envs/latest/lib/python3.6/site-packages/sphinx/application.py", line 331, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/envs/latest/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 342, in build_update
    'out of date' % len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/envs/latest/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 355, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/envs/latest/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 568, in update
    self._read_serial(docnames, self.app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/envs/latest/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 587, in _read_serial
    self.read_doc(docname, app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/envs/latest/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 670, in read_doc
    app.emit('doctree-read', doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/envs/latest/lib/python3.6/site-packages/sphinx/application.py", line 444, in emit
    return self.events.emit(event, self, *args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/envs/latest/lib/python3.6/site-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/envs/latest/lib/python3.6/site-packages/releases/__init__.py", line 612, in generate_changelog
    doctree.walk(changelog_visitor)
  File "/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/envs/latest/lib/python3.6/site-packages/docutils/nodes.py", line 138, in walk
    if child.walk(visitor):
  File "/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/envs/latest/lib/python3.6/site-packages/docutils/nodes.py", line 138, in walk
    if child.walk(visitor):
  File "/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/envs/latest/lib/python3.6/site-packages/docutils/nodes.py", line 130, in walk
    visitor.dispatch_visit(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/envs/latest/lib/python3.6/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/envs/latest/lib/python3.6/site-packages/releases/__init__.py", line 595, in visit_bullet_list
    releases, _ = construct_releases(node.children, self.app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/envs/latest/lib/python3.6/site-packages/releases/__init__.py", line 502, in construct_releases
    stripped_entries[index + 1:], manager
  File "/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/envs/latest/lib/python3.6/site-packages/releases/__init__.py", line 429, in handle_upcoming_major_release
    version = Version(obj.number)
  File "/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/envs/latest/lib/python3.6/site-packages/releases/models.py", line 14, in __init__
    super(Version, self).__init__(version_string, partial)
  File "/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/envs/latest/lib/python3.6/site-packages/semantic_version/base.py", line 77, in __init__
    major, minor, patch, prerelease, build = self.parse(version_string, partial)
  File "/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/envs/latest/lib/python3.6/site-packages/semantic_version/base.py", line 205, in parse
    raise ValueError('Invalid version string: %r' % version_string)
ValueError: Invalid version string: '0.100.5a0'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/raiden-network/envs/latest/lib/python3.6/site-packages/semantic_version/base.py", line 205, in parse
    raise ValueError('Invalid version string: %r' % version_string)
ValueError: Invalid version string: '0.100.5a0'
The full traceback has been saved in /tmp/sphinx-err-tmousacz.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by palango** [comment]
Might be related to #4764
