### ISSUE TITLE
On-chain ChannelOpen with settle_timeout smaller than configured reveal_timeout causes Raiden to crash

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden#4997]
## Problem Definition

Latest `raiden-contracts v0.32` were deployed on testnets with a smaller `settle_timeout_min=20`, than previous default of `500`, to make testing faster. The default values for `settle_timeout=500` & `reveal_timeout=50` are still hardcoded (which is ok, we can have defaults or configured values higher than minimum), but the problem is Raiden node crashing when a channel is opened on-chain with a settle timeout smaller than the hardcoded `reveal_timeout`.
Traceback:
```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/opt/venv/lib/python3.7/site-packages/raiden/tasks.py", line 168, in _run
    self.loop_until_stop()
  File "/opt/venv/lib/python3.7/site-packages/raiden/tasks.py", line 207, in loop_until_stop
    self._maybe_run_callbacks(latest_block)
  File "/opt/venv/lib/python3.7/site-packages/raiden/tasks.py", line 263, in _maybe_run_callbacks
    result = callback(latest_block)
  File "/opt/venv/lib/python3.7/site-packages/raiden/raiden_service.py", line 789, in _callback_new_block
    blockchainevent_to_statechange(self, event, latest_confirmed_block_number)
  File "/opt/venv/lib/python3.7/site-packages/raiden/blockchain/decode.py", line 358, in blockchainevent_to_statechange
    new_channel_details, channel_config, event
  File "/opt/venv/lib/python3.7/site-packages/raiden/blockchain/decode.py", line 157, in contractreceivechannelnew_from_event
    settle_transaction=settle_transaction,
  File "<string>", line 14, in __init__
  File "/opt/venv/lib/python3.7/site-packages/raiden/transfer/state.py", line 376, in __post_init__
    raise ValueError("reveal_timeout must be smaller than settle_timeout")
ValueError: reveal_timeout must be smaller than settle_timeout
2019-09-28T16:03:21Z <Greenlet "AlarmTask._run node:0xAAAAAA219100005A77eF9dEf76b24dfB2cD6B35e" at 0x7fd76e0cb710: <bound method AlarmTask._run of <AlarmTask node:0xAAAAAA219100005A77eF9dEf76b24dfB2cD6B35e>>> failed with ValueError
```
Raiden node must handle this gracefuly, and set the (local default) reveal timeout for this channel as a sensible value e.g. half the `settle_timeout`, or some other proper handling of this case. 
This may be a DoS vector, if hardcoded defaults somehow mismatch with what's possible on-chain. Defaults aren't a lower-bound, they can be higher than minimum on-chain values, and the safety limits should be somehow fetched either from blockchain or from deployment files instead of being hardcoded.

Full log:
[raiden-debug_2019-09-28T15:35:50.923980.log](https://github.com/raiden-network/raiden/files/3665727/raiden-debug_2019-09-28T15.35.50.923980.log)

### System Description

Docker nightly from yesterday:
```
{
  "raiden": "0.100.5a1.dev456+g684cef6f5",
  "raiden_db_version": 23,
  "python_implementation": "CPython",
  "python_version": "3.7.4",
  "system": "Linux 64bit 4.19.75-1-lts",
  "architecture": "x86_64",
  "distribution": "source"
}
```

**Comment by andrevmatos** [comment]
Related: #4905

**Comment by andrevmatos** [comment]
Node crash on startup now, account is unusable since even removing the database won't save it, as it'll crash when fetching this event.
Database (before cleanup attempt): 
[node_aaaaaa21.tar.gz](https://github.com/raiden-network/raiden/files/3665751/node_aaaaaa21.tar.gz)

**Comment by andrevmatos** [comment]
Additionally, webUI doesn't allow to set a `settle_timeout` smaller than 100 when opening a channel. Not sure if it gets this value as double default value, or it's hardcoded, but should be adapted for consistency as well.

**Comment by rakanalh** [comment]
#4999 will resolve this issue because the condition which crashes the node was removed. However, having a settle timeout that is smaller than the reveal timeout will make the channel unusable for mediating transfers. (See: `is_channel_usable_for_new_transfer`)
