### ISSUE TITLE
SerializationError: Can't deserialize

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/raiden#5055]
## Problem Definition
I can't start my Raiden node due to the following error. 
Before I did a withdraw that did not succeed because of the channel partner being offline. I restarted Raiden and this error occurred.

```
2019-10-09 08:44:50.528507 [info     ] Using Matrix server            [raiden.network.transport.matrix.utils] average_rtt=0.036513 server_ident=Synapse/1.3.1 server_url=https://transport03.raiden.network
Traceback (most recent call last):
  File "raiden/storage/serialization/serializer.py", line 78, in deserialize
  File "marshmallow/schema.py", line 732, in load
  File "marshmallow/schema.py", line 894, in _do_load
marshmallow.exceptions.ValidationError: {'queueids_to_queues': defaultdict(<class 'dict'>, {'0x2222222222222222222222222222222222222222-5|0xE36995596D456aaEcD226a303250Bf99cf16b2A0|1': {'value': {0: ["Unable to use schema. Error: Invalid deserializer type\nEnsure there is a deserialization_schema_selector and then it returns a field or a schema when the function is passed in {'message_identifier': '1431118866062413431', 'expiration': '1435675', 'nonce': '1', 'canonical_identifier': {'token_network_address': '0xE36995596D456aaEcD226a303250Bf99cf16b2A0', 'chain_identifier': '5', 'channel_identifier': '1'}, 'recipient': '0x2222222222222222222222222222222222222222', 'participant': '0x034776C91b9B825b44A1c69268B84ae0Fc024243', 'total_withdraw': '100000000000000', '_type': 'raiden.transfer.events.SendWithdrawRequest'}. This is the class I got. Make sure it is a field or a schema: None"], 1: ["Unable to use schema. Error: Invalid deserializer type\nEnsure there is a deserialization_schema_selector and then it returns a field or a schema when the function is passed in {'message_identifier': '5272966244846671265', 'expiration': '1435728', 'nonce': '2', 'canonical_identifier': {'token_network_address': '0xE36995596D456aaEcD226a303250Bf99cf16b2A0', 'chain_identifier': '5', 'channel_identifier': '1'}, 'recipient': '0x2222222222222222222222222222222222222222', 'participant': '0x034776C91b9B825b44A1c69268B84ae0Fc024243', 'total_withdraw': '110000000000000', '_type': 'raiden.transfer.events.SendWithdrawRequest'}. This is the class I got. Make sure it is a field or a schema: None"], 2: ["Unable to use schema. Error: Invalid deserializer type\nEnsure there is a deserialization_schema_selector and then it returns a field or a schema when the function is passed in {'message_identifier': '9057944751723415765', 'nonce': '3', 'expiration': '1435675', 'canonical_identifier': {'token_network_address': '0xE36995596D456aaEcD226a303250Bf99cf16b2A0', 'chain_identifier': '5', 'channel_identifier': '1'}, 'recipient': '0x2222222222222222222222222222222222222222', 'participant': '0x034776C91b9B825b44A1c69268B84ae0Fc024243', 'total_withdraw': '100000000000000', '_type': 'raiden.transfer.events.SendWithdrawExpired'}. This is the class I got. Make sure it is a field or a schema: None"], 3: ["Unable to use schema. Error: Invalid deserializer type\nEnsure there is a deserialization_schema_selector and then it returns a field or a schema when the function is passed in {'message_identifier': '16642911611485154191', 'nonce': '4', 'expiration': '1435728', 'canonical_identifier': {'token_network_address': '0xE36995596D456aaEcD226a303250Bf99cf16b2A0', 'chain_identifier': '5', 'channel_identifier': '1'}, 'recipient': '0x2222222222222222222222222222222222222222', 'participant': '0x034776C91b9B825b44A1c69268B84ae0Fc024243', 'total_withdraw': '110000000000000', '_type': 'raiden.transfer.events.SendWithdrawExpired'}. This is the class I got. Make sure it is a field or a schema: None"]}}})}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "raiden-script.py", line 2, in <module>
  File "raiden/__main__.py", line 13, in main
  File "click/core.py", line 764, in __call__
  File "click/core.py", line 717, in main
  File "click/core.py", line 1114, in invoke
  File "click/core.py", line 956, in invoke
  File "click/core.py", line 555, in invoke
  File "click/decorators.py", line 17, in new_func
  File "raiden/ui/cli.py", line 568, in run
  File "raiden/ui/runners.py", line 243, in run
  File "raiden/ui/runners.py", line 92, in _start_services
  File "raiden/ui/app.py", line 353, in run_app
  File "raiden/app.py", line 137, in start
  File "raiden/raiden_service.py", line 346, in start
  File "raiden/storage/wal.py", line 40, in restore_to_state_change
  File "raiden/storage/sqlite.py", line 805, in get_snapshot_before_state_change
  File "raiden/storage/serialization/serializer.py", line 100, in deserialize
  File "raiden/storage/serialization/serializer.py", line 80, in deserialize
raiden.exceptions.SerializationError: Can't deserialize: 
// JSON, left out because it is too huge, see attached zip file

[6236] Failed to execute script raiden-script
Exception ignored in: <function SQLiteStorage.__del__ at 0x7fdfb5551b90>
Traceback (most recent call last):
  File "raiden/storage/sqlite.py", line 731, in __del__
RuntimeError: The database connection was not closed.
--- Logging error ---
Traceback (most recent call last):
  File "logging/handlers.py", line 69, in emit
  File "logging/handlers.py", line 183, in shouldRollover
  File "logging/__init__.py", line 1116, in _open
NameError: name 'open' is not defined
Call stack:
  File "filelock.py", line 331, in __del__
  File "filelock.py", line 318, in release
  File "logging/__init__.py", line 1378, in info
  File "logging/__init__.py", line 1514, in _log
  File "logging/__init__.py", line 1524, in handle
  File "logging/__init__.py", line 1586, in callHandlers
  File "logging/__init__.py", line 894, in handle
  File "logging/handlers.py", line 73, in emit
Message: 'Lock %s released on %s'
Arguments: (140598782831888, '/home/manuel/.raiden/node_034776c9/netid_5/network_754b1fa6/.lock')
```

Log & DB files + JSON, that was not deserializable in the above error:
[log-db-json.zip](https://github.com/raiden-network/raiden/files/3706450/log-db-json.zip)

### System Description
Raiden v0.200.0rc1
internal BB parity node
Goerli testnet

**Comment by palango** [comment]
Here's a small script Konrad and I wrote yesterday that triggers the exception


[m.py.zip](https://github.com/raiden-network/raiden/files/3711273/m.py.zip)

**Comment by rakanalh** [comment]
@palango the script doesn't raise any exceptions in my case.
