### ISSUE TITLE
make_client utility fails with unreachable servers

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#5063]
## Problem Definition

The `make_client()` utility (from `raiden.network.transport.matrix.utils`) fails to exclude unreachable servers and instead leads to a crash.

Recently seen in the pfs while the test matrix servers were being rebuilt (see log below).

First assumption from quickly scanning the log: The unreachable exception isn't bubbled up and instead retried and then re-raised as an exception type that isn't expected by `make_client`.

```
2019-10-10 10:52:09.792890 [debug    ] Got http _send exception, waiting then retrying [raiden.network.transport.matrix.client] _exception=MatrixHttpLibError("Something went wrong in GET requesting https://transport01.raiden.network/_matrix/client/versions: HTTPSConnectionPool(host='transport01.raiden.network', port=443): Max retries exceeded with url: /_matrix/client/versions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a2606dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))") wait_for=1
2019-10-10 10:52:10.889766 [debug    ] Got http _send exception, waiting then retrying [raiden.network.transport.matrix.client] _exception=MatrixHttpLibError("Something went wrong in GET requesting https://transport01.raiden.network/_matrix/client/versions: HTTPSConnectionPool(host='transport01.raiden.network', port=443): Max retries exceeded with url: /_matrix/client/versions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a2632c90>: Failed to establish a new connection: [Errno 111] Connection refused'))") wait_for=1
2019-10-10 10:52:11.987229 [debug    ] Got http _send exception, waiting then retrying [raiden.network.transport.matrix.client] _exception=MatrixHttpLibError("Something went wrong in GET requesting https://transport01.raiden.network/_matrix/client/versions: HTTPSConnectionPool(host='transport01.raiden.network', port=443): Max retries exceeded with url: /_matrix/client/versions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a25bd250>: Failed to establish a new connection: [Errno 111] Connection refused'))") wait_for=1
2019-10-10 10:52:13.085954 [debug    ] Got http _send exception, waiting then retrying [raiden.network.transport.matrix.client] _exception=MatrixHttpLibError("Something went wrong in GET requesting https://transport01.raiden.network/_matrix/client/versions: HTTPSConnectionPool(host='transport01.raiden.network', port=443): Max retries exceeded with url: /_matrix/client/versions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a25bd810>: Failed to establish a new connection: [Errno 111] Connection refused'))") wait_for=1
2019-10-10 10:52:14.183517 [debug    ] Got http _send exception, waiting then retrying [raiden.network.transport.matrix.client] _exception=MatrixHttpLibError("Something went wrong in GET requesting https://transport01.raiden.network/_matrix/client/versions: HTTPSConnectionPool(host='transport01.raiden.network', port=443): Max retries exceeded with url: /_matrix/client/versions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a25bd350>: Failed to establish a new connection: [Errno 111] Connection refused'))") wait_for=1
2019-10-10 10:52:15.282027 [debug    ] Got http _send exception, waiting then retrying [raiden.network.transport.matrix.client] _exception=MatrixHttpLibError("Something went wrong in GET requesting https://transport01.raiden.network/_matrix/client/versions: HTTPSConnectionPool(host='transport01.raiden.network', port=443): Max retries exceeded with url: /_matrix/client/versions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a25c2250>: Failed to establish a new connection: [Errno 111] Connection refused'))") wait_for=2
2019-10-10 10:52:17.379880 [debug    ] Got http _send exception, waiting then retrying [raiden.network.transport.matrix.client] _exception=MatrixHttpLibError("Something went wrong in GET requesting https://transport01.raiden.network/_matrix/client/versions: HTTPSConnectionPool(host='transport01.raiden.network', port=443): Max retries exceeded with url: /_matrix/client/versions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a25c2810>: Failed to establish a new connection: [Errno 111] Connection refused'))") wait_for=4
2019-10-10 10:52:21.487436 [debug    ] Got http _send exception, waiting then retrying [raiden.network.transport.matrix.client] _exception=MatrixHttpLibError("Something went wrong in GET requesting https://transport01.raiden.network/_matrix/client/versions: HTTPSConnectionPool(host='transport01.raiden.network', port=443): Max retries exceeded with url: /_matrix/client/versions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a25c2350>: Failed to establish a new connection: [Errno 111] Connection refused'))") wait_for=5
2019-10-10 10:52:26.586365 [debug    ] Got http _send exception, waiting then retrying [raiden.network.transport.matrix.client] _exception=MatrixHttpLibError("Something went wrong in GET requesting https://transport01.raiden.network/_matrix/client/versions: HTTPSConnectionPool(host='transport01.raiden.network', port=443): Max retries exceeded with url: /_matrix/client/versions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a25cc250>: Failed to establish a new connection: [Errno 111] Connection refused'))") wait_for=5
2019-10-10 10:52:31.688046 [debug    ] Got http _send exception, waiting then retrying [raiden.network.transport.matrix.client] _exception=MatrixHttpLibError("Something went wrong in GET requesting https://transport01.raiden.network/_matrix/client/versions: HTTPSConnectionPool(host='transport01.raiden.network', port=443): Max retries exceeded with url: /_matrix/client/versions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a25cc810>: Failed to establish a new connection: [Errno 111] Connection refused'))") wait_for=5
2019-10-10 10:52:36.788543 [debug    ] Got http _send exception, waiting then retrying [raiden.network.transport.matrix.client] _exception=MatrixHttpLibError("Something went wrong in GET requesting https://transport01.raiden.network/_matrix/client/versions: HTTPSConnectionPool(host='transport01.raiden.network', port=443): Max retries exceeded with url: /_matrix/client/versions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a25c26d0>: Failed to establish a new connection: [Errno 111] Connection refused'))") wait_for=5
2019-10-10 10:52:41.887081 [debug    ] Got http _send exception, waiting then retrying [raiden.network.transport.matrix.client] _exception=MatrixHttpLibError("Something went wrong in GET requesting https://transport01.raiden.network/_matrix/client/versions: HTTPSConnectionPool(host='transport01.raiden.network', port=443): Max retries exceeded with url: /_matrix/client/versions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a25c2d50>: Failed to establish a new connection: [Errno 111] Connection refused'))") wait_for=5
2019-10-10 10:52:46.987593 [debug    ] Got http _send exception, waiting then retrying [raiden.network.transport.matrix.client] _exception=MatrixHttpLibError("Something went wrong in GET requesting https://transport01.raiden.network/_matrix/client/versions: HTTPSConnectionPool(host='transport01.raiden.network', port=443): Max retries exceeded with url: /_matrix/client/versions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a25c2ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))") wait_for=5
2019-10-10 10:52:52.086840 [warning  ] Selected server not usable     [raiden.network.transport.matrix.utils] _exception=MatrixHttpLibError("Something went wrong in GET requesting https://transport01.raiden.network/_matrix/client/versions: HTTPSConnectionPool(host='transport01.raiden.network', port=443): Max retries exceeded with url: /_matrix/client/versions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a2632b90>: Failed to establish a new connection: [Errno 111] Connection refused'))") server_url=https://transport01.raiden.network
2019-10-10 10:52:52.087554 [info     ] Stopping Pathfinding Service... [__main__]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
  File "/usr/local/lib/python3.7/site-packages/gevent/_socket3.py", line 335, in connect
    raise error(err, strerror(err))
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 316, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a2632b90>: Failed to establish a new connection: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='transport01.raiden.network', port=443): Max retries exceeded with url: /_matrix/client/versions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a2632b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/matrix_client/api.py", line 670, in _send
    verify=self.validate_cert
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='transport01.raiden.network', port=443): Max retries exceeded with url: /_matrix/client/versions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a2632b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/utils.py", line 571, in make_client
    client.api._send("GET", "/versions", api_path="/_matrix/client")
  File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/client.py", line 151, in _send
    return super()._send(method, path, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matrix_client/api.py", line 673, in _send
    raise MatrixHttpLibError(e, method, endpoint)
matrix_client.errors.MatrixHttpLibError: Something went wrong in GET requesting https://transport01.raiden.network/_matrix/client/versions: HTTPSConnectionPool(host='transport01.raiden.network', port=443): Max retries exceeded with url: /_matrix/client/versions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a2632b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/services/src/pathfinding_service/cli.py", line 116, in <module>
    main(auto_envvar_prefix="PFS")  # pragma: no cover
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/services/src/raiden_libs/cli.py", line 177, in call_with_blockchain_info
    return callback(**params)
  File "/services/src/raiden_libs/cli.py", line 122, in call_with_common_options_initialized
    return func(**params)
  File "/services/src/pathfinding_service/cli.py", line 88, in main
    db_filename=state_db,
  File "/services/src/pathfinding_service/service.py", line 99, in __init__
    address_reachability_changed_callback=self.handle_reachability_change,
  File "/services/src/raiden_libs/matrix.py", line 141, in __init__
    http_retry_delay=matrix_http_retry_delay,
  File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/utils.py", line 586, in make_client
    ) from last_ex
raiden.exceptions.TransportError: Unable to find a reachable Matrix server. Please check your network connectivity.
```

**Comment by ulope** [comment]
Actually I'm now not sure this issue exists. For debugging purposes the PFS had manually constrained it's server selection to only one. This seems to be the reason why no server could be found.

However we should probably reduce (or even remove) the retries during the initial server 'scan'.
