### ISSUE TITLE
Fails to initialize raiden console 

### ISSUE THREAD

**Issue by lullis** [raiden-network/raiden#5071]
## Problem Definition

Running `raiden --config-file=/home/raphael/.local/share/raiden/config-4fc827dd1f22cf0ae042e79c3d71b959c25039a8-goerli.toml --console
` from latest develop, raiden starts but throws an exception shortly after and exits.

The contents of the exception file:

```
$ cat /tmp/raiden-exception-2019-10-10T17-09w5y2_5r5.txt
Traceback (most recent call last):
  File "/home/raphael/code/brainbot/raiden/client/raiden/ui/runners.py", line 195, in _start_services
    event.get()
  File "src/gevent/event.py", line 381, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 409, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 399, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 379, in gevent._event.AsyncResult._raise_exception
  File "/home/raphael/.virtualenvs/raiden/lib/python3.7/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/raphael/code/brainbot/raiden/client/raiden/ui/console.py", line 128, in _run
    tools = ConsoleTools(self.app.raiden, self.app.config["settle_timeout"])
  File "/home/raphael/code/brainbot/raiden/client/raiden/ui/console.py", line 154, in __init__
    self._chain = raiden_service.chain
  File "/home/raphael/code/brainbot/raiden/client/raiden/utils/runnable.py", line 101, in __getattr__
    return getattr(self.greenlet, item)
AttributeError: 'gevent._greenlet.Greenlet' object has no attribute 'chain'
```

Tracing down the error seems to indicate that there is an access to `raiden_service.chain`

**Comment by rakanalh** [comment]
Console doesn't work and isn't a supported feature of Raiden at the moment.
