### ISSUE TITLE
All Scenarios Fail, Failed to start Raiden node 0

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5110]
## Problem Definition
All Scenarios fail with the same 
**scenario_player.exceptions.legacy.ScenarioError: Failed to start Raiden node 0**  exception.

Sample traceback
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/scenario_player/node_support.py", line 220, in start
    ret = self.executor.start(**self._output_files)
  File "/usr/local/lib/python3.7/site-packages/scenario_player/utils/legacy.py", line 145, in start
    self.wait_for(self.check_subprocess)
  File "/usr/local/lib/python3.7/site-packages/mirakuru/base.py", line 348, in wait_for
    if wait_for():
  File "/usr/local/lib/python3.7/site-packages/mirakuru/base.py", line 449, in check_subprocess
    raise ProcessExitedWithError(self, exit_code)
mirakuru.exceptions.ProcessExitedWithError: The process invoked by the <scenario_player.utils.legacy.HTTPExecutor: "/usr/local/bin/raiden --accept-disclaimer --datadir /data/scenarios/mfee4_combined_fees/node_26_000 --keystore-path /data/scenarios/mfee4_combined_fees/node_26_000/keys --address 0xC14991590FF68810497dABfbafd5d855F4717EF3 --password-file /data/scenarios/mfee4_combined_fees/node_26_000/password.txt --network-id 5 --sync-check --gas-price fast --eth-rpc-endpoint http://parity.goerli.ethnodes.brainbot.com:8545 --log-config :info,raiden:debug,raiden_contracts:debug,raiden.api.rest.pywsgi:warning --log-json --log-file /data/scenarios/mfee4_combined_fees/node_26_000/run-026.log --disable-debug-logfile --matrix-server auto --api-address 127.0.0.1:39229 --no-web-ui --pathfinding-service-address https://pfs-goerli-with-fee.services-dev.raiden.network --environment-type development --gas-price fast --routing-mode pfs --proportional-imbalance-fee 0x62083c80353Df771426D209eF578619EE68D5C7A 20000 --pathfinding-max-fee 100 --proportional-fee 0x62083c80353Df771426D209eF578619EE68D5C7A 10000 --flat-fee 0x62083c80353Df771426D209eF578619EE68D5C7A 100 --pathfinding-max-paths 5"> executor has exited with a non-zero code: 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/scenario_player/main.py", line 230, in run
    runner.run_scenario()
  File "/usr/local/lib/python3.7/site-packages/scenario_player/runner.py", line 260, in run_scenario
    node_starter.get(block=True)
  File "src/gevent/greenlet.py", line 633, in gevent._greenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "/usr/local/lib/python3.7/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.7/site-packages/scenario_player/node_support.py", line 477, in _start
    pool.join(raise_error=True)
  File "/usr/local/lib/python3.7/site-packages/gevent/pool.py", line 433, in join
    greenlet._raise_exception()
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "/usr/local/lib/python3.7/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.7/site-packages/scenario_player/node_support.py", line 222, in start
    raise ScenarioError(f"Failed to start Raiden node {self._index}") from ex
scenario_player.exceptions.legacy.ScenarioError: Failed to start Raiden node 0
```

Sample logs of mfee4, though scenarios fail due to one reason only.
[Scenario_player_Logs-mfee4_combined_fees-1-latest-2019-10-17.tar.gz](https://github.com/raiden-network/raiden/files/3737648/Scenario_player_Logs-mfee4_combined_fees-1-latest-2019-10-17.tar.gz)

**Comment by Dominik1999** [comment]
Thank you Sohan for creating this issue. 

This issue again has the wrong logs of the nodes. Those again are from the 26th of September. 

@christianbrb @agatsoh can you please make sure somehow that you provide us every morning with the correct logs of the nightly failures

**Comment by agatsoh** [comment]
@Dominik1999 The wrong logs are because of this issue https://github.com/raiden-network/scenario-player/issues/364.

**Comment by Dominik1999** [comment]
I see, but we still cannot use that issue here then until we get the real logs. 
Please do not provide the wrong logs to an issue though. This creates more work for everyone. In case you cannot access the real logs, please escalate to @christianbrb 

However, I have already seen the correct logs on the server. The reason for the failure described here, is that the client is upgraded to [contracts 0.33.1](https://github.com/raiden-network/raiden/pull/5097) whereas the services are not.

**Comment by Dominik1999** [comment]
Thank you for creating those issues every day! That part is really helpful!
