### ISSUE TITLE
Raiden Client connected to Goerli infura Node tries to deploy to mainnet

### ISSUE THREAD

**Issue by nlsdfnbch** [raiden-network/raiden#5167]
While implementing the smoketests for the SP (https://github.com/raiden-network/scenario-player/issues/350), I ran into a curios problem when running a scenario against raiden clients using infura nodes:
```
[...]
2019-10-29 06:43:07.006653 [info     ] Registering token with network [scenario_player.runner] url=http://127.0.0.1:50505/api/v1/tokens/0x98B88640231Dd3776218d213dAD24327A093352a
2019-10-29 06:43:08.018109 [error    ] Couldn't register token with network [scenario_player.runner] code=501 message={"errors": "Registering a new token is currently disabled in the Ethereum mainnet"}
2019-10-29 06:43:08.020220 [error    ] Run finished                   [scenario_player.main] result=scenario error
Traceback (most recent call last):
  File "/home/nls/.virtualenvs/scenario-player/lib/python3.7/site-packages/scenario_player/main.py", line 230, in run
    runner.run_scenario()
  File "/home/nls/.virtualenvs/scenario-player/lib/python3.7/site-packages/scenario_player/runner.py", line 280, in run_scenario
    raise TokenRegistrationError(msg)
scenario_player.exceptions.legacy.TokenRegistrationError: {"errors": "Registering a new token is currently disabled in the Ethereum mainnet"}
[...]
```

The Scenario player was called as follows:
```bash
scenario_player \                          
            --data-path=/tmp \
            --chain goerli:https://goerli.infura.io/v3/de4710375b854c759ee2813bf78c30a6 \
            run tests/smoketests/smoketests.yml \
            --keystore-file=.circleci/smoketest.keystore \
            --password=${SMOKETEST_PW} \
            --no-ui
```

and the underlying nodes all report having connected to `goerli` after being started with the following command (example from node2's stdout log):

```bash
Command line: /tmp/raiden_releases/bin/raiden-nightly-2019-10-28T00-25-48-v0.100.5a1.dev650+g78dcbaf9b-linux-x86_64 --accept-disclaimer --datadir /tmp/scenarios/smoketests/node_0_002 --keystore-path /tmp/scenarios/smoketests/node_0_002/keys --address 0x5F3863bd0a3B4531Ea61D1ef217F882Ca4204883 --password-file /tmp/scenarios/smoketests/node_0_002/password.txt --network-id 5 --sync-check --gas-price normal --eth-rpc-endpoint https://goerli.infura.io/v3/de4710375b854c759ee2813bf78c30a6 --log-config :info,raiden:debug,raiden_contracts:debug,raiden.api.rest.pywsgi:warning --log-json --log-file /tmp/scenarios/smoketests/node_0_002/run-000.log --disable-debug-logfile --matrix-server auto --api-address 127.0.0.1:35315 --no-web-ui --pathfinding-service-address https://pfs-goerli-with-fee.services-dev.raiden.network
```

The logs for the scenario run can be found here:
https://gist.github.com/nlsdfnbch/d21f909ca533224b092f58878e43d392

**Comment by LefterisJP** [comment]
Okay so this is because of a small number of things:

1. The scenario run did not provide `--environment-type development` so it defaulted to `production`. In production users are not supposed to deploy their own token. Even though this limitation I thought should have been only for production + mainnet.

2. The error string is incorrect.

https://github.com/raiden-network/raiden/blob/f832fe9027f020910a661b66f66d0952e89cbc78/raiden/api/rest.py#L544-L548

Either it should be checking both network and environment type or it should just say that  for `production` token deployment is not activated.

@rakan @Dominik1999 which of the two should it be?

**Comment by Dominik1999** [comment]
I would go for the latter, on production environment token deployment is not activated
