### ISSUE TITLE
404: {"errcode":"M_NOT_FOUND","error":"Profile was not found"}

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#5260]
Some Scenarios fail a traceback with 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py", line 51, in _run
    method=self._method, url=url, json=self._request_params, timeout=self._timeout
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/scenario_player/main.py", line 281, in run
    runner.run_scenario()
  File "/usr/local/lib/python3.7/site-packages/scenario_player/runner.py", line 294, in run_scenario
    gevent.joinall(greenlets, raise_error=True)
  File "src/gevent/greenlet.py", line 849, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 865, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "/usr/local/lib/python3.7/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py", line 74, in __call__
    return self._run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/scenario_player/tasks/execution.py", line 41, in _run
    task()
  File "/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py", line 74, in __call__
    return self._run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/scenario_player/tasks/execution.py", line 65, in _run
    group.join(raise_error=True)
  File "/usr/local/lib/python3.7/site-packages/gevent/pool.py", line 433, in join
    greenlet._raise_exception()
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "/usr/local/lib/python3.7/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py", line 74, in __call__
    return self._run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py", line 56, in _run
    raise RESTAPIError(f"Error performing REST-API call: {self._name}") from ex
scenario_player.exceptions.legacy.RESTAPIError: Error performing REST-API call: open_channel
```

whereas the node logs show 

```FATAL: An unexpected exception occured. A traceback has been written to /tmp/raiden-exception-2019-11-08T10-44jr0v3p8c.txt
404: {"errcode":"M_NOT_FOUND","error":"Profile was not found"}
``` 

here are some logs 
- http://68.183.70.168/Scenario_player_Logs-pfs6_simple_path_rewards-1-latest-2019-11-08.tar.gz
- http://scenario-player.ci.raiden.network/Scenario_player_Logs-ms3_simple_monitoring-1-latest-2019-11-08.tar.gz
- http://scenario-player.ci.raiden.network/Scenario_player_Logs-ms2_simple_monitoring-1-latest-2019-11-08.tar.gz

## Issue checklist

To help us more easily debug your issue please check the boxes for which requirements for safe usage or Raiden were followed:

- [ ] The Ethereum node was always up to date with the chain tip and never stopped running.
- [ ] No Ethereum transaction was sent for the account that Raiden manages by another app.
- [ ] The Ethereum account used by Raiden always had sufficient ETH.
- [ ] The Raiden DB that exists by default at ~/.raiden was never altered or deleted.
- [ ] The Raiden node was never restarted. If yes please provide more info.
- [ ] The ethereum node was not switched while Raiden was running.
- [ ] The Raiden REST API is protected from public access.

-->

## Problem Definition

Provide a description of what is the current problem and why you are raising this issue.
If it's a bug please describe what was the unexpected thing that occured and what was the
expected behaviour.

Raiden also logs debug information to the `raiden-debug.log` file. Please attach it to the
issue as it may help us find the source of the issue faster. It would also help if you provide us with the database located under `~/.raiden/node_xxxxxx/netid_x/network_xxxx/`. If you are on the mainnet and would like to keep your data private you can encrypt them and send it to us via email. Read [here](https://github.com/raiden-network/raiden/blob/master/CONTRIBUTING.md#including-sensitive-data-in-your-issue-reports) to see how the process works.

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
uname -a
command -v solc && solc --version
command -v geth && geth version
command -v parity && parity --version
command -v raiden && raiden version
[ -d .git ] && git rev-parse HEAD
```

**Comment by ulope** [comment]
The error message is produced in synapse's [get_displayname](https://github.com/matrix-org/synapse/blob/782dd72037cf71fb3f9e4922b07c56df2f59de75/synapse/handlers/profile.py#L125) method.

**Comment by LefterisJP** [comment]
Why was this closed? How was it solved?
