### ISSUE TITLE
All Scenarios fail due to  MatrixRequestError: 404 Profile was not found 

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5264]
## Problem Definition
A common matrix problem affecting the raiden nodes at different point in their scenarios nonetheless this exception can be encountered in probably most of the nodes of the scenarios 

```
Traceback (most recent call last):
  File "/usr/local/bin/raiden", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/raiden/__main__.py", line 13, in main
    run(auto_envvar_prefix="RAIDEN")  # pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/raiden/ui/cli.py", line 597, in run
    app = runner.run()
  File "/usr/local/lib/python3.7/site-packages/raiden/ui/runners.py", line 245, in run
    return self._start_services()
  File "/usr/local/lib/python3.7/site-packages/raiden/ui/runners.py", line 236, in _start_services
    raise_error=True,
  File "src/gevent/greenlet.py", line 849, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 865, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "/usr/local/lib/python3.7/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.7/site-packages/raiden/ui/runners.py", line 231, in stop_task
    task.get()  # re-raise
  File "src/gevent/greenlet.py", line 633, in gevent._greenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "/usr/local/lib/python3.7/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.7/site-packages/raiden/raiden_service.py", line 446, in _run
    self.stop_event.wait()
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
matrix_client.errors.MatrixRequestError: 404: {"errcode":"M_NOT_FOUND","error":"Profile was not found"}
--------- Stopped ---------
```
The scenarios might fail at different points but generally the nodes eventually stop due to this exception
[Scenario_player_Logs-mfee4_combined_fees-1-latest-2019-11-11.tar.gz](https://github.com/raiden-network/raiden/files/3830387/Scenario_player_Logs-mfee4_combined_fees-1-latest-2019-11-11.tar.gz)

[Scenario_player_Logs-mfee3_only_imbalance_fees-1-latest-2019-11-11.tar.gz](https://github.com/raiden-network/raiden/files/3830410/Scenario_player_Logs-mfee3_only_imbalance_fees-1-latest-2019-11-11.tar.gz)

[Scenario_player_Logs-mfee2_proportional_fees-1-latest-2019-11-11.tar.gz](https://github.com/raiden-network/raiden/files/3830413/Scenario_player_Logs-mfee2_proportional_fees-1-latest-2019-11-11.tar.gz)

[Scenario_player_Logs-mfee1_flat_fee-1-latest-2019-11-11.tar.gz](https://github.com/raiden-network/raiden/files/3830416/Scenario_player_Logs-mfee1_flat_fee-1-latest-2019-11-11.tar.gz)

[Scenario_player_Logs-bf1_basic_functionality-1-latest-2019-11-11.tar.gz](https://github.com/raiden-network/raiden/files/3830420/Scenario_player_Logs-bf1_basic_functionality-1-latest-2019-11-11.tar.gz)

[Scenario_player_Logs-bf3_multi_directional_payment-1-latest-2019-11-11.tar.gz](https://github.com/raiden-network/raiden/files/3830421/Scenario_player_Logs-bf3_multi_directional_payment-1-latest-2019-11-11.tar.gz)

**Comment by agatsoh** [comment]
Closing because it is duplicate of #5260
