### ISSUE TITLE
Installing Raiden w/ other packages breaks raiden executable.

### ISSUE THREAD

**Issue by nlsdfnbch** [raiden-network/raiden#5323]
For our nightliy scenario runs, it's important to install the latest `raiden` version.
On top of this, we install our scenario-player package.

We do this using a dockerfile which looks like this:
```
FROM python:3.7

ADD raiden-upstream /raiden-upstream
RUN cd /raiden-upstream &&  pip install .

ADD scenario-player /scenario-player
RUN cd /scenario-player && pip install pysnooper .

ENTRYPOINT ["/usr/local/bin/scenario_player"]
```

the folders `/raiden-upstream` and `/scenario-player` are git repositories which are updated like so before building the image:

```bash
...
# Directories
BASE_DIR=/var/lib/scenario-player
RAIDEN_GIT=${BASE_DIR}/raiden-upstream
SCENARIOS_DIR=${RAIDEN_GIT}/raiden/tests/scenarios
SP_GIT=${BASE_DIR}/scenario-player

...

prepare() {
    # Update raiden and SP packages via git repo.
    cd ${RAIDEN_GIT}
    git reset --hard
    git fetch origin
    git checkout origin/${RAIDEN_BRANCH}
    cd ${SP_GIT}
    git reset --hard
    git fetch origin
    git checkout origin/${SP_BRANCH}

    # Build docker image
    cd ${BASE_DIR}
    docker build -t raiden/scenario-player .
}
...
prepare
...
```

This has been working until yesterday, when `raiden` started complaining about not being able to detect a Raiden version:

```bash
20191120T074230 Running ms1_simple_monitoring
ESC[33mWriting log to /data/scenarios/ms1_simple_monitoring/scenario-player-run_ms1_simple_monitoring_2019-11-20T07:42:31.logESC[0m
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/raiden/utils/__init__.py", line 123, in get_system_spec
    version = pkg_resources.require(raiden.__name__)[0].version
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (marshmallow 3.2.2 (/usr/local/lib/python3.7/site-packages), Requirement.parse('marshmallow==3.0.0rc8'), {'raiden'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/scenario_player", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/scenario_player/main.py", line 112, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/scenario_player/main.py", line 145, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/scenario_player/main.py", line 128, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/scenario_player/main.py", line 210, in run
    log.info("Scenario Player version:", version_info=get_complete_spec())
  File "/usr/local/lib/python3.7/site-packages/scenario_player/utils/version.py", line 9, in get_complete_spec
    spec = raiden_system_spec()
  File "/usr/local/lib/python3.7/site-packages/raiden/utils/__init__.py", line 126, in get_system_spec
    "Cannot detect Raiden version. Did you do python setup.py?  "
RuntimeError: Cannot detect Raiden version. Did you do python setup.py?  Refer to https://raiden-network.readthedocs.io/en/latest/overview_and_guide.html#for-developers
```

As I was trying things out, @ulope pointed out that installing `raiden` by itself in a dockerfile works fine:

```
FROM python:3.7

RUN python3 -m venv /venv
ENV PATH=/venv/bin:${PATH}

RUN git clone -b develop https://github.com/raiden-network/raiden.git /raiden
WORKDIR /raiden
RUN make install
WORKDIR /
RUN raiden version
```

Initially I believed this to be a Docker issue - however, since the SP nightly docker setup has not changed, I suspect that there was a change in the way raiden is installed and/or handles upgraded/packages - **as can be seen from the stacktrace, the error is a result of a dependency not matching an expectation in `raiden`.**

**Comment by palango** [comment]
Is this still an issue?

**Comment by nlsdfnbch** [comment]
Been a while since I opened this, but essentially it boils down to this:

If raiden pins all its packages, it's reasonable to believe that it cannot be used as a library by other tools (assuming they pin packages of their own). 

I believe to have read somewhere that you dropped this behavior/feature (raiden being usable as a library) and no longer support it?

If that's the case, this issue can be closed.

**Comment by ulope** [comment]
Yes, Raiden isn't intended to be used as a library (anymore, a long while ago we had plans in that direction).
For some of our internal tools we effectively do use parts of it as a library.

If we ever are able to switch to a monorepo things may improve there.
