### ISSUE TITLE
PFS 8 Selected Pathfinding Service returned unexpected reply

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5371]
## Problem Definition

The Scenario does not run at all and the nodes get 
```
There was an error with the Pathfinding Service with address https://pfs-goerli-with-fee.services-dev.raiden.network. Raiden will shut down. Please try a different Pathfinding Service. 
Error Message: Selected Pathfinding Service returned unexpected reply
```
This may be related to issue #5370 

[pfs8_mediator_goes_offline_2019_11_26.tar.gz](https://github.com/raiden-network/raiden/files/3890840/pfs8_mediator_goes_offline_2019_11_26.tar.gz)

**Comment by rakanalh** [comment]
The logs from the PFS show that it crashed with the following exception:
```
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]: Traceback (most recent call last):
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:     "__main__", mod_spec)
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:     exec(code, run_globals)
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:   File "/services/src/pathfinding_service/cli.py", line 130, in <module>
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:     main(auto_envvar_prefix="PFS")  # pragma: no cover
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:     exec(code, run_globals)
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:   File "/services/src/pathfinding_service/cli.py", line 130, in <module>
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:     main(auto_envvar_prefix="PFS")  # pragma: no cover
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:     return self.main(*args, **kwargs)
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:     rv = self.invoke(ctx)
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:     return ctx.invoke(self.callback, **ctx.params)
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:     return callback(*args, **kwargs)
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:   File "/services/src/raiden_libs/cli.py", line 183, in call_with_blockchain_info
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:     return callback(**params)
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:   File "/services/src/raiden_libs/cli.py", line 128, in call_with_common_options_initialized
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:     return func(**params)
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:   File "/services/src/pathfinding_service/cli.py", line 115, in main
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:     service.run()
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:   File "src/gevent/greenlet.py", line 718, in gevent._greenlet.Greenlet.run
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:   File "src/gevent/greenlet.py", line 706, in gevent._greenlet.Greenlet._report_error
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:   File "/services/src/raiden_libs/gevent_error_handler.py", line 24, in error_handler
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:     Hub.handle_system_error(self, etype, value)
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:   File "/usr/local/lib/python3.7/site-packages/gevent/hub.py", line 488, in handle_system_error
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]:     self.parent.throw(type, value)
Nov 26 03:36:45 services-dev e8e174bcfd67[5820]: TypeError: can't compare offset-naive and offset-aware datetimes
Nov 26 03:36:55 services-dev e8e174bcfd67[5820]: {"address": "0xb6569e9Ff96C19584ac0B26CB802002eA70CD0dc", "current_presence": "<AddressReachability.UNKNOWN: 3>", "refresh": false, "event": "Tracking address", "level": "debug", "logger": "
Nov 26 03:36:55 services-dev e8e174bcfd67[5820]: {"address": "0x102766D3Ca72E4d3381cC2d516b69f554721C310", "current_presence": "<AddressReachability.UNKNOWN: 3>", "refresh": false, "event": "Tracking address", "level": "debug", "logger": "
Nov 26 03:36:55 services-dev e8e174bcfd67[5820]: {"address": "0xE76Fffe0271Cd6f8E299F759E98C574009C07f12", "current_presence": "<AddressReachability.UNKNOWN: 3>", "refresh": false, "event": "Tracking address", "level": "debug", "logger": "
Nov 26 03:36:55 services-dev e8e174bcfd67[5820]: {"address": "0x69829510B1328500A48F3507ef9e69E24D7a2Ee1", "current_presence": "<AddressReachability.UNKNOWN: 3>", "refresh": false, "event": "Tracking address", "level": "debug", "logger": "
```

So between 03:36:45 and 03:36:55 the PFS was down.

The logs from the SP PFS8 show that the nodes attempted to start at: 03:36:52 when the PFS wasn't handling any requests. 

An issue has been created for the above stacktrace: https://github.com/raiden-network/raiden-services/issues/660

So i will close this issue.
