### ISSUE TITLE
SerializationError on startup

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/raiden#5392]
## Problem Definition

I can't start Raiden with one specific account due to the following SerializationError.

```
2019-11-27 16:15:23.107107 [info     ] Using Matrix server            [raiden.network.transport.matrix.utils] average_rtt=0.15878866666666666 server_ident=Synapse/1.5.1 server_url=https://transport01.raiden.network
Traceback (most recent call last):
  File "raiden/storage/serialization/serializer.py", line 78, in deserialize
  File "marshmallow/schema.py", line 714, in load
  File "marshmallow/schema.py", line 892, in _do_load
marshmallow.exceptions.ValidationError: {'channel_state': {'open_transaction': {'started_block_number': ['Not a valid integer.']}}}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "raiden-script.py", line 2, in <module>
  File "raiden/__main__.py", line 13, in main
  File "click/core.py", line 764, in __call__
  File "click/core.py", line 717, in main
  File "click/core.py", line 1114, in invoke
  File "click/core.py", line 956, in invoke
  File "click/core.py", line 555, in invoke
  File "click/decorators.py", line 17, in new_func
  File "raiden/ui/cli.py", line 603, in run
  File "raiden/ui/runners.py", line 248, in run
  File "raiden/ui/runners.py", line 92, in _start_services
  File "raiden/ui/app.py", line 371, in run_app
  File "raiden/app.py", line 137, in start
  File "raiden/raiden_service.py", line 346, in start
  File "raiden/storage/wal.py", line 65, in restore_to_state_change
  File "raiden/storage/sqlite.py", line 857, in get_statechanges_by_range
  File "raiden/storage/sqlite.py", line 851, in get_statechanges_records_by_range
  File "raiden/storage/sqlite.py", line 851, in <listcomp>
  File "raiden/storage/serialization/serializer.py", line 100, in deserialize
  File "raiden/storage/serialization/serializer.py", line 80, in deserialize
raiden.exceptions.SerializationError: Can't deserialize: {'block_number': '1515293', 'channel_state': {'reveal_timeout': 50, 'token_address': '0x62083c80353Df771426D209eF578619EE68D5C7A', 'close_transaction': None, 'open_transaction': {'result': 'success', 'finished_block_number': '1515293', 'started_block_number': ''}, 'partner_state': {'address': '0xB8Dbb6ed5B86b5F369f294838B5b7e0e66CBe319', 'nonce': '0', 'withdraws_expired': [], 'contract_balance': 0, 'onchain_total_withdraw': '0', 'pending_locks': {'locks': []}, 'balance_proof': None, 'onchain_locksroot': '0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470', 'secrethashes_to_onchain_unlockedlocks': {}, 'withdraws_pending': {}, 'secrethashes_to_unlockedlocks': {}, 'secrethashes_to_lockedlocks': {}}, 'update_transaction': None, 'token_network_registry_address': '0x62436bbadB629498107278486C2A367FfdFEb2f3', 'our_state': {'address': '0x1888f6aF921f350eD71e6e86381Aae1A537A3fDF', 'nonce': '0', 'withdraws_expired': [], 'contract_balance': 0, 'onchain_total_withdraw': '0', 'pending_locks': {'locks': []}, 'balance_proof': None, 'onchain_locksroot': '0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470', 'secrethashes_to_onchain_unlockedlocks': {}, 'withdraws_pending': {}, 'secrethashes_to_unlockedlocks': {}, 'secrethashes_to_lockedlocks': {}}, 'fee_schedule': {'imbalance_penalty': None, 'cap_fees': True, 'flat': '0', 'proportional': 4000}, 'canonical_identifier': {'channel_identifier': '171', 'token_network_address': '0xDa1fBc048f503635950058953f5c60FC1F564ee6', 'chain_identifier': '5'}, 'settle_transaction': None, 'settle_timeout': 500}, 'block_hash': '0xdc858690af9150a43585a57782f4c795849dfe0f38f6b94bfa200e6559504ce1', 'transaction_hash': '0x58097f2bb31773bf4c4f5705032c960f21222e8bc67565927ed630e32c0f1ca7', '_type': 'raiden.transfer.state_change.ContractReceiveChannelNew'}
[2959] Failed to execute script raiden-script
Exception ignored in: <function SQLiteStorage.__del__ at 0x7f3f5c7cd710>
Traceback (most recent call last):
  File "raiden/storage/sqlite.py", line 731, in __del__
RuntimeError: The database connection was not closed.
--- Logging error ---
Traceback (most recent call last):
  File "logging/handlers.py", line 69, in emit
  File "logging/handlers.py", line 183, in shouldRollover
  File "logging/__init__.py", line 1116, in _open
NameError: name 'open' is not defined
Call stack:
  File "filelock.py", line 331, in __del__
  File "filelock.py", line 318, in release
  File "logging/__init__.py", line 1378, in info
  File "logging/__init__.py", line 1514, in _log
  File "logging/__init__.py", line 1524, in handle
  File "logging/__init__.py", line 1586, in callHandlers
  File "logging/__init__.py", line 894, in handle
  File "logging/handlers.py", line 73, in emit
Message: 'Lock %s released on %s'
Arguments: (139910075535312, '/home/manuel/.raiden/node_1888f6af/netid_5/network_62436bba/.lock')
```

### System 
Raiden v0.200.0rc2

**Comment by palango** [comment]
Do you use the RC or the latest develop?

**Comment by palango** [comment]
What looks strange here is `'started_block_number': ''`

**Comment by rakanalh** [comment]
@manuelwedler can you attach the DB for that node?

**Comment by manuelwedler** [comment]
I used the new RC,  v0.200.0rc2. Here is the database:
[db.zip](https://github.com/raiden-network/raiden/files/3900900/db.zip)

**Comment by rakanalh** [comment]
Note: The account used seems to have started it's history with Raiden on the 22nd of October 2019. 

With the current version of develop, i tried doing the following:
```
>>> from raiden.transfer.state import TransactionExecutionStatus
>>> status = TransactionExecutionStatus(None, 123, "success")
>>>
>>> from raiden.storage.serialization import JSONSerializer
>>> JSONSerializer.serialize(status)
'{"finished_block_number": "123", "started_block_number": null, "result": "success", "_type": "raiden.transfer.state.TransactionExecutionStatus"}'
```

Apparently that works. 

Checking DB version stored in the database is 23 which is equal to the current value. That tells me that the DB has been created by a db-compatible version with the latest RC.

**Comment by rakanalh** [comment]
This incompatibility was introduced on 11th of Nov in this commit:

https://github.com/raiden-network/raiden/commit/5c2e4960b7541abdedad2daf3d35b07d8f414be6#diff-bdc5a4be99947da291f8d465e41125c9

Where `Optional[BlockNumber]` serialized "None" to an empty string and vice versa (which was a hack at the time to be backwards-compatible). Now that we're breaking compatibility prior to the Alderaan release, a proper fix was introduced by the above change.

Nothing to be done here, closing.

**Comment by christianbrb** [comment]
@rakanalh Thanks a lot for your investigation :)

In my opinion, the user should get informed, that the database is incompatible with his Raiden version. Within the error message @manuelwedler was reporting I do not see that.

Reopening
