### ISSUE TITLE
RestAPI and RaidenService initialization needs synchronization.

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#5401]
Note: I got this error while stop *and* starting the node, with the WebUI running in the background. Probably the refresh of the webui arrived while the RestAPI was finishing it's initialization.

```
Welcome to Raiden, version 0.100.5a1.dev867+gdd9ab647b!
----------------------------------------------------------------------
| This is an Alpha version of experimental open source software      |
| released as a test version under an MIT license and may contain    |
| errors and/or bugs. No guarantee or representations whatsoever is  |
| made regarding its suitability (or its use) for any purpose or     |
| regarding its compliance with any applicable laws and regulations. |
| Use of the software is at your own risk and discretion and by      |
| using the software you acknowledge that you have read this         |
| disclaimer, understand its contents, assume all risk related       |
| thereto and hereby release, waive, discharge and covenant not to   |
| sue Brainbot Labs Establishment or any officers, employees or      |
| affiliates from and for any direct or indirect liability resulting |
| from the use of the software as permissible by applicable laws and |
| regulations.                                                       |
|                                                                    |
| Privacy Warning: Please be aware, that by using the Raiden Client, |
| among others, your Ethereum address, channels, channel deposits,   |
| settlements and the Ethereum address of your channel counterparty  |
| will be stored on the Ethereum chain, i.e. on servers of Ethereum  |
| node operators and ergo are to a certain extent publicly available.|
| The same might also be stored on systems of parties running Raiden |
| nodes connected to the same token network. Data present in the     |
| Ethereum chain is very unlikely to be able to be changed, removed  |
| or deleted from the public arena.                                  |
|                                                                    |
| Also be aware, that data on individual Raiden token transfers will |
| be made available via the Matrix protocol to the recipient,        |
| intermediating nodes of a specific transfer as well as to the      |
| Matrix server operators.                                           |
----------------------------------------------------------------------
2019-11-28 14:20:57.328869 [info     ] Starting Raiden                [raiden.ui.runners] architecture=x86_64 distribution=bundled python_implementation=CPython python_version=3.7.5 raiden=0.100.5a1.dev867+gdd9ab647b raiden_db_version=23 system=Linux 64bit_ELF 5.3.11.a-1-hardened
Raiden is running in production mode
Checking if the ethereum node is synchronized

You are connected to the 'goerli' network and the DB path is: /home/hack/work/brainbot/test-env/node-73ffda9f548230dcfc1dc256e8ca7e32878c9d19/node_73ffda9f/netid_5/network_11fa4cd3/v23_log.db
2019-11-28 14:20:59.989093 [info     ] Using Matrix server            [raiden.network.transport.matrix.utils] average_rtt=0 server_ident=Synapse/1.5.1 server_url=http://raidentransport.demo-env.raiden.network
2019-11-28 14:21:01.544873 [info     ] Raiden started                 [raiden.app] node=0x73ffdA9f548230dCFc1dc256e8Ca7E32878C9D19
The Raiden API RPC server is now running at http://127.0.0.1:5001/.

See the Raiden documentation for all available endpoints at
http://raiden-network.readthedocs.io/en/stable/rest_api.html
2019-11-28 14:21:27.658276 [info     ] 127.0.0.1 - - [2019-11-28 11:21:27] "GET /api/v1/pending_transfers HTTP/1.1" 200 137 0.004757 [raiden.api.rest.pywsgi]
2019-11-28 14:21:30.735863 [info     ] 127.0.0.1 - - [2019-11-28 11:21:30] "GET /api/v1/channels HTTP/1.1" 200 137 0.006182 [raiden.api.rest.pywsgi]
2019-11-28 14:21:32.681692 [info     ] 127.0.0.1 - - [2019-11-28 11:21:32] "GET /api/v1/pending_transfers HTTP/1.1" 200 137 0.000872 [raiden.api.rest.pywsgi]
^CSignal received. Shutting down ...
2019-11-28 14:21:35.775417 [critical ] Unhandled exception when processing endpoint request [raiden.api.rest] node=0x73ffdA9f548230dCFc1dc256e8Ca7E32878C9D19
Traceback (most recent call last):
  File "flask/app.py", line 1830, in full_dispatch_request
  File "flask/app.py", line 2106, in preprocess_request
  File "raiden/api/rest.py", line 393, in _is_raiden_running
RuntimeError: The RaidenService must be started before the API can be used
2019-11-28 14:21:36.779477 [info     ] 127.0.0.1 - - [2019-11-28 11:21:36] "GET /api/v1/channels HTTP/1.1" 500 161 1.004604 [raiden.api.rest.pywsgi]
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "raiden/api/rest.py", line 440, in _run
  File "gevent/baseserver.py", line 364, in serve_forever
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
RuntimeError: The RaidenService must be started before the API can be used
2019-11-28T14:21:36Z <Greenlet "APIServer|Greenlet-3" at 0x6ee54babe830: <bound method APIServer._run of <raiden.api.rest.APIServer object at 0x6ee54b81a750>>> failed with RuntimeError

Traceback (most recent call last):
  File "build/raiden/raiden-script.py", line 2, in <module>
  File "raiden/__main__.py", line 13, in main
  File "click/core.py", line 764, in __call__
  File "click/core.py", line 717, in main
  File "click/core.py", line 1114, in invoke
  File "click/core.py", line 956, in invoke
  File "click/core.py", line 555, in invoke
  File "click/decorators.py", line 17, in new_func
  File "raiden/ui/cli.py", line 419, in run
  File "raiden/ui/runners.py", line 286, in run
  File "raiden/ui/runners.py", line 277, in _start_services
  File "src/gevent/greenlet.py", line 849, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 865, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "gevent/_compat.py", line 47, in reraise
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "raiden/api/rest.py", line 440, in _run
  File "gevent/baseserver.py", line 364, in serve_forever
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
RuntimeError: The RaidenService must be started before the API can be used
[466582] Failed to execute script raiden-script
```

**Comment by hackaugusto** [comment]
should have been fixed with: https://github.com/raiden-network/raiden/issues/5505
