### ISSUE TITLE
Connection manager causes MatrixRequestError

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/raiden#5465]
## Problem Definition

I tried to use the connection manager. It opened two channels but then Raiden quitted due to the following error:
```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "raiden/tasks.py", line 168, in _run
  File "raiden/tasks.py", line 207, in loop_until_stop
  File "raiden/tasks.py", line 263, in _maybe_run_callbacks
  File "raiden/raiden_service.py", line 807, in _callback_new_block
  File "raiden/raiden_service.py", line 608, in handle_and_track_state_changes
  File "raiden/raiden_service.py", line 631, in handle_state_changes
  File "raiden/blockchain_events_handler.py", line 96, in after_blockchain_statechange
  File "raiden/blockchain_events_handler.py", line 59, in after_new_channel_start_healthcheck
  File "raiden/raiden_service.py", line 720, in start_health_check_for
  File "raiden/network/transport/matrix/transport.py", line 520, in start_health_check
  File "raiden/network/transport/matrix/transport.py", line 513, in whitelist
  File "raiden/network/transport/matrix/transport.py", line 1041, in _maybe_create_room_for_address
  File "matrix_client/client.py", line 305, in create_room
  File "matrix_client/api.py", line 182, in create_room
  File "raiden/network/transport/matrix/client.py", line 159, in _send
  File "matrix_client/api.py", line 691, in _send
matrix_client.errors.MatrixRequestError: 500: {"errcode":"M_UNKNOWN","error":"Internal server error"}
2019-12-09T11:07:34Z <Greenlet "AlarmTask._run node:0x7aA95680A42A96F64De070C4C30eE7e5F02A484b" at 0x7f2a1ffe2710: <bound method AlarmTask._run of <AlarmTask node:0x7aA95680A42A96F64De070C4C30eE7e5F02A484b>>> failed with MatrixRequestError

2019-12-09 11:07:34.709906 [error    ] Runnable subtask died!         [raiden.utils.runnable] exc=MatrixRequestError('500: {"errcode":"M_UNKNOWN","error":"Internal server error"}') running=True subtask=<Greenlet "AlarmTask._run node:0x7aA95680A42A96F64De070C4C30eE7e5F02A484b" at 0x7f2a1ffe2710: <bound method AlarmTask._run of <AlarmTask node:0x7aA95680A42A96F64De070C4C30eE7e5F02A484b>>> this=<RaidenService node:0x7aA95680A42A96F64De070C4C30eE7e5F02A484b>
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "raiden/raiden_service.py", line 445, in _run
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
matrix_client.errors.MatrixRequestError: 500: {"errcode":"M_UNKNOWN","error":"Internal server error"}
2019-12-09T11:07:35Z <Greenlet "RaidenService._run node:0x7aA95680A42A96F64De070C4C30eE7e5F02A484b" at 0x7f2a1ffe2950: <bound method RaidenService._run of <RaidenService node:0x7aA95680A42A96F64De070C4C30eE7e5F02A484b>>> failed with MatrixRequestError

FATAL: An unexpected exception occured. A traceback has been written to /tmp/raiden-exception-2019-12-09T11-07g12ymue3.txt
500: {"errcode":"M_UNKNOWN","error":"Internal server error"}
```
[db.zip](https://github.com/raiden-network/raiden/files/3939377/db.zip)
[raiden-debug_2019-12-09T10:00:39.972736.log](https://github.com/raiden-network/raiden/files/3939368/raiden-debug_2019-12-09T10.00.39.972736.log)

### System Description
Raiden v0.200.0rc2

**Comment by palango** [comment]
Did you try this this morning? We had a full disk at the transport04 server, so that might explain it.

**Comment by manuelwedler** [comment]
Yes, it was this morning. It seems that this was the reason for the error. I can't reproduce it anymore.

**Comment by palango** [comment]
This needs a better error message: ref https://github.com/raiden-network/raiden/issues/5461
