### ISSUE TITLE
BF5 fails Couldn't register token with network

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5470]
Logs and more analysis will follow
## Problem Definition

```
{
  "code": -1,
  "message": "HTTPConnectionPool(host='127.0.0.1', port=44333): Max retries exceeded with url: /api/v1/tokens/0x807cF8C9B84F838e15277Ca0003B7A055b687d0F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9880bbb668>: Failed to establish a new connection: [Errno 111] Connection refused'))",
  "event": "Couldn't register token with network",
  "logger": "scenario_player.runner",
  "level": "error",
  "timestamp": "2019-12-10 02:55:50.943791"
}
```
What does the exception say:

1. **Couldn't register token with network**

2. Fails while calling url
`/api/v1/tokens/0x807cF8C9B84F838e15277Ca0003B7A055b687d0F`	
Relevant API description from the docs
https://raiden-network.readthedocs.io/en/latest/rest_api.html#get--api-(version)-tokens-(token_address)
Registers a token. If a token is not registered yet (i.e.: A token network for that token does not exist in the registry), we need to register it by deploying a token network contract for that token.

3. The SP deploys a new token. This can be verified from etherscan too
https://goerli.etherscan.io/address/0x807cf8c9b84f838e15277ca0003b7a055b687d0f
```
{
  "address": "0x807cF8C9B84F838e15277Ca0003B7A055b687d0F",
  "name": "Scenario Test Token 90edd9e6-4490-4b78-b138-94d437065138 2019-12-10T02:53",
  "symbol": "T90e",
  "event": "Deployed token",
  "logger": "scenario_player.utils.token",
  "level": "info",
  "timestamp": "2019-12-10 02:55:22.425461"
}
```
Edit Node logs Findings:

Stdout:
`FATAL: Either the given address is for a different smart contract, or the contract was not yet deployed at the block 0x26742f0ae9f6232c92642c2fba1807d3a86e801a2181d583ca17f0a15f699eff. Either way this call should never happened.`

Stderr:
```
--------- Starting ---------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/web3/contract.py", line 1372, in call_contract_function
    output_data = decode_abi(output_types, return_data)
  File "/usr/local/lib/python3.7/site-packages/eth_abi/abi.py", line 96, in decode_abi
    return decoder(stream)
  File "/usr/local/lib/python3.7/site-packages/eth_abi/decoding.py", line 118, in __call__
    return self.decode(stream)
  File "/usr/local/lib/python3.7/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/usr/local/lib/python3.7/site-packages/eth_abi/decoding.py", line 164, in decode
    yield decoder(stream)
  File "/usr/local/lib/python3.7/site-packages/eth_abi/decoding.py", line 118, in __call__
    return self.decode(stream)
  File "/usr/local/lib/python3.7/site-packages/eth_abi/decoding.py", line 186, in decode
    raw_data = self.read_data_from_stream(stream)
  File "/usr/local/lib/python3.7/site-packages/eth_abi/decoding.py", line 296, in read_data_from_stream
    len(data),
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/raiden/network/proxies/token_network_registry.py", line 132, in add_token
    token_supply = token_proxy.total_supply(block_identifier=block_identifier)
  File "/usr/local/lib/python3.7/site-packages/raiden/network/proxies/token.py", line 168, in total_supply
    self.proxy.contract.functions.totalSupply().call(block_identifier=block_identifier)
  File "/usr/local/lib/python3.7/site-packages/web3/contract.py", line 1115, in call
    **self.kwargs
  File "/usr/local/lib/python3.7/site-packages/web3/contract.py", line 1394, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not decode contract function call totalSupply return data b'' for output_types ['uint256']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.7/site-packages/raiden/api/rest.py", line 441, in _run
    self.wsgiserver.serve_forever()
  File "/usr/local/lib/python3.7/site-packages/gevent/baseserver.py", line 364, in serve_forever
    self._stop_event.wait()
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
raiden.exceptions.RaidenUnrecoverableError: Either the given address is for a different smart contract, or the contract was not yet deployed at the block 0x26742f0ae9f6232c92642c2fba1807d3a86e801a2181d583ca17f0a15f699eff. Either way this call should never happened.
2019-12-10T02:55:45Z <Greenlet "APIServer|Greenlet-3" at 0x7fc589c61158: <bound method APIServer._run of <raiden.api.rest.APIServer object at 0x7fc583a032b0>>> failed with RaidenUnrecoverableError

--------- Stopped ---------
```

[bf5_join_and_leave_2019_12_10.tar.gz](https://github.com/raiden-network/raiden/files/3944108/bf5_join_and_leave_2019_12_10.tar.gz)

**Comment by czepluch** [comment]
BF5 failed in the same way last night.

Logs: 
- [Scenario logs](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/scenario-player-run_bf5_join_and_leave_2019-12-12T22%3A34%3A53.log)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/node_26_000/)
- [node1](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/node_26_001/)
- [node2](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/node_26_002/)
- [node3](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/node_26_003/)

**Comment by czepluch** [comment]
Happened again in BF5 on 14th of December

Logs:
- [Scenario log](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/scenario-player-run_bf5_join_and_leave_2019-12-14T23%3A12%3A01.log)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/node_28_000/)
- [node1](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/node_28_001/)
- [node2](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/node_28_002/)
- [node3](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/node_28_003/)

**Comment by czepluch** [comment]
Happened in BF5 on 15th of December too

Logs:
- [Scenario log](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/scenario-player-run_bf5_join_and_leave_2019-12-15T23%3A16%3A01.log)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/node_29_000/)
- [node1](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/node_29_001/)
- [node2](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/node_29_002/)
- [node3](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/node_29_003/)

**Comment by czepluch** [comment]
Happened in BF on dec 17th too

Logs:
- [Scenario log](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/scenario-player-run_bf5_join_and_leave_2019-12-16T22%3A04%3A21.log)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/node_30_000/)
- [node1](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/node_30_001/)
- [node2](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/node_30_002/)
- [node3](http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/node_30_003/)

**Comment by palango** [comment]
This issue is quite old now and a lot of code changed since then. Please reopen if it happens again.
