### ISSUE TITLE
[META] MatrixSyncMaxTimeoutReached in several scenarios [DO NOT PICK UP]

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#5498]
I encountered the following error in multiple nodes when running the bf6 scenario locally:
```
Traceback (most recent call last):
  File "/home/karl/raiden/raiden/network/transport/matrix/client.py", line 281, in listen_forever
    self._sync(timeout_ms)
  File "/home/karl/raiden/raiden/network/transport/matrix/client.py", line 498, in _sync
    f"Processing Matrix response took {processing_time_in_seconds}s, "
raiden.exceptions.MatrixSyncMaxTimeoutReached: Processing Matrix response took 25.108961582183838s, poll timeout is 20s.
```

Logs for only two of the nodes are attached to keep the zip below githubs 10MB limit.
[run_101.zip](https://github.com/raiden-network/raiden/files/3955306/run_101.zip)

## Update

We are working on this Meta-Issue in several sub-issues & PRs. Current Assumption is: Deepcopy takes on average more than 1s, since copying the old state with this one huge token_network takes time. If there are more than 20 messages being sent, we get this timeout. Our ScenarioPlayer Token Netwrok is simply too big.

- Reproducing #5562
- Proper Analysis of deepcopy #5565 
- Proxy Manager #5559 
- Response Queue #5275
- Ignore broadcasting rooms #5343
- Filtering room messages #5535 
- Message dispatching #5537

**Comment by palango** [comment]
Happens for me as well in BF6

**Comment by Dominik1999** [comment]
Next steps (Planning 16.12.): 
- Keep bf6 in test suite 
- Try to get faster (caching address formatting)
- Looking at the flamegraph and executing the issues:
< Link the issues of flamegraph analysis >

**Comment by czepluch** [comment]
Also happened for PFS9 on 15th of December

Logs:
- [Scenario log](http://68.183.70.168:8000/scenario-player/scenarios/pfs9_partial_withdraw/scenario-player-run_pfs9_partial_withdraw_2019-12-15T03%3A49%3A32.log)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/pfs9_partial_withdraw/node_61_000/)
- [node1](http://68.183.70.168:8000/scenario-player/scenarios/pfs9_partial_withdraw/node_61_001/)
- [node2](http://68.183.70.168:8000/scenario-player/scenarios/pfs9_partial_withdraw/node_61_002/)
- [node3](http://68.183.70.168:8000/scenario-player/scenarios/pfs9_partial_withdraw/node_61_003/)
- [node4](http://68.183.70.168:8000/scenario-player/scenarios/pfs9_partial_withdraw/node_61_004/)

**Comment by czepluch** [comment]
Happened in BF1 on 16th of December

Logs:
- [Scenario log](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/scenario-player-run_bf1_basic_functionality_2019-12-15T22%3A03%3A06.log)
- [node0](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_16_000/)
- [node1](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_16_001/)
- [node2](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_16_002/)
- [node3](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_16_003/)
- [node4](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_16_004/)

**Comment by czepluch** [comment]
Also happened in pfs9 on 16th of December

Logs:
- [Scenario log](http://68.183.70.168:8000/scenario-player/scenarios/pfs9_partial_withdraw/scenario-player-run_pfs9_partial_withdraw_2019-12-16T03%3A52%3A06.log)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/pfs9_partial_withdraw/node_62_000/)
- [node1](http://68.183.70.168:8000/scenario-player/scenarios/pfs9_partial_withdraw/node_62_001/)
- [node2](http://68.183.70.168:8000/scenario-player/scenarios/pfs9_partial_withdraw/node_62_002/)
- [node3](http://68.183.70.168:8000/scenario-player/scenarios/pfs9_partial_withdraw/node_62_003/)
- [node4](http://68.183.70.168:8000/scenario-player/scenarios/pfs9_partial_withdraw/node_62_004/)

**Comment by palango** [comment]
Looks like something like this also happened on 15th of December for BF1 where it fails with: 
```
"message": "HTTP status code \"500\" while fetching http://127.0.0.1:36201/api/v1/channels/0x62083c80353Df771426D209eF578619EE68D5C7A/0xae8037d15CE130D298611a937c1142f9c3A22189. Expected 200: Internal Server Error
```

Logs:
- [Scenario logs](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/scenario-player-run_bf1_basic_functionality_2019-12-14T22%3A03%3A03.log)
- [node0](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_15_000/)
- [node1](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_15_001/)
- [node2](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_15_002/)
- [node3](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_15_003/)
- [node4](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_15_004/)

**Comment by rakanalh** [comment]
Got the same error:
```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/rakan/Brainbot/raiden/raiden/network/transport/matrix/client.py", line 280, in listen_forever
    self._sync(timeout_ms)
  File "/home/rakan/Brainbot/raiden/raiden/network/transport/matrix/client.py", line 497, in _sync
    f"Processing Matrix response took {processing_time_in_seconds}s, "
raiden.exceptions.MatrixSyncMaxTimeoutReached: Processing Matrix response took 122.0680296421051s, poll timeout is 20s.
2019-12-16T15:06:25Z <Greenlet "GMatrixClient.listen_forever user_id:@0x61783591bf55beba80ae9d824e8144d4cd6d0e48:transport03.raiden.network" at 0x7fa5dd121ae8: <bound method GMatrixClient.listen_forever of <raiden.network.transport.matrix.client.GMatrixClient object at 0x7fa5d7f06cf8>>(20000, None)> failed with MatrixSyncMaxTimeoutReached

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/rakan/Brainbot/raiden/raiden/network/transport/matrix/transport.py", line 446, in _run
    self._broadcast_worker()
  File "/home/rakan/Brainbot/raiden/raiden/network/transport/matrix/transport.py", line 620, in _broadcast_worker
    self._broadcast_event.wait(self._config["retry_interval"])
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
raiden.exceptions.MatrixSyncMaxTimeoutReached: Processing Matrix response took 122.0680296421051s, poll timeout is 20s.
2019-12-16T15:06:55Z <Greenlet "MatrixTransport._run node:0x61783591BF55beBa80Ae9D824E8144d4Cd6D0E48" at 0x7fa5dd1217b8: <bound method MatrixTransport._run of <MatrixTransport node:0x61783591BF55beBa80Ae9D824E8144d4Cd6D0E48 id:4ef06c39-b0e2-4e92-9424-29ff7c65ee6c>>> failed with MatrixSyncMaxTimeoutReached

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/rakan/Brainbot/raiden/raiden/api/rest.py", line 441, in _run
    self.wsgiserver.serve_forever()
  File "/home/rakan/.pyenv/versions/raiden/lib/python3.7/site-packages/gevent/baseserver.py", line 364, in serve_forever
    self._stop_event.wait()
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
AssertionError: Waiting for protocol messages requires a running transport.
2019-12-16T15:06:56Z <Greenlet "APIServer|Greenlet-3" at 0x7fa5d4ed6048: <bound method APIServer._run of <raiden.api.rest.APIServer object at 0x7fa5d555ba90>>> failed with AssertionError
```

[scenario-player-run_bf1_basic_functionality_2019-12-16T15:34:42.log](https://github.com/raiden-network/raiden/files/3968728/scenario-player-run_bf1_basic_functionality_2019-12-16T15.34.42.log)


[node0](https://github.com/raiden-network/raiden/files/3968715/run-108.log)
[node1](https://github.com/raiden-network/raiden/files/3968716/run-108.log)
[node2](https://github.com/raiden-network/raiden/files/3968717/run-108.log)
[node3](https://github.com/raiden-network/raiden/files/3968719/run-108.log)
[node5](https://github.com/raiden-network/raiden/files/3968722/run-108.log)

**Comment by Dominik1999** [comment]
Also happened in bf6, see node0 http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_23_000/

**Comment by Dominik1999** [comment]
in case that helps, flamegraphs of a bf6 scenario 
[flamegraphs_bf6_nodes.zip](https://github.com/raiden-network/raiden/files/3977618/flamegraphs_bf6_nodes.zip)

**Comment by czepluch** [comment]
On dec 19th BF1 also failed with a similar looking error to this. I do not find the error described in https://github.com/raiden-network/raiden/issues/5472#issuecomment-567062654 though. But the .stdout for node000 does look quite weird. It's like Raiden was started twice.

Logs:
- [Scenario log](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/scenario-player-run_bf1_basic_functionality_2019-12-18T22%3A02%3A51.log)
- [node0](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_19_000/)
- [node1](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_19_001/)
- [node2](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_19_002/)
- [node3](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_19_003/)
- [node4](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_19_004/)

**Comment by czepluch** [comment]
BF6 failed on dec 19th with `FATAL: Processing Matrix response took 25.210399389266968s, poll timeout is 20s.` in node000

Logs:
- [Scenario log](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/scenario-player-run_bf6_stress_hub_node_2019-12-18T23%3A58%3A18.log)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_24_000/)
- [node1](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_24_001/)
- [node2](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_24_002/)
- [node3](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_24_003/)
- [node4](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_24_004/)
- [node5](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_24_005/)
- [node6](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_24_006/)
- [node7](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_24_007/)
- [node8](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_24_008/)
- [node9](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_24_009/)

**Comment by czepluch** [comment]
Similar to https://github.com/raiden-network/raiden/issues/5498#issuecomment-567385288 MS2 also failed with a REST API error, but none of the node logs has the FATAL error. 
Let me know if I instead should reopen the https://github.com/raiden-network/raiden/issues/5472 issue and put those that file like this one there.

- [Scenario log](http://68.183.70.168:8000/scenario-player/scenarios/ms2_simple_monitoring/scenario-player-run_ms2_simple_monitoring_2019-12-19T01%3A50%3A29.log)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/ms2_simple_monitoring/node_14_000/)
- [node1](http://68.183.70.168:8000/scenario-player/scenarios/ms2_simple_monitoring/node_14_001/)

**Comment by Dominik1999** [comment]
happened again 2 times tonight, see [bf1 node logs](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_49_003/)

``` 
--------- Starting ---------
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/client.py", line 300, in listen_forever
    self._sync(timeout_ms)
  File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/client.py", line 478, in _sync
    f"Time between syncs exceeded timeout:  "
raiden.exceptions.MatrixSyncMaxTimeoutReached: Time between syncs exceeded timeout:  22.342976808547974s > 22s.
2020-01-14T22:38:55Z <Greenlet "GMatrixClient._sync_worker user_id:@0x51a8708b8cb5261e564bf2c1bccead79933bee26:transport04.raiden.network" at 0x7fc598404598: <bound method GMatrixClient.listen_forever of <raiden.network.transport.matrix.client.GMatrixClient object at 0x7fc5974886d8>>(20000, None)> failed with MatrixSyncMaxTimeoutReached

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/transport.py", line 469, in _run
    self._broadcast_worker()
  File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/transport.py", line 644, in _broadcast_worker
    self._broadcast_event.wait(self._config.retry_interval)
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
raiden.exceptions.MatrixSyncMaxTimeoutReached: Time between syncs exceeded timeout:  22.342976808547974s > 22s.
2020-01-14T22:38:56Z <Greenlet "MatrixTransport._run node:0x51A8708b8cB5261e564bf2C1bCCeAD79933Bee26" at 0x7fc598404378: <bound method MatrixTransport._run of <MatrixTransport node:0x51A8708b8cB5261e564bf2C1bCCeAD79933Bee26 id:b9f029da-e69e-494e-9571-3a8000e43105>>> failed with MatrixSyncMaxTimeoutReached

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.7/site-packages/raiden/raiden_service.py", line 373, in _run
    self.stop_event.wait()
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
raiden.exceptions.MatrixSyncMaxTimeoutReached: Time between syncs exceeded timeout:  22.342976808547974s > 22s.
2020-01-14T22:38:56Z <Greenlet "RaidenService._run node:0x51A8708b8cB5261e564bf2C1bCCeAD79933Bee26" at 0x7fc5984046a8: <bound method RaidenService._run of <RaidenService node:0x51A8708b8cB5261e564bf2C1bCCeAD79933Bee26>>> failed with MatrixSyncMaxTimeoutReached

ReturnCode.FATAL
--------- Stopped ---------
```

**Comment by karlb** [comment]
This happened in two scenarios overnight. According to the idle timing, load has not been the problem:
```
bf4_multi_payments_same_node/node_505_005/run-505.log:
MatrixSyncMaxTimeoutReached('Time between syncs exceeded timeout:  36.908530473709106s > 35s. The thread had 26 context_switches, and idled 0.973104701048447% of the time.')
```
```
bf5_join_and_leave/node_505_002/run-505.log:
MatrixSyncMaxTimeoutReached('Time between syncs exceeded timeout:  55.85460376739502s > 35s. The thread had 44 context_switches, and idled 0.9939996189602991% of the time.')
```

**Comment by palango** [comment]
Logs for a recent local scenario failure:
```
{"timestamp":"2020-01-28 10:40:17.095096","event":"Sync called"}
{"timestamp":"2020-01-28 10:40:18.906135","event":"Matrix started"}
{"timestamp":"2020-01-28 10:40:18.906558","event":"Alarm task started"}
{"timestamp":"2020-01-28 10:40:18.906786","event":"Raiden Service started"}
{"timestamp":"2020-01-28 10:40:18.906993","event":"Raiden started"}
{"timestamp":"2020-01-28 10:40:18.924528","event":"REST API starting"}
{"timestamp":"2020-01-28 10:40:18.926470","event":"REST API started"}
{"timestamp":"2020-01-28 10:40:19.006730","event":"Request successful"}
{"timestamp":"2020-01-28 10:40:22.331114","event":"Idle"}
{"timestamp":"2020-01-28 10:40:23.962575","event":"Received new block"}
{"timestamp":"2020-01-28 10:40:23.963152","event":"Synchronizing blockchain events"}
{"timestamp":"2020-01-28 10:40:23.963457","event":"StatelessFilter: querying new entries"}
{"timestamp":"2020-01-28 10:40:24.001767","event":"StatelessFilter: fetched new entries"}
{"timestamp":"2020-01-28 10:40:24.043142","event":"State changes"}
{"timestamp":"2020-01-28 10:40:24.048644","event":"Copied state before applying state changes"}
{"timestamp":"2020-01-28 10:40:24.049122","event":"Raiden events"}
{"timestamp":"2020-01-28 10:40:24.049760","event":"Synchronized to a new confirmed block"}
{"timestamp":"2020-01-28 10:40:33.930954","event":"Idle"}
{"timestamp":"2020-01-28 10:40:39.148144","event":"Received new block"}
{"timestamp":"2020-01-2s 10:40:39.148406","event":"Synchronizing blockchain events"}
{"timestamp":"2020-01-28 10:40:39.148577","event":"StatelessFilter: querying new entries"}
{"timestamp":"2020-01-28 10:40:39.175494","event":"StatelessFilter: fetched new entries"}
{"timestamp":"2020-01-28 10:40:39.206188","event":"State changes"}
{"timestamp":"2020-01-28 10:40:39.209718","event":"Copied state before applying state changes"}
{"timestamp":"2020-01-28 10:40:39.210034","event":"Raiden events"}
{"timestamp":"2020-01-28 10:40:39.210324","event":"Synchronized to a new confirmed block"}
{"timestamp":"2020-01-28 10:40:43.937790","event":"Idle"}
{"timestamp":"2020-01-28 10:40:53.791819","event":"Sync returned"}
```

I find it quite surprising that we have multiple `Idle`s in there.

**Comment by palango** [comment]
Full logs for the above range:

[logs-during-sync.log](https://github.com/raiden-network/raiden/files/4122010/logs-during-sync.log)

**Comment by palango** [comment]
Completet logs incl. switch logs.

[Archive.zip](https://github.com/raiden-network/raiden/files/4128272/Archive.zip)

**Comment by hackaugusto** [comment]
the problem from the logs above will be fixed by this issue: https://github.com/raiden-network/raiden/issues/5774

**Comment by palango** [comment]
@Dominik1999 Can we close this now?
