### ISSUE TITLE
Exception in APIServer during shutdown

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#5507]
## Problem Definition

When the API is used (for example by the WebUI, polling for updates) while Raiden is shutting down the following exception can occur:
```
RuntimeError: The RaidenService must be started before the API can be used
```

The reason seems to be that the REST-API is still accepting requests while the RaidenService is already in the process of shutting down. 

Full traceback:
```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.7/site-packages/raiden/api/rest.py", line 441, in _run
    self.wsgiserver.serve_forever()
  File "/usr/local/lib/python3.7/site-packages/gevent/baseserver.py", line 364, in serve_forever
    self._stop_event.wait()
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
RuntimeError: The RaidenService must be started before the API can be used
2019-12-13T02:39:27Z <Greenlet "APIServer|Greenlet-3" at 0x7fa38168b9d8: <bound method APIServer._run of <raiden.api.rest.APIServer object at 0x7fa378b91f28>>> failed with RuntimeError

Traceback (most recent call last):
  File "/usr/local/bin/raiden", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/raiden/__main__.py", line 13, in main
    run(auto_envvar_prefix="RAIDEN")  # pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/raiden/ui/cli.py", line 606, in run
    app = runner.run()
  File "/usr/local/lib/python3.7/site-packages/raiden/ui/runners.py", line 260, in run
    return self._start_services()
  File "/usr/local/lib/python3.7/site-packages/raiden/ui/runners.py", line 251, in _start_services
    raise_error=True,
  File "src/gevent/greenlet.py", line 849, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 865, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "/usr/local/lib/python3.7/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.7/site-packages/raiden/api/rest.py", line 441, in _run
    self.wsgiserver.serve_forever()
  File "/usr/local/lib/python3.7/site-packages/gevent/baseserver.py", line 364, in serve_forever
    self._stop_event.wait()
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
RuntimeError: The RaidenService must be started before the API can be used
```

**Comment by hackaugusto** [comment]
duplicate https://github.com/raiden-network/raiden/issues/5505
