### ISSUE TITLE
Crash with 'Transaction with the same hash was already imported.'

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#5556]
In the BF1 scneario a node crashed with `ValueError: {'code': -32010, 'message': 'Transaction with the same hash was already imported.'}`
```
--------- Starting ---------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/raiden/network/rpc/smartcontract_proxy.py", line 123, in transact
    data=decode_hex(data),
  File "/usr/local/lib/python3.7/site-packages/raiden/network/rpc/client.py", line 405, in send_transaction
    tx_hash = self._client.web3.eth.sendRawTransaction(signed_txn.rawTransaction)
  File "/usr/local/lib/python3.7/site-packages/web3/eth.py", line 275, in sendRawTransaction
    [raw_transaction],
  File "/usr/local/lib/python3.7/site-packages/web3/manager.py", line 112, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32010, 'message': 'Transaction with the same hash was already imported.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.7/site-packages/raiden/api/rest.py", line 439, in _run
    self.wsgiserver.serve_forever()
  File "/usr/local/lib/python3.7/site-packages/gevent/baseserver.py", line 364, in serve_forever
    self._stop_event.wait()
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
raiden.exceptions.EthereumNonceTooLow: Transaction rejected because the nonce has been already mined.
2020-01-02T22:07:14Z <Greenlet "APIServer|Greenlet-3" at 0x7f380754f6a8: <bound method APIServer._run of <raiden.api.rest.APIServer object at 0x7f3804d1c898>>> failed with EthereumNonceTooLow
```

Logs are here: http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_35_002/

**Comment by palango** [comment]
Same happens in the SP: http://68.183.70.168:8000/scenario-player/scenarios/ms1_simple_monitoring/scenario-player-run_ms1_simple_monitoring_2020-01-02T22%3A30%3A29.log

**Comment by palango** [comment]
Maybe related: https://github.com/raiden-network/raiden/issues/3211

**Comment by Dominik1999** [comment]
- as a start, we could check the ethereum node logs for that time
- Could be a bug in geth or parity

**Comment by ulope** [comment]
Possibly related: #5561

**Comment by Dominik1999** [comment]
Which condition are we not handling and provide better error message

**Comment by Dominik1999** [comment]
Valid fix is the better error message
