### ISSUE TITLE
Runnable is missing 'loop' property

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#5582]
Seen during test shutdown:

```
Traceback (most recent call last):
  File "/Users/paul/Projects/brainbot/raiden/raiden/raiden_service.py", line 399, in _run
    self.stop_event.wait()
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
greenlet.GreenletExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/Users/paul/Projects/brainbot/raiden/raiden/raiden_service.py", line 402, in _run
    gevent.killall([self.alarm, self.transport])  # kill children
  File "src/gevent/greenlet.py", line 924, in gevent._greenlet.killall
AttributeError: 'AlarmTask' object has no attribute 'loop'
2020-01-07T11:14:53Z <Greenlet "RaidenService._run node:0x52974f194B167F7A25Fd89320E1E159011797e8A" at 0x112c2c830: <bound method RaidenService._run of <RaidenService node:0x52974f194B167F7A25Fd89320E1E159011797e8A>>> failed with AttributeError
```

Alternative solution is by fixing https://github.com/raiden-network/raiden/issues/5601

**Comment by Dominik2002** [comment]
Discuss with @hackaugusto whether to remove the runnable

**Comment by Dominik1999** [comment]
Runnable is being removed
