### ISSUE TITLE
M_TOO_LARGE / event too large

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#5609]
When trying to run the stress test, I reproducibly get
```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/karl/raiden/raiden/network/transport/matrix/transport.py", line 265, in _run
    self._check_and_send()
  File "/home/karl/raiden/raiden/network/transport/matrix/transport.py", line 249, in _check_and_send
    self.transport._send_raw(self.receiver, "\n".join(message_texts))
  File "/home/karl/raiden/raiden/network/transport/matrix/transport.py", line 941, in _send_raw
    room.send_text(data)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/matrix_client/room.py", line 105, in send_text
    return self.client.api.send_message(self.room_id, text)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/matrix_client/api.py", line 336, in send_message
    timestamp=timestamp
  File "/home/karl/tools/venv/lib/python3.7/site-packages/matrix_client/api.py", line 256, in send_message_event
    return self._send("PUT", path, content, query_params=params)
  File "/home/karl/raiden/raiden/network/transport/matrix/client.py", line 178, in _send
    return super()._send(method, path, *args, **kwargs)
  File "/home/karl/tools/venv/lib/python3.7/site-packages/matrix_client/api.py", line 691, in _send
    code=response.status_code, content=response.text
matrix_client.errors.MatrixRequestError: 413: {"errcode":"M_TOO_LARGE","error":"event too large"}
```

The message it's trying to send is [failed_send.txt](https://github.com/raiden-network/raiden/files/4039789/failed_send.txt)

Are we just missing handling for large batches, or is there something else going wrong? @ulope @andrevmatos

**Comment by ulope** [comment]
Yes, see #3512

**Comment by karlb** [comment]
Thanks for the quick answer! Duplicate of #3512.
