### ISSUE TITLE
BF5 RaidenUnrecoverableError Exception due to BadFunctionCallOutput

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5625]
Scenario in a nutshell:

node0: `0xEE48A28309120329F0db3c6eed0fA6540a4f87f1`
node1: `0x975002Ae52D109De1E313B9f072f1Fa03755D974`
node2: `0xb1b5325E611848c927E09011BB737DF9B9a62f96`
node3: `0x5eC6d224cE559489eB38974bb7F55c5eFf7cB0fF`

node0 stderr gives the exception

```
--------- Starting ---------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/web3/contract.py", line 1372, in call_contract_function
    output_data = decode_abi(output_types, return_data)
  File "/usr/local/lib/python3.7/site-packages/eth_abi/abi.py", line 96, in decode_abi
    return decoder(stream)
  File "/usr/local/lib/python3.7/site-packages/eth_abi/decoding.py", line 118, in __call__
    return self.decode(stream)
  File "/usr/local/lib/python3.7/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/usr/local/lib/python3.7/site-packages/eth_abi/decoding.py", line 164, in decode
    yield decoder(stream)
  File "/usr/local/lib/python3.7/site-packages/eth_abi/decoding.py", line 118, in __call__
    return self.decode(stream)
  File "/usr/local/lib/python3.7/site-packages/eth_abi/decoding.py", line 186, in decode
    raw_data = self.read_data_from_stream(stream)
  File "/usr/local/lib/python3.7/site-packages/eth_abi/decoding.py", line 296, in read_data_from_stream
    len(data),
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/raiden/network/proxies/token_network_registry.py", line 124, in add_token
    token_supply = token_proxy.total_supply(block_identifier=block_identifier)
  File "/usr/local/lib/python3.7/site-packages/raiden/network/proxies/token.py", line 169, in total_supply
    self.proxy.contract.functions.totalSupply().call(block_identifier=block_identifier)
  File "/usr/local/lib/python3.7/site-packages/web3/contract.py", line 1115, in call
    **self.kwargs
  File "/usr/local/lib/python3.7/site-packages/web3/contract.py", line 1394, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not decode contract function call totalSupply return data b'' for output_types ['uint256']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.7/site-packages/raiden/api/rest.py", line 439, in _run
    self.wsgiserver.serve_forever()
  File "/usr/local/lib/python3.7/site-packages/gevent/baseserver.py", line 364, in serve_forever
    self._stop_event.wait()
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
raiden.exceptions.RaidenUnrecoverableError: Either the given address is for a different smart contract, or the contract was not yet deployed at the block 0x836537d818c686bcfa524102a8c1a1225197615984f676e32d6d413f100df87a. Either way this call should never happened.
2020-01-09T23:03:13Z <Greenlet "APIServer|Greenlet-3" at 0x7fa920da38c8: <bound method APIServer._run of <raiden.api.rest.APIServer object at 0x7fa91ba17c50>>> failed with RaidenUnrecoverableError

ReturnCode.FATAL
--------- Stopped ---------
```

**eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes**

The above exception was the direct cause of the following exception:

**web3.exceptions.BadFunctionCallOutput: Could not decode contract function call totalSupply return data b'' for output_types ['uint256']**

which results in the RaidenUnrecoverableError

**raiden.exceptions.RaidenUnrecoverableError: Either the given address is for a different smart contract, or the contract was not yet deployed at the block 0x836537d818c686bcfa524102a8c1a1225197615984f676e32d6d413f100df87a. Either way this call should never happened.**

https://drive.google.com/drive/folders/1MdROjSbLLifDGI_oiuVdFEN_N1eDxWAs?usp=sharing

**Comment by Dominik1999** [comment]
- Talk with @ulope and coordinate how to fix
- check address has code should use confirmed block 
- increase confirmed blocks in SP and validation in RestAPI
