### ISSUE TITLE
Failure with MatrixSyncMaxTimeoutReached, Time between syncs exceeded timeout:  22.628389358520508s > 22s

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#5685]
## Problem Definition

BF4 scenario logs
```
{
  "event": "Node error",
  "logger": "scenario_player.node_support",
  "level": "error",
  "timestamp": "2020-01-16 22:43:06.018173",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/node_support.py\", line 277, in check\n    self.executor.check_subprocess()\n  File \"/usr/local/lib/python3.7/site-packages/mirakuru/base.py\", line 449, in check_subprocess\n    raise ProcessExitedWithError(self, exit_code)\nmirakuru.exceptions.ProcessExitedWithError: The process invoked by the <scenario_player.utils.legacy.HTTPExecutor: \"/usr/local/bin/raiden --accept-disclaimer --datadir /data/scenarios/bf4_multi_payments_same_node/node_3_004 --keystore-path /data/scenarios/bf4_multi_payments_same_node/node_3_004/keys --address 0x5fB5D5E0245d49620e253E551c65B2d23A1D7AFC --password-file /data/scenarios/bf4_multi_payments_same_node/node_3_004/password.txt --network-id 5 --sync-check --gas-price fast --eth-rpc-endpoint http://parity.goerli.ethnodes.brainbot.com:8545 --log-config :info,raiden:debug,raiden_contracts:debug,raiden.api.rest.pywsgi:warning --log-json --log-file /data/scenarios/bf4_multi_payments_same_node/node_3_004/run-003.log --disable-debug-logfile --matrix-server auto --api-address 127.0.0.1:42971 --no-web-ui --pathfinding-service-address https://pfs-goerli-with-fee.services-dev.raiden.network --gas-price fast --routing-mode pfs --pathfinding-max-fee 100 --default-reveal-timeout 20 --pathfinding-max-paths 5 --enable-monitoring --proportional-imbalance-fee 0x62083c80353Df771426D209eF578619EE68D5C7A 0 --default-settle-timeout 40 --environment-type development --proportional-fee 0x62083c80353Df771426D209eF578619EE68D5C7A 0\"> executor has exited with a non-zero code: -9.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/node_support.py\", line 281, in check\n    ) from ex\nscenario_player.exceptions.legacy.ScenarioError: Raiden node 4 died with non-zero exit status: -9"
}
```

Raiden Node 4 run-003.stdout

**Time between syncs exceeded timeout:  22.628389358520508s > 22s.**

```
--------- Starting ---------
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/client.py", line 301, in listen_forever
    self._sync(timeout_ms)
  File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/client.py", line 479, in _sync
    f"Time between syncs exceeded timeout:  "
raiden.exceptions.MatrixSyncMaxTimeoutReached: Time between syncs exceeded timeout:  22.628389358520508s > 22s.
2020-01-16T22:43:02Z <Greenlet "GMatrixClient._sync_worker user_id:@0x5fb5d5e0245d49620e253e551c65b2d23a1d7afc:transport04.raiden.network" at 0x7fbe75aa96a8: <bound method GMatrixClient.listen_forever of <raiden.network.transport.matrix.client.GMatrixClient object at 0x7fbe742a1e80>>(20000, None)> failed with MatrixSyncMaxTimeoutReached

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/transport.py", line 468, in _run
    self._broadcast_worker()
  File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/transport.py", line 643, in _broadcast_worker
    self._broadcast_event.wait(self._config.retry_interval)
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
raiden.exceptions.MatrixSyncMaxTimeoutReached: Time between syncs exceeded timeout:  22.628389358520508s > 22s.
2020-01-16T22:43:02Z <Greenlet "MatrixTransport._run node:0x5fB5D5E0245d49620e253E551c65B2d23A1D7AFC" at 0x7fbe75aa9488: <bound method MatrixTransport._run of <MatrixTransport node:0x5fB5D5E0245d49620e253E551c65B2d23A1D7AFC id:3a638b90-046e-40ae-8a83-2eb7d20264df>>> failed with MatrixSyncMaxTimeoutReached

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.7/site-packages/raiden/raiden_service.py", line 374, in _run
    self.stop_event.wait()
  File "src/gevent/event.py", line 240, in gevent._event.Event.wait
  File "src/gevent/event.py", line 140, in gevent._event._AbstractLinkable._wait
  File "src/gevent/event.py", line 117, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/event.py", line 119, in gevent._event._AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
raiden.exceptions.MatrixSyncMaxTimeoutReached: Time between syncs exceeded timeout:  22.628389358520508s > 22s.
2020-01-16T22:43:02Z <Greenlet "RaidenService._run node:0x5fB5D5E0245d49620e253E551c65B2d23A1D7AFC" at 0x7fbe75aa97b8: <bound method RaidenService._run of <RaidenService node:0x5fB5D5E0245d49620e253E551c65B2d23A1D7AFC>>> failed with MatrixSyncMaxTimeoutReached

ReturnCode.FATAL
--------- Stopped ---------
```

raiden.exceptions.MatrixSyncMaxTimeoutReached: Time between syncs exceeded timeout:  22.628389358520508s > 22s.
2020-01-16T22:43:02Z <Greenlet "RaidenService._run node:0x5fB5D5E0245d49620e253E551c65B2d23A1D7AFC" at 0x7fbe75aa97b8: <bound method RaidenService._run of <RaidenService node:0x5fB5D5E0245d49620e253E551c65B2d23A1D7AFC>>> failed with **MatrixSyncMaxTimeoutReached**

Logs
http://68.183.70.168:8000/scenario-player/scenarios/bf4_multi_payments_same_node/
Individual node logs could be downloaded quickly like this (Please install `lftp`)

```
mkdir node_3_004 && cd node_3_004 && lftp -c "open http://68.183.70.168:8000/scenario-player/scenarios/bf4_multi_payments_same_node/node_3_004/; mirror" && cd ..
```

**Comment by agatsoh** [comment]
Same exception occurs in BF2 logs can be downloaded from 
http://139.59.211.171:8000/scenario-player/scenarios/bf2_long_running/
Download individual logs 
```
mkdir node_49_002 && cd node_49_002 && lftp -c "open http://139.59.211.171:8000/scenario-player/scenarios/bf2_long_running/node_49_002/; mirror" && cd ..
```

**Comment by agatsoh** [comment]
BF5 also fails with same exception, logs can  be downloaded here
http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/
Individual node logs can be downloaded like this 
```
mkdir node_3_003 && cd node_3_003 && lftp -c "open http://68.183.70.168:8000/scenario-player/scenarios/bf5_join_and_leave/node_3_003/; mirror" && cd ..
```

**Comment by agatsoh** [comment]
Most of all the scenarios have got the same error

**Comment by Dominik1999** [comment]
tracked in #5498
