### ISSUE TITLE
Raiden binary docker build: pyinstaller error

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/raiden#5849]
## Problem Definition

When trying to build the raiden binary with `make bundle-docker` pyinstaller returns the following error: 
```
Step 20/21 : RUN pyinstaller --noconfirm --clean raiden.spec
 ---> Running in 58623f33e4a9
42 INFO: PyInstaller: 3.6
42 INFO: Python: 3.7.5
42 INFO: Platform: Linux-5.3.0-28-generic-x86_64-with-debian-9.11
44 INFO: UPX is not available.
44 INFO: Removing temporary files and cleaning cache in /root/.cache/pyinstaller
1354 INFO: Extending PYTHONPATH with paths
['/raiden/build/raiden', '/venv/lib/python3.7/site-packages']
1354 INFO: checking Analysis
1354 INFO: Building Analysis because Analysis-00.toc is non existent
1354 INFO: Initializing module dependency graph...
1356 INFO: Caching module graph hooks...
creating script for entry point raiden console_scripts raiden
Traceback (most recent call last):
  File "/venv/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/venv/lib/python3.7/site-packages/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/venv/lib/python3.7/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/venv/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/venv/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 681, in build
    exec(code, spec_namespace)
  File "raiden.spec", line 92, in <module>
    excludes=['FixTk', 'tcl', 'tk', '_tkinter', 'tkinter', 'Tkinter'],
  File "raiden.spec", line 60, in Entrypoint
    datas=datas
  File "/venv/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 244, in __init__
    self.__postinit__()
  File "/venv/lib/python3.7/site-packages/PyInstaller/building/datastruct.py", line 160, in __postinit__
    self.assemble()
  File "/venv/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 343, in assemble
    excludes=self.excludes, user_hook_dirs=self.hookspath)
  File "/venv/lib/python3.7/site-packages/PyInstaller/depend/analysis.py", line 734, in initialize_modgraph
    user_hook_dirs=user_hook_dirs,
  File "/venv/lib/python3.7/site-packages/PyInstaller/depend/analysis.py", line 116, in __init__
    self._reset(user_hook_dirs)
  File "/venv/lib/python3.7/site-packages/PyInstaller/depend/analysis.py", line 134, in _reset
    self._hooks = self._cache_hooks("")
  File "/venv/lib/python3.7/site-packages/PyInstaller/depend/analysis.py", line 215, in _cache_hooks
    return ModuleHookCache(self, hook_dirs)
  File "/venv/lib/python3.7/site-packages/PyInstaller/depend/imphook.py", line 100, in __init__
    self._cache_hook_dirs(hook_dirs)
  File "/venv/lib/python3.7/site-packages/PyInstaller/depend/imphook.py", line 133, in _cache_hook_dirs
    hook_module_name_prefix=self._hook_module_name_prefix,
  File "/venv/lib/python3.7/site-packages/PyInstaller/depend/imphook.py", line 289, in __init__
    assert self.hook_module_name not in HOOKS_MODULE_NAMES
AssertionError
The command '/bin/sh -c pyinstaller --noconfirm --clean raiden.spec' returned a non-zero code: 1
Makefile:118: recipe for target 'bundle-docker' failed
make: *** [bundle-docker] Error 1
```

**Comment by palango** [comment]
Fixed with https://github.com/raiden-network/raiden/pull/5873
