### ISSUE TITLE
source distribution on PyPI is broken

### ISSUE THREAD

**Issue by schmir-at-bb** [raiden-network/raiden#5852]
The source distribution's setup.py tries to access non-existent files. Installation is not possible from the source distribution:
```
% pip install --no-binary raiden raiden
Collecting raiden
  Downloading https://files.pythonhosted.org/packages/b2/ce/d24e17df04767c6dc8106a9d8afc57757522b40cbc001e3b55d0aae51515/raiden-0.100.4.tar.gz (470kB)
     |████████████████████████████████| 471kB 2.0MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_zekxx1d/raiden/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_zekxx1d/raiden/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-_zekxx1d/raiden/pip-egg-info
         cwd: /tmp/pip-install-_zekxx1d/raiden/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_zekxx1d/raiden/setup.py", line 46, in <module>
        with open("requirements/requirements.txt") as req_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements/requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by ulope** [comment]
`MANIFEST.in` is referencing the wrong path for `requirements.txt`.

Thanks for the report @schmir

**Comment by Dominik1999** [comment]
That one? https://github.com/raiden-network/raiden/blob/develop/MANIFEST.in
