### ISSUE TITLE
Raiden crashes when I attempt to send money to myself

### ISSUE THREAD

**Issue by eorituz** [raiden-network/raiden#5922]
## Issue checklist

To help us more easily debug your issue please check the boxes for which requirements for safe usage or Raiden were followed:

- [x] The Ethereum node was always up to date with the chain tip and never stopped running.
- [x] No Ethereum transaction was sent for the account that Raiden manages by another app.
- [x] The Ethereum account used by Raiden always had sufficient ETH.
- [x] The Raiden DB that exists by default at ~/.raiden was never altered or deleted.
- [x] The Raiden node was never restarted. If yes please provide more info.
- [x] The ethereum node was not switched while Raiden was running.
- [x] The Raiden REST API is protected from public access.

-->

## Problem Definition
I got confused with addresses and attempted to send money to myself. (From 0xABCD --> 0xABCD) via the API. (The WebUI tells me that I cannot send funds to myself)

Raiden Crashed with 
```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "site-packages/raiden/network/transport/matrix/transport.py", line 629, in _health_check_worker
  File "site-packages/raiden/network/transport/matrix/transport.py", line 606, in immediate_health_check_for
  File "site-packages/raiden/network/transport/matrix/transport.py", line 577, in whitelist
  File "site-packages/raiden/network/transport/matrix/transport.py", line 1194, in _maybe_create_room_for_address
  File "site-packages/raiden/network/transport/matrix/utils.py", line 876, in my_place_or_yours
ValueError: Addresses to compare must differ
2020-02-19T14:55:13Z <Greenlet "Greenlet<fn:_health_check_worker>" at 0x7f1f5e02a050: <bound method MatrixTransport._health_check_worker of <MatrixTransport node:0x812f85143bdF6d28228FC580Ef649AA95ba6Fcd9 id:585de50e-f064-4a93-b3f4-df2bf40f8078>>> failed with ValueError

2020-02-19 14:55:13.088967 [error    ] Runnable subtask died!         [raiden.utils.runnable] exc=ValueError('Addresses to compare must differ') running=True subtask=<Greenlet "Greenlet<fn:_health_check_worker>" at 0x7f1f5e02a050: <bound method MatrixTransport._health_check_worker of <MatrixTransport node:0x812f85143bdF6d28228FC580Ef649AA95ba6Fcd9 id:585de50e-f064-4a93-b3f4-df2bf40f8078>>> this=<MatrixTransport node:0x812f85143bdF6d28228FC580Ef649AA95ba6Fcd9 id:585de50e-f064-4a93-b3f4-df2bf40f8078>
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "site-packages/raiden/network/transport/matrix/transport.py", line 496, in _run
  File "site-packages/raiden/network/transport/matrix/transport.py", line 718, in _broadcast_worker
  File "src/gevent/event.py", line 133, in gevent._event.Event.wait
  File "src/gevent/_abstract_linkable.py", line 208, in gevent.__abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 178, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 196, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 182, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
ValueError: Addresses to compare must differ
2020-02-19T14:55:13Z <Greenlet "MatrixTransport._run node:0x812f85143bdF6d28228FC580Ef649AA95ba6Fcd9" at 0x7f1f5f9a3a70: _run> failed with ValueError

2020-02-19 14:55:13.259801 [error    ] Runnable subtask died!         [raiden.utils.runnable] exc=ValueError('Addresses to compare must differ') running=True subtask=<Greenlet "MatrixTransport._run node:0x812f85143bdF6d28228FC580Ef649AA95ba6Fcd9" at 0x7f1f5f9a3a70: _run> this=<RaidenService node:0x812f85143bdF6d28228FC580Ef649AA95ba6Fcd9>
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "site-packages/raiden/raiden_service.py", line 375, in _run
  File "src/gevent/event.py", line 133, in gevent._event.Event.wait
  File "src/gevent/_abstract_linkable.py", line 208, in gevent.__abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 178, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 196, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 182, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
ValueError: Addresses to compare must differ
2020-02-19T14:55:13Z <Greenlet "RaidenService._run node:0x812f85143bdF6d28228FC580Ef649AA95ba6Fcd9" at 0x7f1f5f625b90: _run> failed with ValueError

FATAL: An unexpected exception occured. A traceback has been written to /tmp/raiden-exception-2020-02-19T14-5542cjz658.txt
Addresses to compare must differ
ReturnCode.FATAL
```

## Expectation
I would expect raiden to NOT crash and return that request with an "error" message, that I'm not allowed to send funds to myself.

**Comment by ulope** [comment]
I don’t think this is a transport issue. The fact that we’re trying to send to ourselves should be caught at a higher layer.
