### ISSUE TITLE
BF5: "The receipt `gasUsed` reported in the receipt is higher than the transaction startgas!"

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6001]
In bf5, the following error happens when a node tries to leave the network:

```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "/home/karl/raiden/raiden/raiden_service.py", line 899, in _handle_events
    raiden=self, chain_state=chain_state, events=raiden_events
  File "/home/karl/raiden/raiden/raiden_event_handler.py", line 782, in on_raiden_events
    self.wrapped.on_raiden_events(raiden, chain_state, events)
  File "/home/karl/raiden/raiden/raiden_event_handler.py", line 188, in on_raiden_events
    self.handle_contract_send_channelclose(raiden, chain_state, event)
  File "/home/karl/raiden/raiden/raiden_event_handler.py", line 462, in handle_contract_send_channelclose
    block_identifier=channel_close_event.triggered_by_block_hash,
  File "/home/karl/raiden/raiden/network/proxies/payment_channel.py", line 178, in close
    given_block_identifier=block_identifier,
  File "/home/karl/raiden/raiden/network/proxies/token_network.py", line 1602, in close
    log_details=log_details,
  File "/home/karl/raiden/raiden/network/proxies/token_network.py", line 1658, in _close
    check_transaction_gas_used(transaction_mined)
  File "/home/karl/raiden/raiden/network/proxies/utils.py", line 176, in check_transaction_gas_used
    raise RaidenUnrecoverableError(msg)
raiden.exceptions.RaidenUnrecoverableError: The receipt `gasUsed` reported in the receipt is higher than the transaction startgas!.`closeChannel` failed and all gas was used (28173). This can happen for a few reasons: 1. The smart contract code may have an assert inside an if statement, at the time of gas estimation the condition was false, but another transaction changed the state of the smart contrat making the condition true. 2. The call to `closeChannel` executes an opcode with variable gas, at the time of gas estimation the cost was low, but another transaction changed the environment so that the new cost is high. This is particularly problematic storage is set to `0`, since the cost of a `SSTORE` increases 4 times. 3. The cost of the function varies with external state, if the cost increases because of another transaction the transaction can fail.
2020-03-19T14:00:09Z <Greenlet "rs-handle_events" at 0x7f90c7a02048: <bound method RaidenService._handle_events of <RaidenService node:0xE25B2e300869C9eF849EE3Aed21C23051EBc6A90>>(ChainState(block_number=2372969 block_hash=0xa9634, [ContractSendChannelClose(triggered_by_block_hash=)> failed with RaidenUnrecoverableError
```

**Comment by palango** [comment]
This is also weird as the current estimate in the contracts is **117733**:
https://github.com/raiden-network/raiden-contracts/blob/b1772dbbcaed160df6f4baa52e713f95d2fd147e/raiden_contracts/data/gas.json#L15

**Comment by Dominik1999** [comment]
We have no logs and cannot reproduce

**Comment by karlb** [comment]
I haven’t been able to reproduce it on the current develop. I’ve run it 4 times so far. I’ll post the logs when I get it again. If I can't reproduce it at least once today, I'll assume this is resolved on develop and close the issue.

**Comment by karlb** [comment]
Could not be reproduced on develop branch. If you see this, please reopen!
