### ISSUE TITLE
Raiden node 0.200.0-rc3 gets EthereumNonceTooLow

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#6036]
## Problem Definition
The raiden node suddenly gets EthereumNonceTooLow

The action performed on the webui immediately preceding this error was `withdraw`. 
I performed minting also through the webui but almost 2 to 3 hours back.
Also minted the service token that too a long time back.
Node address `0xAa1Ab1fDA93e14c2d564B25Ba08c9d374F5F9541`
```
Traceback (most recent call last):
  File "raiden/network/rpc/client.py", line 1161, in transact
    tx_hash = client.web3.eth.sendRawTransaction(signed_txn.rawTransaction)
  File "web3/eth.py", line 392, in sendRawTransaction
  File "web3/manager.py", line 153, in request_blocking
ValueError: {'code': -32000, 'message': 'nonce too low'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "raiden/raiden_service.py", line 889, in _handle_events
    raiden=self, chain_state=chain_state, events=raiden_events
  File "raiden/raiden_event_handler.py", line 783, in on_raiden_events
    self.wrapped.on_raiden_events(raiden, chain_state, events)
  File "raiden/raiden_event_handler.py", line 201, in on_raiden_events
    self.handle_contract_send_channelwithdraw(raiden, event)
  File "raiden/raiden_event_handler.py", line 409, in handle_contract_send_channelwithdraw
    block_identifier=channel_withdraw_event.triggered_by_block_hash,
  File "raiden/network/proxies/payment_channel.py", line 157, in set_total_withdraw
    partner=self.participant2,
  File "raiden/network/proxies/token_network.py", line 1323, in set_total_withdraw
    log_details=log_details,
  File "raiden/network/proxies/token_network.py", line 1356, in _set_total_withdraw
    transaction_sent = self.client.transact(estimated_transaction)
  File "raiden/network/rpc/client.py", line 1209, in transact
    raise EthereumNonceTooLow(reason)
raiden.exceptions.EthereumNonceTooLow: Transaction rejected because the nonce has been already mined.
2020-03-31T12:26:52Z <Greenlet "rs-handle_events" at 0x7f994f9365f0: <bound method RaidenService._handle_events of <RaidenService node:0xAa1Ab1fDA93e14c2d564B25Ba08c9d374F5F9541>>(ChainState(block_number=2441715 block_hash=0x6b469, [ContractSendChannelWithdraw< canonical_identifier)> failed with EthereumNonceTooLow

Traceback (most recent call last):
  File "raiden/network/rpc/client.py", line 1161, in transact
    tx_hash = client.web3.eth.sendRawTransaction(signed_txn.rawTransaction)
  File "web3/eth.py", line 392, in sendRawTransaction
  File "web3/manager.py", line 153, in request_blocking
ValueError: {'code': -32000, 'message': 'nonce too low'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "raiden/raiden_service.py", line 394, in _run
    self.stop_event.wait()
  File "src/gevent/event.py", line 133, in gevent._event.Event.wait
  File "src/gevent/_abstract_linkable.py", line 208, in gevent.__abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 178, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 196, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 182, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
raiden.exceptions.EthereumNonceTooLow: Transaction rejected because the nonce has been already mined.
2020-03-31T12:26:54Z <Greenlet "RaidenService._run node:0xAa1Ab1fDA93e14c2d564B25Ba08c9d374F5F9541" at 0x7f9954cb3ef0: _run> failed with EthereumNonceTooLow

Transaction rejected because the nonce has been already mined.. Please make sure that this Raiden node is the only user of the selected account
ReturnCode.ETH_ACCOUNT_ERROR

```
[node-bc8dBE-mainnet.6Sep2019.log](https://github.com/raiden-network/raiden/files/4409359/node-bc8dBE-mainnet.6Sep2019.log)

[node_aa1ab1fd_31stmarch_noncelow.tar.gz](https://github.com/raiden-network/raiden/files/4409382/node_aa1ab1fd_31stmarch_noncelow.tar.gz)

**Comment by karlb** [comment]
The wallet might have been used outside of Raiden. Closing until this is seen again.
