### ISSUE TITLE
0.200.0rc5: Interrupted network connection causes JSONDecodeError

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#6060]
## Problem Definition

All my 0.200.0rc5 mainnet test nodes crashed with a `JSONDecodeError` sometime this night.
It seems that my VPN (or entire internet) connection briefly dropped out at that time. 

Therefore I'd guess this is "just" a cosmetic problem.

Traceback:
```
Traceback (most recent call last):
  File "web3/_utils/encoding.py", line 217, in json_decode
  File "json/__init__.py", line 348, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "raiden/tasks.py", line 169, in _run
  File "raiden/tasks.py", line 194, in loop_until_stop
  File "raiden/network/rpc/client.py", line 913, in get_block
  File "web3/eth.py", line 217, in getBlock
  File "web3/manager.py", line 149, in request_blocking
  File "web3/manager.py", line 128, in _make_request
  File "web3/middleware/cache.py", line 134, in middleware
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3/middleware/formatting.py", line 75, in apply_formatters
  File "web3/middleware/gas_price_strategy.py", line 34, in middleware
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3/middleware/formatting.py", line 75, in apply_formatters
  File "web3/middleware/attrdict.py", line 33, in middleware
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3/middleware/formatting.py", line 73, in apply_formatters
  File "web3/middleware/normalize_errors.py", line 25, in middleware
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3/middleware/formatting.py", line 75, in apply_formatters
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3/middleware/formatting.py", line 75, in apply_formatters
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3/middleware/formatting.py", line 75, in apply_formatters
  File "web3/middleware/exception_retry_request.py", line 104, in middleware
  File "web3/providers/rpc.py", line 85, in make_request
  File "web3/providers/base.py", line 89, in decode_rpc_response
  File "web3/_utils/encoding.py", line 223, in json_decode
json.decoder.JSONDecodeError: Could not decode '' because of Expecting value: line 1 column 1 (char 0).: line 1 column 1 (char 0)
2020-04-09T19:09:22Z <Greenlet "AlarmTask._run node:0xF573C35c75aB5896CE8E081d68b8626f9233bC4c" at 0x10926b598: <bound method AlarmTask._run of <AlarmTask node:0xF573C35c75aB5896CE8E081d68b8626f9233bC4c>>> failed with JSONDecodeError

2020-04-09 19:09:22.455169 [error    ] Runnable subtask died!         [raiden.utils.runnable] exc=JSONDecodeError("Could not decode '' because of Expecting value: line 1 column 1 (char 0).: line 1 column 1 (char 0)") running=True subtask=<Greenlet "AlarmTask._run node:0xF573C35c75aB5896CE8E081d68b8626f9233bC4c" at 0x10926b598: <bound method AlarmTask._run of <AlarmTask node:0xF573C35c75aB5896CE8E081d68b8626f9233bC4c>>> this=<RaidenService node:0xF573C35c75aB5896CE8E081d68b8626f9233bC4c>
Traceback (most recent call last):
  File "web3/_utils/encoding.py", line 217, in json_decode
  File "json/__init__.py", line 348, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "raiden/raiden_service.py", line 394, in _run
  File "src/gevent/event.py", line 133, in gevent._event.Event.wait
  File "src/gevent/_abstract_linkable.py", line 208, in gevent.__abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 178, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 196, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 182, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
json.decoder.JSONDecodeError: Could not decode '' because of Expecting value: line 1 column 1 (char 0).: line 1 column 1 (char 0)
2020-04-09T19:09:23Z <Greenlet "RaidenService._run node:0xF573C35c75aB5896CE8E081d68b8626f9233bC4c" at 0x10926b488: _run> failed with JSONDecodeError

FATAL: An unexpected exception occurred. A traceback has been written to /var/folders/j9/c57mj6sd41bfx1c9m4bqj46r0000gn/T/raiden-exception-2020-04-09T19-098ecrirz5.txt
Could not decode '' because of Expecting value: line 1 column 1 (char 0).: line 1 column 1 (char 0)
ReturnCode.FATAL
```

[Entire log for completenes' sake](https://ds.ulo.pe/rY7HBsQA85.log)

**Comment by konradkonrad** [comment]
There must have been some glitch in the matrix(?)
```
{"this": "<RaidenService node:0x298e4ac53B44fA951e043bc674ed26528B6F8Dd0>", "running": true, "subtask": "<Greenlet \"AlarmTask._run node:0x298e4ac53B44fA951e043bc674ed26528B6F8Dd0\" at 0x7f5bfaf08cb0: <bound method AlarmTask._run of <AlarmTask node:0x298e4ac53B44fA951e043bc674ed26528B6F8Dd0>>>", "exc": "JSONDecodeError(\"Could not decode '' because of Expecting value: line 1 column 1 (char 0).: line 1 column 1 (char 0)\")", "event": "Runnable subtask died!", "logger": "raiden.utils.runnable", "level": "error", "timestamp": "2020-04-09 19:09:20.597981"}
```
