### ISSUE TITLE
Bug in node already running for address message

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#6079]
## Problem Definition

I updated to RC7 from RC5 and with 2 out of the 3 nodes that I've been using for testing on RC5 started with no problem. For one of them I did however start it with a wrong `--api-address`. I accidentally used `localhost:5001`, but this was already in use by another node. When I then again tried to start it up with a unused port I got the below error. I don't know if the things are related, but this is the only thing that was done differently for this node compared to those that work.

```
Traceback (most recent call last):
  File "raiden/ui/cli.py", line 610, in run
  File "raiden/ui/runners.py", line 21, in run_services
  File "raiden/ui/app.py", line 438, in run_app
  File "raiden/app.py", line 91, in start
  File "raiden/raiden_service.py", line 363, in start
  File "raiden/raiden_service.py", line 499, in _initialize_wal
  File "filelock.py", line 278, in acquire
filelock.Timeout: The file lock '/home/jacob/.raiden/node_f8f85702/netid_1/network_2f88f826/.lock' could not be acquired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "raiden-script.py", line 2, in <module>
  File "raiden/__main__.py", line 13, in main
  File "click/core.py", line 764, in __call__
  File "click/core.py", line 717, in main
  File "click/core.py", line 1114, in invoke
  File "click/core.py", line 956, in invoke
  File "click/core.py", line 555, in invoke
  File "click/decorators.py", line 17, in new_func
  File "raiden/ui/cli.py", line 644, in run
  File "raiden/utils/formatting.py", line 54, in to_checksum_address
AttributeError: 'NoneType' object has no attribute 'hex'
[21514] Failed to execute script raiden-script
```

Logs: 
[raiden-debug_2020-04-16T12:25:34.988405.log](https://github.com/raiden-network/raiden/files/4487023/raiden-debug_2020-04-16T12.25.34.988405.log)

**Comment by czepluch** [comment]
Forget about this issue. This was an error on my side. I was providing the same address for two nodes.

**Comment by ulope** [comment]
This is still a problem. A proper message should be printed telling you about this problem. But it looks like there's a bug in that code
