### ISSUE TITLE
`Token.transfer` does not cleanly handle error case

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6082]
I saw the following error in the SP, but it looks like a bug in the Token proxy:
```python
Traceback (most recent call last):                                                                                                                                                           
  File "/home/karl/scenario-player/scenario_player/main.py", line 315, in run_                                                                                                               
    environment=environment,                                                                                                                                                                 
  File "/home/karl/scenario-player/scenario_player/main.py", line 390, in orchestrate                                                                                                        
    scenario_runner.run_scenario()                                                                                                                                                           
  File "/home/karl/scenario-player/scenario_player/runner.py", line 386, in run_scenario
    gevent.joinall(greenlets, raise_error=True, count=1)                                                                                                                                     
  File "src/gevent/greenlet.py", line 1002, in gevent._greenlet.joinall                                                                                                                      
  File "src/gevent/greenlet.py", line 1018, in gevent._greenlet.joinall                                                                                                                      
  File "src/gevent/greenlet.py", line 364, in gevent._greenlet.Greenlet._raise_exception                                                                                                     
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/gevent/_compat.py", line 62, in reraise                                                                                  
    raise value.with_traceback(tb)                                                                                                                                                           
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run                                                                                                                  
  File "/home/karl/scenario-player/scenario_player/runner.py", line 477, in setup_environment_and_run_main_task                                                                              
    pool.join(raise_error=True)                                                                                                                                                              
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/gevent/pool.py", line 435, in join                                                                                       
    greenlet._raise_exception()                                                                                                                                                              
  File "src/gevent/greenlet.py", line 364, in gevent._greenlet.Greenlet._raise_exception                                                                                                     
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/gevent/_compat.py", line 62, in reraise                                                                                  
    raise value.with_traceback(tb)                                                                                                                                                           
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run                                                                                                                  
  File "/home/karl/scenario-player/scenario_player/utils/token.py", line 42, in token_maybe_transfer                                                                                         
    token_proxy.transfer(to_address=target_address, amount=transfer_amount)                                                                                                                  
  File "/home/karl/raiden/raiden/network/proxies/token.py", line 214, in transfer                                                                                                            
    if not was_transaction_successfully_mined(transaction_mined):                                                                                                                            
UnboundLocalError: local variable 'transaction_mined' referenced before assignment 
```

**Comment by fredo** [comment]
Can you provide more logs? 

It seems that the gas estimation failed. do you see `Transaction gas estimation failed` in the logs?

**Comment by fredo** [comment]
from  `Transaction_pending.estimate_gas` it states 
```
Returns `None` transaction would fail because it hit an assert/require,
or if the amount of gas required is larger than the block gas limit.
```

**Comment by karlb** [comment]
The transaction failure it totally ok (I was out of funds), but the error handling should not hit an `UnboundLocalError`.

**Comment by fredo** [comment]
definitely not. Then I suggest tansaction failure should lead to not send the transaction at all?
