### ISSUE TITLE
Cannot start RC7 with Geth and old DB

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#6083]
When I start RC7 with a **used database** (the node already worked fine with RC5) I get 

```
{'code': -32000, 'message': 'missing trie node 92f440810da9bc1384641dbf53e30ee1571973091b37a1528d4d3f22706b1240 (path )'}
```

My VPN is running and in that case I tried to connect to the geth brainbot node

```
➜  Binaries ./raiden-v0.200.0-rc7-linux-x86_64 --eth-rpc-endpoint geth.mainnet.ethnodes.brainbot.com:8545 --accept-disclaimer --address 0xBEf06bc6B22780E613892c1C397Ce2DD42115Ab0 --password-file mn.txt --enable-monitoring --keystore-path .

Welcome to Raiden, version 0.200.0rc7!
----------------------------------------------------------------------
| This is an Alpha version of experimental open source software      |
| released as a test version under an MIT license and may contain    |
| errors and/or bugs. No guarantee or representations whatsoever is  |
| made regarding its suitability (or its use) for any purpose or     |
| regarding its compliance with any applicable laws and regulations. |
| Use of the software is at your own risk and discretion and by      |
| using the software you acknowledge that you have read this         |
| disclaimer, understand its contents, assume all risk related       |
| thereto and hereby release, waive, discharge and covenant not to   |
| sue Brainbot Labs Establishment or any officers, employees or      |
| affiliates from and for any direct or indirect liability resulting |
| from the use of the software as permissible by applicable laws and |
| regulations.                                                       |
|                                                                    |
| Privacy Warning: Please be aware, that by using the Raiden Client, |
| among others, your Ethereum address, channels, channel deposits,   |
| settlements and the Ethereum address of your channel counterparty  |
| will be stored on the Ethereum chain, i.e. on servers of Ethereum  |
| node operators and ergo are to a certain extent publicly available.|
| The same might also be stored on systems of parties running Raiden |
| nodes connected to the same token network. Data present in the     |
| Ethereum chain is very unlikely to be able to be changed, removed  |
| or deleted from the public arena.                                  |
|                                                                    |
| Also be aware, that data on individual Raiden token transfers will |
| be made available via the Matrix protocol to the recipient,        |
| intermediating nodes of a specific transfer as well as to the      |
| Matrix server operators.                                           |
----------------------------------------------------------------------
The Raiden API RPC server is now running at http://127.0.0.1:5001/.

 See the Raiden documentation for all available endpoints at
 http://raiden-network.readthedocs.io/en/stable/rest_api.html
Checking if the ethereum node is synchronized
You have chosen the Pathfinding Service at https://pfs.rsb02.test.raiden.network.
Operator: "PFS RSB02", running version: 0.8.0, chain_id: 1.
Fees will be paid to 0xBA2439F05983D4604ceE5006E9d3652980B7E3D0. Each request costs 0.05 RDN.
Message from the Pathfinding Service:
"This is the PFS of rsb02.test.raiden.network"
2020-04-16 15:46:26.847937 [info     ] Using Pathfinding Service      [raiden.network.pathfinding] pfs_info=PFSInfo(url='https://pfs.rsb02.test.raiden.network', price=50000000000000000, chain_id=1, token_network_registry_address=b'/\x88\xf8&\x18\x19\xc4\xd63F\x80J\x17\xaa\x93\xc3\\\xc7\x9dy', user_deposit_address=b'\x15\xac7\x1a\xde!\xc4\xf3\x1d\xa3jL\xf9\xa0\xef5\xaf\xdez\x9f', payment_address=b'\xba$9\xf0Y\x83\xd4`L\xeeP\x06\xe9\xd3e)\x80\xb7\xe3\xd0', message='"This is the PFS of rsb02.test.raiden.network"', operator='"PFS RSB02"', version='0.8.0', confirmed_block_number=9884378)
Raiden is running in production mode

You are connected to the 'mainnet' network and the DB path is: /home/pirate/.raiden/node_bef06bc6/netid_1/network_2f88f826/v26_log.db
2020-04-16 15:46:30.408371 [info     ] Using Matrix server            [raiden.network.transport.matrix.utils] average_rtt=0.029655 server_ident=Synapse/1.10.0 server_url=https://transport.rsb02.test.raiden.network
2020-04-16 15:46:30.870360 [info     ] Synchronizing blockchain events [raiden.raiden_service] blocks_per_second=21542853.032971248 blocks_to_sync=9884378 elapsed=0.458824 to_block=9884378
FATAL: An unexpected exception occurred. A traceback has been written to /tmp/raiden-exception-2020-04-16T15-46bmqhu6pl.txt
{'code': -32000, 'message': 'missing trie node 92f440810da9bc1384641dbf53e30ee1571973091b37a1528d4d3f22706b1240 (path )'}
```

**Comment by Dominik1999** [comment]
here is the traceback

```
➜  Binaries cat /tmp/raiden-exception-2020-04-16T15-46bmqhu6pl.txt
Traceback (most recent call last):
  File "raiden/blockchain/state.py", line 114, in get_contractreceivechannelsettled_data_from_event
  File "raiden/network/proxies/utils.py", line 95, in get_onchain_locksroots
  File "raiden/network/proxies/proxy_manager.py", line 258, in payment_channel
  File "raiden/network/proxies/proxy_manager.py", line 206, in token_network
  File "raiden/network/proxies/token_network.py", line 154, in __init__
  File "raiden/network/rpc/client.py", line 323, in check_address_has_code
  File "web3/eth.py", line 198, in getCode
  File "web3/manager.py", line 153, in request_blocking
ValueError: {'code': -32000, 'message': 'missing trie node e876d364865860adb0c36a183db6d5729cd0ae6f3f4738352d98b1f3bfa37c0e (path )'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "raiden/ui/cli.py", line 610, in run
  File "raiden/ui/runners.py", line 21, in run_services
  File "raiden/ui/app.py", line 438, in run_app
  File "raiden/app.py", line 91, in start
  File "raiden/raiden_service.py", line 364, in start
  File "raiden/raiden_service.py", line 670, in _synchronize_with_blockchain
  File "raiden/raiden_service.py", line 1002, in _poll_until_target
  File "raiden/blockchain/decode.py", line 413, in blockchainevent_to_statechange
  File "raiden/blockchain/state.py", line 134, in get_contractreceivechannelsettled_data_from_event
  File "raiden/network/proxies/utils.py", line 95, in get_onchain_locksroots
  File "raiden/network/proxies/proxy_manager.py", line 258, in payment_channel
  File "raiden/network/proxies/proxy_manager.py", line 206, in token_network
  File "raiden/network/proxies/token_network.py", line 154, in __init__
  File "raiden/network/rpc/client.py", line 323, in check_address_has_code
  File "web3/eth.py", line 198, in getCode
  File "web3/manager.py", line 153, in request_blocking
ValueError: {'code': -32000, 'message': 'missing trie node 92f440810da9bc1384641dbf53e30ee1571973091b37a1528d4d3f22706b1240 (path )'}
```

**Comment by ulope** [comment]
The exception is raised in `check_address_has_code`. This would suggest the block at which it's trying to check for that is too old.

**Comment by Dominik1999** [comment]
With RC8, I still get 

```
FATAL: An unexpected exception occurred. A traceback has been written to /tmp/raiden-exception-2020-04-22T07-23j98roz4y.txt
{'code': -32000, 'message': 'missing trie node 92f440810da9bc1384641dbf53e30ee1571973091b37a1528d4d3f22706b1240 (path )'}
ReturnCode.FATAL
➜  Binaries cat /tmp/raiden-exception-2020-04-22T07-23j98roz4y.txt 
Traceback (most recent call last):
  File "raiden/blockchain/state.py", line 114, in get_contractreceivechannelsettled_data_from_event
  File "raiden/network/proxies/utils.py", line 103, in get_onchain_locksroots
  File "raiden/network/proxies/token_network.py", line 525, in detail_participants
  File "raiden/network/proxies/token_network.py", line 436, in _detail_participant
  File "web3/contract.py", line 911, in call
  File "web3/contract.py", line 1436, in call_contract_function
  File "raiden/network/rpc/client.py", line 577, in patched_web3_eth_call
  File "raiden/network/rpc/client.py", line 570, in patched_web3_eth_call
  File "web3/manager.py", line 153, in request_blocking
ValueError: {'code': -32000, 'message': 'missing trie node e876d364865860adb0c36a183db6d5729cd0ae6f3f4738352d98b1f3bfa37c0e (path )'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "raiden/ui/cli.py", line 610, in run
  File "raiden/ui/runners.py", line 21, in run_services
  File "raiden/ui/app.py", line 438, in run_app
  File "raiden/app.py", line 91, in start
  File "raiden/raiden_service.py", line 364, in start
  File "raiden/raiden_service.py", line 675, in _synchronize_with_blockchain
  File "raiden/raiden_service.py", line 1006, in _poll_until_target
  File "raiden/blockchain/decode.py", line 413, in blockchainevent_to_statechange
  File "raiden/blockchain/state.py", line 134, in get_contractreceivechannelsettled_data_from_event
  File "raiden/network/proxies/utils.py", line 103, in get_onchain_locksroots
  File "raiden/network/proxies/token_network.py", line 525, in detail_participants
  File "raiden/network/proxies/token_network.py", line 436, in _detail_participant
  File "web3/contract.py", line 911, in call
  File "web3/contract.py", line 1436, in call_contract_function
  File "raiden/network/rpc/client.py", line 577, in patched_web3_eth_call
  File "raiden/network/rpc/client.py", line 570, in patched_web3_eth_call
  File "web3/manager.py", line 153, in request_blocking
ValueError: {'code': -32000, 'message': 'missing trie node 92f440810da9bc1384641dbf53e30ee1571973091b37a1528d4d3f22706b1240 (path )'}
```

**Comment by Dominik1999** [comment]
on the second try it worked with all my nodes
