### ISSUE TITLE
Show a user friendly error message when trying to register an invalid smart contract as a token

### ISSUE THREAD

**Issue by anmolshl** [raiden-network/raiden#6095]
## Problem Definition

No error message displayed when previously registered token is registered on a different computer on the same network.

**Comment by manuelwedler** [comment]
I tried to register the ENS registry contract as a token and the API died. It should return an error message instead that can be displayed in the WebUI.

```
2020-04-22 08:22:55.996692 [critical ] Unhandled exception when processing endpoint request [raiden.api.rest] node=0xa455Fe85Ee161fb1da7AaD492268388c910D86A6
Traceback (most recent call last):
  File "web3/contract.py", line 1444, in call_contract_function
  File "eth_abi/codec.py", line 181, in decode_abi
  File "eth_abi/decoding.py", line 127, in __call__
  File "eth_utils/functional.py", line 45, in inner
  File "eth_abi/decoding.py", line 173, in decode
  File "eth_abi/decoding.py", line 127, in __call__
  File "eth_abi/decoding.py", line 198, in decode
  File "eth_abi/decoding.py", line 308, in read_data_from_stream
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "raiden/network/proxies/token_network_registry.py", line 143, in add_token
  File "raiden/network/proxies/token.py", line 177, in total_supply
  File "web3/contract.py", line 911, in call
  File "web3/contract.py", line 1466, in call_contract_function
web3.exceptions.BadFunctionCallOutput: Could not decode contract function call totalSupply return data b'' for output_types ['uint256']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask/app.py", line 1832, in full_dispatch_request
  File "flask/app.py", line 1818, in dispatch_request
  File "flask_restful/__init__.py", line 458, in wrapper
  File "flask/views.py", line 88, in view
  File "flask_restful/__init__.py", line 573, in dispatch_request
  File "raiden/api/rest_utils.py", line 60, in decorated
  File "raiden/api/v1/resources.py", line 208, in put
  File "raiden/api/rest.py", line 560, in register_token
  File "raiden/api/python.py", line 284, in token_network_register
  File "raiden/network/proxies/token_network_registry.py", line 170, in add_token
  File "raiden/network/proxies/utils.py", line 125, in raise_on_call_returned_empty
raiden.exceptions.RaidenUnrecoverableError: Either the given address is for a different smart contract, or the contract was not yet deployed at the block 0xf4967ff0fdd24591c4a86040f27dc98aab46a1df38f8acfb7b4d554f050e9cf8. Either way this call should never happened.
2020-04-22 08:22:57.000393 [info     ] 127.0.0.1 - - [2020-04-22 10:22:56] "PUT /api/v1/tokens/0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e HTTP/1.1" 500 161 1.236997 [raiden.api.rest.pywsgi] 
Traceback (most recent call last):
  File "web3/contract.py", line 1444, in call_contract_function
  File "eth_abi/codec.py", line 181, in decode_abi
  File "eth_abi/decoding.py", line 127, in __call__
  File "eth_utils/functional.py", line 45, in inner
  File "eth_abi/decoding.py", line 173, in decode
  File "eth_abi/decoding.py", line 127, in __call__
  File "eth_abi/decoding.py", line 198, in decode
  File "eth_abi/decoding.py", line 308, in read_data_from_stream
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "raiden/network/proxies/token_network_registry.py", line 143, in add_token
  File "raiden/network/proxies/token.py", line 177, in total_supply
  File "web3/contract.py", line 911, in call
  File "web3/contract.py", line 1466, in call_contract_function
web3.exceptions.BadFunctionCallOutput: Could not decode contract function call totalSupply return data b'' for output_types ['uint256']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "raiden/api/rest.py", line 402, in _run
  File "gevent/baseserver.py", line 389, in serve_forever
  File "src/gevent/event.py", line 133, in gevent._event.Event.wait
  File "src/gevent/_abstract_linkable.py", line 208, in gevent.__abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 178, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 196, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 182, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
raiden.exceptions.RaidenUnrecoverableError: Either the given address is for a different smart contract, or the contract was not yet deployed at the block 0xf4967ff0fdd24591c4a86040f27dc98aab46a1df38f8acfb7b4d554f050e9cf8. Either way this call should never happened.
2020-04-22T08:22:57Z <Greenlet "APIServer|Greenlet-0" at 0x7fd992beb950: _run> failed with RaidenUnrecoverableError
```
