### ISSUE TITLE
RC8, FATAL: Could not restore state

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#6097]
After upgrading from RC7 to RC8 I get below error when starting Raiden. 

```
FATAL: An un-recoverable error happen, Raiden is bailing Could not restore state. It seems like the existing database is incompatible with the current version of Raiden. Consider using a stable version of the Raiden client.
```

Stacktrace:
```
Traceback (most recent call last):
  File "raiden/storage/serialization/serializer.py", line 79, in deserialize
  File "marshmallow/schema.py", line 723, in load
  File "marshmallow/schema.py", line 904, in _do_load
marshmallow.exceptions.ValidationError: {'pending_transactions': {0: ["Unable to use schema. Error: '_type'\nEnsure there is a deserialization_schema_selector and then it returns a field or a schema when the function is passed in {'triggered_by_block_hash': '0xc6f4126b52a7b85ecd2c0102327c0e17eee93ed8bd48af4849a8f9cac9d1ef5a'}. This is the class I got. Make sure it is a field or a schema: None"]}}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "raiden/raiden_service.py", line 519, in _initialize_wal
  File "raiden/storage/wal.py", line 40, in restore_to_state_change
  File "raiden/storage/sqlite.py", line 812, in get_snapshot_before_state_change
  File "raiden/storage/serialization/serializer.py", line 101, in deserialize
  File "raiden/storage/serialization/serializer.py", line 81, in deserialize
raiden.exceptions.SerializationError: Can't deserialize: {'block_number': '9885129', 'identifiers_to_tokennetworkregistries': {'0x2f88f8261819c4d63346804a17aa93c35cc79d79': {'tokennetworkaddresses_to_tokennetworks': {'0x4261f6eaf3acf568a5ee6e15be0dfcda379dac8b': {'network_graph': {'network': '[]', 'channel_identifier_to_participants': {}, 'token_network_address': '0x4261f6eaf3acf568a5ee6e15be0dfcda379dac8b'}, 'partneraddresses_to_channelidentifiers': {}, 'address': '0x4261f6eaf3acf568a5ee6e15be0dfcda379dac8b', 'channelidentifiers_to_channels': {}, 'token_address': '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2'}, '0x34ff4c1cb40687d0b64accc24154d187265a3f3d': {'network_graph': {'network': '[["0x298e4ac53b44fa951e043bc674ed26528b6f8dd0", "0x94eee3b101a2c153dad1022be4eae89ec447bdaa"], ["0x298e4ac53b44fa951e043bc674ed26528b6f8dd0", "0xf8f857026c39bdea5fcc2eb652dd02a23a07cf13"], ["0x298e4ac53b44fa951e043bc674ed26528b6f8dd0", "0xbef06bc6b22780e613892c1c397ce2dd42115ab0"], ["0x298e4ac53b44fa951e043bc674ed26528b6f8dd0", "0xd08cd0b81271ac2776da40ebc74f447bcc8a809d"], ["0x298e4ac53b44fa951e043bc674ed26528b6f8dd0", "0x50602491e5e9f3e7fb6dc1ea4381b66867cad493"], ["0x298e4ac53b44fa951e043bc674ed26528b6f8dd0", "0xf573c35c75ab5896ce8e081d68b8626f9233bc4c"], ["0x94eee3b101a2c153dad1022be4eae89ec447bdaa", "0xf8f857026c39bdea5fcc2eb652dd02a23a07cf13"], ["0x94eee3b101a2c153dad1022be4eae89ec447bdaa", "0xf128a427deff3a4f792373f4be38beecd07d4ffe"], ["0x94eee3b101a2c153dad1022be4eae89ec447bdaa", "0x13e1e3021e5ec6503a17963f933fad63576fc19c"], ["0x94eee3b101a2c153dad1022be4eae89ec447bdaa", "0x865b332b0b058c472ee3b46c5a66b8d1699740e1"], ["0xf8f857026c39bdea5fcc2eb652dd02a23a07cf13", "0xa787fa214a168efa12ae01e9b614de9a4d81ccf6"], ["0xf8f857026c39bdea5fcc2eb652dd02a23a07cf13", "0x13e1e3021e5ec6503a17963f933fad63576fc19c"], ["0xbef06bc6b22780e613892c1c397ce2dd42115ab0", "0x3bbce117895da723f6b4668272406b83614db915"], ["0xbef06bc6b22780e613892c1c397ce2dd42115ab0", "0xee12f8e36574c97effef86723053c533649a561b"], ["0xd08cd0b81271ac2776da40ebc74f447bcc8a809d", "0x3bbce117895da723f6b4668272406b83614db915"], ["0x50602491e5e9f3e7fb6dc1ea4381b66867cad493", "0x2b0554e020fdf43e1b5e64fc1652203ca5a26aeb"], ["0x50602491e5e9f3e7fb6dc1ea4381b66867cad493", "0x83c1c6f002ed22b331cd779dc77be08537f46fd1"], ["0x50602491e5e9f3e7fb6dc1ea4381b66867cad493", "0xee12f8e36574c97effef86723053c533649a561b"], ["0xf573c35c75ab5896ce8e081d68b8626f9233bc4c", "0x2b0554e020fdf43e1b5e64fc1652203ca5a26aeb"], ["0xf573c35c75ab5896ce8e081d68b8626f9233bc4c", "0xab6d3fddff1303ce6c136584197a78c5a94e1531"], ["0xf573c35c75ab5896ce8e081d68b8626f9233bc4c", "0xee12f8e36574c97effef86723053c533649a561b"], ["0xf573c35c75ab5896ce8e081d68b8626f9233bc4c", "0x13e1e3021e5ec6503a17963f933fad63576fc19c"], ["0xf128a427deff3a4f792373f4be38beecd07d4ffe", "0x3bbce117895da723f6b4668272406b83614db915"], ["0x13e1e3021e5ec6503a17963f933fad63576fc19c", "0x865b332b0b058c472ee3b46c5a66b8d1699740e1"], ["0xa787fa214a168efa12ae01e9b614de9a4d81ccf6", "0x865b332b0b058c472ee3b46c5a66b8d1699740e1"], ["0xee12f8e36574c97effef86723053c533649a561b", "0xab6d3fddff1303ce6c136584197a78c5a94e1531"], ["0x2b0554e020fdf43e1b5e64fc1652203ca5a26aeb", "0xab6d3fddff1303ce6c136584197a78c5a94e1531"], ["0x2b0554e020fdf43e1b5e64fc1652203ca5a26aeb", "0xf822888cb72bf54209c739e4db271d7c91487213"], ["0x2b0554e020fdf43e1b5e64fc1652203ca5a26aeb", "0x83c1c6f002ed22b331cd779dc77be08537f46fd1"]]', 'channel_identifier_to_participants': {'3': ['0x94eee3b101a2c153dad1022be4eae89ec447bdaa', '0x298e4ac53b44fa951e043bc674ed26528b6f8dd0'], '4': ['0x298e4ac53b44fa951e043bc674ed26528b6f8dd0', '0xf8f857026c39bdea5fcc2eb652dd02a23a07cf13'], '6': ['0x2b0554e020fdf43e1b5e64fc1652203ca5a26aeb', '0xab6d3fddff1303ce6c136584197a78c5a94e1531'], '7': ['0x2b0554e020fdf43e1b5e64fc1652203ca5a26aeb', '0xf822888cb72bf54209c739e4db271d7c91487213'], '8': ['0xbef06bc6b22780e613892c1c397ce2dd42115ab0', '0x3bbce117895da723f6b4668272406b83614db915'], '9': ['0x3bbce117895da723f6b4668272406b83614db915', '0xd08cd0b81271ac2776da40ebc74f447bcc8a809d'], '10': ['0xbef06bc6b22780e613892c1c397ce2dd42115ab0', '0x298e4ac53b44fa951e043bc674ed26528b6f8dd0'], '12': ['0x2b0554e020fdf43e1b5e64fc1652203ca5a26aeb', '0x83c1c6f002ed22b331cd779dc77be08537f46fd1'], '13': ['0xd08cd0b81271ac2776da40ebc74f447bcc8a809d', '0x298e4ac53b44fa951e043bc674ed26528b6f8dd0'], '15': ['0xee12f8e36574c97effef86723053c533649a561b', '0xab6d3fddff1303ce6c136584197a78c5a94e1531'], '16': ['0x50602491e5e9f3e7fb6dc1ea4381b66867cad493', '0x83c1c6f002ed22b331cd779dc77be08537f46fd1'], '17': ['0x50602491e5e9f3e7fb6dc1ea4381b66867cad493', '0x2b0554e020fdf43e1b5e64fc1652203ca5a26aeb'], '18': ['0x50602491e5e9f3e7fb6dc1ea4381b66867cad493', '0x298e4ac53b44fa951e043bc674ed26528b6f8dd0'], '19': ['0xf573c35c75ab5896ce8e081d68b8626f9233bc4c', '0x298e4ac53b44fa951e043bc674ed26528b6f8dd0'], '20': ['0xf573c35c75ab5896ce8e081d68b8626f9233bc4c', '0x2b0554e020fdf43e1b5e64fc1652203ca5a26aeb'], '21': ['0xf573c35c75ab5896ce8e081d68b8626f9233bc4c', '0xab6d3fddff1303ce6c136584197a78c5a94e1531'], '22': ['0xee12f8e36574c97effef86723053c533649a561b', '0xbef06bc6b22780e613892c1c397ce2dd42115ab0'], '23': ['0xf128a427deff3a4f792373f4be38beecd07d4ffe', '0x3bbce117895da723f6b4668272406b83614db915'], '24': ['0xa787fa214a168efa12ae01e9b614de9a4d81ccf6', '0xf8f857026c39bdea5fcc2eb652dd02a23a07cf13'], '25': ['0x94eee3b101a2c153dad1022be4eae89ec447bdaa', '0xf8f857026c39bdea5fcc2eb652dd02a23a07cf13'], '27': ['0xf573c35c75ab5896ce8e081d68b8626f9233bc4c', '0xee12f8e36574c97effef86723053c533649a561b'], '28': ['0xee12f8e36574c97effef86723053c533649a561b', '0x50602491e5e9f3e7fb6dc1ea4381b66867cad493'], '29': ['0xf128a427deff3a4f792373f4be38beecd07d4ffe', '0x94eee3b101a2c153dad1022be4eae89ec447bdaa'], '30': ['0x13e1e3021e5ec6503a17963f933fad63576fc19c', '0x94eee3b101a2c153dad1022be4eae89ec447bdaa'], '32': ['0x13e1e3021e5ec6503a17963f933fad63576fc19c', '0xf8f857026c39bdea5fcc2eb652dd02a23a07cf13'], '33': ['0x13e1e3021e5ec6503a17963f933fad63576fc19c', '0xf573c35c75ab5896ce8e081d68b8626f9233bc4c'], '35': ['0x865b332b0b058c472ee3b46c5a66b8d1699740e1', '0x13e1e3021e5ec6503a17963f933fad63576fc19c'], '36': ['0xa787fa214a168efa12ae01e9b614de9a4d81ccf6', '0x865b332b0b058c472ee3b46c5a66b8d1699740e1'], '37': ['0x865b332b0b058c472ee3b46c5a66b8d1699740e1', '0x94eee3b101a2c153dad1022be4eae89ec447bdaa']}, 'token_network_address': '0x34ff4c1cb40687d0b64accc24154d187265a3f3d'}, 'partneraddresses_to_channelidentifiers': {'0xf8f857026c39bdea5fcc2eb652dd02a23a07cf13': ['24'], '0x865b332b0b058c472ee3b46c5a66b8d1699740e1': ['36']}, 'address': '0x34ff4c1cb40687d0b64accc24154d187265a3f3d', 'channelidentifiers_to_channels': {'24': {'reveal_timeout': '50', 'partner_state': {'balance_proof': {'balance_hash': '0x47fa5ed149a64c08edfe52c39e2f11aed36dfa064f2af93d22ebe80b23e8fecc', 'transferred_amount': '328168185308643603', 'locked_amount': '0', 'canonical_identifier': {'chain_identifier': '1', 'token_network_address': '0x34ff4c1cb40687d0b64accc24154d187265a3f3d', 'channel_identifier': '24'}, 'message_hash': '0x2d5590868dca771f6aeabc3b8b8e5eb83768fdee74cbed3e1b7b9445237e7c55', 'sender': '0xf8f857026c39bdea5fcc2eb652dd02a23a07cf13', 'nonce': '459', 'locksroot': '0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470', 'signature': '0x14502991327771e3139e34f70c782bdf1aa0e045fc1341e23abcd29141f6df7078d9d6c46d3a6e9197fcfce1aced132e5b905d017feac151819d6a3d852ad9b21b', '_type': 'raiden.transfer.architecture.BalanceProofSignedState'}, 'withdraws_pending': {}, 'secrethashes_to_unlockedlocks': {}, 'secrethashes_to_lockedlocks': {}, 'pending_locks': {'locks': []}, 'withdraws_expired': [], 'address': '0xf8f857026c39bdea5fcc2eb652dd02a23a07cf13', 'secrethashes_to_onchain_unlockedlocks': {}, 'contract_balance': 1000000000000000000, 'onchain_total_withdraw': '0', 'onchain_locksroot': '0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470', 'nonce': '459'}, 'fee_schedule': {'flat': '0', 'proportional': '4000', 'imbalance_penalty': [['0', '6000000000000000'], ['100000000000000000', '2092070640600000'], ['200000000000000000', '644245094400000'], ['300000000000000000', '169485149400000'], ['400000000000000000', '36279705600000'], ['500000000000000000', '5859375000000'], ['600000000000000000', '629145600000'], ['700000000000000000', '35429400000'], ['800000000000000000', '614400000'], ['900000000000000000', '600000'], ['1000000000000000000', '0'], ['1100000000000000000', '600000'], ['1200000000000000000', '614400000'], ['1300000000000000000', '35429400000'], ['1400000000000000000', '629145600000'], ['1500000000000000000', '5859375000000'], ['1600000000000000000', '36279705600000'], ['1700000000000000000', '169485149400000'], ['1800000000000000000', '644245094400000'], ['1900000000000000000', '2092070640600000'], ['2000000000000000000', '6000000000000000']], 'cap_fees': True}, 'close_transaction': None, 'update_transaction': None, 'our_state': {'balance_proof': {'balance_hash': '0x666482ca5b22bfd09a7cd3e990fe87ce28178f45f0cce88b0fe7144eef50795b', 'transferred_amount': '402631602428425130', 'locked_amount': '0', 'canonical_identifier': {'chain_identifier': '1', 'token_network_address': '0x34ff4c1cb40687d0b64accc24154d187265a3f3d', 'channel_identifier': '24'}, 'nonce': '9', 'locksroot': '0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470', '_type': 'raiden.transfer.architecture.BalanceProofUnsignedState'}, 'withdraws_pending': {}, 'secrethashes_to_unlockedlocks': {}, 'secrethashes_to_lockedlocks': {}, 'pending_locks': {'locks': []}, 'withdraws_expired': [], 'address': '0xa787fa214a168efa12ae01e9b614de9a4d81ccf6', 'secrethashes_to_onchain_unlockedlocks': {}, 'contract_balance': 2000000000000000000, 'onchain_total_withdraw': '1000000000000000000', 'onchain_locksroot': '0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470', 'nonce': '9'}, 'token_network_registry_address': '0x2f88f8261819c4d63346804a17aa93c35cc79d79', 'canonical_identifier': {'chain_identifier': '1', 'token_network_address': '0x34ff4c1cb40687d0b64accc24154d187265a3f3d', 'channel_identifier': '24'}, 'open_transaction': {'started_block_number': None, 'finished_block_number': '9870890'}, 'settle_transaction': None, 'settle_timeout': '100', 'token_address': '0x6b175474e89094c44da98b954eedeac495271d0f'}, '36': {'reveal_timeout': '50', 'partner_state': {'balance_proof': {'balance_hash': '0x2f23d618306c6e17f2b54319d57013e1ee2336966d4150cd49bad8853854dcd5', 'transferred_amount': '100000000000000000', 'locked_amount': '0', 'canonical_identifier': {'chain_identifier': '1', 'token_network_address': '0x34ff4c1cb40687d0b64accc24154d187265a3f3d', 'channel_identifier': '36'}, 'message_hash': '0x42c95335354ba9919440ce829140c1c8bc9b66475c0504bb993ba2fd8fb468b8', 'sender': '0x865b332b0b058c472ee3b46c5a66b8d1699740e1', 'nonce': '2', 'locksroot': '0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470', 'signature': '0xa84e3a9404ea1076eafc2ed171f313060609e92e0fc048eb6af24af576e32aca6afe3652522011e85fcc1e355c583ee07f3ce8403b53e5b8ea8d708021ad99e81b', '_type': 'raiden.transfer.architecture.BalanceProofSignedState'}, 'withdraws_pending': {}, 'secrethashes_to_unlockedlocks': {}, 'secrethashes_to_lockedlocks': {}, 'pending_locks': {'locks': []}, 'withdraws_expired': [], 'address': '0x865b332b0b058c472ee3b46c5a66b8d1699740e1', 'secrethashes_to_onchain_unlockedlocks': {}, 'contract_balance': 400000000000000000, 'onchain_total_withdraw': '0', 'onchain_locksroot': '0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470', 'nonce': '2'}, 'fee_schedule': {'flat': '0', 'proportional': '4000', 'imbalance_penalty': [['0', '1230000000000000'], ['20500000000000000', '428874481323000'], ['41000000000000000', '132070244352000'], ['61500000000000000', '34744455627000'], ['82000000000000000', '7437339648000'], ['102500000000000000', '1201171875000'], ['123000000000000000', '128974848000'], ['143500000000000000', '7263027000'], ['164000000000000000', '125952000'], ['184500000000000000', '123000'], ['205000000000000000', '0'], ['225500000000000000', '123000'], ['246000000000000000', '125952000'], ['266500000000000000', '7263027000'], ['287000000000000000', '128974848000'], ['307500000000000000', '1201171875000'], ['328000000000000000', '7437339648000'], ['348500000000000000', '34744455627000'], ['369000000000000000', '132070244352000'], ['389500000000000000', '428874481323000'], ['410000000000000000', '1230000000000000']], 'cap_fees': True}, 'close_transaction': None, 'update_transaction': None, 'our_state': {'balance_proof': None, 'withdraws_pending': {}, 'secrethashes_to_unlockedlocks': {}, 'secrethashes_to_lockedlocks': {}, 'pending_locks': {'locks': []}, 'withdraws_expired': [], 'address': '0xa787fa214a168efa12ae01e9b614de9a4d81ccf6', 'secrethashes_to_onchain_unlockedlocks': {}, 'contract_balance': 10000000000000000, 'onchain_total_withdraw': '0', 'onchain_locksroot': '0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470', 'nonce': '0'}, 'token_network_registry_address': '0x2f88f8261819c4d63346804a17aa93c35cc79d79', 'canonical_identifier': {'chain_identifier': '1', 'token_network_address': '0x34ff4c1cb40687d0b64accc24154d187265a3f3d', 'channel_identifier': '36'}, 'open_transaction': {'started_block_number': None, 'finished_block_number': '9883816'}, 'settle_transaction': None, 'settle_timeout': '500', 'token_address': '0x6b175474e89094c44da98b954eedeac495271d0f'}}, 'token_address': '0x6b175474e89094c44da98b954eedeac495271d0f'}}, 'address': '0x2f88f8261819c4d63346804a17aa93c35cc79d79', 'token_network_list': [], 'tokenaddresses_to_tokennetworkaddresses': {'0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2': '0x4261f6eaf3acf568a5ee6e15be0dfcda379dac8b', '0x6b175474e89094c44da98b954eedeac495271d0f': '0x34ff4c1cb40687d0b64accc24154d187265a3f3d'}}}, 'queueids_to_queues': {}, 'block_hash': '0xec14cbcd32c441b2bfe5064b766f62fcfe6fd4abf4f943c9b69214f5eb345726', 'chain_id': '1', 'payment_mapping': {'secrethashes_to_task': {}}, 'our_address': '0xa787fa214a168efa12ae01e9b614de9a4d81ccf6', 'nodeaddresses_to_networkstates': {'0xf8f857026c39bdea5fcc2eb652dd02a23a07cf13': 'REACHABLE', '0x94eee3b101a2c153dad1022be4eae89ec447bdaa': 'REACHABLE', '0x865b332b0b058c472ee3b46c5a66b8d1699740e1': 'REACHABLE'}, 'pending_transactions': [{'triggered_by_block_hash': '0xc6f4126b52a7b85ecd2c0102327c0e17eee93ed8bd48af4849a8f9cac9d1ef5a'}], 'pseudo_random_generator': [3, [1889212648, 938296596, 3849180327, 3747925038, 1780999439, 283645787, 3662146521, 3050315304, 1437217602, 505446736, 3471803301, 3931317527, 2287748534, 2833350342, 1163359438, 1271494049, 3871967792, 1274904672, 11783416, 3825342186, 1628467238, 2340246268, 2327967171, 2323016271, 667365011, 1091952992, 875714240, 2728897273, 36322305, 1039597150, 3911474622, 343980856, 6847626, 363659097, 1775355569, 804167072, 1289231642, 3180189215, 1360887816, 4277051816, 983388720, 581565281, 3072209814, 3417000136, 32663453, 2780489758, 2714841640, 3734838584, 3043147807, 741952011, 955763258, 827315980, 1682842405, 2139564676, 1869903226, 2618713280, 2761795120, 1097795523, 2350823543, 1067292711, 751159908, 2231440126, 1587212331, 998929646, 3091282271, 4145827968, 180789178, 382567631, 3449580120, 1132323895, 3855975547, 3679695985, 3432791193, 181769963, 466337222, 36507971, 3485670727, 3552640106, 2058043203, 4267113196, 3485593323, 3200371010, 1252001389, 2274463385, 2654002520, 3910496414, 664189561, 1761623215, 1526776118, 1747995083, 3290442798, 3116547094, 592911288, 3843883052, 519685097, 2124916628, 1230593810, 1981468169, 2671611136, 720724866, 3659577969, 3221502809, 443090730, 2718237188, 4023267799, 657784715, 3558264313, 3715101214, 2551471793, 3701591951, 2370016733, 3997348992, 1449403283, 2089944685, 236940597, 652211911, 4222500964, 3660003671, 1916838647, 4093745900, 3460118073, 2326367300, 2346929804, 2913997539, 72926595, 3411798187, 2364747235, 3903904045, 1886715121, 3048074690, 570841894, 1098027122, 2722420372, 1965326379, 2588375022, 752800259, 2148513343, 2571920646, 1679902485, 1556401115, 283655434, 2991564826, 3433927305, 1612176315, 2199077091, 253640434, 1561530061, 1272968887, 2924818823, 1492713868, 308870118, 3150990820, 4055757709, 384458314, 1605655558, 366664722, 1162802777, 3176297345, 350922001, 4081654013, 788866040, 3651408175, 2221010504, 3398917733, 3807100418, 615247257, 3769784051, 805594163, 675662619, 2850691418, 2160116132, 3227801329, 138582586, 3064569622, 2619219257, 852384883, 3371577255, 1412855813, 1048933932, 2121228107, 2615167635, 3996803957, 3612875289, 1779054481, 3951205265, 3002411435, 461167458, 2431072588, 3418245617, 2500522947, 1991885648, 159768786, 55325713, 3756343056, 1374667885, 707605726, 1342451369, 4047222818, 2663011021, 3081846816, 2536976523, 278495905, 2538360614, 827860193, 3246356435, 2977575102, 2507329983, 2764339208, 784022859, 314365094, 1581833158, 610172062, 3451944045, 1062509159, 918126811, 465526606, 2189131892, 2480283613, 1525518672, 103310146, 283519046, 4085725432, 67815135, 3838139184, 2576354916, 338373690, 3532846878, 1452843244, 146406359, 493640118, 2352855441, 1857548136, 2150670610, 141183627, 4245256620, 126251300, 2112946900, 1392631711, 232200743, 586580799, 1807850262, 3235244302, 3759992684, 1542110296, 4240648104, 925333178, 1797850417, 35563067, 3733158131, 4180479039, 3271567294, 109793519, 3096411158, 3291524560, 1788902698, 2686673694, 3305945829, 1103231407, 1710814671, 3467576064, 1830709153, 2128224599, 1700239211, 3687389561, 1094274340, 1362169736, 3223078301, 2219352941, 3669715553, 2753131999, 747174646, 3961876528, 4238883129, 947099224, 404231481, 4139251046, 188605148, 1143449331, 3429171902, 910371875, 2332913029, 1430230394, 2136781399, 2451843207, 3221781865, 3114272564, 978696447, 718479390, 1420004749, 1389719816, 1082167381, 968921556, 1399807688, 1093692972, 1771123283, 2507143556, 1664766368, 51156385, 794413071, 1745832716, 3697091053, 3390986174, 309041399, 3800711759, 4164410640, 1685195131, 3559073842, 2867789026, 2994416625, 2724420916, 3340011293, 473296712, 3470661424, 1584065077, 751855005, 1285389693, 3043160331, 56314429, 4010310567, 2631223281, 3326853788, 3492793492, 2823491404, 3704739654, 3387300102, 2927776762, 2185872404, 611350922, 4112400005, 2052244019, 1871557309, 4162215226, 3932815438, 3349411940, 3345020645, 32714988, 2440431656, 1445229063, 2180824951, 2550619563, 3734298269, 4020045342, 3010815612, 3682813205, 4004304776, 2946497445, 979351238, 3266162371, 2965720171, 1549935823, 1570205923, 540085660, 1087039897, 244141040, 2620149074, 763787922, 3742091738, 1354593971, 1190340103, 2751434892, 379905823, 3575489574, 3480035590, 1634935994, 2538432612, 4084422163, 2908111660, 3230378759, 1084225350, 128877458, 319852667, 1577724673, 562755537, 202507785, 777995830, 2152193997, 2992679639, 3761639968, 4206643158, 2327800526, 11993118, 2164009024, 3718368326, 549803302, 423166180, 828964671, 3111485983, 4211171530, 375850645, 107175893, 3252277643, 1663889845, 4051476935, 2167659250, 1196505834, 3792519729, 2039117200, 1260844768, 1200063187, 3797238312, 4074702493, 3520109965, 2678711159, 3410139680, 2742029562, 122004484, 2070317511, 3152186112, 3824909621, 752029930, 788189635, 2805068417, 3843716176, 1805295137, 792162085, 2158972135, 2412735385, 3030380508, 2981336654, 1782900373, 1822406522, 1045949360, 3777406381, 2336639242, 1889072709, 484636267, 1302735262, 182300142, 717182494, 2405057476, 3258593780, 3755775354, 2057691139, 402872199, 164976539, 2830097819, 3882584373, 4160746719, 3253871644, 1105275563, 1556231359, 1643637043, 3260422193, 3095177887, 2915958478, 2283553999, 3633945083, 4193936926, 2198528205, 2123335790, 1337107374, 658013880, 3990156483, 697261485, 149987228, 1594736940, 1219954974, 3804741160, 700588809, 90421415, 1240615088, 503625274, 2037053641, 2437238649, 1377497646, 4005475037, 2145006343, 3085509609, 2107899646, 1360158330, 2071908393, 3323929205, 2036058118, 2388498030, 333620505, 891222242, 1205391816, 3369753122, 1928391266, 1239258446, 1984371376, 756985951, 570334478, 1871573024, 2047314991, 3223893925, 4221033910, 876116026, 774541094, 2844108059, 58020675, 64583165, 2016913863, 34018351, 2724462205, 303966847, 787682596, 3138577720, 480565686, 303436455, 600360788, 3972999365, 507169604, 3181875307, 2857342565, 2745380268, 3583193855, 3156772390, 2474535853, 983882223, 2169503724, 1884782508, 3318672025, 1419722529, 3341997931, 124948309, 1977558733, 3434910343, 4273909511, 1893086553, 888865189, 3216849492, 1127047106, 2057239742, 1428690476, 1116038581, 3619376522, 3743430513, 3410374471, 1098284336, 989456626, 2915363211, 2890311745, 92628745, 2565309182, 3477985736, 536440711, 1555472013, 762823764, 386587439, 4262211247, 771430562, 2777112248, 2355824525, 2446520791, 4187659915, 4031565101, 1256107815, 2994331829, 1861752024, 13477524, 1695447651, 2694108505, 2556748175, 3905267734, 1816116187, 60045168, 1153915887, 2193192284, 1247438873, 2673154872, 622428176, 3055633789, 2394782575, 1030149524, 161371476, 89612214, 2249003458, 4271123233, 2228560056, 2756003523, 1893172533, 3674432298, 2571465101, 3238902984, 1223183986, 180933115, 700868234, 3855316559, 325636371, 1647583514, 1157928847, 161178022, 648037953, 628675756, 2975499310, 3543690335, 3966803936, 4013062294, 2299413267, 4250136627, 3739290439, 1167276913, 4119314733, 378507479, 3119869642, 48231529, 2101766487, 2910897975, 4227728416, 2394534730, 1605392492, 2981075038, 2211687251, 1942304194, 1703383122, 4286082474, 2763826457, 3458319732, 3964454478, 2979839387, 4075668739, 820642426, 3755140653, 454433516, 2362251042, 3808883117, 1093664114, 3053460649, 1567539347, 2467073333, 2891971061, 319411166, 1103624676, 417], None], 'tokennetworkaddresses_to_tokennetworkregistryaddresses': {'0x4261f6eaf3acf568a5ee6e15be0dfcda379dac8b': '0x2f88f8261819c4d63346804a17aa93c35cc79d79', '0x34ff4c1cb40687d0b64accc24154d187265a3f3d': '0x2f88f8261819c4d63346804a17aa93c35cc79d79'}, '_type': 'raiden.transfer.state.ChainState'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "raiden/ui/cli.py", line 610, in run
  File "raiden/ui/runners.py", line 21, in run_services
  File "raiden/ui/app.py", line 438, in run_app
  File "raiden/app.py", line 91, in start
  File "raiden/raiden_service.py", line 363, in start
  File "raiden/raiden_service.py", line 527, in _initialize_wal
raiden.exceptions.RaidenUnrecoverableError: Could not restore state. It seems like the existing database is incompatible with the current version of Raiden. Consider using a stable version of the Raiden client.
```

**Comment by Dominik1999** [comment]
- Close channels with metamask by hand. (we won't write a migration) 
- Not a critical bug, since we do not provide backwards compatibility. 
- Still something that we should prevent in the future
