### ISSUE TITLE
RC8, Request not supported because of state pruning

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#6098]
## Problem Definition

Upgraded to RC8 from RC7 on one of my nodes that I haven't started for a longer period of time (~7 days). During start up I get below error. I have another node that I also just upgraded from RC7 to RC8 that was started with RC7 yesterday and that node has no problems and is now running fine.

Stacktrace:
```
Traceback (most recent call last):
  File "raiden/blockchain/state.py", line 114, in get_contractreceivechannelsettled_data_from_event
  File "raiden/network/proxies/utils.py", line 103, in get_onchain_locksroots
  File "raiden/network/proxies/token_network.py", line 525, in detail_participants
  File "raiden/network/proxies/token_network.py", line 436, in _detail_participant
  File "web3/contract.py", line 911, in call
  File "web3/contract.py", line 1436, in call_contract_function
  File "raiden/network/rpc/client.py", line 577, in patched_web3_eth_call
  File "raiden/network/rpc/client.py", line 570, in patched_web3_eth_call
  File "web3/manager.py", line 153, in request_blocking
ValueError: {'code': -32000, 'message': 'This request is not supported because your node is running with state pruning. Run with --pruning=archive.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "raiden/ui/cli.py", line 610, in run
  File "raiden/ui/runners.py", line 21, in run_services
  File "raiden/ui/app.py", line 438, in run_app
  File "raiden/app.py", line 91, in start
  File "raiden/raiden_service.py", line 364, in start
  File "raiden/raiden_service.py", line 675, in _synchronize_with_blockchain
  File "raiden/raiden_service.py", line 1006, in _poll_until_target
  File "raiden/blockchain/decode.py", line 413, in blockchainevent_to_statechange
  File "raiden/blockchain/state.py", line 134, in get_contractreceivechannelsettled_data_from_event
  File "raiden/network/proxies/utils.py", line 103, in get_onchain_locksroots
  File "raiden/network/proxies/token_network.py", line 525, in detail_participants
  File "raiden/network/proxies/token_network.py", line 436, in _detail_participant
  File "web3/contract.py", line 911, in call
  File "web3/contract.py", line 1436, in call_contract_function
  File "raiden/network/rpc/client.py", line 577, in patched_web3_eth_call
  File "raiden/network/rpc/client.py", line 570, in patched_web3_eth_call
  File "web3/manager.py", line 153, in request_blocking
ValueError: {'code': -32000, 'message': 'This request is not supported because your node is running with state pruning. Run with --pruning=archive.'}
```

**Comment by Dominik1999** [comment]
same here https://github.com/raiden-network/raiden/issues/6083#issuecomment-617610316

**Comment by Dominik1999** [comment]
is already tracked https://github.com/raiden-network/raiden/issues/6083 that's why I will close
