### ISSUE TITLE
Timeout when running 4 mainnet Raiden nodes on the same geth node

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6106]
When running the PFS1 scenario on a single geth node, it results in
```
Traceback (most recent call last):
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/webargs/core.py", line 464, in wrapper
    return func(*args, **kwargs)
  File "/home/karl/raiden/raiden/api/rest_utils.py", line 60, in decorated
    return method(self, *args, **kwargs)
  File "/home/karl/raiden/raiden/api/v1/resources.py", line 78, in put
    registry_address=self.rest_api.raiden_api.raiden.default_registry.address, **kwargs
  File "/home/karl/raiden/raiden/api/rest.py", line 692, in open
    total_deposit=total_deposit,
  File "/home/karl/raiden/raiden/api/python.py", line 715, in set_total_channel_deposit
    block_identifier=confirmed_block_identifier,
  File "/home/karl/raiden/raiden/network/proxies/proxy_manager.py", line 264, in payment_channel
    contract_manager=self.contract_manager,
  File "/home/karl/raiden/raiden/network/proxies/payment_channel.py", line 40, in __init__
    from_block=token_network.metadata.filters_start_at,
  File "/home/karl/raiden/raiden/network/proxies/utils.py", line 48, in get_channel_participants_from_open_event
    events = token_network.proxy.web3.eth.getLogs(filter_args)
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/eth.py", line 497, in getLogs
    RPC.eth_getLogs, [filter_params],
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/manager.py", line 149, in request_blocking
    response = self._make_request(method, params)
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/manager.py", line 128, in _make_request
    return request_func(method, params)
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/middleware/cache.py", line 134, in middleware                                                                        
    return make_request(method, params)                                                                                                                                                       
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__                                                                                                                 
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/middleware/formatting.py", line 73, in apply_formatters                                                              
    response = make_request(method, formatted_params)                                                                                                                                         
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware                                                            
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/middleware/formatting.py", line 73, in apply_formatters
    response = make_request(method, formatted_params)
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/middleware/formatting.py", line 73, in apply_formatters
    response = make_request(method, formatted_params)                                 
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/middleware/normalize_errors.py", line 25, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/middleware/formatting.py", line 73, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
    response = make_request(method, params)
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/middleware/exception_retry_request.py", line 104, in middleware
    return make_request(method, params)
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/providers/rpc.py", line 83, in make_request
    **self.get_request_kwargs()
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/_utils/request.py", line 34, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)  # type: ignore
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='geth.mainnet.ethnodes.brainbot.com', port=8545): Read timed out. (read timeout=10)
```

With enabled web3 debug logging, the last web3 logs before the timeout are
```json
{"event": "Making request. Method: eth_getBlockByNumber", "logger": "web3.RequestManager", "level": "debug", "greenlet_name": "AlarmTask._run node:0x3904A2961b1Bf144DC8ACE00955db135e4F523e5", "timestamp": "2020-04-27 13:07:11.545446"}
{"event": "Making request HTTP. URI: http://geth.mainnet.ethnodes.brainbot.com:8545, Method: eth_getBlockByNumber", "logger": "web3.providers.HTTPProvider", "level": "debug", "greenlet_name": "AlarmTask._run node:0x3904A2961b1Bf144DC8ACE00955db135e4F523e5", "timestamp": "2020-04-27 13:07:11.546306"}
```
[last-lines.log](https://github.com/raiden-network/raiden/files/4544064/last-lines.log)

Since it is likely that some users run will multiple Raiden nodes on the same geth node, we should find out what is going on here and if there's a way to avoid the timeout.

**Comment by hackaugusto** [comment]
The problem is that the proxy constructor is validating the `channel_identifier` here:

https://github.com/raiden-network/raiden/blob/1fcaef4a1c58b369e21f7a8cadc87598bfd5f13c/raiden/network/proxies/payment_channel.py#L36-L41

This was done to prevent invalid proxies, since that would lead to problems while sending on-chain transactions. The problem with that code is that it will query for a very long range of blocks:

https://github.com/raiden-network/raiden/blob/1fcaef4a1c58b369e21f7a8cadc87598bfd5f13c/raiden/network/proxies/utils.py#L37-L46

were `token_network.metadata.filters_start_at` is the block at which the token network was deployed and `to_block` is latest, which will do a linear search in Geth and overload the node. There are a few things we could do:

1. Use adaptive ranges like it is done during the initialization. This however would make instantiating the proxy very slow.
2. Just remove the invalidation, the error is not that common and it is currently leading to failures with mainnet.
3. We already have the data because we are synchronizing with the blockchain. We could check the value using the state machine instead of the blockchain, since the data is already locally synced and timeouts were handled.

I believe we should do the third option, however that requires some additional changes. I would add proper types do express a "valid channel_identifier", that type should only be provided from a view from the state, and only be updated by a `ContractReceiveChannelNew` state change. For now I will just disable the check and create another issue for the proper solution.
