### ISSUE TITLE
Raiden 0.200.0RC8 - Selected Pathfinding Service returned unexpected reply

### ISSUE THREAD

**Issue by macintosh-HD** [raiden-network/raiden#6111]
## Problem Definition

Raiden reports `Selected Pathfinding Service returned unexpected reply` on start-up. I freshly installed Raiden on my machine.
I ran this command to start Raiden:  
`raiden --keystore-path  ~/.ethereum/testnet/keystore --eth-rpc-endpoint "https://goerli.infura.io/v3/ddb67d57bac64e52bc61c2ae217fac29" --network-id 5 --pathfinding-service-address https://pfs-goerli.services-test.raiden.network`

```
Traceback (most recent call last):
  File "/Users/julian/ethereum/raiden/venv-raiden/lib/python3.7/site-packages/raiden/network/pathfinding.py", line 133, in get_pfs_info
    to_canonical_address(infos["network_info"]["token_network_registry_address"])
KeyError: 'token_network_registry_address'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/julian/ethereum/raiden/venv-raiden/lib/python3.7/site-packages/raiden/network/pathfinding.py", line 262, in configure_pfs_or_exit
    pathfinding_service_info = get_pfs_info(pfs_url)
  File "/Users/julian/ethereum/raiden/venv-raiden/lib/python3.7/site-packages/raiden/network/pathfinding.py", line 149, in get_pfs_info
    raise ServiceRequestFailed(msg) from e
raiden.exceptions.ServiceRequestFailed: Selected Pathfinding Service returned unexpected reply

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/julian/ethereum/raiden/venv-raiden/lib/python3.7/site-packages/raiden/ui/cli.py", line 610, in run
    run_services(kwargs)
  File "/Users/julian/ethereum/raiden/venv-raiden/lib/python3.7/site-packages/raiden/ui/runners.py", line 21, in run_services
    app = run_app(**options)
  File "/Users/julian/ethereum/raiden/venv-raiden/lib/python3.7/site-packages/raiden/ui/app.py", line 358, in run_app
    enable_monitoring=enable_monitoring,
  File "/Users/julian/ethereum/raiden/venv-raiden/lib/python3.7/site-packages/raiden/ui/startup.py", line 370, in services_bundle_from_contracts_deployment
    pathfinding_max_fee=config.services.pathfinding_max_fee,
  File "/Users/julian/ethereum/raiden/venv-raiden/lib/python3.7/site-packages/raiden/network/pathfinding.py", line 265, in configure_pfs_or_exit
    f"There was an error with the Pathfinding Service with address "
raiden.exceptions.RaidenError: There was an error with the Pathfinding Service with address https://pfs-goerli.services-test.raiden.network. Raiden will shut down. Please try a different Pathfinding Service. 
Error Message: Selected Pathfinding Service returned unexpected reply
```

### System Description

I am running on MacOSX 10.15.4 using brew
```
19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
/usr/local/bin/solc
solc, the solidity compiler commandline interface
Version: 0.6.6+commit.6c089d02.Darwin.appleclang
/usr/local/bin/geth
Geth
Version: 1.9.12-stable
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.14
Operating System: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.14/libexec
```

**Comment by palango** [comment]
Hello @macintosh-HD , looks like you use one of our internal PFS that is only compatible with an older version of Raiden. Can you try starting with `--pathfinding-service-address https://pfs-goerli.services-dev.raiden.network` instead (services-**test** changed to services-**dev**) and let me know if that solves to problem?

**Comment by macintosh-HD** [comment]
Hello @palango , when I use that address I get the following error:
```
Traceback (most recent call last):
  File "/Users/julian/ethereum/raiden/venv-raiden/lib/python3.7/site-packages/raiden/ui/cli.py", line 610, in run
    run_services(kwargs)
  File "/Users/julian/ethereum/raiden/venv-raiden/lib/python3.7/site-packages/raiden/ui/runners.py", line 21, in run_services
    app = run_app(**options)
  File "/Users/julian/ethereum/raiden/venv-raiden/lib/python3.7/site-packages/raiden/ui/app.py", line 358, in run_app
    enable_monitoring=enable_monitoring,
  File "/Users/julian/ethereum/raiden/venv-raiden/lib/python3.7/site-packages/raiden/ui/startup.py", line 378, in services_bundle_from_contracts_deployment
    service_registry=proxies["service_registry"], pfs_info=pfs_info
  File "/Users/julian/ethereum/raiden/venv-raiden/lib/python3.7/site-packages/raiden/network/pathfinding.py", line 332, in check_pfs_for_production
    f"The Pathfinding Service at {pfs_info.url} is not registered "
raiden.exceptions.RaidenError: The Pathfinding Service at https://pfs-goerli.services-dev.raiden.network is not registered with the Service Registry at 0x735722704E365c37247Bb3e4eC52D6c937C54539 or the registered URL (https://pfs-goerli-with-fee.services-dev.raiden.network) doesn't match the given URL https://pfs-goerli.services-dev.raiden.network. Raiden will shut down. Please select a registered Pathfinding Service.
```

**Comment by palango** [comment]
Hi @macintosh-HD . Thanks for checking this out. The problem you run into is solvable in two ways:
- The check is only done in the production environment, so you can add `--environment-type development` to the CLI args
- Use `https://pfs-goerli-with-fee.services-dev.raiden.network` instead, but then you must mint token to pay for the PFS (this is harder than option 1)

**Comment by palango** [comment]
@macintosh-HD From my tests this should work with the instructions above. I'm closing this. Feel free to reopen or opening a new issue if you run into any other problems.
