### ISSUE TITLE
Requested block number is in a range that is not available yet

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6112]
When running a bf1 scenario on mainnet/parity, one of the nodes failed to start up with the error
```
ancient block sync is still in progress.'}
Traceback (most recent call last):
  File "/home/karl/raiden/raiden/ui/cli.py", line 610, in run
    run_services(kwargs)
  File "/home/karl/raiden/raiden/ui/runners.py", line 21, in run_services
    app = run_app(**options)
  File "/home/karl/raiden/raiden/ui/app.py", line 438, in run_app
    raiden_app.start()
  File "/home/karl/raiden/raiden/app.py", line 91, in start
    self.raiden.start()
  File "/home/karl/raiden/raiden/raiden_service.py", line 363, in start
    self._initialize_wal()
  File "/home/karl/raiden/raiden/raiden_service.py", line 547, in _initialize_wal
    last_log_block_hash = self.rpc_client.blockhash_from_blocknumber(last_log_block_number)
  File "/home/karl/raiden/raiden/network/rpc/client.py", line 927, in blockhash_from_blocknumber
    block = self.get_block(block_number)
  File "/home/karl/raiden/raiden/network/rpc/client.py", line 913, in get_block
    return self.web3.eth.getBlock(block_identifier)
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/eth.py", line 217, in getBlock
    [block_identifier, full_transactions],
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/web3/manager.py", line 153, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'Requested block number is in a range that is not available yet, because the ancient block sync is still in progress.'}
```

Is this an issue with Raiden or with our parity node?

[run-111.log](https://github.com/raiden-network/raiden/files/4574167/run-111.log)

**Comment by karlb** [comment]
According to @ulope :
> Yeah it’s what the message says. It was fast synced and hasn’t caught up with backfilling all the old blocks.

So not a problem with Raiden.
