### ISSUE TITLE
Could not join broadcast room in MFEE3

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#6127]
During the scenario run on 2020-05-03 MFEE3 failed as the node couldn't join the broadcast room:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/utils.py", line 544, in join_broadcast_room
    room = client.join_room(broadcast_room_alias)
  File "/usr/local/lib/python3.7/site-packages/matrix_client/client.py", line 320, in join_room
    response = self.api.join_room(room_id_or_alias)
  File "/usr/local/lib/python3.7/site-packages/matrix_client/api.py", line 195, in join_room
    return self._send("POST", path)
  File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/client.py", line 180, in _send
    return super()._send(method, path, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matrix_client/api.py", line 691, in _send
    code=response.status_code, content=response.text
matrix_client.errors.MatrixRequestError: 500: {"errcode":"M_UNKNOWN","error":"Internal server error"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/transport.py", line 850, in _join_broadcast_room
    client=transport._client, broadcast_room_alias=broadcast_room_alias
  File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/utils.py", line 549, in join_broadcast_room
    f"Could not join broadcast room {broadcast_room_alias}. "
raiden.exceptions.RaidenUnrecoverableError: Could not join broadcast room #raiden_goerli_discovery:transport04.raiden.network. Make sure the Matrix server you're trying to connect to uses the recommended server setup, esp. the server-side broadcast room creation. See https://github.com/raiden-network/raiden-transport.
2020-05-03T23:27:02Z <Greenlet "Greenlet-4" at 0x7f1d3f3a96a8: _join_broadcast_room(<MatrixTransport node:0x7B2E5f23Ae392145837528F3C5, 'raiden_goerli_discovery')> failed with RaidenUnrecoverableError

ReturnCode.FATAL
KeyboardInterrupt
2020-05-03T23:27:02Z

Aborted!
KeyboardInterrupt
2020-05-03T23:27:02Z

Aborted!
```

**Comment by palango** [comment]
This didn't happen the last 3 days.

**Comment by palango** [comment]
@ulope Might that be related to a full disk as well?

**Comment by ulope** [comment]
Quite possible.

I will update the servers to the recent RSB release in a bit.
We'll see tomorrow then.

**Comment by Dominik1999** [comment]
Not reproducible
