### ISSUE TITLE
Scenarios aborted due to KeyboardInterrupt

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#6128]
Multiple scenarios on 2020-05-03 were aborted due to `KeyboardInterrupt`s. 

Scenario list:
- mfee1
- pfs2 (also mentions `ReturnCode.PORT_ALREADY_IN_USE`)
- mfee3 (there's another problem as well, see https://github.com/raiden-network/raiden/issues/6127)
- mfee4
- bf7
- ms1

**Comment by karlb** [comment]
The `KeyboardInterrupt` will be raised when the SP stops nodes after one node experienced a problem (Why don't we use SIGTERM, again?). So look closely into what happened in the first node. See also https://github.com/raiden-network/scenario-player/issues/474.

**Comment by karlb** [comment]
The real error for MFEE1 is
```
There was an error with the Pathfinding Service with address https://pfs-goerli-with-fee.services-dev.raiden.network. Raiden will shut down. Please try a different Pathfinding Service.                                                                     
Error Message: Selected Pathfinding Service returned unexpected reply
```

**Comment by palango** [comment]
Around that time (1:47) I see crashes in the PFS logs.

@ulope @fredo Any ideas why we still might have users without a `displayname`: `TransportError("Could not get 'display_name' for user")`

```
May 11 23:46:21 services-dev c9ddced6c7dc[20320]: Traceback (most recent call last):
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:     "__main__", mod_spec)
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:     exec(code, run_globals)
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "/services/src/pathfinding_service/cli.py", line 156, in <module>
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:     main(auto_envvar_prefix="PFS")  # pragma: no cover
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:     return self.main(*args, **kwargs)
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:     rv = self.invoke(ctx)
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:     return ctx.invoke(self.callback, **ctx.params)
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:     return callback(*args, **kwargs)
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "/services/src/raiden_libs/cli.py", line 243, in call_with_blockchain_info
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:     return callback(**params)
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "/services/src/raiden_libs/cli.py", line 168, in call_with_common_options_initialized
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:     return func(**params)
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "/services/src/pathfinding_service/cli.py", line 141, in main
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:     service.get()
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "src/gevent/greenlet.py", line 795, in gevent._greenlet.Greenlet.get
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "src/gevent/greenlet.py", line 364, in gevent._greenlet.Greenlet._raise_exception
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "/usr/local/lib/python3.7/site-packages/gevent/_compat.py", line 62, in reraise
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:     raise value.with_traceback(tb)
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "/services/src/pathfinding_service/service.py", line 159, in _run
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:     gevent.joinall({self.matrix_listener}, timeout=0, raise_error=True)
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "src/gevent/greenlet.py", line 1002, in gevent._greenlet.joinall
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "src/gevent/greenlet.py", line 1018, in gevent._greenlet.joinall
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "src/gevent/greenlet.py", line 364, in gevent._greenlet.Greenlet._raise_exception
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "/usr/local/lib/python3.7/site-packages/gevent/_compat.py", line 62, in reraise
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:     raise value.with_traceback(tb)
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "/services/src/raiden_libs/matrix.py", line 200, in _run
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:     self._client.stop_listener_thread()
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/client.py", line 479, in stop_listener_thread
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:     {self.message_worker}, timeout=SHUTDOWN_TIMEOUT, raise_error=True
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "src/gevent/greenlet.py", line 1002, in gevent._greenlet.joinall
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "src/gevent/greenlet.py", line 1018, in gevent._greenlet.joinall
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "src/gevent/greenlet.py", line 364, in gevent._greenlet.Greenlet._raise_exception
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "/usr/local/lib/python3.7/site-packages/gevent/_compat.py", line 62, in reraise
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:     raise value.with_traceback(tb)
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/client.py", line 716, in _handle_message
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:     self._handle_responses(currently_queued_responses)
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/client.py", line 799, in _handle_responses
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:     self.handle_messages_callback(all_messages)
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "/services/src/raiden_libs/matrix.py", line 256, in _handle_matrix_sync
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:     all_messages.extend(self._handle_message(room, text))
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "/services/src/raiden_libs/matrix.py", line 279, in _handle_message
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:     self._displayname_cache.warm_users([user])
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:   File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/utils.py", line 141, in warm_users
May 11 23:46:21 services-dev c9ddced6c7dc[20320]:     raise TransportError("Could not get 'display_name' for user")
May 11 23:46:21 services-dev c9ddced6c7dc[20320]: raiden.exceptions.TransportError: Could not get 'display_name' for user
May 11 23:46:21 services-dev c9ddced6c7dc[20320]: Sentry is attempting to send 0 pending error messages
May 11 23:46:21 services-dev c9ddced6c7dc[20320]: Waiting up to 2 seconds
```

**Comment by ulope** [comment]
Hm, there should be no (Raiden) users without display name.
When a fresh node logs in for the first time there is a short time before the display name gets set. 

But this doesn't seem to apply here since (if I read the traceback right) this displayname lookup was done in response to an incoming message. At that point the displayname has long been set.

Can you tell me which transport server the PFS was connected to? Maybe there's something in the matrix logs that will give more information.

**Comment by palango** [comment]
> Can you tell me which transport server the PFS was connected to? Maybe there's something in the matrix logs that will give more information.

`transport04` was used.

```
May 11 09:43:56 services-dev 513e76b8e931[20320]: {"server_url": "https://transport04.raiden.network", "server_ident": "Synapse/1.5.1", "average_rtt": 0.005811, "event": "Using Matrix server", "level": "info", "logger": "raiden.network.transport.matrix.utils", "timestamp": "2020-05-11 09:43:56.354247"}
May 11 12:08:13 services-dev c9ddced6c7dc[20320]: {"server_url": "https://transport04.raiden.network", "server_ident": "Synapse/1.5.1", "average_rtt": 0.008324666666666666, "event": "Using Matrix server", "level": "info", "logger": "raiden.network.transport.matrix.utils", "timestamp": "2020-05-11 12:08:13.964443"}
```

**Comment by ulope** [comment]
Ah, yeah so that was still the old setup before the upgrade yesterday. And possibly while the servers where out of disk space. 

I'd say this is probably not a real issue. We should close it and see if it re-appears.
