### ISSUE TITLE
BF4 scenarion consistently fail on mainnet

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#6169]
## Problem Definition 

I have tried running the BF4 scenario twice on mainnet, and both times it fails with:

```
2020-05-15 13:33:10.944916 [error    ] Exception while running scenario [scenario_player.main] 
Traceback (most recent call last):
  File "/home/jacob/dev/scenario-player/scenario_player/main.py", line 335, in run_
    environment=environment,
  File "/home/jacob/dev/scenario-player/scenario_player/main.py", line 410, in orchestrate
    scenario_runner.run_scenario()
  File "/home/jacob/dev/scenario-player/scenario_player/runner.py", line 351, in run_scenario
    gevent.joinall(greenlets, raise_error=True, count=1)
  File "src/gevent/greenlet.py", line 1002, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 1018, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 364, in gevent._greenlet.Greenlet._raise_exception
  File "/home/jacob/dev/scenario-player/.env/lib/python3.7/site-packages/gevent/_compat.py", line 62, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "/home/jacob/dev/scenario-player/scenario_player/runner.py", line 431, in setup_environment_and_run_main_task
    pool.join(raise_error=True)
  File "/home/jacob/dev/scenario-player/.env/lib/python3.7/site-packages/gevent/pool.py", line 435, in join
    greenlet._raise_exception()
  File "src/gevent/greenlet.py", line 364, in gevent._greenlet.Greenlet._raise_exception
  File "/home/jacob/dev/scenario-player/.env/lib/python3.7/site-packages/gevent/_compat.py", line 62, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "/home/jacob/dev/scenario-player/scenario_player/utils/token.py", line 136, in userdeposit_maybe_deposit
    target_address, new_total_deposit, userdeposit_proxy.client.get_confirmed_blockhash()
  File "/home/jacob/dev/raiden/raiden/network/proxies/user_deposit.py", line 335, in deposit
    self._deposit_check_result(transaction_hash, token, total_deposit, amount_to_deposit)
  File "/home/jacob/dev/raiden/raiden/network/proxies/user_deposit.py", line 622, in _deposit_check_result
    raise RaidenRecoverableError(msg)
raiden.exceptions.RaidenRecoverableError: Deposit amount already increased after another transaction
```

Scenraio log: [scenario-player-run_bf4_multi_payments_same_node_2020-05-15T15:28:18.log](https://github.com/raiden-network/raiden/files/4634681/scenario-player-run_bf4_multi_payments_same_node_2020-05-15T15.28.18.log)

**Comment by hackaugusto** [comment]
I didn't manage to reproduce locally, I had a different problem (lack of RDN tokens to deposit in the UDC). After looking at the transactions, all of the `deposit`s to the UDC failed:

[`0x59a4c0`](https://etherscan.io/tx/0x59a4c0046af2de9b26777af1bd34eaab15a1ae0c94b4635eb0a906be0cd0b44d) block=10071013
[`0x49829d`](https://etherscan.io/tx/0x49829dc4e73f9c9af4c49ddcb2ad53565df462b7871416e4fe4851f4c860ab58) block=10071013
[`0x8fc630`](https://etherscan.io/tx/0x8fc630ce5656c1a950f2e65b7f77a35ec78d5ec1c970726a8ba79825588a8342) block=10071013 
 
Even though the approve was done at block=10018049 [`0x677809`](https://etherscan.io/tx/0x67780930f34bf7cb661b97351ae0d6a17a60ec56450e7e583223c7bc5ff2b5df). I couldn't find the funding transactions, maybe the account didn't have enough funds when the transactions got mined.

**Comment by czepluch** [comment]
What was wrong in the error message? I can try to rerun with higher funding if needed.

**Comment by palango** [comment]
> What was wrong in the error message? I can try to rerun with higher funding if needed.

https://github.com/raiden-network/raiden/pull/6171

I found another problem, so don't retry yet.

**Comment by palango** [comment]
We don't check if the token balance is big enough before doing a deposit, that leads to failing transactions with unclear messages.
