### ISSUE TITLE
Unhandled exception InsufficientEth on POST /api/v1/_testing/tokens/

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/raiden#6323]
## Problem Definition

I tried to mint some TestTokens in the WebUI but had no ETH. Afterwards I saw `Raiden API connection error!` in the WebUI. 

This was logged: 
```
2020-06-17 15:46:07.582947 [critical ] Transaction to call smart contract function failed [raiden.network.rpc.client] args=(500000000000000000, b'\xe9Xf\xea\xac\xe4\x05+\xaf(\xe0,\xea\x87\xfeX\x94q\xdch') eth_node=<EthClient.PARITY: 'parity'> from_address=0xe95866EaaCE4052bAf28e02cEa87fe589471Dc68 function_name=mintFor gas_price=1036800000 kwargs={} node=0xe95866EaaCE4052bAf28e02cEa87fe589471Dc68 nonce=0 reason=Transaction failed due to insufficient ETH balance. Please top up your ETH account. startgas=67626 to_address=0xC563388e2e2fdD422166eD5E76971D11eD37A466 token=09a148cf-23fe-44bc-80e7-4cedc41f3ace value=0
2020-06-17 15:46:07.585753 [critical ] Unhandled exception when processing endpoint request [raiden.api.rest] node=0xe95866EaaCE4052bAf28e02cEa87fe589471Dc68
Traceback (most recent call last):
  File "raiden/network/rpc/client.py", line 1315, in transact
  File "web3/eth.py", line 392, in sendRawTransaction
  File "web3/manager.py", line 153, in request_blocking
ValueError: {'code': -32010, 'message': 'Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 70114636800000 and got: 0.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask/app.py", line 1950, in full_dispatch_request
  File "flask/app.py", line 1936, in dispatch_request
  File "flask_restful/__init__.py", line 468, in wrapper
  File "flask/views.py", line 89, in view
  File "flask_restful/__init__.py", line 583, in dispatch_request
  File "raiden/api/rest_utils.py", line 59, in decorated
  File "raiden/api/v1/resources.py", line 229, in post
  File "raiden/api/rest.py", line 588, in mint_token_for
  File "raiden/api/python.py", line 566, in mint_token_for
  File "raiden/network/proxies/custom_token.py", line 58, in mint_for
  File "raiden/network/rpc/client.py", line 1342, in transact
raiden.exceptions.InsufficientEth: Transaction failed due to insufficient ETH balance. Please top up your ETH account.
2020-06-17 15:46:08.592341 [info     ] 127.0.0.1 - - [2020-06-17 17:46:08] "POST /api/v1/_testing/tokens/0xC563388e2e2fdD422166eD5E76971D11eD37A466/mint HTTP/1.1" 500 161 1.810512 [raiden.api.rest.pywsgi] 
Traceback (most recent call last):
  File "raiden/network/rpc/client.py", line 1315, in transact
  File "web3/eth.py", line 392, in sendRawTransaction
  File "web3/manager.py", line 153, in request_blocking
ValueError: {'code': -32010, 'message': 'Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 70114636800000 and got: 0.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "raiden/api/rest.py", line 398, in _run
  File "gevent/baseserver.py", line 400, in serve_forever
  File "src/gevent/event.py", line 159, in gevent._gevent_cevent.Event.wait
  File "src/gevent/_abstract_linkable.py", line 381, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 346, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 348, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 303, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
raiden.exceptions.InsufficientEth: Transaction failed due to insufficient ETH balance. Please top up your ETH account.
2020-06-17T15:46:08Z <Greenlet "APIServer|Greenlet-0" at 0x7f2f277b2a70: _run> failed with InsufficientEth
```

I couldn't do any API requests anymore afterwards. So the API server crashed but the node is still running. Might be related to https://github.com/raiden-network/raiden/issues/6217.

## System
- Raiden: v1.0.1
- WebUI: v1.0.1
- Environment: development
- Network: Görli

**Comment by palango** [comment]
Solving the underlying unhandled exception is left.

**Comment by Dominik1999** [comment]
Im Mint Teil wird sie nicht gehandlet
