### ISSUE TITLE
Fatal 404 when starting v1.1.1 on goerli

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#6413]
## Problem Definition

Just tried running v1.1.1 like this:
```
./raiden-v1.1.1-linux-x86_64 --keystore-path ~/Dropbox/testnet_backup/keystore --network-id 5 --environment-type development --eth-rpc-endpoint http://geth.goerli.ethnodes.brainbot.com:8545 --api-address localhost:5001
```
and I get the following error:
```
Traceback (most recent call last):
  File "raiden/ui/cli.py", line 617, in run
  File "raiden/ui/runners.py", line 21, in run_services
  File "raiden/ui/app.py", line 446, in run_app
  File "raiden/app.py", line 90, in start
  File "raiden/raiden_service.py", line 444, in start
  File "raiden/raiden_service.py", line 552, in _start_transport
  File "raiden/network/transport/matrix/transport.py", line 449, in start
  File "raiden/network/transport/matrix/utils.py", line 711, in login
  File "raiden/network/transport/matrix/utils.py", line 623, in first_login
  File "matrix_client/client.py", line 270, in login
  File "matrix_client/api.py", line 160, in login
  File "raiden/network/transport/matrix/client.py", line 180, in _send
  File "matrix_client/api.py", line 691, in _send
matrix_client.errors.MatrixRequestError: 404: 404 page not found

FATAL: An unexpected exception occurred. A traceback has been written to /tmp/raiden-exception-2020-07-24T10-1697wpw94b.txt
404: 404 page not found
```

logs:  
[raiden-debug_2020-07-24T10:16:16.861310.log](https://github.com/raiden-network/raiden/files/4971474/raiden-debug_2020-07-24T10.16.16.861310.log)

**Comment by czepluch** [comment]
Might have been a temporary unavailable service. Tried again a bit later and everything worked fine.

**Comment by palango** [comment]
@czepluch Can we close this or what should be done?
