### ISSUE TITLE
joining room None failed for Anyblocks matrix server

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#6432]
## Problem Definition

while joining room on the anyblocks matrix servers we get this error

```
You are connected to the 'mainnet' network and the DB path is: /home/devaki/.raiden/node_f128a427/netid_1/network_6d07a2ef/v26_log.db
Synchronization complete, REST API services now available.
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "raiden/network/transport/matrix/transport.py", line 491, in _process_queued_invites
    self._handle_invite(room_id, state)
  File "raiden/network/transport/matrix/transport.py", line 1040, in _handle_invite
    assert room is not None, f"joining room {room} failed"
AssertionError: joining room None failed
2020-07-29T11:12:54Z <Greenlet "Greenlet<fn:_process_queued_invites>" at 0x7f0f69318710: <bound method MatrixTransport._process_queued_invites of <MatrixTransport node:0xF128A427DeFf3a4f792373f4BE38bEecD07d4ffE id:930c6961-f453-4e2f-9bd3-e9c8a91ab1ad>>> failed with AssertionError

```
`joining room None failed`

This error is not encountered while connecting to any other matrix servers.

logs of the node
[node-F128A4-mainnet.29thJuly2020.log](https://github.com/raiden-network/raiden/files/5000242/node-F128A4-mainnet.29thJuly2020.log)

**Comment by karlb** [comment]
We don't use any rooms anymore, so this is obsolete.
