### ISSUE TITLE
Missing displayname causes AssertionError in validate_userid_signature

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#6555]
## Problem Definition

The assert in `validate_userid_signature()`

https://github.com/raiden-network/raiden/blob/14164ecb3f0ba53de5dee51893d49258d6430827/raiden/network/transport/matrix/utils.py#L772-L773

Causes a crash in case a user really has no displayname set which can happen for non-Raiden users.

At the very least this assert should be restricted to only development mode, probably even removed entirely.

Traceback:
```
Traceback (most recent call last):
  File "raiden/ui/cli.py", line 617, in run
  File "raiden/ui/runners.py", line 21, in run_services
  File "raiden/ui/app.py", line 446, in run_app
  File "raiden/app.py", line 90, in start
  File "raiden/raiden_service.py", line 444, in start
  File "raiden/raiden_service.py", line 552, in _start_transport
  File "raiden/network/transport/matrix/transport.py", line 467, in start
  File "raiden/network/transport/matrix/transport.py", line 790, in _initialize_first_sync
  File "raiden/network/transport/matrix/client.py", line 567, in blocking_sync
  File "raiden/network/transport/matrix/client.py", line 774, in _handle_responses
  File "raiden/network/transport/matrix/transport.py", line 1063, in _handle_member_join
  File "raiden/network/transport/matrix/transport.py", line 824, in _leave_unexpected_rooms
  File "raiden/network/transport/matrix/transport.py", line 932, in _extract_addresses
  File "raiden/network/transport/matrix/transport.py", line 932, in <genexpr>
  File "cachetools/decorators.py", line 36, in wrapper
  File "raiden/network/transport/matrix/utils.py", line 728, in validate_userid_signature
AssertionError: The User instance provided to validate_userid_signature must have the displayname attribute set. Make sure to warm the value using the DisplayNameCache.
FATAL: An unexpected exception occurred. A traceback has been written to /tmp/raiden-exception-2020-09-21T14-498mov1ija.txt
The User instance provided to validate_userid_signature must have the displayname attribute set. Make sure to warm the value using the DisplayNameCache.
```

**Comment by fredo** [comment]
I looked into the function and I suggest to remove the assert.

For all other cases where the displayname is not correct the function returns None. So the normal behavior of the function is to return None if the displayname is not correct anyway. For that reason, returning None should already be handled at all usages. IMO It is okay to go with returning None when displayname is missing.
