### ISSUE TITLE
Raiden crashes when querying displayname from user whose server is down

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden#6584]
# Description
If a server in the federation is down and a raiden node tries to query a displayname of a user which is connected to the shut server, matrix will return a `500`. 

This exception is currently not handled and leads to the crash of the raiden node. This is the same cause as in #6568

# Proposal
Handle the HTTP Error and treat the user as not verified. Since the server is down anyway the user cannot be online and thus no communication is possible anyway. But nonetheless, it should not lead to the raiden node crashing.

# Traceback
```
Traceback (most recent call last):
  File "raiden/ui/cli.py", line 617, in run
  File "raiden/ui/runners.py", line 21, in run_services
  File "raiden/ui/app.py", line 446, in run_app
  File "raiden/app.py", line 90, in start
  File "raiden/raiden_service.py", line 444, in start
  File "raiden/raiden_service.py", line 552, in _start_transport
  File "raiden/network/transport/matrix/transport.py", line 449, in start
  File "raiden/network/transport/matrix/utils.py", line 711, in login
  File "raiden/network/transport/matrix/utils.py", line 623, in first_login
  File "matrix_client/client.py", line 270, in login
  File "matrix_client/api.py", line 160, in login
  File "raiden/network/transport/matrix/client.py", line 180, in _send
  File "matrix_client/api.py", line 691, in _send
matrix_client.errors.MatrixRequestError: 500: {"errcode":"M_UNKNOWN","error":"Internal server error"}
``

**Comment by ezdac** [comment]
In what way is the above traceback connected to the bug?
The traceback seems to happens on a login without auth token, while the bug report indicates an unhandled error on calling `User.get_display_name( )`.
How could I replicate this behaviour?

**Comment by ezdac** [comment]
As discussed, the traceback does not relate to the issue description.
Also, we couldn't find an exact code-piece, where a crash would be caused according to the issue description.
But we decided on defensively ignoring all or some `5xx` HTTP errors from Matrix in places where 
the API call is not operation-critical (see #6698).
