### ISSUE TITLE
ms3: update transfer failed for an unknown reason

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6594]
In ms3, node1 stops with
```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.7/site-packages/raiden/raiden_service.py", line 1036, in _handle_events
    raiden=self, chain_state=chain_state, events=raiden_events
  File "/usr/local/lib/python3.7/site-packages/raiden/raiden_event_handler.py", line 823, in on_raiden_events
    self.wrapped.on_raiden_events(raiden, chain_state, events)
  File "/usr/local/lib/python3.7/site-packages/raiden/raiden_event_handler.py", line 196, in on_raiden_events
    self.handle_contract_send_channelupdate(raiden, event)
  File "/usr/local/lib/python3.7/site-packages/raiden/raiden_event_handler.py", line 521, in handle_contract_send_channelupdate
    block_identifier=channel_update_event.triggered_by_block_hash,
  File "/usr/local/lib/python3.7/site-packages/raiden/network/proxies/payment_channel.py", line 175, in update_transfer
    given_block_identifier=block_identifier,
  File "/usr/local/lib/python3.7/site-packages/raiden/network/proxies/token_network.py", line 1843, in update_transfer
    log_details=log_details,
  File "/usr/local/lib/python3.7/site-packages/raiden/network/proxies/token_network.py", line 1964, in _update_transfer
    raise RaidenUnrecoverableError("update transfer failed for an unknown reason")
raiden.exceptions.RaidenUnrecoverableError: update transfer failed for an unknown reason
2020-10-06T17:17:39Z <Greenlet "rs-handle_blocking_events" at 0x7fedc2f72cb0: <bound method RaidenService._handle_events of <RaidenService node:0x36802AEd6f1d5beB95e46182E6E4e9537b02f26C>>(ChainState(block_number=3528830 block_hash=0xc50dc, [ContractSendChannelUpdateTransfer(triggered_by_bl)> failed with RaidenUnrecoverableError
```

Logs and db: https://drive.google.com/file/d/1CcyQwPgc9cVln0SO6_-T85kyS82_dWwi/view?usp=sharing

**Comment by konradkonrad** [comment]
### Recap:
- [Raiden Version](https://github.com/raiden-network/raiden/commit/922e4fdf0d54c150c1bada0d101f8085e04b68bd) `1.1.1.dev256+g922e4fdf0`
- [TokenNetworkContract](https://goerli.etherscan.io/address/0x3ea2a1fed7fdef300da19e97092ce8fdf8bf66a3#code)
- [ChannelOpening](https://goerli.etherscan.io/tx/0xbc6aa6fd09a3d8684af784e411984a622dd9d708a82c23ad5f4f3b2c4fcd0690#eventlog)
- ChannelIdentifier: `6111`
- Settle Timeout: `40`
- [Participant1](https://goerli.etherscan.io/address/0xfb113fc13b22d70aa03b967b2e9072ab8c94c0c9)
- [Participant2](https://goerli.etherscan.io/address/0x36802aed6f1d5beb95e46182e6e4e9537b02f26c)
- [Channel Close](https://goerli.etherscan.io/tx/0x9d774266a2b6943e142d889b827d0718866664a4f34f611b0c066712ea3a77b0#eventlog) at Block `3528807` by [Participant1](https://goerli.etherscan.io/address/0xfb113fc13b22d70aa03b967b2e9072ab8c94c0c9)
- [Failing TX for UpdateNonClosingBalanceProof](https://goerli.etherscan.io/tx/0x8f98fec4da72e74752b39597642911cbdc95cc3e73ee4ec6b543e2117c153847) by [Participant2](https://goerli.etherscan.io/address/0x36802aed6f1d5beb95e46182e6e4e9537b02f26c)

**Comment by karlb** [comment]
I'm also unable to reproduce this. Maybe we had a problem with our eth node? I'm closing this until it happens a second time.

**Comment by konradkonrad** [comment]
The EVM does not throw dice :) 

The tx failed, because of a nonce mismatch:
```
Executing EVM code in 0x3ea2a1fed7fdef300da19e97092ce8f─────Gas available: 128,596; stack:────────
327a PUSH 0x0                               #1 0x2                                                 
327c SHA3                                      2                                                   
327d SWAP1                                  #2 0x2                                                 
327e POP                                       2                                                   
327f DUP1                                   #3 FromKeccak "\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL
3280 PUSH 0x4                                  1344673432836026442494942739692216895916734640406066
3282 ADD                                    #4 0xccb9141b3d5607454ad127b738a13ec7c78f635810e865d0b8
3283 SLOAD                                     9259882658727527997675929354345272160745951303819811
3284 DUP4                                   #5 0x2                                                 
-> 3285 GT                                     2                                                   
3286 PUSH 0x328e                            #6 0xfb113fc13b22d70aa03b967b2e9072ab8c94c0c9          
3289 JUMPI                                     1433341349972274609217023675989424944422902350025   
328a PUSH 0x0                               #7 FromKeccak "\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL
328c DUP1                                      9279618518908503986368638637856643151887839655680450
328d REVERT                                 #8 0x2c76 

///////////////// source ////////////////////
require(nonce > participant_state.nonce);
```

Thanks to `seth run-tx --debug` [0] I could finally solve more of the puzzle. The `nonClosingBalanceProof` was already posted before. After some more digging, I could [find the `monitor` call](https://goerli.etherscan.io/tx/0x96f48e5e3601b0d911c7ba135ca43874cb52bc5c477b4b5fc45eb04fcf4b0086) in block `3528836`.

The remaining question is, why the node did not send the tx earlier?

[0] 
```
seth run-tx --rpc-url=https://goerli.infura.io/v3/<REDACTED> --chain goerli --source combined.json --debug 0x8f98fec4da72e74752b39597642911cbdc95cc3e73ee4ec6b543e2117c153847
```
