### ISSUE TITLE
Token network object should be registered if we got events with it

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#6615]
## Problem Definition
Accessing webui on raiden client gets this error on latest develop version 1.1.1.dev270+g4b910649d
**Token network object should be registered if we got events with it**

```
See the Raiden documentation for all available endpoints at
https://docs.raiden.network/raiden-api-1
Checking if the ethereum node is synchronized
You have chosen the Pathfinding Service at https://pfs.transport01.raiden.network.
Operator: Raiden testnet RSB 01, running version: 0.13.1, chain_id: 5.
Fees will be paid to 0x23A74bd16E98a83be6F9c61807010C8e778ED3E2. Each request costs 0.05 RDN.
Message from the Pathfinding Service:
PFS at pfs.tranport01.raiden.network with fee
Raiden is running in development mode

You are connected to the 'goerli' network and the DB path is: /home/devaki/.raiden/node_aa1ab1fd/netid_5/network_5a5cf4a6/v26_log.db
Synchronization complete, REST API services now available.
You're running version 1.1.1.dev270+g4b910649d. The latest version is 1.1.1
It's time to update! Releases: https://github.com/raiden-network/raiden/releases
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/devaki/raidenforked/raiden/raiden/api/rest.py", line 355, in _run
    self.wsgiserver.serve_forever()
  File "/home/devaki/Envs/raiden_env/lib/python3.7/site-packages/gevent/baseserver.py", line 400, in serve_forever
    self._stop_event.wait()
  File "src/gevent/event.py", line 159, in gevent._gevent_cevent.Event.wait
  File "src/gevent/_abstract_linkable.py", line 381, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 346, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 348, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 303, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
AssertionError: Token network object should be registered if we got events with it
2020-10-15T11:13:04Z <Greenlet "APIServer|Greenlet-0" at 0x7f4c73d38950: _run> failed with AssertionError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/devaki/raidenforked/raiden/raiden/raiden_service.py", line 496, in _run
    self.stop_event.wait()
  File "src/gevent/event.py", line 159, in gevent._gevent_cevent.Event.wait
  File "src/gevent/_abstract_linkable.py", line 381, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 346, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 348, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 303, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
AssertionError: Token network object should be registered if we got events with it
2020-10-15T11:13:05Z <Greenlet "RaidenService._run node:0xAa1Ab1fDA93e14c2d564B25Ba08c9d374F5F9541" at 0x7f4c72780050: _run> failed with AssertionError

Traceback (most recent call last):
  File "/home/devaki/raidenforked/raiden/raiden/ui/cli.py", line 631, in run
    run_services(kwargs)
  File "/home/devaki/raidenforked/raiden/raiden/ui/runners.py", line 93, in run_services
    signal_received = stop_event.get()
  File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 335, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 323, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 303, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "/home/devaki/Envs/raiden_env/lib/python3.7/site-packages/gevent/_compat.py", line 65, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/devaki/raidenforked/raiden/raiden/raiden_service.py", line 496, in _run
    self.stop_event.wait()
  File "src/gevent/event.py", line 159, in gevent._gevent_cevent.Event.wait
  File "src/gevent/_abstract_linkable.py", line 381, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 346, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 348, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 303, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
AssertionError: Token network object should be registered if we got events with it
FATAL: An unexpected exception occurred. A traceback has been written to /tmp/raiden-exception-2020-10-15T11-13ofnqjbaw.txt
Token network object should be registered if we got events with it
ReturnCode.FATAL
```

**Comment by agatsoh** [comment]
Ok update on this issue I tested this out with a fresh address with goerli and the latest develop branch
`version 1.1.1.dev279+gc2862db54!` and I could access the webui.

Plus I tested it with a dirty node again and raiden gets the same error.

**Comment by ezdac** [comment]
@agatsoh thank you for your input. 
Could you clarify on what you mean by "dirty" node?
Do you happen to still have the actual log-file (JSON format) instead of the stdout of the CLI?
