### ISSUE TITLE
Missing missing trie node 2c3e62728ef78310da0b53acb003479bd2d830b84a1f261ea994db9647fd2368 (path )'

### ISSUE THREAD

**Issue by ketuf** [raiden-network/raiden#6808]
Dear Raiden,

I could launch raiden on the main chain but when i try to run raiden on top of rickeby i get the following error
```

Traceback (most recent call last):
  File "raiden/ui/cli.py", line 617, in run
  File "raiden/ui/runners.py", line 21, in run_services
  File "raiden/ui/app.py", line 368, in run_app
  File "raiden/ui/startup.py", line 334, in services_bundle_from_contracts_deployment
  File "raiden/network/pathfinding.py", line 260, in configure_pfs_or_exit
  File "raiden/network/pathfinding.py", line 209, in get_random_pfs
  File "raiden/network/proxies/service_registry.py", line 80, in ever_made_deposits_len
  File "web3/contract.py", line 964, in call
  File "web3/contract.py", line 1499, in call_contract_function
  File "raiden/network/rpc/client.py", line 626, in patched_web3_eth_call
  File "raiden/network/rpc/client.py", line 619, in patched_web3_eth_call
  File "web3/manager.py", line 153, in request_blocking
ValueError: {'code': -32000, 'message': 'missing trie node 2c3e62728ef78310da0b53acb003479bd2d830b84a1f261ea994db9647fd2368 (path )'}
```

**Comment by konradkonrad** [comment]
Hi! Could you tell us a little bit more about your rinkeby setup?
- How did you connect to the blockchain (`infura`, `OE`, `geth`, `parity`)?
- What version of Raiden do you use? (`raiden version`)
- Do you use different addresses for for main chain and rinkeby?

**Comment by karlb** [comment]
Closing due to lack of details.
