### ISSUE TITLE
UPnP exception on next launch after unclean shutdown

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#696]
## Problem Definition

In environments that use upnp for external port mapping abruptly terminating the raiden process (i.e. `kill -9`, power loss etc.) may leave an upnp port mapping behind which will cause a `ConflictInMappingEntry` exception on next launch in [`upnpsocket.py:63`](https://github.com/raiden-network/raiden/blob/master/raiden/network/upnpsock.py#L63).

## Solution

Check if an upnp mapping exists before trying to register a new one.

## Tasklist

- [ ] Implement check for existing upnp mappings before registering a new one

**Comment by konradkonrad** [comment]
There are also more potential issues with the error handling:
```
INFO:raiden.network.sockfactory	trying to find uPnP port mapper... 
Traceback (most recent call last):
  File "/home/konrad/.virtualenvs/raiden-vanilla/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  <...>
  File "/home/konrad/Projects/raiden/raiden/ui/cli.py", line 339, in cli
    with socket_factory(listen_host, listen_port) as mapped_socket:
  File "/usr/local/lib/python2.7.11/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/konrad/Projects/raiden/raiden/network/sockfactory.py", line 48, in socket_factory
    source_port,
  File "/home/konrad/Projects/raiden/raiden/network/upnpsock.py", line 73, in open_port
    success = register(internal_port, external_port)
  File "/home/konrad/Projects/raiden/raiden/network/upnpsock.py", line 69, in register
    '',
Exception: UnknownError
```

Errors with UPnP should never be fatal, since there is another NAT traversal option available.

**Comment by konradkonrad** [comment]
@ulope please close if you cannot reproduce anymore

**Comment by ulope** [comment]
Will test once I get a chance to reset the misbehaving router (and upnp works again)

**Comment by konradkonrad** [comment]
ping

**Comment by ulope** [comment]
Sorry, forgot about this. The bug is indeed fixed.
