### ISSUE TITLE
Increase DB version

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6986]
We should update the db version as part of the 1.2 -> 2.0 upgrade:

- [ ] increment db version
- [ ] run newer version against older db, make sure there are backup files

**Comment by istankovic** [comment]
I got this when running the new raiden:
```
You are connected to the 'goerli' network and the DB path is: /home/ivan/.raiden/node_42405d66/netid_5/network_e7871b43/v26_log.db
2021-04-26 14:28:20.391478 [info     ] Using Matrix server            [raiden.network.transport.matrix.utils] average_rtt=0.045103000000000004 server_ident=Synapse/1.22.1 server_url=http
s://transport.raiden.overdoze.se                                                                                                                                                          
Traceback (most recent call last):                                                           
  File "/home/ivan/src/raiden/raiden/storage/serialization/serializer.py", line 100, in deserialize
    klass = _import_type(data["_type"])     
  File "/home/ivan/src/raiden/raiden/storage/serialization/serializer.py", line 54, in _import_type
    raise TypeError(f"Could not find {module_name}.{klass_name}")
TypeError: Could not find raiden.transfer.state_change.ActionChangeNodeNetworkState
                                                                                             
The above exception was the direct cause of the following exception:
                                                                                             
Traceback (most recent call last):
  File "/home/ivan/src/raiden/raiden/raiden_service.py", line 676, in _initialize_wal
    state, state_change_qty_unapplied = wal.replay_state_changes(
  File "/home/ivan/src/raiden/raiden/storage/wal.py", line 114, in replay_state_changes
    unapplied_state_changes = storage.get_statechanges_by_range(state_change_range)
  File "/home/ivan/src/raiden/raiden/storage/sqlite.py", line 1033, in get_statechanges_by_range
    for state_change_record in self.get_statechanges_records_by_range(db_range=db_range)
  File "/home/ivan/src/raiden/raiden/storage/sqlite.py", line 1022, in get_statechanges_records_by_range
    return [                                                                                                                                                                              
  File "/home/ivan/src/raiden/raiden/storage/sqlite.py", line 1025, in <listcomp>                                                                                                         
    data=self.serializer.deserialize(state_change.data),                                                                                                                                  
  File "/home/ivan/src/raiden/raiden/storage/serialization/serializer.py", line 124, in deserialize                                                    
    data = DictSerializer.deserialize(decoded_json)                                                                                                                                       
  File "/home/ivan/src/raiden/raiden/storage/serialization/serializer.py", line 104, in deserialize                                    
    raise SerializationError(f"Can't deserialize: {data}") from ex                                                                                                                        
raiden.exceptions.SerializationError: Can't deserialize: {'network_state': 'REACHABLE', 'node_address': '0x3f3b8c7a229b4d5d9d4e4e712c713bbd65517abf', '_type': 'raiden.transfer.state_chan
ge.ActionChangeNodeNetworkState'}
                                                                                                                                                                                          
During handling of the above exception, another exception occurred:             

Traceback (most recent call last):
  File "/home/ivan/src/raiden/raiden/ui/cli.py", line 724, in _run
    run_services(kwargs)
  File "/home/ivan/src/raiden/raiden/ui/runners.py", line 18, in run_services
    raiden_service = run_raiden_service(**options)
  File "/home/ivan/src/raiden/raiden/ui/app.py", line 455, in run_raiden_service
    raiden_service.start()
  File "/home/ivan/src/raiden/raiden/raiden_service.py", line 460, in start
    self._initialize_wal()
  File "/home/ivan/src/raiden/raiden/raiden_service.py", line 684, in _initialize_wal
    raise RaidenUnrecoverableError(
raiden.exceptions.RaidenUnrecoverableError: Could not restore state. It seems like the existing database is incompatible with the current version of Raiden. Consider using a stable versi
on of the Raiden client.
FATAL: An unexpected exception occurred. A traceback has been written to /tmp/raiden-exception-2021-04-26T14-28o515mvuv.txt
Could not restore state. It seems like the existing database is incompatible with the current version of Raiden. Consider using a stable version of the Raiden client.
```
