### ISSUE TITLE
Startup failing when discovery room is missing

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#7019]
Found as part of https://github.com/raiden-network/light-client/issues/2699

Similar to https://github.com/raiden-network/raiden-services/issues/999

It seems like the Raiden (version v2.0.0-a0) is failing to startup when the discovery room is not available.

```
 FATAL: An unexpected exception occurred. A traceback has been written to /tmp/raiden-exception-2021-05-11T09-2623k6nfap.txt
 Could not join broadcast room #raiden_4321_discovery:localhost. Make sure the Matrix server you're trying to connect to uses the recommended server setup, esp. the server-side broadcast room creation. See https://github.com/raiden-network/raiden-transport.
 Traceback (most recent call last):
   File "/opt/raiden/lib/python3.7/site-packages/raiden/network/transport/matrix/utils.py", line 198, in join_broadcast_room
     room = client.join_room(broadcast_room_alias)
   File "/opt/raiden/lib/python3.7/site-packages/matrix_client/client.py", line 320, in join_room
     response = self.api.join_room(room_id_or_alias)
   File "/opt/raiden/lib/python3.7/site-packages/matrix_client/api.py", line 195, in join_room
     return self._send("POST", path)
   File "/opt/raiden/lib/python3.7/site-packages/raiden/network/transport/matrix/client.py", line 182, in _send
     return super()._send(method, path, *args, **kwargs)
   File "/opt/raiden/lib/python3.7/site-packages/matrix_client/api.py", line 691, in _send
     code=response.status_code, content=response.text
 matrix_client.errors.MatrixRequestError: 404: {"errcode":"M_NOT_FOUND","error":"Room alias #raiden_4321_discovery:localhost not found"}

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
   File "/opt/raiden/lib/python3.7/site-packages/raiden/network/transport/matrix/transport.py", line 888, in _join_broadcast_room
     client=transport._client, broadcast_room_alias=broadcast_room_alias
   File "/opt/raiden/lib/python3.7/site-packages/raiden/network/transport/matrix/utils.py", line 203, in join_broadcast_room
     f"Could not join broadcast room {broadcast_room_alias}. "
 raiden.exceptions.RaidenUnrecoverableError: Could not join broadcast room #raiden_4321_discovery:localhost. Make sure the Matrix server you're trying to connect to uses the recommended server setup, esp. the server-side broadcast room creation. See https://github.com/raiden-network/raiden-transport.
 2021-05-11T09:26:22Z <Greenlet "Greenlet-4" at 0x7f16b54d3050: _join_broadcast_room(<MatrixTransport node:None id:38e7525d-d788-418a-b, 'raiden_4321_discovery')> failed with RaidenUnrecoverableError

 Traceback (most recent call last):
   File "/opt/raiden/lib/python3.7/site-packages/raiden/network/transport/matrix/utils.py", line 198, in join_broadcast_room
     room = client.join_room(broadcast_room_alias)
   File "/opt/raiden/lib/python3.7/site-packages/matrix_client/client.py", line 320, in join_room
     response = self.api.join_room(room_id_or_alias)
   File "/opt/raiden/lib/python3.7/site-packages/matrix_client/api.py", line 195, in join_room
     return self._send("POST", path)
   File "/opt/raiden/lib/python3.7/site-packages/raiden/network/transport/matrix/client.py", line 182, in _send
     return super()._send(method, path, *args, **kwargs)
   File "/opt/raiden/lib/python3.7/site-packages/matrix_client/api.py", line 691, in _send
     code=response.status_code, content=response.text
 matrix_client.errors.MatrixRequestError: 404: {"errcode":"M_NOT_FOUND","error":"Room alias #raiden_4321_discovery:localhost not found"}

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/opt/raiden/lib/python3.7/site-packages/raiden/ui/cli.py", line 724, in _run
     run_services(kwargs)
   File "/opt/raiden/lib/python3.7/site-packages/raiden/ui/runners.py", line 18, in run_services
     raiden_service = run_raiden_service(**options)
   File "/opt/raiden/lib/python3.7/site-packages/raiden/ui/app.py", line 455, in run_raiden_service
     raiden_service.start()
   File "/opt/raiden/lib/python3.7/site-packages/raiden/raiden_service.py", line 481, in start
     self._start_transport(chain_state)
   File "/opt/raiden/lib/python3.7/site-packages/raiden/raiden_service.py", line 607, in _start_transport
     self.transport.start(raiden_service=self, prev_auth_data=None)
   File "/opt/raiden/lib/python3.7/site-packages/raiden/network/transport/matrix/transport.py", line 577, in start
     self._initialize_broadcast_rooms()
   File "/opt/raiden/lib/python3.7/site-packages/raiden/network/transport/matrix/transport.py", line 897, in _initialize_broadcast_rooms
     pool.join(raise_error=True)
   File "/opt/raiden/lib/python3.7/site-packages/gevent/pool.py", line 435, in join
     greenlet._raise_exception()
   File "src/gevent/greenlet.py", line 371, in gevent._gevent_cgreenlet.Greenlet._raise_exception
   File "/opt/raiden/lib/python3.7/site-packages/gevent/_compat.py", line 65, in reraise
     raise value.with_traceback(tb)
   File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
   File "/opt/raiden/lib/python3.7/site-packages/raiden/network/transport/matrix/transport.py", line 888, in _join_broadcast_room
     client=transport._client, broadcast_room_alias=broadcast_room_alias
   File "/opt/raiden/lib/python3.7/site-packages/raiden/network/transport/matrix/utils.py", line 203, in join_broadcast_room
     f"Could not join broadcast room {broadcast_room_alias}. "
 raiden.exceptions.RaidenUnrecoverableError: Could not join broadcast room #raiden_4321_discovery:localhost. Make sure the Matrix server you're trying to connect to uses the recommended server setup, esp. the server-side broadcast room creation. See https://github.com/raiden-network/raiden-transport.
 ReturnCode.FATAL

**Comment by fredo** [comment]
will be fixed with #7020
