### ISSUE TITLE
Raiden fails on open channel with unregistered token address

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden#706]
## Problem Definition

Trying to open a channel with an unregisted token (a valid token/contract address, but which isn't yet returned in the list from `/api/1/tokens` endpoint) causes an exception in Raiden, and API request to return code 500.

### Relevant part of the exception:
```ERROR in app: Exception on /api/1/channels [PUT]
Traceback (most recent call last):
  ...
  File "/apps/raiden/raiden/api/v1/resources.py", line 55, in put
    return self.rest_api.open(**kwargs)
  File "/apps/raiden/raiden/api/rest.py", line 183, in open
    settle_timeout
  File "/apps/raiden/raiden/api/python.py", line 140, in open
    channel_manager = self.raiden.chain.manager_by_token(token_address)
  File "/apps/raiden/raiden/network/rpc/client.py", line 360, in manager_by_token
    poll_timeout=self.poll_timeout,
  File "/apps/raiden/raiden/network/rpc/client.py", line 709, in __init__
    'latest',
  File "/usr/local/lib/python2.7/dist-packages/pyethapp/rpc_client.py", line 413, in call
    raise JSONRPCClientReplyError(jsonrpc_reply.error)
JSONRPCClientReplyError: Invalid params: invalid length 0, expected a 0x-prefixed, padded, hex-encoded hash with length 40.
```

### Example requisition causing this error
```
curl -v -H "Content-Type: application/json" -X PUT -d '{"partner_address":"0x000D91Cf263a11F9BfCeE3752E5B03FC1196CE98","token_address":"0x9aBa529db3FF2D8409A1da4C9eB148879b046700","balance":0,"settle_timeout":600}' http://localhost:5001/api/1/channels
```

## Solution

Check why `manager_by_token` is failing to generate a valid `manager_address` when fed a `token_address` not yet on registry, and fix it, so it gets properly returned.

## Tasklist

- [x] Create test for opening channel with unregistered token
- [x] Fix bug so raiden acts accordingly
- [ ] Add a changelog entry

## System Description

Raiden in current master (as of 2017-07-09), running on a Linux system with Linux kernel 4.11.7, over docker. Using parity nightly, but further testing have shown it is not a parity bug, as the requisition goes empty and fails even with geth 1.6.6.

**Comment by andrevmatos** [comment]
Further investigation have shown that the problem is at [client.py#L358](https://github.com/raiden-network/raiden/blob/ebd3731ebc554afb150d1f711bc7673b0c75dc2f/raiden/network/rpc/client.py#L358):
```
manager_address = self.default_registry.manager_address_by_token(token.address)
```
where `manager_address_by_token` (from [client.py#L632](https://github.com/raiden-network/raiden/blob/ebd3731ebc554afb150d1f711bc7673b0c75dc2f/raiden/network/rpc/client.py#L632)) assumes the token exists, and return it's address directly from the RPC call, which gives an empty string in the case the token isn't registed yet.
Solution seems to call [Registry.add_token](https://github.com/raiden-network/raiden/blob/ebd3731ebc554afb150d1f711bc7673b0c75dc2f/raiden/network/rpc/client.py#L636) in case the RPC returns invalid manager address.

**Comment by andrevmatos** [comment]
Per #713 , we won't register channels automatically. Instead, proper interface was added to webUI to allow explicit registering of new tokens, and interface to allow only registered tokens to be selected for channel opening, transfers, etc.
