### ISSUE TITLE
Handle eth node restarts

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#707]
## Problem Definition

If the eth node becomes unavailable on the network a `ConnectionError` exception is thrown. In this case the exception was triggered by `AlarmTask()` since it communicates the most frequently with the eth node.

<details>
<summary>Traceback</summary>
<code><pre>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/app/raiden/tasks.py", line 62, in _run
    self.poll_for_new_block()
  File "/app/raiden/tasks.py", line 79, in poll_for_new_block
    current_block = self.chain.block_number()
  File "/app/raiden/network/rpc/client.py", line 264, in block_number
    return self.client.blocknumber()
  File "/usr/local/lib/python2.7/site-packages/pyethapp/rpc_client.py", line 165, in blocknumber
    return quantity_decoder(self.call('eth_blockNumber'))
  File "/usr/local/lib/python2.7/site-packages/pyethapp/rpc_client.py", line 404, in call
    reply = self.transport.send_message(request.serialize())
  File "/app/raiden/network/rpc/client.py", line 172, in send_message
    **client.transport.request_kwargs
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 549, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='10.0.1.1', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fda4a7fa310&gt;: Failed to establish a new connection: [Errno 111] Connection refused',))
&lt;AlarmTask at 0x7fda4a9b9d70&gt; failed with ConnectionError
</pre></code>
</details>

## Solution

`ConnectionError`s need to be caught and the connection reestablished.

## Tasklist

- [ ] Handle `ConnectionError` in the RPC-Client
- [ ] Handle missing filters if node restarts.

**Comment by LefterisJP** [comment]
I am working on this, but it's not as simple as just retrying after a `ConnectionError`. If the eth node is restarted we also lose the generated filters. We need to regenerate them in such a case:

```
Traceback (most recent call last):
  File "/home/lefteris/ew/raiden/raiden/tasks.py", line 99, in poll_for_new_block
    result = callback(current_block)
  File "/home/lefteris/ew/raiden/raiden/raiden_service.py", line 206, in <lambda>
    alarm.register_callback(lambda _: self.poll_blockchain_events())
  File "/home/lefteris/ew/raiden/raiden/raiden_service.py", line 301, in poll_blockchain_events
    for state_change in self.pyethapp_blockchain_events.poll_state_change():
  File "/home/lefteris/ew/raiden/raiden/blockchain/events.py", line 263, in poll_state_change
    for event in self.poll_all_event_listeners():
  File "/home/lefteris/ew/raiden/raiden/blockchain/events.py", line 256, in poll_all_event_listeners
    event_listener.translator,
  File "/home/lefteris/ew/raiden/raiden/blockchain/events.py", line 45, in poll_event_listener
    for log_event in pyethapp_filter.changes():
  File "/home/lefteris/ew/raiden/raiden/network/rpc/client.py", line 475, in changes
    return self._query_filter('eth_getFilterChanges')
  File "/home/lefteris/ew/raiden/raiden/network/rpc/client.py", line 451, in _query_filter
    filter_changes = self.client.call(function, self.filter_id_raw)
  File "/home/lefteris/.virtualenvs/raiden/src/pyethapp/pyethapp/rpc_client.py", line 413, in call
    raise JSONRPCClientReplyError(jsonrpc_reply.error)
JSONRPCClientReplyError: filter not found
```

No blocker yet, just more work than initially expected.

**Comment by LefterisJP** [comment]
This is something we will keep working on - I have a PR open for quite some time now, but it's not a priority for the developer preview.
