### ISSUE TITLE
Crash when doing partial withdraw

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#7093]
## Problem Definition
During mainnet testing, when doing a partial withdraw with a partner that seems to have been offline, my node crashed with the following error:

```
2021-05-27 09:14:08.382038 [critical ] Unhandled exception when processing endpoint request [raiden.api.rest] node=0x24EF85F0175545849A12bf74EFAedDA2E7e8C7D9
Traceback (most recent call last):
  File "flask/app.py", line 1950, in full_dispatch_request
  File "flask/app.py", line 1936, in dispatch_request
  File "flask_restful/__init__.py", line 468, in wrapper
  File "flask/views.py", line 89, in view
  File "flask_restful/__init__.py", line 583, in dispatch_request
  File "raiden/api/rest_utils.py", line 59, in decorated
  File "raiden/api/v1/resources.py", line 120, in patch
  File "raiden/api/rest.py", line 1312, in patch_channel
  File "raiden/api/rest.py", line 1128, in _withdraw
  File "raiden/api/python.py", line 598, in set_total_channel_withdraw
  File "raiden/network/pathfinding.py", line 569, in query_address_metadata
raiden.exceptions.PFSReturnedError: ('There is no user found online for given address. (PFS error code: 2203)', {'address': '0x1276467EFEE8EEb098889589e7e2CADf6EdCbC46', 'seen_offline_since': 36452.43484})
2021-05-27 09:14:08.493440 [info     ] Synchronizing blockchain events [raiden.raiden_service] blocks_per_second=0.03850091694024404 elapsed=25.97340737500008 greenlet_name=AlarmTask._run node:0x24EF85F0175545849A12bf74EFAedDA2E7e8C7D9 remaining_blocks_to_sync=0 to_block=12515538
2021-05-27 09:14:09.398140 [info     ] 127.0.0.1 - - [2021-05-27 11:14:09] "PATCH /api/v1/channels/0x6B175474E89094C44Da98b954EedeAC495271d0F/0x1276467EFEE8EEb098889589e7e2CADf6EdCbC46 HTTP/1.1" 500 161 1.464026 [raiden.api.rest.pywsgi]
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "raiden/api/rest.py", line 363, in _run
  File "gevent/baseserver.py", line 400, in serve_forever
  File "src/gevent/event.py", line 163, in gevent._gevent_cevent.Event.wait
  File "src/gevent/_abstract_linkable.py", line 521, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 487, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 490, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 442, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
  File "src/gevent/_abstract_linkable.py", line 451, in gevent._gevent_c_abstract_linkable.AbstractLinkable._switch_to_hub
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
raiden.exceptions.PFSReturnedError: ('There is no user found online for given address. (PFS error code: 2203)', {'address': '0x1276467EFEE8EEb098889589e7e2CADf6EdCbC46', 'seen_offline_since': 36452.43484})
2021-05-27T09:14:09Z <Greenlet "APIServer|Greenlet-0" at 0x116d4e830: _run> failed with PFSReturnedError

2021-05-27 09:14:09.410559 [error    ] Runnable subtask died!         [raiden.utils.runnable] exc=PFSReturnedError('There is no user found online for given address. (PFS error code: 2203)', {'address': '0x1276467EFEE8EEb098889589e7e2CADf6EdCbC46', 'seen_offline_since': 36452.43484}) running=True subtask=<Greenlet "APIServer|Greenlet-0" at 0x116d4e830: _run> this=<RaidenService node:0x24EF85F0175545849A12bf74EFAedDA2E7e8C7D9>
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "raiden/raiden_service.py", line 492, in _run
  File "src/gevent/event.py", line 163, in gevent._gevent_cevent.Event.wait
  File "src/gevent/_abstract_linkable.py", line 521, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 487, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 490, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 442, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
  File "src/gevent/_abstract_linkable.py", line 451, in gevent._gevent_c_abstract_linkable.AbstractLinkable._switch_to_hub
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
raiden.exceptions.PFSReturnedError: ('There is no user found online for given address. (PFS error code: 2203)', {'address': '0x1276467EFEE8EEb098889589e7e2CADf6EdCbC46', 'seen_offline_since': 36452.43484})
2021-05-27T09:14:09Z <Greenlet "RaidenService._run node:0x24EF85F0175545849A12bf74EFAedDA2E7e8C7D9" at 0x116d4ecb0: _run> failed with PFSReturnedError

Traceback (most recent call last):
  File "raiden/ui/cli.py", line 723, in _run
  File "raiden/ui/runners.py", line 92, in run_services
  File "src/gevent/event.py", line 329, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 359, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 347, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 327, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "gevent/_compat.py", line 65, in reraise
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "raiden/raiden_service.py", line 492, in _run
  File "src/gevent/event.py", line 163, in gevent._gevent_cevent.Event.wait
  File "src/gevent/_abstract_linkable.py", line 521, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 487, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 490, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 442, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
  File "src/gevent/_abstract_linkable.py", line 451, in gevent._gevent_c_abstract_linkable.AbstractLinkable._switch_to_hub
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
raiden.exceptions.PFSReturnedError: ('There is no user found online for given address. (PFS error code: 2203)', {'address': '0x1276467EFEE8EEb098889589e7e2CADf6EdCbC46', 'seen_offline_since': 36452.43484})
FATAL: An unexpected exception occurred. A traceback has been written to /var/folders/4g/53tsn0qx2hn2x9zmjbkfb0cm0000gn/T/raiden-exception-2021-05-27T09-14ffxrxha6.txt
('There is no user found online for given address. (PFS error code: 2203)', {'address': '0x1276467EFEE8EEb098889589e7e2CADf6EdCbC46', 'seen_offline_since': 36452.43484})
ReturnCode.FATAL
```

**Comment by czepluch** [comment]
And the full logs: 
[raiden-debug_2021-05-27T08:18:02.755799.log.zip](https://github.com/raiden-network/raiden/files/6553010/raiden-debug_2021-05-27T08.18.02.755799.log.zip)
