### ISSUE TITLE
KeyError when using our openethereum node

### ISSUE THREAD

**Issue by istankovic** [raiden-network/raiden#7124]
I get this when trying to run Raiden (ade5d73224601d48e7b54262dfddddac3f45aff6) with our openethereum node,
`http://parity.mainnet.ethnodes.brainbot.com:8545`:
```
Traceback (most recent call last):
  File "/home/ivan/src/raiden/raiden/ui/cli.py", line 721, in _run
    run_services(kwargs)
  File "/home/ivan/src/raiden/raiden/ui/runners.py", line 18, in run_services
    raiden_service = run_raiden_service(**options)
  File "/home/ivan/src/raiden/raiden/ui/app.py", line 457, in run_raiden_service
    raiden_service.start()
  File "/home/ivan/src/raiden/raiden/raiden_service.py", line 459, in start
    self._initialize_wal()
  File "/home/ivan/src/raiden/raiden/raiden_service.py", line 655, in _initialize_wal
    initial_state = self._make_initial_state()
  File "/home/ivan/src/raiden/raiden/raiden_service.py", line 612, in _make_initial_state
    last_log_block_hash = self.rpc_client.blockhash_from_blocknumber(last_log_block_number)
  File "/home/ivan/src/raiden/raiden/network/rpc/client.py", line 1094, in blockhash_from_blocknumber
    block = self.get_block(block_number)
  File "/home/ivan/src/raiden/raiden/network/rpc/client.py", line 1080, in get_block
    return self.web3.eth.getBlock(block_identifier)
  File "/home/ivan/venv-3.9/lib/python3.9/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "/home/ivan/venv-3.9/lib/python3.9/site-packages/web3/manager.py", line 158, in request_blocking
    apply_error_formatters(error_formatters, response)
  File "/home/ivan/venv-3.9/lib/python3.9/site-packages/web3/manager.py", line 62, in apply_error_formatters
    formatted_response = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 669, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 644, in cytoolz.functoolz.c_pipe
  File "/home/ivan/venv-3.9/lib/python3.9/site-packages/web3/_utils/method_formatters.py", line 588, in raise_block_not_found
    block_identifier = params[0]
KeyError: 0
```

**Comment by istankovic** [comment]
Submitted ethereum/web3.py#2010, nothing to do on our side.
