### ISSUE TITLE
Exception on raiden start: 'ChannelSerialization' object has no attribute 'partner_address'

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden#717]
## Problem Definition

Since today, got a couple of exceptions on raiden start. It exits right after starting, with following stacktrace. Not sure if related, but account has a few open channels left since some tests yesterday, which may be triggering this problematic codepath:

```
ERROR:raiden.tasks  unexpected exception on alarm
Traceback (most recent call last):
  File "/apps/raiden/raiden/tasks.py", line 99, in poll_for_new_block
    result = callback(current_block)
  File "/apps/raiden/raiden/raiden_service.py", line 165, in <lambda>
    alarm.register_callback(lambda _: self.poll_blockchain_events())
  File "/apps/raiden/raiden/raiden_service.py", line 260, in poll_blockchain_events
    on_statechange = self.state_machine_event_handler.on_blockchain_statechange
AttributeError: 'RaidenService' object has no attribute 'state_machine_event_handler'
ERROR:raiden.tasks  unexpected exception on alarm
Traceback (most recent call last):
  File "/apps/raiden/raiden/tasks.py", line 99, in poll_for_new_block
    result = callback(current_block)
  File "/apps/raiden/raiden/raiden_service.py", line 236, in set_block_number
    self.state_machine_event_handler.log_and_dispatch_to_all_tasks(state_change)
AttributeError: 'RaidenService' object has no attribute 'state_machine_event_handler'
Traceback (most recent call last):
  File "/usr/local/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/apps/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/apps/raiden/raiden/ui/cli.py", line 323, in run
    app_ = ctx.invoke(app, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/apps/raiden/raiden/ui/cli.py", line 304, in app
    return App(config, blockchain_service, discovery)
  File "/apps/raiden/raiden/app.py", line 70, in __init__
    config,
  File "/apps/raiden/raiden/raiden_service.py", line 207, in __init__
    self.restore_channel(channel)
  File "/apps/raiden/raiden/raiden_service.py", line 490, in restore_channel
    assert channel_details['partner_address'] == serialized_channel.partner_address
AttributeError: 'ChannelSerialization' object has no attribute 'partner_address'
```

## System Description
This bug appeared with Raiden on agatsoh/raiden@33f02e7fd4b33688017fe48f86a57f20d93f3d42 webui branch, merged on current 5747d4353fdcb088f66162c6a096417b3b06762e master.

**Comment by hackaugusto** [comment]
Duplicate https://github.com/raiden-network/raiden/issues/708
