### ISSUE TITLE
Remove the channel address from the channel manager after settlement

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden#739]
## Problem Definition

Starting a Raiden instance, even with no `~/.raiden`, crashes with following traceback:
```Traceback (most recent call last):
  File "/usr/local/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/apps/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/apps/raiden/raiden/ui/cli.py", line 321, in run
    app_ = ctx.invoke(app, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/apps/raiden/raiden/ui/cli.py", line 302, in app
    return App(config, blockchain_service, discovery)
  File "/apps/raiden/raiden/app.py", line 70, in __init__
    config,
  File "/apps/raiden/raiden/raiden_service.py", line 250, in __init__
    self.register_registry(self.chain.default_registry.address)
  File "/apps/raiden/raiden/raiden_service.py", line 606, in register_registry
    registry_address,
  File "/apps/raiden/raiden/blockchain/events.py", line 174, in get_relevant_proxies
    for channel_address in participating_channels
  File "/apps/raiden/raiden/network/rpc/client.py", line 330, in netting_channel
    poll_timeout=self.poll_timeout,
  File "/apps/raiden/raiden/network/rpc/client.py", line 863, in __init__
    address_encoder(channel_address),
ValueError: Netting channel address 0x68301a2a425ac0cbb85e65f49b72bd65e9cfaeb4 does not contain code
```

Not sure if this `0x68301a2a425ac0cbb85e65f49b72bd65e9cfaeb4` address was present on my channels list yesterday, or if it is related, but anything I did different is that, yesterday, tried closing a pair of channels that were on my participating list.
Anyway, somehow, an empty address ended up on the participating_channels, and Raiden crashes everytime it is started because of it.

## Solution

We shoud:
1. Prevent an empty address from being added to participating channels list
2. Handle deleted contracts and remove it from the list before it crashes Raiden
3. If we're deleting the contract (maybe on `close`?), remove it from the list beforehand too

### System Description
Error were with raiden on current master (91e74eb18e65ca8138cd1f8d6bb2a75677ebe75f), running with raiden nightly, but tested with geth and the error was the same (as both correctly returns empty contract for this address).

**Comment by LefterisJP** [comment]
I will work on this for a bit. Let's see how to do this.

**Comment by andrevmatos** [comment]
Workaround PR made, but need proper fix/cleanup. At least the previous accounts are usable now (aparently).

**Comment by LefterisJP** [comment]
@andrevmatos Thank you. We will do a proper fix soon as we figure out what that would be.

**Comment by Sankarshan-Mudkavi** [comment]
I'm going to work on the original fix (the non-workaround version)

**Comment by hackaugusto** [comment]
This is not necessary anymore. We moved from a model with one smart contract per channel to a version were all the channels are kept in the token network.
