### ISSUE TITLE
Raiden won't start after a channel has been settled

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#872]
## Problem Definition

Settling a contract also makes the contract commit suicide. This means that there is node code at it's address after this point. However when we start the blockchain service we check that there is code deployed at all addresses (https://github.com/raiden-network/raiden/blob/master/raiden/network/rpc/client.py#L884-L887). This means that Raiden throws an exception on startup.

Removing the `.raiden` dir does not even solve the problem.

## Solution

Either allow Raiden to start even with settled channels or remove "unregister" the channels in the client once settled.

## Tasklist

- [ ] choose one of the above approaches
- [ ] implement above approach

## Traceback
```
Traceback (most recent call last):
  File "/home/jacob/Dropbox/prgrms/ethereum/raiden/.venv/bin/raiden", line 11, in <module>
    load_entry_point('raiden==0.0.5', 'console_scripts', 'raiden')()
  File "/home/jacob/Dropbox/prgrms/ethereum/raiden/.venv/lib/python2.7/site-packages/raiden-0.0.5-py2.7.egg/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')
  File "/home/jacob/Dropbox/prgrms/ethereum/raiden/.venv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/jacob/Dropbox/prgrms/ethereum/raiden/.venv/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/jacob/Dropbox/prgrms/ethereum/raiden/.venv/lib/python2.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/jacob/Dropbox/prgrms/ethereum/raiden/.venv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jacob/Dropbox/prgrms/ethereum/raiden/.venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jacob/Dropbox/prgrms/ethereum/raiden/.venv/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jacob/Dropbox/prgrms/ethereum/raiden/.venv/lib/python2.7/site-packages/raiden-0.0.5-py2.7.egg/raiden/ui/cli.py", line 443, in run
    app_ = ctx.invoke(app, **kwargs)
  File "/home/jacob/Dropbox/prgrms/ethereum/raiden/.venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jacob/Dropbox/prgrms/ethereum/raiden/.venv/lib/python2.7/site-packages/raiden-0.0.5-py2.7.egg/raiden/ui/cli.py", line 354, in app
    return App(config, blockchain_service, discovery)
  File "/home/jacob/Dropbox/prgrms/ethereum/raiden/.venv/lib/python2.7/site-packages/raiden-0.0.5-py2.7.egg/raiden/app.py", line 77, in __init__
    config,
  File "/home/jacob/Dropbox/prgrms/ethereum/raiden/.venv/lib/python2.7/site-packages/raiden-0.0.5-py2.7.egg/raiden/raiden_service.py", line 255, in __init__
    self.register_registry(self.chain.default_registry.address)
  File "/home/jacob/Dropbox/prgrms/ethereum/raiden/.venv/lib/python2.7/site-packages/raiden-0.0.5-py2.7.egg/raiden/raiden_service.py", line 599, in register_registry
    registry_address,
  File "/home/jacob/Dropbox/prgrms/ethereum/raiden/.venv/lib/python2.7/site-packages/raiden-0.0.5-py2.7.egg/raiden/blockchain/events.py", line 181, in get_relevant_proxies
    netting_channels.append(pyethapp_chain.netting_channel(channel_address))
  File "/home/jacob/Dropbox/prgrms/ethereum/raiden/.venv/lib/python2.7/site-packages/raiden-0.0.5-py2.7.egg/raiden/network/rpc/client.py", line 337, in netting_channel
    poll_timeout=self.poll_timeout,
  File "/home/jacob/Dropbox/prgrms/ethereum/raiden/.venv/lib/python2.7/site-packages/raiden-0.0.5-py2.7.egg/raiden/network/rpc/client.py", line 886, in __init__
    address_encoder(channel_address),
raiden.exceptions.AddressWithoutCode: Netting channel address 0x69cf4cf53f8fb00e7d598fc12e547861712a60af does not contain code
```

**Comment by czepluch** [comment]
fixed by #873

**Comment by rdmXain** [comment]
Get this error when starting new Raiden node from scratch using Etheremint in place of Ethereum.

**Comment by narcis2007** [comment]
I'm getting raiden.exceptions.AddressWithoutCode: [TokenNetworkRegistry]: Address 0x4a6E1fe3dB979e600712E269b26207c49FEe116E does not contain code
when I try to start raiden too

**Comment by LefterisJP** [comment]
@narcis2007 please make sure that your geth is synced. And perhaps open another issue and attach all relevant logs.
