### ISSUE TITLE
Can't running!ImportError: No module named blocks

### ISSUE THREAD

**Issue by 6593942** [raiden-network/raiden#897]
## Problem Definition

Traceback (most recent call last):
  File "/usr/local/python2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/python2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/raiden/raiden/__main__.py", line 15, in <module>
    main()
  File "/root/raiden/raiden/__main__.py", line 7, in main
    from raiden.ui.cli import run
  File "/usr/local/python2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/root/raiden/raiden/ui/cli.py", line 16, in <module>
    from pyethapp.jsonrpc import address_decoder, address_encoder
  File "/usr/local/python2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/python2.7/lib/python2.7/site-packages/pyethapp/jsonrpc.py", line 6, in <module>
    import ethereum.blocks
  File "/usr/local/python2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named blocks

### System Description
Here add a detailed description of your system, raiden version, geth version, solidity version e.t.c.

**Comment by LefterisJP** [comment]
Have you tried to follow the [installation guide](https://github.com/raiden-network/raiden/blob/master/docs/overview_and_guide.rst)?

**Comment by LefterisJP** [comment]
Closing the issue. If you have other problems in installing and using raiden please wait until the developer preview release is ready and ask us questions/support in [gitter](https://gitter.im/raiden-network/raiden)
